application_fee_receipts = [
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "applicationReceipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "application_fee_report_gurukula",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "bluebell_appln_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "narayana_brainova_appln_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "svips_appln_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "sspcbs_appln_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "puttana_appln_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "jaihind_appln_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "template-9_appln_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "vasavi_application_fee",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "jaihind1_appln_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "shishandhara_application_feereceipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "manasa_application_fee",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "vbs_application_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "vidya_sagar_application",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "osy_application_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "setbatkal_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "application_fees",
            "name": "svvk_application_recipt",
            "no_of_copies": 2,
        },
    ]