hall_ticket = [
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "natushalticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_pre-kg",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_lkg",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_ukg",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_1_to_10",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "jnanajyothi_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "asian_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_pre-kg_SA1",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_Lkg_SA1",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_ukg_SA1",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "sphoorthi_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "janavi_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "vikas_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "sunshine_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "brillient_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "dvsshilpashree_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_2",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_lkg_SA2",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_prekg_SA2",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "abchs_halticket_ukg_SA2",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_1std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_2std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_3std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_4std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_5std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_6std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_7std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_8std",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_prekg",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_lkg",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svips_halticket_annual_ukg",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "angaliconvent_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "rrgobalschool_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "default_morning_afternoonsession",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "cordial_halticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "navodhaya_halticket",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "jaihindinternational_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "amardeepvidyamandira",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "sphoorthi_halticket_2",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "saraswathividya_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "angelpublic_halticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "ssps_halticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "ssess_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "holycross_halticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "inps_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "construe_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "gupta_halticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "skyhigh_halticket",
            "no_of_copies": 2,
         },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "jnanajyothi_halticket_pu",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "championsjp_halticket_pu",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "anjali_halticket",
            "no_of_copies": 6,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name": "siri",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name": "vishnu",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name": "srivishnu",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name": "jnanajyothi_anekal_hallticket",
            "no_of_copies":3,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"sainik_hallticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"apuc_hallticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"jnana_sangama_hall_ticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"nisarga_hall_ticket",
            "no_of_copies":2,
        },
        # {
        #     "template_type":"pdf",
        #     "module":"hall_ticket",
        #     "name":"gupta_college_hall_ticket",
        #     "no_of_copies":2,
        # },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"svnenglish_hall_ticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"srignanajyothi_hall_ticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"shikshanadhaara_hall_ticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"apuc_halticket",
            "no_of_copies":2,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"aadhithya_halticket",
            "no_of_copies":2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "nps_jalhalli",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "sainik_kolar_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "srignanajyothi_10",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "jdb_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "pvk_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "ghghs_hall_ticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "nortwest_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "sbvs_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svems_college_hall_ticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "bgsimschikkaballapur_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "svems_hall_ticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "mis_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "wges_hombegowda_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "srignanajyothi_general_halticket",
            "name": "lumbini_halticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "vss_ukg_hallticket",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "weis_halticket",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "hall_ticket",
            "name": "jjv_hallticket",
            "no_of_copies": 2,
        },
        
    ]

marks_card = [
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "jnana_jyothi_marks_card_1_to_10",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "jnana_jyothi_marks_card_lkg_to_ukg",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "jnana_jyothi_marks_card_puc",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "nisarga_marks_card_10",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "nisarga_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "spoorthi_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "aips_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "narayana_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "ssps_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "template_2",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "ssps_marks_card_SA",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "amardeep_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "jnanajyothinew_marks_card_pu",
            "no_of_copies": 1,
        },
         {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "akshara_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "jaihind_primary_marks_card",
            "no_of_copies": 1,
        },
          {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "jaihind_marks_card",
            "no_of_copies": 1,

        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "apuc_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "gupta_college_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "inps_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "svnenglish_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "lourdes_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "srignanajyothi_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type":"pdf",
            "module":"hall_ticket",
            "name":"svnthanisandra_a5_10th",
            "no_of_copies":2,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "nps_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "svems_raichur_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "vss_marks_card",
            "no_of_copies": 1,
        },
        { 
         "template_type": "pdf",
            "module": "marks_card",
            "name": "vss_marks_card_old",
            "no_of_copies": 1
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "vss_nursery_marks_card",
            "no_of_copies": 1,
        },
         {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "apuc_1puc_marks",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "springwell_marks_card",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "marks_card",
            "name": "sbvshr_marks_card",
            "no_of_copies": 1,
        },
        {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "magnus_marks_card",
            "no_of_copies": 1 
        },
         {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "sunlight_marks_card",
            "no_of_copies": 1
        },
          {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "jaihind_gbpalya_marks_card",
            "no_of_copies": 1
        },
        {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "we_care_marks_card",
            "no_of_copies": 1
        },
         {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "inps_marks_card2",
            "no_of_copies": 1
        },
        {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "cis_colour_marks_card",
            "no_of_copies": 1
        },
        {
           "template_type": "pdf",
            "module": "marks_card",
            "name": "nightingales_marks_card",
            "no_of_copies": 1
        },
    ]

consolidated_report = [
        {
            "template_type": "pdf",
            "module": "consolidated_report",
            "name": "nightingales_consolidated_report",
            "no_of_copies": 1,
        },
    ]