fee_collection_fee_receipts = [
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "feesReceipt",
        "no_of_copies": 2,
    },  # default
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "gurukula_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "jnanajyothi_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "acharya_mahapragya",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "shiksha_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "bluebell_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "kvtattva_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "anniebesant_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "nisarga_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "sadguru_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "vikas_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "childhood_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "svips_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "bluebell_book_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "bluebell_fee_receipt_type_wise",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "shiksha_fee_receipt_type_wise",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "new_st_marys_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "aksharasrividya_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "mandara_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "narayana_brainova_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "janatha_vidyalaya_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "omsai_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "saraswathi_vidya_mandir_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "siri_fee_receipt",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "puttanapublicschool",
        "no_of_copies": 2,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "sspscbs_uniform_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "sspscbs_book_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "sspscbs_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "natus_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "newbaldwin_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "newbaldwin_fee_receipt_book",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "newbaldwin_fee_receipt_uniform",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "default_fee_receipt_1",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "sharada_shidlaghatta_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "spoorthi_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "default1_A5",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "gurukul_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "default3_A5",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "gurukulhigh_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "template-5",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "default4_A5",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "niveditha_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "vidyamandir_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "jaihind",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "dvsshilpashree_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "holycross_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "mohre_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "omganesh_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "default8",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "default9_A5",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "template-9",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "slv_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "anjaliconvent_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "akshara_international_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "skyhigh_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "jdbschool_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "jnanajyothi_anekal_fee_receipt",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "natus_bookuniform",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "vasavi_admissionfee_receipt",
        "no_of_copies": 2,
    },
     {
        "template_type": "pdf",
        "module": "fee_collection",
        "name": "vasavi_trust_feereceipt",
        "no_of_copies": 2,
    },
     {
         "template_type":"pdf",
         "module": "fee_collection",
         "name":"navodaya_public_school_fee_reciept",
         "no_of_copies":2, 
     },
     {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "shantiniketanschoolaustin_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "apuc_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "jjps_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "acharya_mahapragya_sqirrel",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "acharya_mahapragya_rves",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "jnana_sangama_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "sbvshr_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "stella_marris_a5",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "nvhs_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "gupta_college",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "lourdes_fee_receipt",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "lourdes_fee_receipt_transport",
            "no_of_copies": 1,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "wecare_fee_receipt",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "slvis_fee_receipt_a5",
            "no_of_copies": 1,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "breezy_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "stanford_fee_receipt_a5",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "sgh_hombegowda_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "cv_raman_feereceipt_a5",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "manasa_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "shikshadara_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "vidya_bharathi_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "rkmconvent_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "mangalavidyakendra.fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "nandini_vidyanikethana_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "pre_cambridge_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "sakalya_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "vidya_sagar_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "oxford_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "springwell_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "santosh_paramedical_fee_receipt_A4",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "stanford_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "uhs_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "svvk_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "swvk_kannada_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "swvk_english_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "swvk_van_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "svvk_van_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "sldps_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "svems_raichur1_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "sunlight_fee_receipt",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "rkm_fees_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "nightingales_fee_receipt",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "cvrambtech_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "manasa_mallur_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "cvramandegree_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "cvramanintermediate_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "vidhatri_academy_fee_receipt_a5",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "vidya_sagar_fee_receipt_A5",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "vsstuition_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "saraswathi_education_trust",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "konkan_education_trust_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "osy_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "jaintoddlers_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "svn_nagawara_fee_receipt",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "thermal_printer_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "puttanna_annual_fee_receipt",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection",
            "name": "vjc_fee_receipt",
            "no_of_copies": 2,
        },

]

fee_collection_report = [
        {
            "template_type": "pdf",
            "module": "fee_collection_report",
            "name": "feesReport",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection_report",
            "name": "feesReportDiplomaDefault",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection_report",
            "name": "sspscbs_fee_collection_report",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection_report",
            "name": "puttannatransportfee",
            "no_of_copies": 2,
        },
         {
            "template_type": "pdf",
            "module": "fee_collection_report",
            "name": "wecare_feesReport",
            "no_of_copies": 2,
        },
        {
            "template_type": "pdf",
            "module": "fee_collection_report",
            "name": "sainik_fee_collection_report",
            "no_of_copies": 2,
        },
    ]

fee_collection_student_copy = [
        {
            'template_type': 'pdf', 'module': 'fee_collection_student_copy', 'name': 'feesReceiptStudentCopy',
            'no_of_copies': 2
        }
    ]


cashbook_reports = [
        {
            "template_type": "pdf",
            "module": "cashbook_report",
            "name": "saraswathi_cashbook_report",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "cashbook_report",
            "name": "stlawerence_cashbook_report",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "cashbook_report",
            "name": "jaihind_cashbook_report",
            "no_of_copies": 1,
        },
        {
            "template_type": "pdf",
            "module": "cashbook_report",
            "name": "natus_cashbook_report",
            "no_of_copies": 1,
        },
    ]

cashbook_report_fy_wise = [
    {
            "template_type": "pdf",
            "module": "cashbook_report_fy_wise",
            "name": "cordial_cashbook_report_fy_wise",
            "no_of_copies": 1,
    },
]

balance_sheet_reports = [
    {
        "template_type": "pdf",
        "module": "balance_sheet",
        "name": "default_balance_sheet_report",
        "no_of_copies": 1,
    },
]

recoverable_asset_reports = [
    {
        "template_type": "pdf",
        "module": "recoverable_asset",
        "name": "default_recoverable_ledger_report",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "recoverable_asset",
        "name": "default_recoverable_category_summary",
        "no_of_copies": 1,
    },
    {
        "template_type": "pdf",
        "module": "recoverable_asset",
        "name": "default_recoverable_period_report",
        "no_of_copies": 1,
    },
]