# Generated by Django 3.2.24 on 2023-04-01 15:24

from django.db import migrations



class Migration(migrations.Migration):

    def initial_misc_types(apps, schema_editor):
        MiscellaneousType= apps.get_model('finance', 'MiscellaneousType')
        MiscellaneousType.objects.bulk_create([
            MiscellaneousType(name='Study Certificate', code_name='sc', is_active=True),
            MiscellaneousType(name='Transfer Certificate', code_name='tc', is_active=True),
        ])

    dependencies = [
        ('finance', '0011_auto_20230409_2002'),
    ]

    operations = [
        migrations.RunPython(initial_misc_types)
    ]
