# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_initial'),
        ('shared', '0001_initial'),
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_initial'),
        ('payments', '0001_initial'),
        ('staffs', '0001_initial'),
        ('finance', '0003_miscellaneous_student'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestandardmapping',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='feestandardmapping',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feetype'),
        ),
        migrations.AddField(
            model_name='feestandardmapping',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_types', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='standard_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_fee', to='finance.feestandardmapping'),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='student_feature',
            field=models.ManyToManyField(blank=True, related_name='student_feature', to='students.Student'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='online_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_collection_online_payment', to='payments.onlinepayment'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='online_payout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_collection_payout', to='payments.payout'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collection', to='students.student'),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fee_collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concession',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='concession',
            name='concession_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_type', to='finance.concessiontype'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_attachment', to='shared.document'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='finance.bankdetail'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='bankfeetypemapping',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_type_bank', to='finance.bankdetail'),
        ),
        migrations.AddField(
            model_name='bankfeetypemapping',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_fee_type', to='finance.feetype'),
        ),
        migrations.AddField(
            model_name='applicationplan',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='applicationplan',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_standard', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='applicationpaymentdetail',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_payment', to='forms.applicationstudent'),
        ),
        migrations.AddField(
            model_name='applicationpaymentdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_admission', to='students.student'),
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='concession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_adjustment', to='finance.concession'),
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='fee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_plan', to='finance.feeplan'),
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
