# Generated by Django 2.2.24 on 2021-08-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    def initial_fee_types(apps, schema_editor):
        FeeType = apps.get_model('finance', 'FeeType')
        FeeType.objects.bulk_create([
            FeeType(name='Admission fee', codename='admission', is_feature=False),
            FeeType(name='Transport fee', codename='transport', is_feature=True),
            FeeType(name='Application fee', codename='application', is_feature=True),
            FeeType(name='Hostel fee', codename='hostel', is_feature=True),
        ])

    dependencies = [
        ('finance', '0004_initial'),
    ]

    operations = [
        migrations.RunPython(initial_fee_types)
    ]
