# Generated by Django 3.2 on 2023-03-09 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('students', '0005_remove_studentsiblingmapping_relation_ship'),
        ('finance', '0005_custom_fee_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStandardMappingItemSellingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_standard_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_standard_mapping_item_selling_price_fee_standard_mapping', to='finance.feestandardmapping')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_standard_mapping_item_selling_price_stock', to='store.stock')),
            ],
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StudentStoreMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_standard_mapping_item_selling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_store_mapping_fee_standard_mapping_item_selling', to='finance.feestandardmappingitemsellingprice')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_store_mapping_student', to='students.student')),
            ],
        ),
    ]
