# Generated by Django 3.2 on 2023-03-31 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20230312_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessiontype',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeePlanConcessionMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('concession_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plan_concession_mapping_concession_type', to='finance.concessiontype')),
            ],
        ),
        migrations.CreateModel(
            name='FeePlanConcessionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plan_concession_mapping_fee_plan', to='finance.feeplan')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plan_concession_mapping_master', to='finance.feeplanconcessionmappingmaster')),
            ],
        ),
    ]
