# Generated by Django 3.2.24 on 2023-04-01 15:24

from django.db import migrations



class Migration(migrations.Migration):

    def initial_concession_types(apps, schema_editor):
        ConcessionType= apps.get_model('finance', 'ConcessionType')
        ConcessionType.objects.bulk_create([
            ConcessionType(name='One Time Paymet', code='one_time_payment', is_active=True),
        ])

    dependencies = [
        ('finance', '0008_auto_20230331_0250'),
    ]

    operations = [
        migrations.RunPython(initial_concession_types)
    ]
