# Generated by Django 3.2 on 2023-04-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0008_alter_reason_reason_type'),
        ('finance', '0009_custom_concession_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustmentfee',
            name='reason',
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='reason_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_reason', to='institutes.reason'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='receipt_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
