# Generated by Django 3.2 on 2023-04-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '00012_custom_misc_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeGroupName',
            new_name='FeeGroup',
        ),
    ]
