# Generated by Django 3.2 on 2023-04-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_rename_feegroupname_feegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='payment_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
