# Generated by Django 3.2 on 2023-04-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_feecollection_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentfee',
            name='fee_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_fee_collection_id', to='finance.feecollection'),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='is_permission_to_edit',
            field=models.BooleanField(default=True),
        ),
    ]
