# Generated by Django 3.2 on 2023-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_admissionformhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='payment_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
