# Generated by Django 3.2 on 2023-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_applicationpaymentdetail_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestandardmappingitemsellingprice',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='studentstoremapping',
            name='issued_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentstoremapping',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
