# Generated by Django 3.2 on 2023-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20230430_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeplan',
            name='term_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
