# Generated by Django 3.2.24 on 2023-05-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    def initial_fee_types(apps, schema_editor):
        FeeType = apps.get_model('finance', 'FeeType')
        FeeType.objects.bulk_create([
            FeeType(name='Pending Amount', codename='custom', is_feature=True),
        ])

    dependencies = [
        ('finance', '0020_feeplan_term_alias'),
    ]

    operations = [
        migrations.RunPython(initial_fee_types)
    ]
