# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_medium_list(apps, schema_editor):
        FeePlan = apps.get_model('finance', 'FeePlan')
        FeeplanStudentFeature = apps.get_model('finance', 'FeeplanStudentFeature')
        fee_plan_data = FeePlan.objects.all()
        data_to_save = []
        for fee_plan in fee_plan_data:
            for row in fee_plan.student_feature.values():
                data_to_save.append(FeeplanStudentFeature(
                    fee_plan = fee_plan,
                    student_id = row['id'],
                    amount=0
                ))
        if data_to_save:
            FeeplanStudentFeature.objects.bulk_create(data_to_save)

    dependencies = [
        ('finance', '0022_feeplanstudentfeature'),
    ]

    operations = [
        migrations.RunPython(initial_medium_list)
    ]
