# Generated by Django 3.2 on 2023-05-11 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20230415_1926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0023_custom_migration_copy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeplan',
            name='student_feature',
        ),
        migrations.AlterField(
            model_name='feeplanstudentfeature',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeplanstudentfeature',
            name='fee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_plan_student_feature_fee_plan', to='finance.feeplan'),
        ),
        migrations.AlterField(
            model_name='feeplanstudentfeature',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_plan_student_feature_student', to='students.student'),
        ),
    ]
