# Generated by Django 3.2 on 2023-05-15 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0024_auto_20230511_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentFeeApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[(0, 'Unapproved'), (1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default='0', max_length=1)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_approval_requested_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentRequestedToUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[(0, 'Unapproved'), (1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default='0', max_length=1)),
                ('approval_history', models.JSONField()),
                ('sequence', models.IntegerField(default=0)),
                ('rejected_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('adjustment_fee_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_requested_to_users_adjustment_fee_approval', to='finance.adjustmentfeeapproval')),
                ('requested_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_requested_to_users_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentApprovalMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_approval_mapping_adjustment', to='finance.adjustmentfee')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_approval_mapping_approval', to='finance.adjustmentfeeapproval')),
            ],
        ),
    ]
