# Generated by Django 3.2 on 2023-05-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20230415_1926'),
        ('finance', '0025_adjustmentapprovalmapping_adjustmentfeeapproval_adjustmentrequestedtousers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentFeeParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_parent_student', to='students.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='adjustmentfeeapproval',
            name='requested_by_user',
        ),
        migrations.RemoveField(
            model_name='adjustmentrequestedtousers',
            name='adjustment_fee_approval',
        ),
        migrations.RemoveField(
            model_name='adjustmentrequestedtousers',
            name='requested_to_user',
        ),
        migrations.DeleteModel(
            name='AdjustmentApprovalMapping',
        ),
        migrations.DeleteModel(
            name='AdjustmentFeeApproval',
        ),
        migrations.DeleteModel(
            name='AdjustmentRequestedToUsers',
        ),
        migrations.AddField(
            model_name='adjustmentfee',
            name='adjustment_fee_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_fee_adjustment_fee_parent', to='finance.adjustmentfeeparent'),
        ),
    ]
