# Generated by Django 3.2 on 2023-06-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20230605_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='online_payout',
        ),
    ]
