# Generated by Django 3.2 on 2023-07-04 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20230415_1926'),
        ('finance', '0028_remove_feecollection_online_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestandardmapping',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_standard_mapping_student_group', to='students.studentgroup'),
        ),
    ]
