# Generated by Django 3.2 on 2024-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_feestandardmapping_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online'), ('Debit', 'Debit'), ('Credit', 'Credit')], max_length=20, null=True),
        ),
    ]
