# Generated by Django 3.2 on 2024-04-14 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_feecollection_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FeeCollectionModeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_ref_num', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collection_mode_of_payment_fee_collection', to='finance.feecollection')),
            ],
        ),
    ]
