# Generated by Django 3.2 on 2024-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_auto_20240502_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpaymentdetail',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
