# Generated by Django 3.2 on 2024-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_auto_20240504_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestandardmapping',
            name='receipt_alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
