# Generated by Django 3.2 on 2024-09-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_feestandardmapping_receipt_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestandardmapping',
            name='gender',
            field=models.CharField(blank=True, choices=[('Boy', 'Boy'), ('Girl', 'Girl'), ('Other', 'Other')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feestandardmapping',
            name='is_new_student',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_category', to='finance.feecategory'),
        ),
    ]
