# Generated by Django 3.2 on 2025-04-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_auto_20240925_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStoreMappingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_addition', models.BooleanField(default=True)),
                ('current_assigned_quantity', models.IntegerField()),
                ('current_issued_quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student_store_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.studentstoremapping')),
            ],
        ),
    ]
