# Generated by Django 3.2 on 2025-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_studentstoremappinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='terms',
            field=models.CharField(blank=True, choices=[('Term1', 'Term1'), ('Term2', 'Term2'), ('Term3', 'Term3'), ('Term4', 'Term4'), ('Term5', 'Term5'), ('Term6', 'Term6'), ('Term7', 'Term7'), ('Term8', 'Term8'), ('Term9', 'Term9'), ('Term10', 'Term10'), ('Term11', 'Term11'), ('Term12', 'Term12'), ('Term13', 'Term13'), ('Term14', 'Term14'), ('Term15', 'Term15'), ('Term16', 'Term16'), ('Term17', 'Term17'), ('Term18', 'Term18'), ('Term19', 'Term19'), ('Term20', 'Term20')], max_length=10, null=True),
        ),
    ]
