# Generated by Django 2.2.24 on 2021-08-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    def initial_misc_tax(apps, schema_editor):
        Misc = apps.get_model('finance','Miscellaneous')
        misc_details = Misc.objects.all()
        Miscellaneous = apps.get_model('finance','Miscellaneous')
        for miscellaneous_data in misc_details:
            Miscellaneous.objects.filter(id=miscellaneous_data.id).update(amount = miscellaneous_data.total_amount)

    dependencies = [
        ('finance', '0038_auto_20250513_1227'),
    ]

    operations = [
        migrations.RunPython(initial_misc_tax)
    ]
