# Generated by Django 3.2 on 2025-07-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_staff_blood_group'),
        ('finance', '0039_custom_misctax'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscellaneous_staff', to='staffs.staff'),
        ),
    ]
