# Generated by Django 3.2 on 2025-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_miscellaneous_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollectionmodeofpayment',
            name='loan_credited_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feecollectionmodeofpayment',
            name='loan_from_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feecollectionmodeofpayment',
            name='loan_to_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feecollectionmodeofpayment',
            name='loan_utr_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
