# Generated by Django 3.2 on 2025-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0040_custom_staff_app_menu'),
        ('finance', '0041_auto_20251021_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentfeeparent',
            name='approved_documents',
            field=models.ManyToManyField(blank=True, help_text='Approved documents for adjustment', related_name='adjustment_fee_parent_documents', to='shared.Document'),
        ),
    ]
