# Generated by Django 3.2 on 2025-11-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0042_adjustmentfeeparent_approved_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeplan',
            name='hide_from_app',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
