# Generated by Django 3.2 on 2025-11-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0043_feeplan_hide_from_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollectionmodeofpayment',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collection_mode_of_payment_bank_detail', to='finance.bankdetail'),
        ),
    ]
