# Generated by Django 3.2 on 2025-12-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0030_auto_20251010_1108'),
        ('students', '0010_auto_20240730_1717'),
        ('institutes', '0022_custom_resource_migrations'),
        ('finance', '0044_feecollectionmodeofpayment_bank_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDashboardCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_concession', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('fee_type_breakdown', models.JSONField(blank=True, default=dict, null=True)),
                ('payment_mode_breakdown', models.JSONField(blank=True, default=dict, null=True)),
                ('monthly_collection', models.JSONField(blank=True, default=dict, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cache', to='institutes.academicyear')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_cache', to='classes.standard')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cache', to='students.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='financedashboardcache',
            index=models.Index(fields=['academic_year', 'standard'], name='finance_fin_academi_2c7a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='financedashboardcache',
            index=models.Index(fields=['academic_year', 'student'], name='finance_fin_academi_6b73ad_idx'),
        ),
        migrations.AddIndex(
            model_name='financedashboardcache',
            index=models.Index(fields=['academic_year'], name='finance_fin_academi_bec634_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financedashboardcache',
            unique_together={('academic_year', 'standard', 'student')},
        ),
    ]
