# Generated by Django 3.2 on 2026-01-23 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0022_custom_resource_migrations'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0045_auto_20251223_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWithdrawRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.IntegerField(default=True)),
                ('transaction_from', models.IntegerField(default=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bank_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_record_transaction_details_bank_from', to='finance.bankdetail')),
                ('bank_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_record_transaction_details_bank_to', to='finance.bankdetail')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_record_created_by', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_financial_year', to='institutes.financialyear')),
                ('user_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_record_transaction_details_user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_record_transaction_details_user_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
