# Generated by Django 3.2 on 2026-02-09 23:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0010_auto_20240730_1717'),
        ('institutes', '0023_institute_social_links'),
        ('staffs', '0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting'),
        ('finance', '0046_depositwithdrawrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverableAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('STABILITY_FUND', 'Stability Fund'), ('LOAN', 'Loan'), ('ADVANCE', 'Advance'), ('STAFF_SALARY_ADVANCE', 'Staff Salary Advance')], max_length=25)),
                ('counterparty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('counterparty_type', models.CharField(blank=True, choices=[('INSTITUTION', 'Institution'), ('VENDOR', 'Vendor'), ('INDIVIDUAL', 'Individual'), ('BANK', 'Bank'), ('EMPLOYEE', 'Employee')], max_length=20, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_label', models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total advance/loan amount for staff advances', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monthly_recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly recovery amount for staff advances', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_month', models.DateField(blank=True, help_text='Recovery starts from this month', null=True)),
                ('tenure_months', models.PositiveIntegerField(blank=True, help_text='Tenure in months', null=True)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, help_text='EMI amount for loan type', max_digits=15, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate percentage', max_digits=5)),
                ('interest_type', models.CharField(choices=[('NONE', 'No Interest'), ('SIMPLE', 'Simple Interest'), ('COMPOUND', 'Compound Interest')], default='NONE', max_length=10)),
                ('auto_deduct_from_payroll', models.BooleanField(default=False)),
                ('deduction_priority', models.PositiveIntegerField(default=1)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('closure_reason', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('NORMAL_RECOVERY', 'Fully Recovered'), ('WRITE_OFF', 'Written Off'), ('SETTLEMENT', 'Settled')], default='', max_length=20)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recoverable_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverable_asset_created', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutes.financialyear')),
                ('staff', models.ForeignKey(blank=True, help_text='For staff salary advance type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recoverable_assets', to='staffs.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverable_asset_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recoverable Asset',
                'verbose_name_plural': 'Recoverable Assets',
                'db_table': 'stability_fund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoverableAssetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('ADVANCE', 'Advance'), ('RECOVERY', 'Recovery'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST', 'Interest Charge'), ('PENALTY', 'Late Payment Penalty'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('PAYROLL', 'Payroll'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST_CALC', 'Interest Calculation'), ('PENALTY_CALC', 'Penalty Calculation')], default='MANUAL', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment_reason', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('WRITE_OFF', 'Write-off'), ('SETTLEMENT', 'Settlement'), ('CORRECTION', 'Correction'), ('WAIVER', 'Interest/Penalty Waiver')], default='', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverable_asset_transaction_created', to=settings.AUTH_USER_MODEL)),
                ('recoverable_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.recoverableasset')),
            ],
            options={
                'verbose_name': 'Recoverable Asset Transaction',
                'verbose_name_plural': 'Recoverable Asset Transactions',
                'db_table': 'stability_fund_transaction',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoverableAssetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recoverable_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.recoverableasset')),
                ('recoverable_asset_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='finance.recoverableassettransaction')),
            ],
            options={
                'verbose_name': 'Recoverable Asset History',
                'verbose_name_plural': 'Recoverable Asset Histories',
                'db_table': 'stability_fund_history',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeMismatchReconciliationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_is_new_student', models.BooleanField(blank=True, null=True)),
                ('new_is_new_student', models.BooleanField(blank=True, null=True)),
                ('original_total_fee', models.FloatField(default=0)),
                ('new_total_fee', models.FloatField(default=0)),
                ('total_paid', models.FloatField(default=0)),
                ('adjustment_amount', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_mismatch_reconciliation_log_academic_year', to='institutes.academicyear')),
                ('new_student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_mismatch_new_student_group', to='students.studentgroup')),
                ('original_student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_mismatch_original_student_group', to='students.studentgroup')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_mismatch_reconciled_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_mismatch_reconciliation_log_student', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Mismatch Reconciliation Log',
                'verbose_name_plural': 'Fee Mismatch Reconciliation Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FeeMismatchPaymentChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_detail_id', models.IntegerField()),
                ('old_fee_plan_id', models.IntegerField(blank=True, null=True)),
                ('new_fee_plan_id', models.IntegerField(blank=True, null=True)),
                ('old_fee_plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_fee_plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_standard_fee_id', models.IntegerField(blank=True, null=True)),
                ('new_standard_fee_id', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reconciliation_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_changes', to='finance.feemismatchreconciliationlog')),
            ],
            options={
                'verbose_name': 'Fee Mismatch Payment Change Log',
                'verbose_name_plural': 'Fee Mismatch Payment Change Logs',
                'ordering': ['id'],
            },
        ),
    ]
