# Generated by Django 3.2 on 2026-03-04 21:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0025_auto_20260225_2054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0047_customdesigntemplatemap_templatesamplejson'),
        ('finance', '0047_feemismatchpaymentchangelog_feemismatchreconciliationlog_recoverableasset_recoverableassethistory_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('CAPITAL', 'Capital / Fund')], max_length=20)),
                ('sub_type', models.CharField(choices=[('FIXED_ASSET', 'Fixed Asset'), ('CURRENT_ASSET', 'Current Asset'), ('INVESTMENT', 'Investment'), ('WIP', 'Work in Progress'), ('CURRENT_LIABILITY', 'Current Liability'), ('LONG_TERM_LIABILITY', 'Long Term Liability'), ('CAPITAL_FUND', 'Capital Fund'), ('BRANCH', 'Branch / Division'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('schedule_number', models.CharField(blank=True, help_text='Schedule reference e.g. A1, B3', max_length=20, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_model', models.CharField(choices=[('ASSET_GROUP', 'Fixed Asset Group'), ('RECOVERABLE_ASSET', 'Recoverable Asset'), ('BALANCE_SHEET_ENTRY', 'Balance Sheet Entry'), ('COMPUTED', 'System Computed')], default='BALANCE_SHEET_ENTRY', max_length=30)),
                ('is_system', models.BooleanField(default=False, help_text='True = auto-populated from linked model')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.financialcategory')),
            ],
            options={
                'verbose_name': 'Financial Category',
                'verbose_name_plural': 'Financial Categories',
                'ordering': ['category_type', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Linked bank account for stability fund / deposit types', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverable_assets', to='finance.bankdetail'),
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='linked_transfer_type',
            field=models.CharField(blank=True, choices=[('CASH_TO_BANK', 'Cash in Hand to Bank'), ('BANK_TO_BANK', 'Bank to Bank'), ('CASH_TO_CASH', 'Cash in Hand to Cash in Hand'), ('BANK_TO_CASH', 'Bank to Cash')], help_text='Optional: link this asset to a specific transfer type. When making transfers of this type, this asset can be selected.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='report_group_name',
            field=models.ForeignKey(blank=True, help_text='Linked report group for Sundry Debtors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverable_assets', to='shared.reportgroupname'),
        ),
        migrations.AlterField(
            model_name='recoverableasset',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('STABILITY_FUND', 'Stability Fund'), ('LOAN', 'Loan'), ('ADVANCE', 'Advance'), ('DEPOSIT', 'Deposit'), ('STAFF_SALARY_ADVANCE', 'Staff Salary Advance'), ('SUNDRY', 'Sundry Debtors')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='recoverableassettransaction',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PAYROLL', 'Payroll'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST_CALC', 'Interest Calculation'), ('PENALTY_CALC', 'Penalty Calculation'), ('BANK_TRANSFER', 'Bank/Cash Transfer')], default='MANUAL', max_length=20),
        ),
        migrations.AlterModelTable(
            name='recoverableasset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recoverableassettransaction',
            table=None,
        ),
        migrations.CreateModel(
            name='RecoverableAssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset_types', models.JSONField(default=list, help_text='List of ASSET_TYPE_CHOICES that belong to this category')),
                ('default_counterparty_type', models.CharField(blank=True, choices=[('INSTITUTION', 'Institution'), ('VENDOR', 'Vendor'), ('INDIVIDUAL', 'Individual'), ('BANK', 'Bank'), ('EMPLOYEE', 'Employee')], max_length=20, null=True)),
                ('default_interest_type', models.CharField(choices=[('NONE', 'No Interest'), ('SIMPLE', 'Simple Interest'), ('COMPOUND', 'Compound Interest')], default='NONE', max_length=10)),
                ('is_system', models.BooleanField(default=False, help_text='System categories cannot be deleted')),
                ('is_linked_system', models.BooleanField(default=False, help_text='True for categories whose data also comes from other modules (payroll, student fee). Still allows manual entries.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoverable_asset_category_created', to=settings.AUTH_USER_MODEL)),
                ('financial_category', models.ForeignKey(blank=True, help_text='Maps this category to balance sheet classification (FinancialCategory)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recoverable_categories', to='finance.financialcategory')),
            ],
            options={
                'verbose_name': 'Recoverable Asset Category',
                'verbose_name_plural': 'Recoverable Asset Categories',
                'db_table': 'recoverable_asset_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('additions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('financial_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='finance.financialcategory')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_snapshots', to='institutes.financialyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_financial_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Snapshot',
                'verbose_name_plural': 'Financial Snapshots',
                'db_table': 'financial_snapshot',
                'ordering': ['financial_category__display_order'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetLockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('EDITED', 'Edited')], max_length=10)),
                ('performed_on', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entry_count', models.PositiveIntegerField(default=0, help_text='Number of balance sheet entries affected')),
                ('details', models.JSONField(blank=True, help_text='Extra details about the action (e.g. edited entry info)', null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_lock_history', to='institutes.financialyear')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance Sheet Lock History',
                'verbose_name_plural': 'Balance Sheet Lock Histories',
                'db_table': 'balance_sheet_lock_history',
                'ordering': ['-performed_on'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier per FY', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('particulars', models.TextField(blank=True, help_text='Full description', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('entry_side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='Auto-derived from financial_category.category_type. Do not set manually.', max_length=10)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, help_text='e.g. As per audited BS 31.03.2025', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_opening', models.BooleanField(default=False, help_text='True if seeded from BS migration')),
                ('is_locked', models.BooleanField(default=False, help_text='Set when financial year is locked')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheet_entries_created', to=settings.AUTH_USER_MODEL)),
                ('financial_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financialcategory')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheet_entries', to='institutes.financialyear')),
            ],
            options={
                'verbose_name': 'Balance Sheet Entry',
                'verbose_name_plural': 'Balance Sheet Entries',
                'ordering': ['financial_category__display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for grouping and reporting', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='finance.recoverableassetcategory'),
        ),
        migrations.AddConstraint(
            model_name='financialsnapshot',
            constraint=models.UniqueConstraint(fields=('financial_category', 'financial_year'), name='unique_snapshot_per_category_fy'),
        ),
        migrations.AddConstraint(
            model_name='balancesheetentry',
            constraint=models.UniqueConstraint(fields=('code', 'financial_year'), name='unique_bs_entry_code_per_fy'),
        ),
    ]
