# Generated by Django 3.2 on 2026-03-10 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting'),
        ('institutes', '0025_auto_20260225_2054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0047_customdesigntemplatemap_templatesamplejson'),
        ('finance', '0048_auto_20260304_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='closing_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='institutes.financialyear'),
        ),
        migrations.AddField(
            model_name='depositwithdrawrecord',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_withdraw_attachment', to='shared.document'),
        ),
        migrations.CreateModel(
            name='StaffWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_in_hand_opening_balance_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_in_hand_opening_balance', to='staffs.staff')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
