# Generated by Django 3.2 on 2026-03-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_onlinepayment_entity_name'),
        ('finance', '0049_auto_20260310_2045'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='applicationpaymentdetail',
        #     name='online_payment',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_payment_online_payment', to='payments.onlinepayment'),
        # ),
        # migrations.AddField(
        #     model_name='applicationplan',
        #     name='is_academic_year_online_appln',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='applicationplan',
        #     name='online_amount',
        #     field=models.FloatField(null=True),
        # ),
    ]
