# Generated by Django 3.2 on 2026-03-30 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_auto_20260328_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionDenomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositWithdrawRecordDenomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeAdvanceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('receipt_num', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_ref_num', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeAdvanceCollectionPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeAdvanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='balancesheetentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='balancesheetentry',
            name='financial_category',
        ),
        migrations.RemoveField(
            model_name='balancesheetentry',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='financialcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='financialsnapshot',
            name='financial_category',
        ),
        migrations.RemoveField(
            model_name='financialsnapshot',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='financialsnapshot',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='approved_on',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='as_of_date',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='auto_deduct_from_payroll',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='closure_reason',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='deduction_priority',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='interest_type',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='linked_transfer_type',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='monthly_recovery_amount',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='report_group_name',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='tenure_months',
        ),
        migrations.RemoveField(
            model_name='recoverableasset',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='recoverableassetcategory',
            name='default_counterparty_type',
        ),
        migrations.RemoveField(
            model_name='recoverableassetcategory',
            name='default_interest_type',
        ),
        migrations.RemoveField(
            model_name='recoverableassetcategory',
            name='financial_category',
        ),
        migrations.RemoveField(
            model_name='recoverableassetcategory',
            name='is_linked_system',
        ),
        migrations.RemoveField(
            model_name='recoverableassetcategory',
            name='is_system',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='opening_balance_type',
            field=models.CharField(default='DEBIT', help_text='Whether the opening balance is a debit or credit entry', max_length=10),
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='advance_fee_config',
            field=models.JSONField(blank=True, help_text='Advance fee config for ADVANCE_FEE', null=True),
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='linked_module',
            field=models.CharField(blank=True, choices=[('SUNDRY_DEBTORS', 'Pending Fees'), ('STAFF_SALARY_ADVANCE', 'Staff Salary Advance'), ('CASH_IN_HAND', 'Cash in Hand'), ('BANK_ACCOUNT', 'Bank Account'), ('ADVANCE_FEE', 'Advance Fee')], help_text='Link this asset to a specific module for tracking.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='opening_balance_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', help_text='Whether the opening balance is a debit or credit entry', max_length=10),
        ),
        migrations.AddField(
            model_name='recoverableasset',
            name='pending_fees_config',
            field=models.JSONField(blank=True, help_text='Fee mapping config for SUNDRY_DEBTORS', null=True),
        ),
    ]
