# Generated by Django 3.2 on 2026-03-30 18:33
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_fields_if_missing(apps, schema_editor):
    field_specs = [
        (
            "finance",
            "RecoverableAsset",
            models.ForeignKey(
                blank=True,
                help_text="Linked salary advance from payroll module",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_salary_advance",
                to="payroll.salaryadvance",
            ),
            "salary_advance",
        ),
        (
            "finance",
            "RecoverableAssetCategory",
            models.CharField(
                choices=[("LIABILITY", "Liability"), ("FIXED_ASSET", "Fixed Asset")],
                default="LIABILITY",
                help_text="Determines which side of the balance sheet this category appears on",
                max_length=20,
            ),
            "balance_sheet_classification",
        ),
        (
            "finance",
            "RecoverableAssetCategory",
            models.ForeignKey(
                blank=True,
                help_text="Financial year this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recoverable_asset_category_financial_year",
                to="institutes.financialyear",
            ),
            "financial_year",
        ),
        (
            "finance",
            "StaffWallet",
            models.CharField(
                default="DEBIT",
                help_text="Whether the opening balance is a debit or credit entry",
                max_length=10,
            ),
            "opening_balance_type",
        ),
        (
            "finance",
            "FeeAdvanceCollectionPaymentDetail",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_advance_collection_payment_detail_fee_advance_collection",
                to="finance.feeadvancecollection",
            ),
            "fee_advance_collection",
        ),
        (
            "finance",
            "FeeAdvanceCollectionPaymentDetail",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_advance_collection_payment_detail_fee_plan",
                to="finance.feeplan",
            ),
            "fee_plan",
        ),
        (
            "finance",
            "FeeAdvanceCollection",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_advance_collection_academic_year",
                to="institutes.academicyear",
            ),
            "academic_year",
        ),
        (
            "finance",
            "FeeAdvanceCollection",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_advance_collection_fee_advance_type",
                to="finance.feeadvancetype",
            ),
            "fee_advance_type",
        ),
        (
            "finance",
            "FeeAdvanceCollection",
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_advance_collection_student",
                to="students.student",
            ),
            "student",
        ),
        (
            "finance",
            "DepositWithdrawRecordDenomination",
            models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.denomination"
            ),
            "denomination",
        ),
        (
            "finance",
            "DepositWithdrawRecordDenomination",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposit_withdraw_record_denomination_deposit_withdraw_record",
                to="finance.depositwithdrawrecord",
            ),
            "deposit_withdraw_record",
        ),
        (
            "finance",
            "BankTransactionDenomination",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transaction_denomination_bank_transaction",
                to="finance.banktransaction",
            ),
            "bank_transaction",
        ),
        (
            "finance",
            "BankTransactionDenomination",
            models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.denomination"
            ),
            "denomination",
        ),
    ]
    for app_label, model_name, field, field_name in field_specs:
        model = apps.get_model(app_label, model_name)
        table_name = model._meta.db_table
        field.set_attributes_from_name(field_name)
        field.model = model

        # Resolve FK string references using the historical apps registry
        if (
            hasattr(field, "remote_field")
            and field.remote_field
            and isinstance(field.remote_field.model, str)
        ):
            ref = field.remote_field.model
            ref_app, ref_model = ref.split(".")
            resolved_model = apps.get_model(ref_app, ref_model)
            field.remote_field.model = resolved_model
            if not field.remote_field.field_name:
                field.remote_field.field_name = resolved_model._meta.pk.name

        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }
        if field.column in columns:
            continue
        schema_editor.add_field(model, field)


def sync_finance_table_names(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    renames = [
        ("balance_sheet_lock_history", "finance_balancesheetlockhistory"),
        ("recoverable_asset_category", "finance_recoverableassetcategory"),
        ("stability_fund_history", "finance_recoverableassethistory"),
    ]
    for old_name, new_name in renames:
        if old_name in existing_tables and new_name not in existing_tables:
            schema_editor.alter_db_table(None, old_name, new_name)
            existing_tables.remove(old_name)
            existing_tables.add(new_name)


def delete_models_safely(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS = 0;")
        # Drop FK constraints that reference finance_financialcategory
        try:
            cursor.execute(
                "ALTER TABLE `finance_recoverableassetcategory` DROP FOREIGN KEY "
                "`recoverable_asset_ca_financial_category_i_32503a9a_fk_finance_f`;"
            )
        except Exception:
            pass
        try:
            cursor.execute(
                "ALTER TABLE `financial_snapshot` DROP FOREIGN KEY "
                "`financial_snapshot_financial_category_i_eefb7880_fk_finance_f`;"
            )
        except Exception:
            pass
        # Drop the tables
        for table in [
            "finance_balancesheetentry",
            "finance_financialcategory",
            "finance_financialsnapshot",
            "financial_snapshot",
        ]:
            cursor.execute(f"DROP TABLE IF EXISTS `{table}`;")
        cursor.execute("SET FOREIGN_KEY_CHECKS = 1;")


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0026_auto_20260330_1833"),
        (
            "staffs",
            "0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting",
        ),
        ("shared", "0048_delete_printdocument"),
        ("students", "0011_idcardupdate_studentidcardupdate"),
        ("payroll", "0006_auto_20260330_1833"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0051_auto_20260330_1833"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    sync_finance_table_names, migrations.RunPython.noop
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="balancesheetlockhistory",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="recoverableassetcategory",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="recoverableassethistory",
                    table=None,
                ),
                migrations.AddField(
                    model_name="recoverableassetcategory",
                    name="balance_sheet_classification",
                    field=models.CharField(
                        choices=[
                            ("LIABILITY", "Liability"),
                            ("FIXED_ASSET", "Fixed Asset"),
                        ],
                        default="LIABILITY",
                        help_text="Determines which side of the balance sheet this category appears on",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="recoverableassetcategory",
                    name="financial_year",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Financial year this category belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recoverable_asset_category_financial_year",
                        to="institutes.financialyear",
                    ),
                ),
                migrations.AddField(
                    model_name="staffwallet",
                    name="opening_balance_type",
                    field=models.CharField(
                        default="DEBIT",
                        help_text="Whether the opening balance is a debit or credit entry",
                        max_length=10,
                    ),
                ),
                migrations.AddField(
                    model_name="feeadvancecollectionpaymentdetail",
                    name="fee_advance_collection",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_advance_collection_payment_detail_fee_advance_collection",
                        to="finance.feeadvancecollection",
                    ),
                ),
                migrations.AddField(
                    model_name="feeadvancecollectionpaymentdetail",
                    name="fee_plan",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_advance_collection_payment_detail_fee_plan",
                        to="finance.feeplan",
                    ),
                ),
                migrations.AddField(
                    model_name="feeadvancecollection",
                    name="academic_year",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_advance_collection_academic_year",
                        to="institutes.academicyear",
                    ),
                ),
                migrations.AddField(
                    model_name="feeadvancecollection",
                    name="fee_advance_type",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_advance_collection_fee_advance_type",
                        to="finance.feeadvancetype",
                    ),
                ),
                migrations.AddField(
                    model_name="feeadvancecollection",
                    name="student",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_advance_collection_student",
                        to="students.student",
                    ),
                ),
                migrations.AddField(
                    model_name="depositwithdrawrecorddenomination",
                    name="denomination",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.denomination",
                    ),
                ),
                migrations.AddField(
                    model_name="depositwithdrawrecorddenomination",
                    name="deposit_withdraw_record",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_withdraw_record_denomination_deposit_withdraw_record",
                        to="finance.depositwithdrawrecord",
                    ),
                ),
                migrations.AddField(
                    model_name="banktransactiondenomination",
                    name="bank_transaction",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transaction_denomination_bank_transaction",
                        to="finance.banktransaction",
                    ),
                ),
                migrations.AddField(
                    model_name="banktransactiondenomination",
                    name="denomination",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.denomination",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_fields_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="recoverableasset",
                    name="salary_advance",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Linked salary advance from payroll module",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recoverable_asset_salary_advance",
                        to="payroll.salaryadvance",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="balancesheetlockhistory",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_sheet_lock_history_financial_year",
                to="institutes.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="bankdetail",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_detail_financial_year",
                to="institutes.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="bankfeetypemapping",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_fee_type_mapping_bank",
                to="finance.bankdetail",
            ),
        ),
        migrations.AlterField(
            model_name="bankfeetypemapping",
            name="fee_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_fee_type_mapping_fee_type",
                to="finance.feetype",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="attachment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction_attachment",
                to="shared.document",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction_bank",
                to="finance.bankdetail",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction_staff",
                to="staffs.staff",
            ),
        ),
        migrations.AlterField(
            model_name="depositwithdrawrecord",
            name="attachment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_withdraw_record_attachment",
                to="shared.document",
            ),
        ),
        migrations.AlterField(
            model_name="depositwithdrawrecord",
            name="bank_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_withdraw_record_bank_from",
                to="finance.bankdetail",
            ),
        ),
        migrations.AlterField(
            model_name="depositwithdrawrecord",
            name="bank_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_withdraw_record_bank_to",
                to="finance.bankdetail",
            ),
        ),
        migrations.AlterField(
            model_name="depositwithdrawrecord",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_withdraw_record_financial_year",
                to="institutes.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="depositwithdrawrecord",
            name="user_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_withdraw_record_user_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="depositwithdrawrecord",
            name="user_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_withdraw_record_user_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recoverableasset",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOAN", "Loan"),
                    ("ADVANCE", "Advance"),
                    ("DEPOSIT", "Deposit"),
                    ("STAFF_SALARY_ADVANCE", "Staff Salary Advance"),
                    ("SUNDRY", "Sundry Debtors"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="recoverableasset",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked bank account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_bank",
                to="finance.bankdetail",
            ),
        ),
        migrations.AlterField(
            model_name="recoverableasset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for grouping and reporting",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recoverable_asset_category",
                to="finance.recoverableassetcategory",
            ),
        ),
        migrations.AlterField(
            model_name="recoverableasset",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recoverableasset",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recoverableassetcategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_category_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recoverableassethistory",
            name="recoverable_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recoverable_asset_history_recoverable_asset",
                to="finance.recoverableasset",
            ),
        ),
        migrations.AlterField(
            model_name="recoverableassethistory",
            name="recoverable_asset_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_history_recoverable_asset_transaction",
                to="finance.recoverableassettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="recoverableassettransaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recoverable_asset_transaction_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recoverableassettransaction",
            name="recoverable_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recoverable_asset_transaction_recoverable_asset",
                to="finance.recoverableasset",
            ),
        ),
        migrations.AlterField(
            model_name="staffwallet",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_wallet_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffwallet",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_wallet_staff",
                to="staffs.staff",
            ),
        ),
        migrations.RunPython(delete_models_safely, migrations.RunPython.noop),
    ]
