# Generated by Django 3.2 on 2026-04-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0052_auto_20260330_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpaymentdetail',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_payment_detail_bank_detail', to='finance.bankdetail'),
        ),
        migrations.AddField(
            model_name='feeadvancecollection',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_advance_collection_bank_detail', to='finance.bankdetail'),
        ),
        migrations.AddField(
            model_name='miscellaneouspayment',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscellaneous_payment_bank_detail', to='finance.bankdetail'),
        ),
    ]
