# Generated by Django 3.2 on 2026-04-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0034_auto_20260410_1235'),
        ('finance', '0053_auto_20260410_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='guest_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscellaneous_guest_standard', to='classes.standard'),
        ),
    ]
