# Generated by Django 3.2 on 2026-05-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_onlinepayment_gateway_response'),
        ('finance', '0054_miscellaneous_guest_standard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceSheetEntry',
        ),
        migrations.DeleteModel(
            name='FinancialCategory',
        ),
        migrations.DeleteModel(
            name='FinancialSnapshot',
        ),
        migrations.RemoveField(
            model_name='feeadvancecollection',
            name='bank_detail',
        ),
        migrations.AddField(
            model_name='applicationpaymentdetail',
            name='online_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_payment_online_payment', to='payments.onlinepayment'),
        ),
        migrations.AddField(
            model_name='applicationplan',
            name='is_academic_year_online_appln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationplan',
            name='online_amount',
            field=models.FloatField(null=True),
        ),
    ]
