# Generated by Django 3.2 on 2023-03-09 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20230309_0410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsold',
            old_name='guest_name',
            new_name='order_num',
        ),
        migrations.RemoveField(
            model_name='itemsold',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemsold',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='itemsold',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='itemsold',
            name='student',
        ),
        migrations.AddField(
            model_name='itemsold',
            name='collected_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_collected_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='fee_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_fee_collection', to='finance.feecollection'),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='payee_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='payment_reference_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='tax_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='total_amount_inc_gst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemsold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StockSellingPriceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_selling_price_track_stock', to='store.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockAvailableBalanceTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('current_available_stock', models.FloatField(default=0)),
                ('updating_stock', models.FloatField(default=0)),
                ('is_stock_increment', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_available_balance_track_stock', to='store.stock')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_available_balance_track_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSoldDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock_after_order', models.FloatField(default=0)),
                ('unit_price', models.FloatField()),
                ('is_item_issued', models.BooleanField(default=1)),
                ('quantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_standard_mapping_item_selling_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_standard_mapping_item_selling_price_fee_stamdard_mapping_item_selling_price', to='finance.feestandardmappingitemsellingprice')),
                ('item_sold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_details_item_sold', to='store.itemsold')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_details_item', to='store.stock')),
            ],
        ),
    ]
