# Generated by Django 3.2 on 2023-04-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230309_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolddetails',
            name='is_item_issued',
        ),
    ]
