# Generated by Django 3.2 on 2023-05-01 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20230430_1730'),
        ('store', '0003_remove_itemsolddetails_is_item_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolddetails',
            name='fee_standard_mapping_item_selling_price',
        ),
        migrations.AddField(
            model_name='itemsold',
            name='is_issued_from_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemsolddetails',
            name='student_store_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_details_student_store_mapping', to='finance.studentstoremapping'),
        ),
    ]
