# Generated by Django 3.2 on 2025-07-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_itemsold_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsold',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ItemSoldModeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_ref_num', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_sold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sold_mode_of_payment_item_sold', to='store.itemsold')),
            ],
        ),
    ]
