data_list = {
    "form_name": "enquiry_form",
    "form_label": "Enquiry Form",
    "request_type": "web",
    "sub_sections": {
        "student_details": {
            "name": "student_details",
            "label": "Student Details",
            "can_hide": "false",
            "hidden": "false",
            "list": [
                {
                    "label": "First Name",
                    "regex": "nameRegex",
                    "name": "first_name",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 50
                },
                {
                    "label": "",
                    "regex": "nameRegex",
                    "name": "middle_name",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 25
                },
                {
                    "label": "",
                    "regex": "nameRegex",
                    "name": "last_name",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 25
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "gender",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "dropDown",
                    "maxLength": 25,
                    "list": [
                        {
                            "name": "Boy",
                            "id": "Boy"
                        },
                        {
                            "name": "Girl",
                            "id": "Girl"
                        }
                    ]
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "dob",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "maxLength": "null",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "date",
                    "helperText": "",
                    "minDate": "minDate",
                    "maxDate": "newDate()"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "mobile_num",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "phone_number"
                },
                {
                    "label": "",
                    "regex": "emailRegex",
                    "name": "email",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "view_className": "text-transform-none"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "entry_academic_year",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "dropDownWithGetRequest",
                    "maxLength": 25,
                    "requestURL": "GET_URL.getstandard.api",
                    "params": [
                        "academic_year"
                    ],
                    "updateListTo": "current_standard",
                    "view_name": "entry_academic_year_value"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "current_standard",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "dropDownWithGetRequest",
                    "maxLength": 25,
                    "parent": "entry_academic_year",
                    "helperText": "Please select academic year to enable standard",
                    "view_name": "current_standard_name"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "enquiry_date",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "newDate()",
                    "rows": "null",
                    "type": "date",
                    "minDate": "lastYearDate()",
                    "maxDate": "newDate()"
                }
            ]
        },
        "parent_details": {
            "name": "parent_details",
            "label": "Parent Details",
            "hidden": "false",
            "can_hide": "false",
            "list": [
                {
                    "label": "",
                    "regex": "nameRegex",
                    "name": "father_name",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 100
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "f_mobile_num",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "phone_number",
                    "maxLength": 25
                },
                {
                    "label": "",
                    "regex": "emailRegex",
                    "name": "f_email",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 25,
                    "view_className": "text-transform-none"
                },
                {
                    "label": "",
                    "regex": "nameRegex",
                    "name": "mother_name",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 100
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "m_mobile_num",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "phone_number",
                    "maxLength": 25
                },
                {
                    "label": "",
                    "regex": "emailRegex",
                    "name": "m_email",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 25,
                    "view_className": "text-transform-none"
                },
                {
                    "label": "",
                    "regex": "nameRegex",
                    "name": "guardian_name",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 100
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "g_mobile_num",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "phone_number",
                    "maxLength": 25
                },
                {
                    "label": "",
                    "regex": "emailRegex",
                    "name": "g_email",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 25,
                    "view_className": "text-transform-none"
                }
            ]
        },
        "pre_school_details": {
            "name": "pre_school_details",
            "label": "Previous School Details",
            "hidden": "false",
            "can_hide": "true",
            "list": [
                {
                    "label": "",
                    "regex": "nameWithQuoteRegex",
                    "name": "school_name",
                    "md": 6,
                    "className": "width-form-95",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 100,
                    "view_className": "text-transform-none"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "school_address",
                    "md": 6,
                    "className": "width-form-95",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 100,
                    "allowDuplicates": "true"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "from_date",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "date",
                    "maxLength": "null",
                    "minDate": "minDate",
                    "maxDate": "newDate()"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "to_date",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "date",
                    "maxLength": "null",
                    "parentMinDate": "from_date",
                    "maxDate": "newDate()"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "school_tc_number",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 25,
                    "allowDuplicates": "true"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "tc_issued_date",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "date",
                    "maxLength": "null",
                    "maxDate": "newDate()"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "left_standard",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "false",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text"
                }
            ]
        },
        "address_details": {
            "name": "address_details",
            "label": "Address Details",
            "hidden": "false",
            "can_hide": "true",
            "list": [
                {
                    "label": "",
                    "regex": "null",
                    "name": "address",
                    "md": 8,
                    "className": "width-form-95",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 100,
                    "view_className": "text-transform-none"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "country",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "null",
                    "rows": "null",
                    "type": "DropDownWithSearch",
                    "view_name": "country_name"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "state",
                    "md": 4,
                    "className": "width-form-90",
                    "parentRequired": "country",
                    "id": "outlined-textarea",
                    "default": "null",
                    "rows": "null",
                    "type": "DropDownWithSearch",
                    "required": "true",
                    "view_name": "state_name"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "district",
                    "md": 4,
                    "className": "width-form-90",
                    "parentRequired": "state",
                    "id": "outlined-textarea",
                    "default": "null",
                    "rows": "null",
                    "type": "DropDownWithSearch",
                    "required": "true",
                    "view_name": "district_name"
                },
                {
                    "label": "",
                    "regex": "null",
                    "name": "city",
                    "md": 4,
                    "className": "width-form-90",
                    "parentRequired": "district",
                    "id": "outlined-textarea",
                    "default": "null",
                    "rows": "null",
                    "type": "DropDownWithSearch",
                    "required": "true",
                    "view_name": "city_name"
                },
                {
                    "label": "",
                    "regex": "pinCodeRegex",
                    "name": "pincode",
                    "md": 4,
                    "className": "width-form-90",
                    "required": "true",
                    "id": "outlined-textarea",
                    "default": "",
                    "rows": "null",
                    "type": "text",
                    "maxLength": 6,
                    "parentRequired": "city"
                }
            ]
        }
    }
}