# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_setting(apps, schema_editor):
        Setting = apps.get_model('shared', 'Setting')
        Setting.objects.bulk_create([
            Setting(name='is_academic_branch_mapping', type='users', value=0, is_active=True,
                    description='0: Standard are normally use 1: Academic year comes under branch'),
            
        ])
        

    dependencies = [
        ('shared', '0015_counter_object_id'),
    ]

    operations = [
        migrations.RunPython(initial_setting)
    ]
