# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def intial_menu_url(apps, schema_editor):
        '''
        We can't import the Post model directly as it may be a newer
        version than this migration expects. We use the historical version.
        '''
        Url = apps.get_model('shared', 'Url')
        url = Url.objects.bulk_create([
            Url(id=1, menu_name='Dashboard'),
            Url(id=2, menu_name='Admin'),
            Url(id=3, menu_name='Customize Menu', path='/admin/customize-menu',
                description='Here we can view the customize menu'),
            Url(id=4, menu_name='Permission Add', path='/admin/permissions/view',
                description='Here we can view the urls')
        ])
        Menu = apps.get_model('shared', 'Menu')
        Menu.objects.bulk_create([
            Menu(id=1, alias_name='Dashboard', parent=0, first_child=0, next_menu=2, is_active=1,
                 new_window=0, menu_type='web', url=url[0]),
            Menu(id=2, alias_name='Admin', parent=0, first_child=3, next_menu=0, is_active=1, new_window=0,
                 menu_type='web', url=url[1]),
            Menu(id=3, alias_name='Customize Menu', parent=2, first_child=0, next_menu=4, is_active=1, new_window=0,
                 menu_type='web', url=url[2]),
            Menu(id=4, alias_name='Permission View', parent=2, first_child=0, next_menu=5, is_active=0, new_window=0,
                 menu_type='web', url=url[3]),
        ])

    def initial_setting(apps, schema_editor):
        Setting = apps.get_model('shared', 'Setting')
        Setting.objects.bulk_create([
            Setting(name='userReportingToForHierarchy', type='users', value=1, is_active=True,
                    description='0: user hierarchy based on roles. 1: user hierarchy based on Reporting user of respective users. 2: get all user under user hierarchy'),
            Setting(name='google_map', type='transport', value=0, is_active=True,
                    description='0: google map is not implemented. 1: google map is implemented'),
            Setting(name='decimal_round_off', type='payroll', value=2, is_active=True,
                    description='If value is 2 then 1.2222 is rounded off to 1.22'),
            Setting(name='unique_reg_num', type='student', value=0, is_active=True,
                    description='0: Student register number is not unique. 1: Student register number is unique.'),
            Setting(name='is_residential', type='institutes', value=0, is_active=True,
                    description='0: School/Student type is Day Scholar. 1: School/Student type is Residential'),
            Setting(name='price_on_area', type='transport', value=0, is_active=True,
                    description='0: Transport price is set on km. 1: Transport price is set on area'),
            Setting(name='subject_assignment', type='classes', value=2, is_active=True,
                    description='0: Each language can have 1 subject with subject selection in admission form. 1: Each language can have multiple subject(s) with subject selection in admission form. 2: Each language can have 1 subject with automatic assignment to student(s).'),
            Setting(name='is_application', type='forms', value=1, is_active=True,
                    description='0: Application form is disabled. 1: Application form is enabled.'),
            Setting(name='admission_in_reg', type='students', value=0, is_active=True,
                    description='0: Admission and register number are different. 1: Admission and register number are same.'),
            Setting(name='number_of_language', type='classes', value=1, is_active=True,
                    description='Number of Language(s) based on value, starts from 0. ex: 1 means 1 language'),
            Setting(name='is_application_auto_approve', type='institutes', value=0, is_active=True,
                    description='When application form is filled from student whether it should be auto approved or not. 1:Auto Approve'),
            Setting(name='payment_gateway_for_application_for_student', type='institutes', value=0, is_active=True,
                    description='Whether student can pay the application fees from payment gateway. 1: Payment gateway enabled. 0: Payment gateway disabled'),
            Setting(name='instant_payout', type='institutes', value='201', is_active=True,
                    description='Instant payout will happend immediately to vendor after the successful payment'),
        ])

    dependencies = [
        ('shared', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(intial_menu_url),
        migrations.RunPython(initial_setting)
    ]
