# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_setting(apps, schema_editor):
        Setting = apps.get_model('shared', 'Setting')
        Setting.objects.bulk_create([
            Setting(name='staffstandardmapping', type='users', value=0, is_active=True,
                    description='0: All staff will be having access to all standards. 1: Staff who have access to the standard can view the standard details'),
            
        ])
        

    dependencies = [
        ('shared', '0003_custom_menu'),
    ]

    operations = [
        migrations.RunPython(initial_setting)
    ]
