# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_setting(apps, schema_editor):
        document_type = apps.get_model('shared', 'DocumentType')
        document_type.objects.bulk_create([
            document_type(name='Birth Certificate'),
            document_type(name='Transfer Certificate'),
            document_type(name='Study Certificate'),
            document_type(name='Blood Group Report'),
            document_type(name='Passport size photo of child'),
            document_type(name='Passport size photo of parents'),
            document_type(name='Aadhar card copy of parents and child'),
            document_type(name='Copies of progress report cards for last 3 years'),
            document_type(name='Passport size photos of parents'),
            document_type(name='Community Certificate: SC/ST or OBC'),
            document_type(name='Transportation Form'),
            document_type(name='Covid Vaccine Certificates of family members'),
        ])
        setting = apps.get_model('shared', 'Setting')
        setting.objects.bulk_create([
            setting(name='studentattendancetype', type='users', value=0, is_active=True,
                    description='0: Session wise attendance 1: Rfid based attendance'),
            
        ])

    dependencies = [
        ('shared', '0005_auto_20220919_0033'),
    ]

    operations = [
        migrations.RunPython(initial_setting)
    ]