# Generated by Django 3.2 on 2022-10-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_custom_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
