# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def inital_formdefintion(apps, schema_editor):
        FormDefinition = apps.get_model('shared', 'FormDefinition')
        FormDefinition.objects.bulk_create([
            FormDefinition(form_name='exam_configurations', column_name='grade_plan', column_alias='used_as_local_page_setting', default_value='1'),
            FormDefinition(form_name='exam_configurations', column_name='cumulative_type', column_alias='used_as_local_page_setting', default_value='1')
        ])

    dependencies = [
        ('shared', '0007_alter_receipt_name'),
    ]

    operations = [
        migrations.RunPython(inital_formdefintion)
    ]
