# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def inital_formdefintion(apps, schema_editor):
        form_definition = apps.get_model('shared', 'FormDefinition')
        form_definition.objects.bulk_create([
            form_definition(form_name='exam_configurations', column_name='merge_subject_for_hallticket', column_alias='used_as_local_page_setting', default_value=0),
        ])

    dependencies = [
        ('shared', '0008_custom_form_definition'),
    ]

    operations = [
        migrations.RunPython(inital_formdefintion)
    ]
