# Generated by Django 3.2 on 2022-11-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_custom_form_definition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='TemplateMapping',
        ),
    ]
