# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def inital_formdefintion(apps, schema_editor):
        form_definition = apps.get_model('shared', 'FormDefinition')
        form_definition.objects.bulk_create([
            form_definition(form_name='exam_configurations', column_name='hide_pass_or_fail', column_alias='used_as_local_page_setting', default_value=0),
            form_definition(form_name='exam_configurations', column_name='resultannouncmentconfigurationwise',
                column_alias='used_as_local_page_setting', default_value=0,
            ),
            form_definition(form_name='alias_name', column_name='part1', column_alias='part 1', default_value=''),
            form_definition(form_name='alias_name', column_name='part2', column_alias='part 2', default_value=''),
        ])

    dependencies = [
        ('shared', '0010_rename_receipt_templatemapping'),
    ]

    operations = [
        migrations.RunPython(inital_formdefintion)
    ]
