# Generated by Django 3.2 on 2023-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_custom_form_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemapping',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
