# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_setting(apps, schema_editor):
        Setting = apps.get_model('shared', 'Setting')
        Setting.objects.bulk_create([
            Setting(name='institute_type', type='users', value=0, is_active=True,
                    description='0: For School, 1: For Diploma, 2: For Engineering'),
            
        ])
        

    dependencies = [
        ('shared', '0012_alter_templatemapping_name'),
    ]

    operations = [
        migrations.RunPython(initial_setting)
    ]
