# Generated by Django 3.2 on 2023-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_custom_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
