# Generated by Django 3.2 on 2023-04-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_formdefinition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
