# Generated by Django 3.2 on 2023-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '00016_custom_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemapping',
            name='no_of_copies',
            field=models.IntegerField(default=1),
        ),
    ]
