# Generated by Django 3.2 on 2023-04-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20230412_0540'),
        ('shared', '0017_templatemapping_no_of_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterStandardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_type_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_standard_mapping', to='classes.standard')),
            ],
            options={
                'unique_together': {('counter_type_name', 'standard', 'is_active')},
            },
        ),
    ]
