# Generated by Django 3.2 on 2023-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0018_counterstandardmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstandardmapping',
            name='postfix_str_for_postfix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counterstandardmapping',
            name='postfix_str_for_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counterstandardmapping',
            name='prefix_str_for_postfix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counterstandardmapping',
            name='prefix_str_for_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
