# Generated by Django 3.2 on 2023-04-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0019_auto_20230418_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstandardmapping',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
