# Generated by Django 3.2 on 2023-05-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20230430_1730'),
        ('shared', '0020_counterstandardmapping_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstandardmapping',
            name='default_postfix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counterstandardmapping',
            name='default_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CounterFeeTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_type_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('prefix_str_for_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('postfix_str_for_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix_str_for_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('postfix_str_for_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('default_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('default_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_fee_type_mapping', to='finance.feetype')),
            ],
            options={
                'unique_together': {('counter_type_name', 'fee_type', 'is_active')},
            },
        ),
    ]
