# Generated by Django 3.2 on 2023-06-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_approvaltransition_groupapprovalhierarchy_userapprovalhierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='request_body',
        ),
        migrations.AddField(
            model_name='logdata',
            name='request_body_new',
            field=models.JSONField(null=True),
        ),
    ]
