# Generated by Django 3.2 on 2023-07-13 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0012_biometricmachine'),
        ('classes', '0015_subjectparttype_code_name'),
        ('shared', '0023_auto_20230605_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateStandardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standard')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_standard_mapping_template', to='shared.templatemapping')),
            ],
        ),
    ]
