# Generated by Django 3.2 on 2023-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0024_templatestandardmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='codename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='codename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='codename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='codename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
