# Generated by Django 3.2 on 2023-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_auto_20230916_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongProcessingApiResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(blank=True)),
                ('api_name', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, null=True)),
                ('execution_started_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_process_running', models.BooleanField(default=False)),
            ],
        ),
    ]
