# Generated by Django 3.2 on 2023-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_feestandardmapping_student_group'),
        ('shared', '0026_longprocessingapiresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterfeetypemapping',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='counterfeetypemapping',
            unique_together={('counter_type_name', 'fee_type', 'is_active', 'mode_of_payment')},
        ),
    ]
