# Generated by Django 3.2 on 2024-01-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_feestandardmapping_student_group'),
        ('shared', '0027_auto_20231218_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatestandardmapping',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feetype'),
        ),
    ]
