# Generated by Django 3.2 on 2024-04-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_templatestandardmapping_fee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=75, null=True)),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('mandatory_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('display_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_app_types', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
