# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_setting(apps, schema_editor):
        ModeOfPayment = apps.get_model('shared', 'ModeOfPayment')
        ModeOfPayment.objects.bulk_create([
            ModeOfPayment(
                label='Cash',
                name='Cash',
                allowed_app_types='staff_web',
                mandatory_fields='',
                display_fields=''
            ),
            ModeOfPayment(
                label='Phone Pe',
                name='PhonePe',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='Google Pay',
                name='Gpay',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='Credit',
                name='Credit',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='Debit',
                name='Debit',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='Cheque',
                name='Cheque',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='Net Banking',
                name='NetBanking',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='UPI Payments',
                name='UPIPayments',
                allowed_app_types='staff_web',
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            ),
            ModeOfPayment(
                label='Online',
                name='Online',
                allowed_app_types=None,
                mandatory_fields='payment_ref_num',
                display_fields='payment_ref_num'
            )
        ])

    dependencies = [
        ('shared', '0029_modeofpayment'),
    ]

    operations = [
        migrations.RunPython(initial_setting)
    ]
