# Generated by Django 3.2 on 2024-04-30 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_feecategory_feecategoryfeestandardsectionmapping'),
        ('classes', '0019_auto_20240325_1239'),
        ('shared', '0030_custom_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.CreateModel(
            name='CounterStandardSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_type_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('prefix_str_for_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('postfix_str_for_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix_str_for_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('postfix_str_for_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('default_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_standard_section_mapping_fee_type', to='finance.feetype')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_standard_section_mapping_standard_section', to='classes.standardsectionmapping')),
            ],
            options={
                'unique_together': {('counter_type_name', 'standard_section', 'is_active')},
            },
        ),
    ]
