# Generated by Django 3.2 on 2024-05-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0031_auto_20240430_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeofpayment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modeofpayment',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
