# Generated by Django 3.2 on 2024-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0032_auto_20240504_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='menu_type',
            field=models.CharField(blank=True, default='web', max_length=255, null=True),
        ),
    ]
