# Generated by Django 3.2 on 2024-07-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0033_url_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionIdTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
