# Generated by Django 3.2 on 2024-06-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0034_transactionidtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='documenttype',
            name='group_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.grouptype'),
        ),
        migrations.AddField(
            model_name='templatestandardmapping',
            name='multiple_template_no',
            field=models.IntegerField(null=True),
        ),
    ]
