# Generated by Django 2.2.24 on 2021-08-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    def initial_group_type(apps, schema_editor):
        GroupType = apps.get_model('shared', 'GroupType')
        GroupType.objects.bulk_create([
            GroupType(id=1, name=u'Teaching'),
            GroupType(id=2, name=u'NonTeaching'),
        ])
    dependencies = [
        ('shared', '0035_auto_20240629_1748'),
    ]

    operations = [
        migrations.RunPython(initial_group_type)
    ]
