# Generated by Django 3.2 on 2024-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_custom_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='group_type',
            field=models.CharField(blank=True, default='1', max_length=255, null=True),
        ),
    ]
