# Generated by Django 3.2 on 2024-08-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0035_feestandardmapping_receipt_alias'),
        ('general', '0007_longprocessingapiresult'),
        ('shared', '0037_alter_documenttype_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterMiscTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_type_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online')], max_length=20, null=True)),
                ('prefix_str_for_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('postfix_str_for_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix_str_for_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('postfix_str_for_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('default_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('default_postfix', models.CharField(blank=True, max_length=255, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('misc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_misc_type_mapping', to='finance.miscellaneoustype')),
            ],
            options={
                'unique_together': {('counter_type_name', 'misc_type', 'is_active', 'mode_of_payment')},
            },
        ),
        migrations.CreateModel(
            name='CustomDownloadTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LongProcessingAPIResultMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('long_processing_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_processing_api_result_report_mapping_long_processing_api', to='general.longprocessingapiresult')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('process_hook', models.CharField(max_length=255)),
                ('process_function', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.IntegerField(default=0)),
                ('email_template', models.CharField(max_length=255, null=True)),
                ('push_template', models.CharField(max_length=255, null=True)),
                ('sms_template', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('column_alias', models.CharField(max_length=255)),
                ('formate_type', models.CharField(max_length=255)),
                ('is_default_selected', models.BooleanField(default=False)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_column_report_name', to='shared.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDocumentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_document_mapping_document', to='shared.document')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_document_mapping_report', to='shared.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
                ('filter_alias', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_default_selected', models.BooleanField(default=False)),
                ('filter_data_type', models.IntegerField(default=0)),
                ('filter_seleted_values', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_filter_report_name', to='shared.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportsubcategory_reportcategory', to='shared.reportcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('calculation_type', models.CharField(max_length=255)),
                ('report_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_summary_report_column', to='shared.reportcolumn')),
            ],
        ),
        migrations.CreateModel(
            name='SheetClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('sheet_alias', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TabClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=255)),
                ('tab_alias', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LongProcessingApiResult',
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_column_sheet_name', to='shared.sheetclassification'),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_column_tab_name', to='shared.tabclassification'),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_reportcategory', to='shared.reportcategory'),
        ),
        migrations.AddField(
            model_name='report',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_reportsubcategory', to='shared.reportsubcategory'),
        ),
    ]
