# Generated by Django 3.2 on 2024-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0038_auto_20240819_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='supported_doc_formate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
