# Generated by Django 3.2 on 2025-11-18 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0030_auto_20251010_1108'),
        ('institutes', '0022_custom_resource_migrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0040_custom_staff_app_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_data', models.JSONField(help_text='Stores the template design structure (droppedItems, pageSize, etc.)')),
                ('sample_data', models.JSONField(blank=True, help_text='Sample student mark data used for design', null=True)),
                ('api_config', models.JSONField(blank=True, help_text='API configuration: endpoint, exam, standard_section, student_ids', null=True)),
                ('module', models.CharField(default='marks_card', help_text='Module name (e.g., marks_card)', max_length=100)),
                ('template_type', models.CharField(default='pdf', help_text='Template type: pdf or html', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_predefined', models.BooleanField(default=False, help_text='True for system templates, False for user-created templates')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_templates', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(blank=True, help_text='Null for predefined templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_design_templates', to='institutes.institute')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standard')),
            ],
            options={
                'verbose_name': 'Custom Design Template',
                'verbose_name_plural': 'Custom Design Templates',
                'db_table': 'custom_design_template',
                'ordering': ['-created'],
            },
        ),
    ]
