# Generated by Django 3.2 on 2025-11-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_customdesigntemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDesignTemplate',
        ),
    ]
