# Generated by Django 3.2 on 2026-01-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0043_customdesigntemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroupHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('heading_alias', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_alias', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_group_name_report', to='shared.report')),
                ('report_group_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_group_name_report_group_heading', to='shared.reportgroupheading')),
            ],
        ),
        migrations.CreateModel(
            name='ReportGroupNameValuesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('report_group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_group_name_values_mapping_report_group_name', to='shared.reportgroupname')),
            ],
        ),
    ]
