# Generated by Django 3.2 on 2026-01-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shared', '0044_reportgroupheading_reportgroupname_reportgroupnamevaluesmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.FloatField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='logdata',
            name='action',
            field=models.CharField(blank=True, help_text='Action type: CREATE, UPDATE, DELETE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The model/table that was modified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='logdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='new_data',
            field=models.JSONField(blank=True, help_text='Data after the change', null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='object_id',
            field=models.CharField(blank=True, help_text='The primary key of the modified object', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='previous_data',
            field=models.JSONField(blank=True, help_text='Data before the change', null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='related_changes',
            field=models.JSONField(blank=True, help_text='Changes to related models: [{"model": "ModelName", "object_id": "1", "action": "CREATE/UPDATE/DELETE", "previous_data": {...}, "new_data": {...}}]', null=True),
        ),
    ]
