# Generated by Django 3.2 on 2026-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_auto_20260123_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='custom_calculation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
