# Generated by Django 3.2 on 2026-03-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0046_auto_20260209_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSampleJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_data', models.JSONField(help_text='Stores the template design structure (droppedItems, pageSize, etc.)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Sample Json',
                'verbose_name_plural': 'Template Sample Jsons',
                'db_table': 'template_sample',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CustomDesignTemplateMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique name to identify the design mapping', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_maps', to='shared.customdesigntemplate')),
            ],
            options={
                'verbose_name': 'Custom Design Template Map',
                'verbose_name_plural': 'Custom Design Template Maps',
                'db_table': 'custom_design_template_map',
                'ordering': ['key'],
            },
        ),
    ]
