# Generated by Django 3.2 on 2026-03-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0047_customdesigntemplatemap_templatesamplejson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintDocument',
        ),
    ]
