# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemployeeplan',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_salary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeplan',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_component', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salaryemployeeplan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_staff_account', to='staffs.accountdetail'),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_component', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_staff', to='staffs.staff'),
        ),
    ]
