# Generated by Django 2.2.24 on 2021-08-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    def initial_salary_component(apps, schema_editor):
        SalaryComponent = apps.get_model('payroll', 'SalaryComponent')
        SalaryComponent.objects.bulk_create([
            SalaryComponent(name='Loss Of Pay', codename='lop', is_active=True, is_deduction=True)
        ])

    dependencies = [
        ('payroll', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(initial_salary_component),
    ]
