# Generated by Django 3.2 on 2023-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_lop_salary_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryemployeeplan',
            name='is_fixed_deduction',
            field=models.BooleanField(default=False),
        ),
    ]
