# Generated by Django 3.2 on 2026-03-04 21:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting'),
        ('institutes', '0025_auto_20260225_2054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0004_salaryemployeeplan_is_fixed_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ATTENDANCE_INIT', 'Attendance Initialized'), ('ATTENDANCE_UPDATE', 'Attendance Updated'), ('SALARY_GENERATED', 'Salary Generated'), ('SALARY_REGENERATED', 'Salary Regenerated'), ('SETUP_CREATED', 'Salary Setup Created'), ('SETUP_UPDATED', 'Salary Setup Updated'), ('SETUP_DELETED', 'Salary Setup Deleted')], max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.JSONField(blank=True, help_text='Previous values before change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New values after change', null=True)),
                ('performed_by', models.CharField(help_text='Username who performed the action', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollFormulaAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATE', 'Generate Single'), ('GENERATE_BULK', 'Generate Bulk'), ('LOCK', 'Lock Month'), ('OVERRIDE', 'Override'), ('INCREMENT', 'Increment'), ('BONUS', 'Bonus'), ('SEED_PRESET', 'Seed Preset')], max_length=50)),
                ('salary_month', models.DateField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryEmployeeIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('increment_type', models.CharField(choices=[('INCREMENT', 'Salary Increment'), ('BONUS', 'One-time Bonus')], default='INCREMENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_mode', models.CharField(choices=[('AMOUNT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='AMOUNT', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage value when calculation_mode is PERCENTAGE', max_digits=6, null=True)),
                ('old_gross', models.DecimalField(blank=True, decimal_places=2, help_text='Staff gross salary before this increment', max_digits=12, null=True)),
                ('new_gross', models.DecimalField(blank=True, decimal_places=2, help_text='Staff gross salary after this increment', max_digits=12, null=True)),
                ('bonus_name', models.CharField(blank=True, help_text='Name/title of the bonus (for BONUS type)', max_length=255, null=True)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('applied', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', 'staff_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryEmployeeOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('salary_year', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_month', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-salary_year', '-salary_month', 'staff_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='SalaryFormulaRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENT', 'Percentage of Component'), ('REMAINING', 'Remaining Amount'), ('EXPRESSION', 'Custom Expression')], default='FIXED', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expression', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['formula', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='StaffMonthlyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(help_text='1 = Jan, 12 = Dec')),
                ('working_days', models.PositiveIntegerField(help_text='Total working days in the month (auto-calculated)')),
                ('present_days', models.PositiveIntegerField(help_text='Days present (defaults to working_days, editable)')),
                ('is_finalized', models.BooleanField(default=False, help_text='True after salary generation - attendance becomes read-only')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['staff_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMonthlySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(help_text='1 = Jan, 12 = Dec')),
                ('working_days', models.PositiveIntegerField()),
                ('present_days', models.PositiveIntegerField()),
                ('gross_salary', models.PositiveIntegerField()),
                ('hra', models.PositiveIntegerField()),
                ('ba', models.PositiveIntegerField()),
                ('da', models.PositiveIntegerField()),
                ('ba_da', models.PositiveIntegerField()),
                ('other_allowance', models.PositiveIntegerField(default=0)),
                ('pf', models.PositiveIntegerField()),
                ('esic', models.PositiveIntegerField(default=0)),
                ('pt', models.PositiveIntegerField(default=0)),
                ('lic', models.PositiveIntegerField(default=0)),
                ('total_deduction', models.PositiveIntegerField()),
                ('net_salary', models.PositiveIntegerField()),
                ('account_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'staff_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalarySetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_category', models.CharField(choices=[('SCHOOL', 'School'), ('PU_COLLEGE', 'PU College'), ('DEGREE_COLLEGE', 'Degree College'), ('MCOM', 'M.Com')], default='SCHOOL', help_text='Staff belongs to which institution/department', max_length=20)),
                ('gross_salary', models.PositiveIntegerField(help_text='Monthly gross salary')),
                ('esic_opted', models.BooleanField(default=False, help_text='Whether ESIC is applicable for this staff')),
                ('lic_amount', models.PositiveIntegerField(default=0, help_text='Fixed LIC deduction amount')),
                ('account_number', models.CharField(help_text='Bank account number for salary credit', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['staff_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_plan_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='formula_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='formula_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='lop_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_plan_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeplan',
            name='use_formula',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryplan',
            name='use_formula',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['codename'], name='payroll_sal_codenam_ce121a_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryemployeemonthplan',
            index=models.Index(fields=['salary_month'], name='payroll_sal_salary__9a3f32_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryemployeemonthplan',
            index=models.Index(fields=['staff', 'salary_month'], name='payroll_sal_staff_i_53c7ec_idx'),
        ),
        migrations.AddField(
            model_name='staffmonthlysalary',
            name='salary_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_salaries', to='payroll.staffsalarysetup'),
        ),
        migrations.AddField(
            model_name='staffmonthlyattendance',
            name='salary_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_attendances', to='payroll.staffsalarysetup'),
        ),
        migrations.AddField(
            model_name='salaryformularule',
            name='base_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_rules', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salaryformularule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryformularule',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.salaryformula'),
        ),
        migrations.AddField(
            model_name='salaryformularule',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryformularule',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rules', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salaryformula',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_formulas', to='institutes.financialyear'),
        ),
        migrations.AddField(
            model_name='salaryemployeeoverride',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_override_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_override_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeoverride',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_override_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeoverride',
            name='month_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='payroll.salaryemployeemonthplan'),
        ),
        migrations.AddField(
            model_name='salaryemployeeoverride',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_overrides', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salaryemployeeoverride',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_overrides', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='salaryemployeeincrement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increment_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeincrement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeincrement',
            name='employee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments', to='payroll.salaryemployeeplan'),
        ),
        migrations.AddField(
            model_name='salaryemployeeincrement',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryemployeeincrement',
            name='new_employee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increment_sources', to='payroll.salaryemployeeplan'),
        ),
        migrations.AddField(
            model_name='salaryemployeeincrement',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_increments', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='payrollformulaauditlog',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payroll.salaryformula'),
        ),
        migrations.AddField(
            model_name='payrollformulaauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollformulaauditlog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_audit_logs', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='payrollauditlog',
            name='monthly_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payroll.staffmonthlyattendance'),
        ),
        migrations.AddField(
            model_name='payrollauditlog',
            name='monthly_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payroll.staffmonthlysalary'),
        ),
        migrations.AddField(
            model_name='payrollauditlog',
            name='salary_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payroll.staffsalarysetup'),
        ),
        migrations.AddField(
            model_name='salaryemployeemonthplan',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_plans', to='payroll.salaryformula'),
        ),
        migrations.AddField(
            model_name='salaryemployeeplan',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_plan_formula', to='payroll.salaryformula'),
        ),
        migrations.AddField(
            model_name='salaryplan',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_plan_formula', to='payroll.salaryformula'),
        ),
        migrations.AlterUniqueTogether(
            name='staffmonthlysalary',
            unique_together={('salary_setup', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='staffmonthlyattendance',
            unique_together={('salary_setup', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryformula',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryemployeeoverride',
            unique_together={('staff', 'salary_year', 'salary_month', 'salary_component')},
        ),
        migrations.AddIndex(
            model_name='payrollauditlog',
            index=models.Index(fields=['action', 'created_at'], name='payroll_pay_action_4b0a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollauditlog',
            index=models.Index(fields=['year', 'month'], name='payroll_pay_year_20295d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollauditlog',
            index=models.Index(fields=['performed_by'], name='payroll_pay_perform_30cf25_idx'),
        ),
    ]
