# Generated by Django 3.2 on 2026-03-30 18:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0026_auto_20260330_1833'),
        ('payroll', '0005_auto_20260304_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total advance/loan amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_balance_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', help_text='Whether the opening balance is a debit or credit entry', max_length=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly recovery amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_month', models.DateField(blank=True, help_text='Recovery starts from this month', null=True)),
                ('tenure_months', models.PositiveIntegerField(blank=True, help_text='Tenure in months', null=True)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, help_text='EMI amount for loan type', max_digits=15, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate percentage', max_digits=5)),
                ('interest_type', models.CharField(choices=[('NONE', 'No Interest'), ('SIMPLE', 'Simple Interest'), ('COMPOUND', 'Compound Interest')], default='NONE', max_length=10)),
                ('auto_deduct_from_payroll', models.BooleanField(default=False)),
                ('deduction_priority', models.PositiveIntegerField(default=1)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20)),
                ('closure_reason', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('NORMAL_RECOVERY', 'Fully Recovered'), ('WRITE_OFF', 'Written Off'), ('SETTLEMENT', 'Settled')], default='', max_length=20)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advance_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advance_created_by', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_financial_year', to='institutes.financialyear')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_staff', to='staffs.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advance_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvanceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('ADVANCE', 'Advance'), ('RECOVERY', 'Recovery'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST', 'Interest Charge'), ('PENALTY', 'Late Payment Penalty'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('PAYROLL', 'Payroll'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST_CALC', 'Interest Calculation'), ('PENALTY_CALC', 'Penalty Calculation')], default='MANUAL', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment_reason', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('WRITE_OFF', 'Write-off'), ('SETTLEMENT', 'Settlement'), ('CORRECTION', 'Correction'), ('WAIVER', 'Interest/Penalty Waiver')], default='', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advance_transaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('salary_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_transaction_salary_advance', to='payroll.salaryadvance')),
            ],
            options={
                'verbose_name': 'Salary Advance Transaction',
                'verbose_name_plural': 'Salary Advance Transactions',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffManualAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.DateField(help_text='First day of the month (e.g. 2026-03-01)')),
                ('working_days', models.PositiveIntegerField(help_text='Total working days in the month')),
                ('present_days', models.FloatField(help_text='Days present (can be fractional for half-days)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_manual_attendance_staff', to='staffs.staff')),
            ],
            options={
                'ordering': ['staff', '-salary_month'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='staffmonthlyattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffmonthlyattendance',
            name='salary_setup',
        ),
        migrations.AlterUniqueTogether(
            name='staffmonthlysalary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffmonthlysalary',
            name='salary_setup',
        ),
        migrations.AlterField(
            model_name='payrollformulaauditlog',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_formula_audit_log_formula', to='payroll.salaryformula'),
        ),
        migrations.AlterField(
            model_name='payrollformulaauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_formula_audit_log_performed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollformulaauditlog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_formula_audit_log_staff', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeincrement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_increment_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeincrement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_increment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeincrement',
            name='employee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_increment_employee_plan', to='payroll.salaryemployeeplan'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeincrement',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_increment_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeincrement',
            name='new_employee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_increment_new_employee_plan', to='payroll.salaryemployeeplan'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeincrement',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_increment_staff', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_plan_account', to='staffs.accountdetail'),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_plan_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_plan_formula', to='payroll.salaryformula'),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_plan_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_plan_salary_component', to='payroll.salarycomponent'),
        ),
        migrations.AlterField(
            model_name='salaryemployeemonthplan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_month_plan_staff', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeoverride',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_override_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_override_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeoverride',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_override_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeoverride',
            name='month_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_override_month_plan', to='payroll.salaryemployeemonthplan'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeoverride',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_override_salary_component', to='payroll.salarycomponent'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeoverride',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_override_staff', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeplan',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_plan_approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryemployeeplan',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_plan_salary_component', to='payroll.salarycomponent'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeplan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_employee_plan_staff', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='salaryformula',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_formula_financial_year', to='institutes.financialyear'),
        ),
        migrations.AlterField(
            model_name='salaryformularule',
            name='base_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_formula_rule_base_component', to='payroll.salarycomponent'),
        ),
        migrations.AlterField(
            model_name='salaryformularule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_formula_rule_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryformularule',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_formula_rule_formula', to='payroll.salaryformula'),
        ),
        migrations.AlterField(
            model_name='salaryformularule',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_formula_rule_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryformularule',
            name='salary_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_formula_rule_salary_component', to='payroll.salarycomponent'),
        ),
        migrations.DeleteModel(
            name='PayrollAuditLog',
        ),
        migrations.DeleteModel(
            name='StaffMonthlyAttendance',
        ),
        migrations.DeleteModel(
            name='StaffMonthlySalary',
        ),
        migrations.DeleteModel(
            name='StaffSalarySetup',
        ),
        migrations.AddIndex(
            model_name='staffmanualattendance',
            index=models.Index(fields=['salary_month'], name='payroll_sta_salary__5fb6b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffmanualattendance',
            unique_together={('staff', 'salary_month')},
        ),
    ]
