# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_subjectstudent_academic_year'),
        ('shared', '0001_initial'),
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectstudent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_student', to='classes.subject'),
        ),
        migrations.AddField(
            model_name='subjectbranchmapping',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_branch_mapping_branch', to='classes.branch'),
        ),
        migrations.AddField(
            model_name='subjectbranchmapping',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_branch_mapping_subject', to='classes.subject'),
        ),
        migrations.AddField(
            model_name='studentstandardmapping',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='studentstandardmapping',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_standard', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='studentstandardmapping',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='standardsectionmapping',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_section', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='standardsectionmapping',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='classes.section'),
        ),
        migrations.AddField(
            model_name='standardsectionmapping',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_standard', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='standard',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_board', to='classes.board'),
        ),
        migrations.AddField(
            model_name='standard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_branch', to='classes.branch'),
        ),
        migrations.AddField(
            model_name='promotestudent',
            name='from_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_academic_year_id', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='promotestudent',
            name='from_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_standard_id', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='promotestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='promotestudent',
            name='to_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_academic_year_id', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='promotestudent',
            name='to_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_standard_id', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='machineattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_attendance_academic_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='machineattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_attendance_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='instituteadresses',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_address_instiute', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='instituteadresses',
            name='map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_address_data', to='shared.mapaddress'),
        ),
        migrations.AddField(
            model_name='instituteadresses',
            name='standard',
            field=models.ManyToManyField(blank=True, related_name='institute_address_standard', to='classes.Standard'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignsubject',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_subjects', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='assignsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignsubject', to='classes.subject'),
        ),
    ]
