# Generated by Django 2.2.24 on 2021-08-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    def initial_standards(apps, schema_editor):
        Standard = apps.get_model('classes', 'Standard')
        Standard.objects.bulk_create([
            Standard(id='1', name='Passed out', codename='passedout', sequence=1),
            Standard(id='2', name='Failed', codename='failed', sequence=2),
            Standard(id='3', name='Pre-KG', codename='prekg', sequence=48),
            Standard(id='4', name='LKG', codename='lkg', sequence=49),
            Standard(id='5', name='UKG', codename='ukg', sequence=50),
            Standard(id='6', name='Standard 1', codename='standard1', sequence=51),
            Standard(id='7', name='Standard 2', codename='standard2', sequence=52),
            Standard(id='8', name='Standard 3', codename='standard3', sequence=53),
            Standard(id='9', name='Standard 4', codename='standard4', sequence=54),
            Standard(id='10', name='Standard 5', codename='standard5', sequence=55),
            Standard(id='11', name='Standard 6', codename='standard6', sequence=56),
            Standard(id='12', name='Standard 7', codename='standard7', sequence=57),
            Standard(id='13', name='Standard 8', codename='standard8', sequence=58),
            Standard(id='14', name='Standard 9', codename='standard9', sequence=59),
            Standard(id='15', name='Standard 10', codename='standard10', sequence=60),
            Standard(id='16', name='Standard 11', codename='standard11', sequence=61),
            Standard(id='17', name='Standard 12', codename='standard12', sequence=62),
        ])

    dependencies = [
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(initial_standards)
    ]