# Generated by Django 3.2 on 2022-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_custom_standard_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteadresses',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
