# Generated by Django 3.2 on 2022-10-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_instituteadresses_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
