# Generated by Django 3.2 on 2022-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_cumulativetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='part_type',
            field=models.CharField(blank=True, choices=[('part1', 'part1'), ('part2', 'part2')], default='part1', max_length=6, null=True),
        ),
    ]
