# Generated by Django 3.2 on 2023-01-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_subject_part_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='part_type',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_part_type', to='classes.subjectparttype'),
        ),
    ]
