# Generated by Django 3.2.24 on 2023-01-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    def initial_part_type(apps, schema_editor):
        SubjectPartType = apps.get_model('classes', 'SubjectPartType')
        SubjectPartType.objects.bulk_create([
            SubjectPartType(id=1, name='Part 1'),
            SubjectPartType(id=2, name='Part 2'),
        ])

    dependencies = [
        ('classes', '0008_auto_20230129_1620'),
    ]

    operations = [
        migrations.RunPython(initial_part_type)
    ]