# Generated by Django 3.2 on 2023-01-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_custom_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_part_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_part_type', to='classes.subjectparttype'),
        ),
    ]