# Generated by Django 3.2 on 2023-04-12 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_is_new_student'),
        ('institutes', '0009_academicyearbranchmapping'),
        ('classes', '0010_alter_subject_subject_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstandardmapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentstandardmapping',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentTcIssuedTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_tc_issued_track_academic_year', to='institutes.academicyear')),
                ('issued_for_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tc_issued_track_current_standard', to='classes.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tc_issued_track_student', to='students.student')),
            ],
        ),
    ]
