# Generated by Django 3.2 on 2023-07-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_attendance_marked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineattendancefailedtosavedata',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
    ]
