# Generated by Django 3.2 on 2023-07-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0012_biometricmachine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0013_machineattendancefailedtosavedata_is_data_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineattendancefailedtosavedata',
            name='machine_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineattendancefailedtosavedata',
            name='operation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machineattendancelog',
            name='machine_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MachineUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_user_id', models.IntegerField()),
                ('is_user_updated_to_machine', models.BooleanField(default=False)),
                ('username_in_machine', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('biometric_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_user_mapping_biometric_machine', to='institutes.biometricmachine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_machine_mapping_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MachineUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_user_id', models.IntegerField(default=True, null=True)),
                ('template', models.JSONField(null=True)),
                ('is_data_processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_user_log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
