# Generated by Django 3.2 on 2023-07-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20230710_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectparttype',
            name='code_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
