# Generated by Django 3.2 on 2023-07-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_subjectparttype_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineattendancefailedtosavedata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
