# Generated by Django 3.2 on 2023-08-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_machineattendancefailedtosavedata_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineuserlog',
            name='operation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
