# Generated by Django 3.2 on 2024-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_machineuserlog_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstandardmapping',
            name='is_new_student',
            field=models.BooleanField(default=False),
        ),
    ]
