# Generated by Django 3.2 on 2024-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_studentstandardmapping_is_new_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineattendance',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineattendance',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineattendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('halfday', 'halfday'), ('late', 'late'), ('lateandhalfday', 'lateandhalfday'), ('halfdaylate', 'halfdaylate'), ('unmarked', 'unmarked'), ('checkinmarked', 'checkinmarked'), ('halfdayandlate', 'halfdayandlate'), ('timenotassigned', 'timenotassigned'), ('nonworkingday', 'nonworkingday'), ('first_ses_leave_sec_sess_half', 'first_ses_leave_sec_sess_half'), ('first_ses_half_sec_sess_leave', 'first_ses_half_sec_sess_leave'), ('holiday', 'holiday'), ('leave_applied', 'leave_applied')], max_length=30),
        ),
    ]
