# Generated by Django 3.2 on 2024-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_auto_20240325_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='course_period',
            field=models.IntegerField(null=True),
        ),
    ]
