# Generated by Django 3.2 on 2024-09-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0039_report_supported_doc_formate'),
        ('institutes', '0015_auto_20240818_2124'),
        ('classes', '0020_standard_course_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeStandardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_type_standard_mapping_academic_year', to='institutes.academicyear')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_standard_mapping_document_type', to='shared.documenttype')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_standard_mapping_standard', to='classes.standard')),
            ],
        ),
    ]
