# Generated by Django 3.2 on 2024-12-18 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20240709_1301'),
        ('students', '0010_auto_20240730_1717'),
        ('hr', '0013_alter_staffattendance_status'),
        ('institutes', '0016_institutepocmapping'),
        ('shared', '0040_custom_staff_app_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0022_auto_20241107_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveTypeAcademicYearMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_leave_num', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_leave_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_forward_num', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assigned_globaly', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.academicyear')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.studentleavetype')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('from_time', models.DateTimeField(blank=True, null=True)),
                ('to_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_marked_by', to=settings.AUTH_USER_MODEL)),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_attendance_standard_section', to='classes.standardsectionmapping')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_student', to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_subject', to='classes.subject')),
                ('timetable_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendence_timetable_schedule', to='hr.timetableschedule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('leave_type_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leave_type_academic_year_mapping_leave_type_map', to='classes.studentleavetypeacademicyearmapping')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leave_type_mapping_student', to='classes.studentleavetype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_to_apply', models.CharField(max_length=255, null=True)),
                ('apply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('NotApproved', 'NotApproved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='NotApproved', max_length=15, null=True)),
                ('applied_from_date', models.DateField()),
                ('applied_to_date', models.DateField()),
                ('cancel_reject_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leaves_approvedby', to='staffs.staff')),
                ('attach_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shared.document')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.studentleavetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fordate', models.DateField()),
                ('session', models.CharField(choices=[('Session1', 'Session1'), ('Session2', 'Session2')], max_length=10)),
                ('student_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_leave_date_student_leave', to='classes.studentleaves')),
            ],
            options={
                'ordering': ['fordate', 'session'],
            },
        ),
        migrations.CreateModel(
            name='StaffStandardSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_standard_section_mapping_staff', to='staffs.staff')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_standard_section_mapping_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
    ]
