# Generated by Django 3.2 on 2025-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_staffstandardsectionmapping_studentleavedates_studentleaves_studentleavetype_studentleavetypeacademi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffstandardsectionmapping',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffstandardsectionmapping',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
