# Generated by Django 3.2 on 2025-04-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20240730_1717'),
        ('classes', '0024_auto_20250324_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstandardmapping',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_standard_mapping_student_group', to='students.studentgroup'),
        ),
    ]
