# Generated by Django 2.2.24 on 2021-08-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    def initial_student_group(apps, schema_editor):
        Student = apps.get_model('students','Student')
        Student = Student.objects.all()
        StudentStandardMapping = apps.get_model('classes', 'StudentStandardMapping')
        for student in Student:
            StudentStandardMapping.objects.filter(student_id=student.id).update(student_group_id = student.student_group_id)

    dependencies = [
        ('classes', '0025_studentstandardmapping_student_group'),
    ]

    operations = [
        migrations.RunPython(initial_student_group)
    ]
