# Generated by Django 3.2 on 2025-07-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0018_auto_20250509_1728'),
        ('hr', '0013_alter_staffattendance_status'),
        ('students', '0010_auto_20240730_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0026_custom_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('code', models.CharField(max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_batch_academic_year', to='institutes.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='period_day_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_period_day_mapping', to='hr.perioddaymapping'),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StandardAttendanceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.IntegerField(default=True, null=True)),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_attendance_configuration_standard', to='classes.standard')),
            ],
        ),
        migrations.CreateModel(
            name='BatchAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attendance_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_attendance_attendance_batch', to='classes.attendancebatch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_attendance_marked_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_attendance_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceBatchStudentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_batch_student_mapping_attendance_batch', to='classes.attendancebatch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_batch_student_mapping_student', to='students.student')),
            ],
        ),
    ]
