# Generated by Django 3.2 on 2025-09-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_staff_blood_group'),
        ('classes', '0027_auto_20250712_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSpecificOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCourseOutcomeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('target', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_mapping_course_outcome', to='classes.courseoutcome')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_mapping_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeachingHourMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_type', models.IntegerField(blank=True, default=0, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teaching_hour_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSubjectTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.IntegerField(blank=True, default=0, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_subject_type_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectProgramSpecificOutcomeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('program_specific_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_program_specific_outcome_mapping_program_specific_outcome', to='classes.programspecificoutcome')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_program_specific_outcome_mapping_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectProgramOutcomeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('program_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_program_outcome_mapping_program_outcome', to='classes.programoutcome')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_program_outcome_mapping_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.IntegerField(blank=True, default=0, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_exam_details_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_details_subject', to='classes.subject')),
                ('subject_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_details_subject_category', to='classes.subjectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCourseOutcomeProgramSpecificOutcomeMappingMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject_course_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_program_specific_mapping_matrix_subject_course_outcome', to='classes.subjectcourseoutcomemapping')),
                ('subject_program_specific_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_program_specific_mapping_matrix_subject_program_specific_outcome', to='classes.subjectprogramspecificoutcomemapping')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCourseOutcomeProgramMappingMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject_course_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_program_mapping_matrix_subject_course_outcome', to='classes.subjectcourseoutcomemapping')),
                ('subject_program_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_program_mapping_matrix_subject_program_outcome', to='classes.subjectprogramoutcomemapping')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSubjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=255)),
                ('teaching_pedagogy', models.CharField(max_length=255)),
                ('credit', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_subject_details_subject', to='classes.subject')),
            ],
        ),
    ]
