# Generated by Django 3.2 on 2025-10-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0028_courseoutcome_programoutcome_programspecificoutcome_staffsubjectdetails_subjectcategory_subjectcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEducationalObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectProgramEducationalObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('program_educational_objectives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_program_educational_objectives_mapping_program_educational_objectives', to='classes.programeducationalobjectives')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_program_educational_objectives_mapping_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCourseOutcomeProgramEducationalObjectivesMappingMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject_course_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_subject_program_educational_objectives_matrix_subject_course_outcome', to='classes.subjectcourseoutcomemapping')),
                ('subject_program_educational_objectives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_course_outcome_subject_program_educational_objectives_matrix_subject_subject_program_educational_objectives', to='classes.subjectprogrameducationalobjectives')),
            ],
        ),
    ]
