# Generated by Django 3.2 on 2025-10-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_programeducationalobjectives_subjectcourseoutcomeprogrameducationalobjectivesmappingmatrix_subjectpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancebatch',
            name='batch_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendancebatch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancebatch',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceBatchStandardSectionSubjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_batch_attendance_batch_standard_section_subject_mapping', to='classes.attendancebatch')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_section_attendance_batch_standard_section_subject_mapping', to='classes.standardsectionmapping')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_attendance_batch_standard_section_subject_mapping', to='classes.subject')),
            ],
        ),
    ]
