# Generated by Django 3.2 on 2026-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_standard_add_sats_id_and_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectattendance',
            name='marked_from',
            field=models.CharField(blank=True, default='normal', max_length=50, null=True),
        ),
    ]
