# Generated by Django 3.2 on 2026-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0032_subjectattendance_marked_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffstandardsectionmapping',
            name='allocation_type',
            field=models.CharField(choices=[('class_teacher', 'Class Teacher'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
