# Generated by Django 3.2 on 2026-03-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0033_staffstandardsectionmapping_allocation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_academic_year', to='institutes.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanSubtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=0, help_text='Order of subtopic')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanSubtopicAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=0, help_text='Order of subtopic')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanSubtopicDetailAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('objectives', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('resource', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('allocated_from_date', models.DateField(blank=True, help_text='First day of allocation (e.g. for 3–4 day subtopic)', null=True)),
                ('allocated_to_date', models.DateField(blank=True, help_text='Last day of allocation', null=True)),
                ('completion_date', models.DateField(blank=True, help_text='Date when the detail was completed', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('allocated_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plan_subtopic_detail_academic_year_allocated_to_user', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan_subtopic_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_subtopic_detail_academic_year_lesson_plan_subtopic_academic_year', to='classes.lessonplansubtopicacademicyear')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='standard',
            name='sats_medium',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='standard_id_according_to_sats',
        ),
        migrations.CreateModel(
            name='LessonPlanTopicAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=0, help_text='Order of topic')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lesson_plan_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_topic_academic_year_lesson_plan_academic_year', to='classes.lessonplanacademicyear')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=0, help_text='Order of topic')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lesson_plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_topic_lesson_plan_template', to='classes.lessonplantemplate')),
            ],
        ),
        migrations.AddField(
            model_name='lessonplantemplate',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_template_standard', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='lessonplantemplate',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_template_subject', to='classes.subject'),
        ),
        migrations.CreateModel(
            name='LessonPlanSubtopicDetailReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Review or feedback text')),
                ('date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plan_subtopic_detail_review_created_by', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan_subtopic_detail_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_subtopic_detail_review_detail', to='classes.lessonplansubtopicdetailacademicyear')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanSubtopicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('objectives', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('resource', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_subtopic_detail_lesson_plan_subtopic', to='classes.lessonplansubtopic')),
            ],
        ),
        migrations.AddField(
            model_name='lessonplansubtopicacademicyear',
            name='lesson_plan_topic_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_subtopic_academic_year_lesson_plan_topic_academic_year', to='classes.lessonplantopicacademicyear'),
        ),
        migrations.AddField(
            model_name='lessonplansubtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_subtopic_lesson_plan_topic', to='classes.lessonplantopic'),
        ),
        migrations.AddField(
            model_name='lessonplanacademicyear',
            name='lesson_plan_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_lesson_plan_template', to='classes.lessonplantemplate'),
        ),
        migrations.AddField(
            model_name='lessonplanacademicyear',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='lessonplanacademicyear',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_subject', to='classes.subject'),
        ),
    ]
