# Generated by Django 3.2 on 2026-03-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0034_auto_20260327_1535'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='lessonplansubtopicdetailacademicyear',
        #     name='allocated_to_user',
        # ),
    ]
