# Generated by Django 3.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0036_lessonplansubtopicdetailacademicyear_allocated_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplansubtopicdetailacademicyear',
            name='source_detail',
            field=models.ForeignKey(
                blank=True,
                help_text='Active detail row this historical copy was split from (null = current row)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='date_shift_snapshots',
                to='classes.lessonplansubtopicdetailacademicyear',
            ),
        ),
    ]
