# Generated by Django 3.2 on 2026-04-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0034_auto_20260410_1235'),
        ('classes', '0037_lessonplansubtopicdetailacademicyear_source_detail'),
    ]

    operations = [
    ]
