# Generated by Django 3.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0038_merge_20260417_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLessonPlanCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('book_title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('text_length', models.PositiveIntegerField(db_index=True, default=0)),
                ('upload_count', models.PositiveIntegerField(default=1)),
                ('plan', models.JSONField()),
                ('last_imported_lesson_plan_id', models.PositiveIntegerField(blank=True, help_text='PK of LessonPlanAcademicYear in the tenant DB', null=True)),
                ('last_imported_tenant_db', models.CharField(blank=True, help_text='Database key of the tenant that last imported this plan', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
