# Generated by Django 3.2 on 2026-05-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0039_ailessonplancache'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplanacademicyear',
            name='lesson_plan_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_lesson_plan_template', to='classes.lessonplantemplate'),
        ),
        migrations.AddField(
            model_name='lessonplanacademicyear',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='lessonplanacademicyear',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_academic_year_subject', to='classes.subject'),
        ),
    ]
