# Generated by Django 3.2 on 2026-05-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0040_auto_20260504_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplansubtopicdetailacademicyear',
            name='is_manually_edited',
            field=models.BooleanField(default=False, help_text='True if a teacher has manually saved changes to this detail'),
        ),
        migrations.AddField(
            model_name='lessonplansubtopicdetailacademicyear',
            name='last_ai_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this record was last updated by AI', null=True),
        ),
        migrations.CreateModel(
            name='LessonPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(help_text='Full serialized plan JSON at this point in time')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of what changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='classes.lessonplanacademicyear')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('lesson_plan', 'version_number')},
            },
        ),
    ]
