# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationApiConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('suggestion', models.CharField(blank=True, max_length=255, null=True)),
                ('customized_message', models.CharField(blank=True, max_length=255, null=True)),
                ('default_message', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_medium', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush')], max_length=15)),
                ('enable_for_school', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('screen_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_medium', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush')], max_length=15)),
                ('channel_data', models.JSONField()),
                ('api_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read_by_user', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255, unique=True)),
                ('notification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_type_mapping_notification_type', to='notification.notificationtype')),
            ],
        ),
    ]
