# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationlog_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='notification_api_configuration_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='notification_api_configuration_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationapiconfiguration',
            unique_together={('api_name', 'notification_medium')},
        ),
    ]
