# Generated by Django 3.2 on 2022-08-08 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0003_custom_resource_migrations'),
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_data', models.TextField()),
                ('heading', models.CharField(max_length=255)),
                ('standard_section_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('user_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('group_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_academic_year', to='institutes.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLangauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_template_language', to='notification.notificationlangauge')),
                ('notification_medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_template_medium', to='notification.notificationmedium')),
            ],
        ),
        migrations.CreateModel(
            name='BulkNotificationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bulk_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_users_bulk_notification', to='notification.bulknotification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_users_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_language', to='notification.notificationlangauge'),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='notification_medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_medium', to='notification.notificationmedium'),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='selected_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_selected_template', to='notification.notificationtemplate'),
        ),
    ]
