# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_medium_list(apps, schema_editor):
        '''
        We can't import the Post model directly as it may be a newer
        version than this migration expects. We use the historical version.
        '''
        NotificationMedium = apps.get_model('notification', 'NotificationMedium')
        NotificationMedium.objects.bulk_create([
            NotificationMedium(name='email'),
            NotificationMedium(name='push'),
            NotificationMedium(name='webpush'),
            NotificationMedium(name='sms')
        ])

        NotificationLangauge = apps.get_model('notification', 'NotificationLangauge')
        NotificationLangauge.objects.bulk_create([
            NotificationLangauge(name='english', code='en'),
            NotificationLangauge(name='kannada', code='kn'),
            NotificationLangauge(name='telugu', code='te'),
            NotificationLangauge(name='hindhi', code='hi')
        ])

    dependencies = [
        ('notification', '0003_auto_20220808_0055'),
    ]

    operations = [
        migrations.RunPython(initial_medium_list)
    ]
