# Generated by Django 3.2 on 2023-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
