# Generated by Django 3.2 on 2023-05-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationapiconfiguration_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
