# Generated by Django 3.2 on 2023-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notificationlog_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationapiconfiguration',
            name='customized_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notificationapiconfiguration',
            name='default_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notificationapiconfiguration',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
