# Generated by Django 3.2 on 2023-05-16 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_auto_20230506_0643'),
        ('notification', '0007_auto_20230514_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotificationDocumentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('bulk_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_document_mapping_bulk_notification', to='notification.bulknotification')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_document_mapping_document', to='shared.document')),
            ],
        ),
    ]
