# Generated by Django 3.2 on 2023-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_bulknotificationdocumentmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='template_for_other_user',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
