# Generated by Django 3.2 on 2023-06-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_notificationapiconfiguration_template_for_other_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulknotification',
            name='group_ids',
        ),
        migrations.RemoveField(
            model_name='bulknotification',
            name='user_ids',
        ),
    ]
