# Generated by Django 3.2 on 2023-07-02 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0010_auto_20230618_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulknotification',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_create', to=settings.AUTH_USER_MODEL),
        ),
    ]
