# Generated by Django 3.2 on 2023-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_bulknotification_created_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_medium', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush')], max_length=20)),
                ('vendor_name', models.CharField(max_length=50)),
                ('sender_id', models.CharField(max_length=50)),
                ('brand_name', models.CharField(default='Edubricz', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
