# Generated by Django 3.2 on 2024-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_notificationvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='enable_for_otherusers',
            field=models.BooleanField(default=True),
        ),
    ]
