# Generated by Django 3.2 on 2024-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_notificationapiconfiguration_enable_for_otherusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='visible_to',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
