# Generated by Django 3.2 on 2024-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_notificationtype_visible_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulknotification',
            name='notification_type',
            field=models.IntegerField(default=0),
        ),
    ]
