# Generated by Django 3.2 on 2024-11-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_auto_20241027_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='bulk_notification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_notification_bulk_notification_category', to='notification.bulknotificationcategory'),
        ),
    ]
