# Generated by Django 3.2 on 2025-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0017_alter_bulknotification_bulk_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='template_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationapiconfiguration',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush'), ('whatsapp', 'whatsapp')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush'), ('whatsapp', 'whatsapp')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationvendor',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush'), ('whatsapp', 'whatsapp')], max_length=20),
        ),
    ]
