# Generated by Django 2.2.24 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    def initial_medium_list(apps, schema_editor):
        '''
        We can't import the Post model directly as it may be a newer
        version than this migration expects. We use the historical version.
        '''
        NotificationMedium = apps.get_model('notification', 'NotificationMedium')
        NotificationMedium.objects.get_or_create(
            name='whatsapp'
        )

    dependencies = [
        ('notification', '0018_auto_20250222_1831'),
    ]

    operations = [
        migrations.RunPython(initial_medium_list)
    ]