# Generated by Django 3.2 on 2025-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_custom_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationapiconfiguration',
            name='template',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
