# Generated by Django 3.2 on 2025-10-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_alter_notificationapiconfiguration_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationapiconfiguration',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush'), ('whatsapp', 'whatsapp'), ('ivr', 'ivr')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush'), ('whatsapp', 'whatsapp'), ('ivr', 'ivr')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationvendor',
            name='notification_medium',
            field=models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('push', 'push'), ('webpush', 'webpush'), ('whatsapp', 'whatsapp'), ('ivr', 'ivr')], max_length=20),
        ),
    ]
