# Generated by Django 3.2 on 2025-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20251013_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='message_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
