# Generated by Django 3.2 on 2025-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_alter_bulknotification_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='is_read_by_user',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'created'], name='notificatio_user_id_f9bf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'is_read_by_user', 'created'], name='notificatio_user_id_c4f278_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created'], name='notificatio_created_d003e6_idx'),
        ),
    ]
