# Generated by Django 3.2 on 2026-04-08 16:49

import apps.notification.models.notification
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_auto_20251122_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationapiconfiguration',
            name='extra_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
