# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_table', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_type', models.CharField(blank=True, choices=[('both', 'both'), ('update', 'update'), ('insert', 'insert')], max_length=6, null=True)),
                ('process_hook', models.CharField(blank=True, max_length=255, null=True)),
                ('process_function', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('read_only', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('bulk_upload_supported', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BduColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_table', models.CharField(blank=True, max_length=255, null=True)),
                ('schema_column', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('update_allowed', models.BooleanField(default=True)),
                ('exclude_from_view', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bdu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdu_column_bdu', to='bdu.bdu')),
            ],
        ),
        migrations.CreateModel(
            name='BduValidationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BduValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bdu_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdu_validation_column', to='bdu.bducolumn')),
                ('bdu_validation_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bdu_validation_class', to='bdu.bduvalidationclass')),
            ],
        ),
    ]
