# Generated by Django 2.2.24 on 2021-08-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    def initial_validation_class(apps, schema_editor):
        ValidationClass = apps.get_model('bdu', 'BduValidationClass')
        ValidationClass.objects.bulk_create([
            ValidationClass(id=1, validation_type='None'),
            ValidationClass(id=2, validation_type='Date (DD-MM-YYYY)'),
            ValidationClass(id=3, validation_type='Is mobile'),
            ValidationClass(id=4, validation_type='Date (YYYY-MM-DD)'),
            ValidationClass(id=5, validation_type='Datetime (YYYY-MM-DD H:M:S)'),
            ValidationClass(id=6, validation_type='Is numeric'),
            ValidationClass(id=7, validation_type='Min length'),
            ValidationClass(id=8, validation_type='Max length'),
            ValidationClass(id=9, validation_type='duplicate in Sheet'),
            ValidationClass(id=10, validation_type='custom Regex')
        ])

    dependencies = [
        ('bdu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_validation_class)
    ]
