# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('hr', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimingparent',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_timing_parent_academic_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='schooltimingcustomdates',
            name='school_timing_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_timing_custom_dats_school_timing', to='general.schooltimingparent'),
        ),
        migrations.AddField(
            model_name='schooltiming',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_timing_day', to='hr.day'),
        ),
        migrations.AddField(
            model_name='schooltiming',
            name='school_timing_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_timing_school_timing_parent', to='general.schooltimingparent'),
        ),
        migrations.AddField(
            model_name='holidaycalenderstudent',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='holidaycalender',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.financialyear'),
        ),
    ]
