# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
        ('general', '0002_initial'),
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='event_staff', to='staffs.Staff', verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='event',
            name='standard_section',
            field=models.ManyToManyField(blank=True, related_name='event_standard_section', to='classes.StandardSectionMapping', verbose_name='standard_section'),
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='event_student', to='students.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_type', to='general.eventtype'),
        ),
    ]
