# Generated by Django 3.2 on 2023-11-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_machineuserlog_operation_id'),
        ('institutes', '0012_biometricmachine'),
        ('general', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_plan_year', to='institutes.academicyear')),
                ('standard', models.ManyToManyField(blank=True, related_name='holiday_plan_standard', to='classes.Standard')),
            ],
        ),
        migrations.AddField(
            model_name='holidaycalenderstudent',
            name='holiday_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_plan', to='general.holidayplan'),
        ),
    ]
