# Generated by Django 3.2 on 2024-07-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0037_alter_documenttype_group_type'),
        ('general', '0004_auto_20231109_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaycalenderstudent',
            name='event_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_calender_student_event_plan', to='general.holidayplan'),
        ),
        migrations.CreateModel(
            name='EventImageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_calender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image_mapping_event_calender', to='general.holidaycalenderstudent')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image_mapping_image', to='shared.document')),
            ],
        ),
    ]
