# Generated by Django 3.2 on 2024-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20240709_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaycalenderstudent',
            name='event_plan',
        ),
        migrations.AddField(
            model_name='eventimagemapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holidaycalenderstudent',
            name='holiday_type',
            field=models.IntegerField(default=1),
        ),
    ]
