# Generated by Django 3.2 on 2024-08-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0006_auto_20240727_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongProcessingApiResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(blank=True)),
                ('api_name', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_date_time', models.DateTimeField(blank=True, null=True)),
                ('execution_started_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_process_running', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_processing_api_result_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
