# Generated by Django 2.2.24 on 2021-08-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    def initial_group(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.bulk_create([
            Group(id=1, name=u'Super Admin'),
            Group(id=2, name=u'Admin'),
            Group(id=3, name=u'Principal'),
            Group(id=4, name=u'Hr'),
            Group(id=5, name=u'Finance'),
            Group(id=6, name=u'Teacher'),
            Group(id=7, name=u'Student'),
            Group(id=8, name=u'Driver'),
            Group(id=9, name=u'Non Teaching'),
            Group(id=10, name=u'Edubriczadmin'),
        ])
        ReportingGroupMapping = apps.get_model('users', 'ReportingGroupMapping')
        ReportingGroupMapping.objects.bulk_create([
            ReportingGroupMapping(group_id=1, reporting_group='0'),
            ReportingGroupMapping(group_id=2, reporting_group='1'),
            ReportingGroupMapping(group_id=3, reporting_group='1,2'),
            ReportingGroupMapping(group_id=4, reporting_group='1,2,3,4'),
            ReportingGroupMapping(group_id=5, reporting_group='1,2,3,4'),
            ReportingGroupMapping(group_id=6, reporting_group='1,2,3,4'),
            ReportingGroupMapping(group_id=7, reporting_group='1,6'),
            ReportingGroupMapping(group_id=8, reporting_group='1,2,3,4'),
            ReportingGroupMapping(group_id=9, reporting_group='1,2,3,4'),
            ReportingGroupMapping(group_id=10, reporting_group='1'),
        ])

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_group)
    ]
