# Generated by Django 3.2 on 2022-09-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custom_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_or_email',
        ),
    ]
