# Generated by Django 3.2 on 2023-01-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_mobile_or_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinggroupmapping',
            name='group_type',
            field=models.IntegerField(default=0),
        ),
    ]
