# Generated by Django 3.2 on 2024-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
