# Generated by Django 2.2.24 on 2021-08-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    def initial_reportinggroup_type(apps, schema_editor):
        Reporting = apps.get_model('users', 'ReportingGroupMapping')
        Reporting.objects.filter(group_type=0).update(group_type=2)
    dependencies = [
        ('users', '0007_user_barcode_number'),
    ]

    operations = [
        migrations.RunPython(initial_reportinggroup_type)
    ]
