# Generated by Django 3.2 on 2024-07-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0036_custom_group_type'),
        ('users', '0008_custom_reportinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinggroupmapping',
            name='group_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shared.grouptype'),
        ),
    ]
