# Generated by Django 3.2 on 2024-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_reportinggroupmapping_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barcode_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
