# Generated by Django 3.2 on 2025-02-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_barcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
