# Generated by Django 3.2 on 2025-09-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0040_custom_staff_app_menu'),
        ('staffs', '0007_staff_blood_group'),
        ('institutes', '0018_auto_20250509_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('classes', '0028_courseoutcome_programoutcome_programspecificoutcome_staffsubjectdetails_subjectcategory_subjectcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('background_color', models.CharField(default='#d9efed', max_length=1000)),
                ('text_color', models.CharField(default='#272124', max_length=1000)),
                ('confirmation_message', models.CharField(default='Your response has been recorded.', max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('is_for_staff', models.BooleanField(default=False)),
                ('form_type', models.CharField(blank=True, max_length=100)),
                ('total_time', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_academic_year', to='institutes.academicyear')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_creater', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_document', to='shared.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_choice_document', to='shared.document')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2500)),
                ('description', models.CharField(blank=True, max_length=2500)),
                ('question_type', models.CharField(blank=True, choices=[(1, 'multiplechoice'), (3, 'oneword')], max_length=25, null=True)),
                ('required', models.BooleanField(default=False)),
                ('feedback', models.CharField(max_length=5000, null=True)),
                ('sequence', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='feedbackform_question_document', to='shared.Document')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_question_form', to='feedbackform.feedbackform')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormStandardSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_standard_section_mapping_form', to='feedbackform.feedbackform')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_standard_section_mapping_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedBackFormMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbackform_mapping_form', to='feedbackform.feedbackform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbackform_mapping_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormUserResponseTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_user_response_tracking_form', to='feedbackform.feedbackform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_user_response_tracking_question', to='feedbackform.feedbackformquestion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_user_response_tracking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormStandardSectionOtherMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('formstandardsectionmapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbackform_standard_section_other_mapping', to='feedbackform.feedbackformstandardsectionmapping')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_response_form', to='feedbackform.feedbackform')),
                ('responder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_response_responderuser', to=settings.AUTH_USER_MODEL)),
                ('respondingto_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_response_respondingtouser', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_response_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial_answer', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('points', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('choices', models.ManyToManyField(blank=True, related_name='feedbackform_choice_answer_choice', to='feedbackform.FeedBackFormChoice')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_choice_answer_document', to='shared.document')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_choice_answer_evaluted_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_choice_answer_question', to='feedbackform.feedbackformquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_choice_answer_response', to='feedbackform.feedbackformresponse')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackformchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_choice_question', to='feedbackform.feedbackformquestion'),
        ),
        migrations.CreateModel(
            name='FeedBackFormBranchMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_branch_mapping_branch', to='classes.branch')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_branch_mapping_form', to='feedbackform.feedbackform')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFormAlternateTeacherMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('evaluate', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_alternate_teacher_mapping_form', to='feedbackform.feedbackform')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackform_alternate_teacher_mapping_staff', to='staffs.staff')),
            ],
        ),
    ]
