            # append base name with _create, _list, _retrive, _update, partial_update, destroy always use given keys
from apps.notification.templates import messages_format

available_types = {
    'finance': {'name': 'finance', 'label': 'Finance'},
    'miscellaneous': {'name': 'miscellaneous', 'label': 'Miscellaneous'},
    'transport': {'name': 'transport', 'label': 'Transport'},
    'admission': {'name': 'admission', 'label': 'Admission'},
    'enquiry': {'name': 'enquiry', 'label': 'Enquiry'},
    'application': {'name': 'application', 'label': 'Application'},
    'expense': {'name': 'expense', 'label': 'Expense'},
    'classes': {'name': 'expense', 'label': 'Classes'},
    'attendance': {'name': 'attendance', 'label': 'Attendance'},
    'staff_attendance': {'name': 'staff_attendance', 'label': 'StaffAttendance'},
    'payroll': {'name': 'payroll', 'label': 'Payroll'},
    'staff': {'name': 'staff', 'label': 'Staff'},
    'shift': {'name': 'shift', 'label': 'Shift'},
    'hostel': {'name': 'hostel', 'label': 'Hostel'},
    'inventory': {'name': 'inventory', 'label': 'inventory'},
    'homework': {'name': 'homework', 'label': 'homework'},
    'concession': {'name': 'concession', 'label': 'concession'},
    'gpsgeofence': {'name': 'gpsgeofence', 'label': 'gpsgeofence'},
    'gpseta': {'name': 'gpseta', 'label': 'gpseta'},
    'chat_message': {'name': 'chat_message', 'label': 'chat_message'},
    'username_password_bulk_notification':{'name':'username_password_bulk_notification','label':'username_password_bulk_notification'},
    'visitor_management': {'name': 'visitor_management', 'label': 'visitor_management'}
}

NotificationSupportedApis = {
    'approve_create': {
        'data_to_save': {
            'api_name': 'approve_create',
            'description': 'Finance Fee Type Approved',
            'suggestion': '',
            'customized_message': '',
            'default_email_message': 'Finance Fee Type As been Approved',
            'default_sms_message': 'Finance Fee Type As been Approved',
            'default_push_message': 'Finance Fee Type As been Approved',
            'default_webpush_message': 'Finance Fee Type As been Approved',
            'default_whatsapp_message': 'Finance Fee Type As been Approved',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Fee Plan Approve Status',
            'push_subject': 'Fee Plan Approve Status',
            'sms_subject': 'Fee Plan Approve Status',
            'webpush_subject': 'Fee Plan Approve Status',
            'whatsapp_subject': 'Fee Plan Approve Status',
            'whatsapp_template_id':'',
            'type': available_types['finance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'otpforemail__retrive': {
        'data_to_save': {
            'api_name': 'otpforemail__retrive',
            'description': 'Otp for Login',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': '',
            'default_push_message': '',
            'default_webpush_message': '',
            'default_email_message': '',
            'default_whatsapp_message': '',
            'notification_medium': ['email', 'sms','whatsapp'],
            'email_subject': 'Your one Time Password',
            'push_subject': 'Your one Time Password',
            'sms_subject': 'Your one Time Password',
            'webpush_subject': 'Your one Time Password',
            'whatsapp_subject': 'Your one Time Password',
            'whatsapp_template_id':'',
            'enable_school': 1,
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',  # when empty fetch email from student / staff table based on user
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'bduupload_update': {
        'data_to_save': {
            'api_name': 'bduupload_update',
            'description': 'Bulk Data Upload Status',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': '',
            'default_push_message': '',
            'default_webpush_message': '',
            'default_whatsapp_message':'',
            'default_email_message': 'Bulk Data Upload task is completed, please review the data',
            'notification_medium': ['email', 'sms'],
            'email_subject': 'Bulk Data Upload Status',
            'push_subject': 'Bulk Data Upload Status',
            'sms_subject': 'Bulk Data Upload Status',
            'webpush_subject': 'Bulk Data Upload Status',
            'whatsapp_subject': 'Bulk Data Upload Status',
            'whatsapp_template_id':'',
            'enable_school': 1,
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'feature_create': {
        'data_to_save': {
            'api_name': 'feature_create',
            'description': 'Finance Fee features selection',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Fee/feature(s) are enabled/disabled',
            'default_push_message': 'Fee/feature(s) are enabled/disabled',
            'default_webpush_message': 'Fee/feature(s) are enabled/disabled',
            'default_email_message': 'Fee/feature(s) are enabled/disabled',
            'default_whatsapp_message': 'Fee/feature(s) are enabled/disabled',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Fee/feature details',
            'push_subject': 'Fee/feature details',
            'sms_subject': 'Fee/feature details',
            'webpush_subject': 'Fee/feature details',
            'whatsapp_subject': 'Fee/feature details',
            'email_template': messages_format.feature_create_email,
            'sms_template': messages_format.feature_create_sms,
            'push_template': messages_format.feature_create_push,
            'webpush_template': messages_format.feature_create_webpush,
            'whatsapp_template': messages_format.feature_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['finance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'medium',
    },
    'feecollection_create': {
        'data_to_save': {
            'api_name': 'feecollection_create',
            'description': 'Fee payment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Your payment is successful.',
            'default_push_message': 'Your payment is successful.',
            'default_webpush_message': 'Your payment is successful.',
            'default_email_message': 'Your payment is successful.',
            'default_whatsapp_message': 'Your payment is successful.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Fee Payment Status',
            'push_subject': 'Fee Payment Status',
            'sms_subject': 'Fee Payment Status',
            'webpush_subject': 'Fee Payment Status',
            'whatsapp_subject': 'Fee Payment Status',
            'email_template': messages_format.feecollection_create_email,
            'sms_template': messages_format.feecollection_create_sms,
            'push_template': messages_format.feecollection_create_push,
            'webpush_template': messages_format.feecollection_create_webpush,
            'whatsapp_template': messages_format.feecollection_create_whatsapp,
            'whatsapp_template_id':'feecollection_create',
            'type': available_types['finance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'username_password_bulk_notification_student': {
        'data_to_save': {
            'api_name': 'username_password_bulk_notification_student',
            'description': 'Fee payment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Admission is successful.',
            'default_push_message': 'Admission is successful.',
            'default_webpush_message': 'Admission is successful.',
            'default_email_message': 'Admission is successful.',
            'default_whatsapp_message': 'Admission is successful.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student App Login',
            'push_subject': 'Student App Login',
            'sms_subject': 'Student App Login',
            'webpush_subject': 'Student App Login',
            'whatsapp_subject': 'Student App Login',
            'email_template': messages_format.username_password_bulk_notification_email_student,
            'sms_template': messages_format.username_password_bulk_notification_sms_student,
            'push_template': '',
            'webpush_template': '',
            'whatsapp_template': messages_format.username_password_bulk_notification_whatsapp_student,
            'whatsapp_template_id':'username_password_bulk_notification_student',
            'type': available_types['username_password_bulk_notification']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'username_password_bulk_notification_staff': {
        'data_to_save': {
            'api_name': 'username_password_bulk_notification_staff',
            'description': 'Fee payment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Staff is added successfully.',
            'default_push_message': 'Staff is added successfully.',
            'default_webpush_message': 'Staff is added successfully.',
            'default_email_message': 'Staff is added successfully.',
            'default_whatsapp_message': 'Staff is added successfully.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Staff App Login',
            'push_subject': 'Staff App Login',
            'sms_subject': 'Staff App Login',
            'webpush_subject': 'Staff App Login',
            'whatsapp_subject': 'Staff App Login',
            'email_template': messages_format.username_password_bulk_notification_email_staff,
            'sms_template': messages_format.username_password_bulk_notification_sms_staff,
            'push_template': '',
            'webpush_template': '',
            'whatsapp_template': messages_format.username_password_bulk_notification_whatsapp_staff,
            'whatsapp_template_id':'username_password_bulk_notification_staff',
            'type': available_types['username_password_bulk_notification']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'gpsgeofence_create': {
        'data_to_save': {
            'api_name': 'gpsgeofence_create',
            'description': 'Gps Geofence',
            'suggestion': '',
            'customized_message': '',
            'default_push_message': 'Route has started from the school.',
            'default_email_message': 'Route has started from the school.',
            'default_sms_message': 'Route has started from the school.',
            'default_webpush_message': 'Route has started from the school.',
            'default_whatsapp_message': 'Route has started from the school.',
            'notification_medium': ['email','push','sms','webpush','whatsapp'],
            'email_subject': 'Vehicle Status',
            'push_subject': 'Vehicle Status',
            'sms_subject': 'Vehicle Status',
            'webpush_subject': 'Vehicle Status',
            'whatsapp_subject': 'Vehicle Status',
            'email_template': messages_format.gps_geofence_create_email,
            'push_template': messages_format.gps_geofence_create_push,
            'sms_template': messages_format.gps_geofence_create_sms,
            'webpush_template': messages_format.gps_geofence_create_webpush,
            'whatsapp_template': messages_format.gps_geofence_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['gpsgeofence']
        },
        'default_to_fetching_fields': {
            'email': '',
            'push': '',
            'sms':'',
            'webpush':'',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'gps_eta_create': {
        'data_to_save': {
            'api_name': 'gps_eta_create',
            'description': 'Gps ETA',
            'suggestion': '',
            'customized_message': '',
            'default_push_message': 'Your child is few meters away from the stop.',
            'default_email_message': 'Your child is few meters away from the stop.',
            'default_sms_message': 'Your child is few meters away from the stop.',
            'default_webpush_message': 'Your child is few meters away from the stop.',
            'default_whatsapp_message': 'Your child is few meters away from the stop.',
            'notification_medium': ['email','push','sms','webpush','whatsapp'],
            'email_subject': 'Vehicle Status',
            'push_subject': 'Vehicle Status',
            'push_subject': 'Vehicle Status',
            'webpush_subject': 'Vehicle Status',
            'whatsapp_subject': 'Vehicle Status',
            'sms_subject':'',
            'email_template': messages_format.gps_eta_create_email,
            'push_template': messages_format.gps_eta_create_push,
            'sms_template': messages_format.gps_eta_create_sms,
            'webpush_template': messages_format.gps_eta_create_webpush,
            'whatsapp_template_id':'',
            'whatsapp_template': messages_format.gps_eta_create_whatsapp,
            'type': available_types['gpseta']
        },
        'default_to_fetching_fields': {
            'email': '',
            'push': '',
            'sms':'',
            'webpush':'',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'feecollection_destroy': {
        'data_to_save': {
            'api_name': 'feecollection_destroy',
            'description': 'Fee Payment Deleted',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Fee Payment deleted Successfully',
            'default_push_message': 'Fee Payment deleted Successfully',
            'default_webpush_message': 'Fee Payment deleted Successfully',
            'default_email_message': 'Fee Payment deleted Successfully',
            'default_whatsapp_message': 'Fee Payment deleted Successfully',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Fee Payment deleted Successfully',
            'push_subject': 'Fee Payment deleted Successfully',
            'sms_subject': 'Fee Payment deleted Successfully',
            'webpush_subject': 'Fee Payment deleted Successfully',
            'whatsapp_subject': 'Fee Payment deleted Successfully',
            'email_template': messages_format.feecollection_destroy_email,
            'sms_template': messages_format.feecollection_destroy_sms,
            'push_template': messages_format.feecollection_destroy_push,
            'webpush_template': messages_format.feecollection_destroy_webpush,
            'whatsapp_template': messages_format.feecollection_destroy_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['finance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'concession_create': {
        'data_to_save': {
            'api_name': 'concession_create',
            'description': 'Concession fee',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Concession is applied.',
            'default_push_message': 'Concession is applied.',
            'default_webpush_message': 'Concession is applied.',
            'default_email_message': 'Concession is applied.',
            'default_whatsapp_message': 'Concession is applied.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Concession is applied',
            'push_subject': 'Concession is applied',
            'sms_subject': 'Concession is applied',
            'webpush_subject': 'Concession is applied',
            'whatsapp_subject': 'Concession is applied',
            'email_template': messages_format.concession_create_email,
            'sms_template': messages_format.concession_create_sms,
            'push_template': messages_format.concession_create_push,
            'webpush_template': messages_format.concession_create_webpush,
            'whatsapp_template': messages_format.concession_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['finance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'misc_create': {
        'data_to_save': {
            'api_name': 'misc_create',
            'description': 'Miscellaneous Payment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Your payment is successful.',
            'default_push_message': 'Your payment is successful.',
            'default_webpush_message': 'Your payment is successful.',
            'default_email_message': 'Your payment is successful.',
            'default_whatsapp_message': 'Your payment is successful.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Fee payment Status',
            'push_subject': 'Fee payment Status',
            'sms_subject': 'Fee payment Status',
            'webpush_subject': 'Fee payment Status',
            'whatsapp_subject': 'Fee payment Status',
            'email_template': messages_format.misc_create_email,
            'sms_template': messages_format.misc_create_sms,
            'push_template': messages_format.misc_create_push,
            'webpush_template': messages_format.misc_create_webpush,
            'whatsapp_template': messages_format.misc_create_webpush,
            'whatsapp_template_id':'',
            'type': available_types['miscellaneous']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'high',
    },
    'vehicledriver_create': {
        'data_to_save': {
            'api_name': 'vehicledriver_create',
            'description': 'Assigning the driver to the vehicle',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'You have been assigned to the Vehicle.',
            'default_push_message': 'You have been assigned to the Vehicle.',
            'default_webpush_message': 'You have been assigned to the Vehicle.',
            'default_email_message': 'You have been assigned to the Vehicle.',
            'default_whatsapp_message': 'You have been assigned to the Vehicle.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Vehicle Assigned',
            'push_subject': 'Vehicle Assigned',
            'sms_subject': 'Vehicle Assigned',
            'webpush_subject': 'Vehicle Assigned',
            'whatsapp_subject': 'Vehicle Assigned',
            'whatsapp_template_id':'',
            'type': available_types['transport']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'vehicledriver_destroy': {
        'data_to_save': {
            'api_name': 'vehicledriver_destroy',
            'description': 'Unassigned the driver from the vehicle',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'You have been unassigned from the Vehicle.',
            'default_push_message': 'You have been unassigned from the Vehicle.',
            'default_webpush_message': 'You have been unassigned from the Vehicle.',
            'default_email_message': 'You have been unassigned from the Vehicle.',
            'default_whatsapp_message': 'You have been unassigned from the Vehicle.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Vehicle Unassigned',
            'push_subject': 'Vehicle Unassigned',
            'sms_subject': 'Vehicle Unassigned',
            'webpush_subject': 'Vehicle Unassigned',
            'whatsapp_subject': 'Vehicle Unassigned',
            'whatsapp_template_id':'',
            'type': available_types['transport']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'routestudentaddress_create': {
        'data_to_save': {
            'api_name': 'routestudentaddress_create',
            'description': 'Student address registration',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student address has been registered for the transport.',
            'default_push_message': 'Student address has been registered for the transport.',
            'default_webpush_message': 'Student address has been registered for the transport.',
            'default_email_message': 'Student address has been registered for the transport.',
            'default_whatsapp_message': 'Student address has been registered for the transport.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Transport | Student Address Registration',
            'push_subject': 'Transport | Student Address Registration',
            'sms_subject': 'Transport | Student Address Registration',
            'webpush_subject': 'Transport | Student Address Registration',
            'whatsapp_subject': 'Transport | Student Address Registration',
            'whatsapp_template_id':'',
            'type': available_types['transport']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'routepriceplanapprove_update': {
        'data_to_save': {
            'api_name': 'routepriceplanapprove_update',
            'description': 'Transport price plan approve',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Transport price plan is approved.',
            'default_push_message': 'Transport price plan is approved.',
            'default_webpush_message': 'Transport price plan is approved.',
            'default_email_message': 'Transport price plan is approved.',
            'default_whatsapp_message': 'Transport price plan is approved.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Transport | Price Plan Approved',
            'push_subject': 'Transport | Price Plan Approved',
            'sms_subject': 'Transport | Price Plan Approved',
            'webpush_subject': 'Transport | Price Plan Approved',
            'whatsapp_subject': 'Transport | Price Plan Approved',
            'whatsapp_template_id':'',
            'type': available_types['transport']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'studentall_create': {
        'data_to_save': {
            'api_name': 'studentall_create',
            'description': 'Student Admission Form',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Admission is successful.',
            'default_push_message': 'Student Admission is successful.',
            'default_webpush_message': 'Student Admission is successful.',
            'default_email_message': 'Student Admission is successful.',
            'default_whatsapp_message': 'Student Admission is successful.',
            'notification_medium': ['email', 'sms', 'webpush','whatsapp'],
            'email_subject': 'Student Admission Status',
            'push_subject': 'Student Admission Status',
            'sms_subject': 'Student Admission Status',
            'webpush_subject': 'Student Admission Status',
            'whatsapp_subject': 'Student Admission Status',
            'email_template': messages_format.studentall_create_email,
            'sms_template': messages_format.studentall_create_sms,
            'push_template': messages_format.studentall_create_push,
            'webpush_template': messages_format.studentall_create_webpush,
            'whatsapp_template': messages_format.studentall_create_whatsapp,
            'whatsapp_template_id':'username_password_bulk_notification',
            'type': available_types['admission']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'enquiry_create': {
        'data_to_save': {
            'api_name': 'enquiry_create',
            'description': 'Student Enquiry Form',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Enquiry form is submitted successfully.',
            'default_push_message': 'Enquiry form is submitted successfully.',
            'default_webpush_message': 'Enquiry form is submitted successfully.',
            'default_email_message': 'Enquiry form is submitted successfully.',
            'default_whatsapp_message': 'Enquiry form is submitted successfully.',
            'notification_medium': ['email', 'sms','whatsapp'],
            'email_subject': 'Enquiry Form Status',
            'push_subject': 'Enquiry Form Status',
            'sms_subject': 'Enquiry Form Status',
            'webpush_subject': 'Enquiry Form Status',
            'whatsapp_subject': 'Enquiry Form Status',
            'email_template': messages_format.enquiry_create_email,
            'sms_template': messages_format.enquiry_create_sms,
            'push_template': messages_format.enquiry_create_push,
            'webpush_template': messages_format.enquiry_create_webpush,
            'whatsapp_template': messages_format.enquiry_create_whatsapp,
            'whatsapp_template_id':'enquiry_create',
            'type': available_types['enquiry']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'application_create': {
        'data_to_save': {
            'api_name': 'application_create',
            'description': 'Student Application Form',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Application form is submitted successfully.',
            'default_push_message': 'Application form is submitted successfully.',
            'default_webpush_message': 'Application form is submitted successfully.',
            'default_email_message': 'Application form is submitted successfully.',
            'default_whatsapp_message': 'Application form is submitted successfully.',
            'notification_medium': ['email', 'sms', 'webpush','whatsapp'],
            'email_subject': 'Application Form Status',
            'push_subject': 'Application Form Status',
            'sms_subject': 'Application Form Status',
            'webpush_subject': 'Application Form Status',
            'whatsapp_subject':  'Application Form Status',
            'email_template': messages_format.application_create_email,
            'sms_template': messages_format.application_create_sms,
            'push_template': messages_format.application_create_push,
            'webpush_template': messages_format.application_create_webpush,
            'whatsapp_template': messages_format.application_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['application']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'token_create': {
        'data_to_save': {
            'api_name': 'token_create',
            'description': 'Fuel Token',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'PFA fuel token.',
            'default_push_message': 'PFA fuel token.',
            'default_webpush_message': 'PFA fuel token.',
            'default_email_message': 'PFA fuel token.',
            'default_whatsapp_message': 'PFA fuel token.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Fuel Token',
            'push_subject': 'Fuel Token',
            'sms_subject': 'Fuel Token',
            'webpush_subject': 'Fuel Token',
            'whatsapp_subject': 'Fuel Token',
            'whatsapp_template_id':'',
            'type': available_types['expense']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'enrollment_create': {
        'data_to_save': {
            'api_name': 'enrollment_create',
            'description': 'Student Enrollment for the Standard & Section',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student is Enrolled for the Standard & Section.',
            'default_push_message': 'Student is Enrolled for the Standard & Section.',
            'default_webpush_message': 'Student is Enrolled for the Standard & Section.',
            'default_email_message': 'Student is Enrolled for Standard & Section.',
            'default_whatsapp_message': 'Student is Enrolled for the Standard & Section.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Enrollment',
            'push_subject': 'Student Enrollment',
            'sms_subject': 'Student Enrollment',
            'webpush_subject': 'Student Enrollment',
            'whatsapp_subject': 'Student Enrollment',
            'email_template': messages_format.enrollment_create_email,
            'sms_template': messages_format.enrollment_create_sms,
            'push_template': messages_format.enrollment_create_push,
            'webpush_template': messages_format.enrollment_create_webpush,
            'whatsapp_template': messages_format.enrollment_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['classes']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'promotestudent_create': {
        'data_to_save': {
            'api_name': 'promotestudent_create',
            'description': 'Student progress report',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student is Promoted.',
            'default_push_message': 'Student is Promoted.',
            'default_webpush_message': 'Student is Promoted.',
            'default_email_message': 'Student is Promoted.',
            'default_whatsapp_message': 'Student is Promoted.',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Progress Report',
            'push_subject': 'Student Progress Report',
            'sms_subject': 'Student Progress Report',
            'webpush_subject': 'Student Progress Report',
            'whatsapp_subject': 'Student Progress Report',
            'email_template': messages_format.promotestudent_create_email,
            'sms_template': messages_format.promotestudent_create_sms,
            'push_template': messages_format.promotestudent_create_push,
            'webpush_template': messages_format.promotestudent_create_webpush,
            'whatsapp_template': messages_format.promotestudent_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['classes']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'attendance_create': {
        'data_to_save': {
            'api_name': 'attendance_create',
            'description': 'Student Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Attendance',
            'default_push_message': 'Student Attendance',
            'default_webpush_message': 'Student Attendance',
            'default_email_message': 'Student Attendance',
            'default_whatsapp_message': 'Student Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Attendance Status',
            'push_subject': 'Student Attendance Status',
            'sms_subject': 'Student Attendance Status',
            'webpush_subject': 'Student Attendance Status',
            'whatsapp_subject': 'Student Attendance Status',
            'email_template': messages_format.attendance_create_email,
            'sms_template': messages_format.attendance_create_sms,
            'push_template': messages_format.attendance_create_push,
            'webpush_template': messages_format.attendance_create_webpush,
            'whatsapp_template': messages_format.attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'attendance_present_create': {
        'data_to_save': {
            'api_name': 'attendance_present_create',
            'description': 'Student Attendance for Present',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Attendance',
            'default_push_message': 'Student Attendance',
            'default_webpush_message': 'Student Attendance',
            'default_email_message': 'Student Attendance',
            'default_whatsapp_message': 'Student Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Attendance Status',
            'push_subject': 'Student Attendance Status',
            'sms_subject': 'Student Attendance Status',
            'webpush_subject': 'Student Attendance Status',
            'whatsapp_subject': 'Student Attendance Status',
            'email_template': messages_format.attendance_create_email,
            'sms_template': messages_format.attendance_create_sms,
            'push_template': messages_format.attendance_create_push,
            'webpush_template': messages_format.attendance_create_webpush,
            'whatsapp_template': messages_format.attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'batch_attendance_create': {
        'data_to_save': {
            'api_name': 'batch_attendance_create',
            'description': 'Student Batch Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Batch Attendance',
            'default_push_message': 'Student Batch Attendance',
            'default_webpush_message': 'Student Batch Attendance',
            'default_email_message': 'Student Batch Attendance',
            'default_whatsapp_message': 'Student Batch Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Batch Attendance Status',
            'push_subject': 'Student Batch Attendance Status',
            'sms_subject': 'Student Batch Attendance Status',
            'webpush_subject': 'Student Batch Attendance Status',
            'whatsapp_subject': 'Student Batch Attendance Status',
            'email_template': messages_format.batch_attendance_create_email,
            'sms_template': messages_format.batch_attendance_create_sms,
            'push_template': messages_format.batch_attendance_create_push,
            'webpush_template': messages_format.batch_attendance_create_webpush,
            'whatsapp_template': messages_format.batch_attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'batch_attendance_present_create': {
        'data_to_save': {
            'api_name': 'batch_attendance_present_create',
            'description': 'Student Batch Attendance for Present',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Batch Attendance',
            'default_push_message': 'Student Batch Attendance',
            'default_webpush_message': 'Student Batch Attendance',
            'default_email_message': 'Student Batch Attendance',
            'default_whatsapp_message': 'Student Batch Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Batch Attendance Status',
            'push_subject': 'Student Batch Attendance Status',
            'sms_subject': 'Student Batch Attendance Status',
            'webpush_subject': 'Student Batch Attendance Status',
            'whatsapp_subject': 'Student Batch Attendance Status',
            'email_template': messages_format.batch_attendance_create_email,
            'sms_template': messages_format.batch_attendance_create_sms,
            'push_template': messages_format.batch_attendance_create_push,
            'webpush_template': messages_format.batch_attendance_create_webpush,
            'whatsapp_template': messages_format.batch_attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'subject_attendance_create': {
        'data_to_save': {
            'api_name': 'subject_attendance_create',
            'description': 'Subject Student Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Attendance',
            'default_push_message': 'Student Attendance',
            'default_webpush_message': 'Student Attendance',
            'default_email_message': 'Student Attendance',
            'default_whatsapp_message': 'Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Attendance Status',
            'push_subject': 'Student Attendance Status',
            'sms_subject': 'Student Attendance Status',
            'webpush_subject': 'Student Attendance Status',
            'whatsapp_subject': 'Student Attendance Status',
            'email_template': messages_format.subject_attendance_create_email,
            'sms_template': messages_format.subject_attendance_create_sms,
            'push_template': messages_format.subject_attendance_create_push,
            'webpush_template': messages_format.subject_attendance_create_webpush,
            'whatsapp_template': messages_format.subject_attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'subject_attendance_present_create': {
        'data_to_save': {
            'api_name': 'subject_attendance_present_create',
            'description': 'Student Attendance for Present',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Attendance',
            'default_push_message': 'Student Attendance',
            'default_webpush_message': 'Student Attendance',
            'default_email_message': 'Student Attendance',
            'default_whatsapp_message': 'Student Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Attendance Status',
            'push_subject': 'Student Attendance Status',
            'sms_subject': 'Student Attendance Status',
            'webpush_subject': 'Student Attendance Status',
            'whatsapp_subject': 'Student Attendance Status',
            'email_template': messages_format.subject_attendance_create_email,
            'sms_template': messages_format.subject_attendance_create_sms,
            'push_template': messages_format.subject_attendance_create_push,
            'webpush_template': messages_format.subject_attendance_create_webpush,
            'whatsapp_template': messages_format.subject_attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'staff_attendance_create': {
        'data_to_save': {
            'api_name': 'staff_attendance_create',
            'description': 'Staff Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Staff Attendance',
            'default_push_message': 'Staff Attendance',
            'default_webpush_message': 'Staff Attendance',
            'default_email_message': 'Staff Attendance',
            'default_whatsapp_message': 'Staff Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Staff Attendance Status',
            'push_subject': 'Staff Attendance Status',
            'sms_subject': 'Staff Attendance Status',
            'webpush_subject': 'Staff Attendance Status',
            'whatsapp_subject': 'Staff Attendance Status',
            'email_template': messages_format.staff_attendance_create_email,
            'sms_template': messages_format.staff_attendance_create_sms,
            'push_template': messages_format.staff_attendance_create_push,
            'webpush_template': messages_format.staff_attendance_create_webpush,
            'whatsapp_template': messages_format.staff_attendance_create_whatsapp,
            'email_template_for_other_user': messages_format.staff_attendance_create_email_for_other_user,
            'sms_template_for_other_user': messages_format.staff_attendance_create_sms_for_other_user,
            'push_template_for_other_user': messages_format.staff_attendance_create_push_for_other_user,
            'webpush_template_for_other_user': messages_format.staff_attendance_create_webpush_for_other_user,
            'whatsapp_template_for_other_user': messages_format.staff_attendance_create_whatsapp_for_other_user,
            'whatsapp_template_id':'',
            'type': available_types['staff_attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'staff_daily_attendance_report_create': {
        'data_to_save': {
            'api_name': 'staff_daily_attendance_report_create',
            'description': 'Staff Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Staff Attendance',
            'default_push_message': 'Staff Attendance',
            'default_webpush_message': 'Staff Attendance',
            'default_email_message': 'Staff Attendance',
            'default_whatsapp_message': 'Staff Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Staff Attendance Status',
            'push_subject': 'Staff Attendance Status',
            'sms_subject': 'Staff Attendance Status',
            'webpush_subject': 'Staff Attendance Status',
            'whatsapp_subject': 'Staff Attendance Status',
            'email_template': messages_format.staff_daily_attendance_email,
            'sms_template': messages_format.staff_daily_attendance_sms,
            'push_template': messages_format.staff_daily_attendance_push,
            'webpush_template': messages_format.staff_daily_attendance_webpush,
            'whatsapp_template': messages_format.staff_daily_attendance_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['staff_attendance'],
            "enable_for_school": 1
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'student_daily_attendance_report_create': {
        'data_to_save': {
            'api_name': 'student_daily_attendance_report_create',
            'description': 'Student Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Attendance',
            'default_push_message': 'Student Attendance',
            'default_webpush_message': 'Student Attendance',
            'default_email_message': 'Student Attendance',
            'default_whatsapp_message': 'Student Attendance',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Attendance Status',
            'push_subject': 'Student Attendance Status',
            'sms_subject': 'Student Attendance Status',
            'webpush_subject': 'Student Attendance Status',
            'whatsapp_subject': 'Student Attendance Status',
            'email_template': messages_format.student_daily_attendance_email,
            'sms_template': messages_format.student_daily_attendance_sms,
            'push_template': messages_format.student_daily_attendance_push,
            'webpush_template': messages_format.student_daily_attendance_webpush,
            'whatsapp_template': messages_format.student_daily_attendance_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance'],
            "enable_for_school": 1
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'salaryemployeemonthplan_create': {
        'data_to_save': {
            'api_name': 'salaryemployeemonthplan_create',
            'description': 'Salary payment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Salary payment',
            'default_push_message': 'Salary payment',
            'default_webpush_message': 'Salary payment',
            'default_email_message': 'Salary payment',
            'default_whatsapp_message': 'Salary payment',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Salary processed',
            'push_subject': 'Salary processed',
            'sms_subject': 'Salary processed',
            'webpush_subject': 'Salary processed',
            'whatsapp_subject': 'Salary processed',
            'email_template': messages_format.salaryemployeemonthplan_create_email,
            'sms_template': messages_format.salaryemployeemonthplan_create_sms,
            'push_template': messages_format.salaryemployeemonthplan_create_push,
            'webpush_template': messages_format.salaryemployeemonthplan_create_webpush,
            'whatsapp_template': messages_format.salaryemployeemonthplan_create_whatsapp,
            'whatsapp_template_id':'',            
            'type': available_types['payroll']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'staffalldetail_create': {
        'data_to_save': {
            'api_name': 'staffalldetail_create',
            'description': 'Staff onBoarding',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': '',
            'default_push_message': '',
            'default_webpush_message': '',
            'default_email_message': '',
            'default_whatsapp_message': '',
            'notification_medium': ['email', 'sms','whatsapp'],
            'email_subject': 'OnBoarding Process',
            'push_subject': 'OnBoarding Process',
            'sms_subject': 'OnBoarding Process',
            'webpush_subject': 'OnBoarding Process',
            'whatsapp_subject': 'OnBoarding Process',
            'email_template': messages_format.staffalldetail_create_email,
            'sms_template': messages_format.staffalldetail_create_sms,
            'push_template': messages_format.staffalldetail_create_push,
            'webpush_template': messages_format.staffalldetail_create_webpush,
            'whatsapp_template': messages_format.staffalldetail_create_whatsapp,
            'whatsapp_template_id':'staff_create',
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'staffalldetail_update': {
        'data_to_save': {
            'api_name': 'staffalldetail_update',
            'description': 'Staff Group update',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Staff Group update',
            'default_push_message': 'Staff Group update',
            'default_webpush_message': 'Staff Group update',
            'default_email_message': 'Staff Group update',
            'default_whatsapp_message': 'Staff Group update',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Role/Group changed',
            'push_subject': 'Role/Group changed',
            'sms_subject': 'Role/Group changed',
            'webpush_subject': 'Role/Group changed',
            'whatsapp_subject': 'Role/Group changed',
            'email_template': messages_format.staffalldetail_update_email,
            'sms_template': messages_format.staffalldetail_update_sms,
            'push_template': messages_format.staffalldetail_update_push,
            'webpush_template': messages_format.staffalldetail_update_webpush,
            'whatsapp_template': messages_format.staffalldetail_update_whatsapp,
            'whatsapp_template_id':'staff_create',
            'type': available_types['staff']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'assignshift_create': {
        'data_to_save': {
            'api_name': 'assignshift_create',
            'description': 'Staff Shift assignment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Staff Shift assignment',
            'default_push_message': 'Staff Shift assignment',
            'default_webpush_message': 'Staff Shift assignment',
            'default_email_message': 'Staff Shift assignment',
            'default_whatsapp_message': 'Staff Shift assignment',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Shift and Timings',
            'push_subject': 'Shift and Timings',
            'sms_subject': 'Shift and Timings',
            'webpush_subject': 'Shift and Timings',
            'whatsapp_subject': 'Shift and Timings',
            'email_template': messages_format.assignshift_create_email,
            'sms_template': messages_format.assignshift_create_sms,
            'push_template': messages_format.assignshift_create_push,
            'webpush_template': messages_format.assignshift_create_webpush,
            'whatsapp_template': messages_format.assignshift_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['shift']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'assignshift_update': {
        'data_to_save': {
            'api_name': 'assignshift_update',
            'description': 'Staff Shift assignment',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Staff Shift assignment',
            'default_push_message': 'Staff Shift assignment',
            'default_webpush_message': 'Staff Shift assignment',
            'default_email_message': 'Staff Shift assignment',
            'default_whatsapp_message': 'Staff Shift assignment',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Shift and Timings',
            'push_subject': 'Shift and Timings',
            'sms_subject': 'Shift and Timings',
            'webpush_subject': 'Shift and Timings',
            'whatsapp_subject': 'Shift and Timings',
            'type': available_types['shift'],
            'email_template': messages_format.assignshift_update_email,
            'sms_template': messages_format.assignshift_update_sms,
            'push_template': messages_format.assignshift_update_push,
            'webpush_template': messages_format.assignshift_update_webpush,
            'whatsapp_template': messages_format.assignshift_update_whatsapp,
            'whatsapp_template_id':'',
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'roomallocation_create': {
        'data_to_save': {
            'api_name': 'roomallocation_create',
            'description': 'Hostel Room Allocation',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Hostel Room Allocation',
            'default_push_message': 'Hostel Room Allocation',
            'default_webpush_message': 'Hostel Room Allocation',
            'default_email_message': 'Hostel Room Allocation',
            'default_whatsapp_message': 'Hostel Room Allocation',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Hostel | Room Allocation',
            'push_subject': 'Hostel | Room Allocation',
            'sms_subject': 'Hostel | Room Allocation',
            'webpush_subject': 'Hostel | Room Allocation',
            'whatsapp_subject': 'Hostel | Room Allocation',
            'whatsapp_template_id':'',
            'type': available_types['hostel']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'purchasemaster_create': {
        'data_to_save': {
            'api_name': 'purchasemaster_create',
            'description': 'Purchasing the stocks',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Purchasing the stocks',
            'default_push_message': 'Purchasing the stocks',
            'default_webpush_message': 'Purchasing the stocks',
            'default_email_message': 'Purchasing the stocks',
            'default_whatsapp_message': 'Purchasing the stocks',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Stock Purchase',
            'push_subject': 'Stock Purchase',
            'sms_subject': 'Stock Purchase',
            'webpush_subject': 'Stock Purchase',
            'whatsapp_subject': 'Stock Purchase',
            'whatsapp_template_id':'',
            'type': available_types['inventory']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'purchasemasterreturn_create': {
        'data_to_save': {
            'api_name': 'purchasemasterreturn_create',
            'description': 'Returning the Stocks',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Returning the Stocks',
            'default_push_message': 'Returning the Stocks',
            'default_webpush_message': 'Returning the Stocks',
            'default_email_message': 'Returning the Stocks',
            'default_whatsapp_message': 'Returning the Stocks',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Stock Return',
            'push_subject': 'Stock Return',
            'sms_subject': 'Stock Return',
            'webpush_subject': 'Stock Return',
            'whatsapp_subject': 'Stock Return',
            'whatsapp_template_id':'',
            'type': available_types['inventory']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'itemsold_create': {
        'data_to_save': {
            'api_name': 'itemsold_create',
            'description': 'Items sold',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Items sold',
            'default_push_message': 'Items sold',
            'default_webpush_message': 'Items sold',
            'default_email_message': 'Items sold',
            'default_whatsapp_message': 'Items sold',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_template': messages_format.itemsold_create_email,
            'sms_template': messages_format.itemsold_create_sms,
            'push_template': messages_format.itemsold_create_push,
            'webpush_template': messages_format.itemsold_create_webpush,
            'whatsapp_template': messages_format.itemsold_create_whatsapp,
            'email_subject': 'Item(s) Purchased',
            'push_subject': 'Item(s) Purchased',
            'sms_subject': 'Item(s) Purchased',
            'webpush_subject': 'Item(s) Purchased',
            'whatsapp_subject': 'Item(s) Purchased',
            'whatsapp_template_id':'',
            'type': available_types['inventory']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'itemsold_min_alert_create': {
        'data_to_save': {
            'api_name': 'itemsold_min_alert_create',
            'description': 'Item(s) minimum alert',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Item(s) minimum alert',
            'default_push_message': 'Item(s) minimum alert',
            'default_webpush_message': 'Item(s) minimum alert',
            'default_email_message': 'Item(s) minimum alert',
            'default_whatsapp_message': 'Item(s) minimum alert',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Stock Limit Alert',
            'push_subject': 'Stock Limit Alert',
            'sms_subject': 'Stock Limit Alert',
            'webpush_subject': 'Stock Limit Alert',
            'whatsapp_subject': 'Stock Limit Alert',
            'whatsapp_template_id':'',
            'type': available_types['inventory']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'company_create': {
        'data_to_save': {
            'api_name': 'company_create',
            'description': 'company creation',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'company creation',
            'default_push_message': 'company creation',
            'default_webpush_message': 'company creation',
            'default_email_message': 'company creation',
            'default_whatsapp_message': 'company creation',
            'notification_medium': ['email'],
            'email_subject': 'compamy create',
            'push_subject': '',
            'sms_subject': '',
            'webpush_subject': '',
            'whatsapp_subject': '',
            'whatsapp_template_id':'',
            'enable_school': 1
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'diary_create': {
        'data_to_save': {
            'api_name': 'diary_create',
            'description': 'Home Work Created',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Home Work Created',
            'default_push_message': 'Home Work Created',
            'default_webpush_message': 'Home Work Created',
            'default_email_message': 'Home Work Created',
            'default_whatsapp_message': 'Home Work Created',
            'notification_medium': ['push','sms', 'email','whatsapp'],
            'email_subject': 'New Home Work Created',
            'push_subject': 'New Home Work Created',
            'sms_subject': 'New Home Work Created',
            'webpush_subject': 'New Home Work Created',
            'whatsapp_subject': 'New Home Work Created',
            'enable_school': 0,
            'email_template': messages_format.diary_create_email,
            'sms_template': messages_format.diary_create_sms,
            'push_template': messages_format.diary_create_push,
            'webpush_template': messages_format.diary_create_webpush,
            'whatsapp_template': messages_format.diary_create_webpush,
            'whatsapp_template_id':'',
            'type': available_types['homework']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'diary_chat_create': {
        'data_to_save': {
            'api_name': 'diary_chat_create',
            'description': 'New Message',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'New Message',
            'default_push_message': 'New Message',
            'default_webpush_message': 'New Message',
            'default_email_message': 'New Message',
            'default_whatsapp_message': 'New Message',
            'notification_medium': ['push','sms', 'email','whatsapp'],
            'email_subject': 'New Message',
            'push_subject': 'New Message',
            'sms_subject': 'New Message',
            'webpush_subject': 'New Message',
            'whatsapp_subject': 'New Message',
            'enable_school': 0,
            'email_template': messages_format.diary_chat_create_email,
            'sms_template': messages_format.diary_chat_create_sms,
            'push_template': messages_format.diary_chat_create_push,
            'webpush_template': messages_format.diary_chat_create_webpush,
            'whatsapp_template': messages_format.diary_chat_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['homework']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'pocket_money_deposit': {
        'data_to_save': {
            'api_name': 'pocket_money_deposit',
            'description': 'Pocket Money',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Pocket Money',
            'default_push_message': 'Pocket Money',
            'default_webpush_message': 'Pocket Money',
            'default_email_message': 'Pocket Money',
            'default_whatsapp_message': 'Pocket Money',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Pocket Money',
            'push_subject': 'Student Pocket Money',
            'sms_subject': 'Student Pocket Money',
            'webpush_subject': 'Student Pocket Money',
            'whatsapp_subject': 'Student Pocket Money',
            'email_template': messages_format.pocket_money_deposit_email,
            'sms_template': messages_format.pocket_money_deposit_sms,
            'push_template': messages_format.pocket_money_deposit_push,
            'webpush_template': messages_format.pocket_money_deposit_webpush,
            'whatsapp_template': messages_format.pocket_money_deposit_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['hostel']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'pocket_money_withdraw': {
        'data_to_save': {
            'api_name': 'pocket_money_withdraw',
            'description': 'Pocket Money',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Pocket Money',
            'default_push_message': 'Pocket Money',
            'default_webpush_message': 'Pocket Money',
            'default_email_message': 'Pocket Money',
            'default_whatsapp_message': 'Pocket Money',
            'notification_medium': ['email', 'sms','whatsapp'],
            'email_subject': 'Student Pocket Money',
            'push_subject': 'Student Pocket Money',
            'sms_subject': 'Student Pocket Money',
            'webpush_subject': 'Student Pocket Money',
            'whatsapp_subject': 'Student Pocket Money',
            'email_template': messages_format.pocket_money_withdraw_email,
            'sms_template': messages_format.pocket_money_withdraw_sms,
            'push_template': messages_format.pocket_money_withdraw_push,
            'webpush_template': messages_format.pocket_money_withdraw_webpush,
            'whatsapp_template': messages_format.pocket_money_withdraw_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['hostel']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'pocket_money_returnback': {
        'data_to_save': {
            'api_name': 'pocket_money_returnback',
            'description': 'Pocket Money',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Pocket Money',
            'default_push_message': 'Pocket Money',
            'default_webpush_message': 'Pocket Money',
            'default_email_message': 'Pocket Money',
            'default_whatsapp_message': 'Pocket Money',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Pocket Money Return Back',
            'push_subject': 'Student Pocket Money Return Back',
            'sms_subject': 'Student Pocket Money Return Back',
            'webpush_subject': 'Student Pocket Money Return Back',
            'whatsapp_subject': 'Student Pocket Money Return Back',
            'email_template': messages_format.pocket_money_reutrnback_email,
            'sms_template': messages_format.pocket_money_reutrnback_sms,
            'push_template': messages_format.pocket_money_reutrnback_push,
            'webpush_template': messages_format.pocket_money_reutrnback_webpush,
            'whatsapp_template': messages_format.pocket_money_reutrnback_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['hostel']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'rfid_attendance_create': {
        'data_to_save': {
            'api_name': 'rfid_attendance_create',
            'description': 'Student Attendance',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Student Attendance',
            'default_push_message': 'Student Attendance',
            'default_webpush_message': 'Student Attendance',
            'default_email_message': 'Student Attendance',
            'default_whatsapp_message': 'Student Attendance',
            'notification_medium': ['email', 'push', 'webpush','whatsapp'],
            'email_subject': 'Student Attendance Status',
            'push_subject': 'Student Attendance Status',
            'sms_subject': 'Student Attendance Status',
            'webpush_subject': 'Student Attendance Status',
            'whatsapp_subject': 'Student Attendance Status',
            'email_template': messages_format.rfid_attendance_create_email,
            'sms_template': messages_format.rfid_attendance_create_sms,
            'push_template': messages_format.rfid_attendance_create_push,
            'webpush_template': messages_format.rfid_attendance_create_webpush,
            'whatsapp_template': messages_format.rfid_attendance_create_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['attendance']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'adjustment_approval': {
        'data_to_save': {
            'api_name': 'adjustment_approval',
            'description': 'Adjustment Approval Request',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': 'Adjustment Approval Request Raised',
            'default_push_message': 'Adjustment Approval Request Raised',
            'default_webpush_message': 'Adjustment Approval Request Raised',
            'default_email_message': 'Adjustment Approval Request Raised',
            'default_whatsapp_message': 'Adjustment Approval Request Raised',
            'notification_medium': ['email', 'sms', 'push', 'webpush','whatsapp'],
            'email_subject': 'Adjustment Approval Request Raised',
            'push_subject': 'Adjustment Approval Request Raised',
            'sms_subject': 'Adjustment Approval Request Raised',
            'webpush_subject': 'Adjustment Approval Request Raised',
            'whatsapp_subject': 'Adjustment Approval Request Raised',
            'email_template': messages_format.adjustment_approval_email,
            'sms_template': messages_format.adjustment_approval_sms,
            'push_template': messages_format.adjustment_approval_push,
            'webpush_template': messages_format.adjustment_approval_webpush,
            'whatsapp_template': messages_format.adjustment_approval_whatsapp,
            'whatsapp_template_id':'',
            'type': available_types['concession']
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': '',
            'whatsapp':''
        },
        'priority': 'low',
    },
    'payout_error': {
        'data_to_save': {
            'api_name': 'payout_error',
            'description': 'Payout Error Description',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': '',
            'default_push_message': '',
            'default_webpush_message': '',
            'default_email_message': 'Payout failed',
            'notification_medium': ['email'],
            'email_subject': 'Payout Error details',
            'push_subject': 'Payout Error details',
            'sms_subject': 'Payout Error details',
            'webpush_subject': 'Payout Error details',
            'enable_school': 1,
            'whatsapp_template_id':'',
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': ''
        },
        'priority': 'low',
    },
    'low_balance_error': {
        'data_to_save': {
            'api_name': 'low_balance_error',
            'description': 'Low Cashfree Balance Error Description',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': '',
            'default_push_message': '',
            'default_webpush_message': '',
            'default_email_message': 'Low cashfree balance',
            'notification_medium': ['push'],
            'email_subject': 'Low cashfree balance',
            'push_subject': 'Low cashfree balance',
            'sms_subject': 'Low cashfree balance',
            'webpush_subject': 'Low cashfree balance',
            'enable_school': 1,
            'whatsapp_template_id':'',
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': ''
        },
        'priority': 'high',
    },
    'chat_send_message':{
        'data_to_save': {
            'api_name': 'chat_send_message',
            'description': 'Chat Send Notification From One User TO Other',
            'suggestion': '',
            'customized_message': '',
            'default_sms_message': '',
            'default_push_message': '',
            'default_webpush_message': '',
            'default_email_message': '',
            'notification_medium': ['email'],
            'email_subject': '',
            'push_subject': '',
            'sms_subject': '',
            'webpush_subject': '',
            'enable_school': 1,
            'type': available_types['attendance'],
            'whatsapp_template_id':'',
        },
        'default_to_fetching_fields': {
            'sms': '',
            'email': '',
            'push': '',
            'webpush': ''
        },
        'priority': 'high',
    },
    'visitor_management_create': {
        'data_to_save': {
            'api_name': 'visitor_management_create',
            'description': 'Visitor Management',
            'suggestion': '',
            'customized_message': '',
            'default_whatsapp_message': 'Visitor Management',
            'notification_medium': ['whatsapp'],
            'whatsapp_subject': 'Visitor Management',
            'whatsapp_template': messages_format.visitor_management_create_whatsapp,
            'whatsapp_template_id':'visitors_management_template',
            'type': available_types['visitor_management'],
        },
        'default_to_fetching_fields': {
            'whatsapp':''
        },
        'priority': 'low',
    }
}