# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('classes', '0003_initial'),
        ('diary', '0001_initial'),
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiary',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_diary', to='students.student'),
        ),
        migrations.AddField(
            model_name='standardsectiondiary',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_standard', to='diary.diary'),
        ),
        migrations.AddField(
            model_name='standardsectiondiary',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_diary', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='staffdiary',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_staff', to='diary.diary'),
        ),
        migrations.AddField(
            model_name='staffdiary',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_diary', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='documentdiary',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_document', to='diary.diary'),
        ),
        migrations.AddField(
            model_name='documentdiary',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_diary', to='shared.document'),
        ),
    ]
