# Generated by Django 3.2 on 2023-05-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_student_can_update',
            field=models.BooleanField(default=True),
        ),
    ]
