# Generated by Django 3.2 on 2023-06-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_is_student_can_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiary',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
