# Generated by Django 3.2 on 2025-03-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0017_custom_resourse'),
        ('classes', '0023_staffstandardsectionmapping_studentleavedates_studentleaves_studentleavetype_studentleavetypeacademi'),
        ('diary', '0005_studentdiary_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiaryTitleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_diary_title_mapping_diary_title', to='institutes.reason')),
                ('student_diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_diary_title_mapping_student_diary', to='diary.studentdiary')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiarySubjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_diary_subject_mapping_student_diary', to='diary.studentdiary')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_diary_subject_mapping_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiaryRemarkMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.reason')),
                ('student_diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_diary_remark_mapping_student_diary', to='diary.studentdiary')),
            ],
        ),
    ]
