# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedulemapping',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentmarksectionwiseapproval',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam'),
        ),
        migrations.AddField(
            model_name='studentmarksectionwiseapproval',
            name='result_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentmarksection_result_config', to='exams.resultconfiguration'),
        ),
        migrations.AddField(
            model_name='studentmarksectionwiseapproval',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examschedule'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
    ]
