# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_initial'),
        ('exams', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='changed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_changed_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_exam', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='result_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_result', to='exams.resultconfiguration'),
        ),
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_section_result', to='exams.resultconfiguration'),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='standard_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_section_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_section_subject', to='classes.subject'),
        ),
        migrations.AddField(
            model_name='resultmarksconfiguration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_marks_configuration_exam', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='resultmarksconfiguration',
            name='result_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_marks_configuration_result_section', to='exams.resultsectionmapping'),
        ),
        migrations.AddField(
            model_name='resultconfiguration',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_configuration_academic_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='resultconfiguration',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_configuration_term', to='exams.examterm'),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standard'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='sub_schedule_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_sub_schedule_parent', to='exams.examschedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_type_related', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_term', to='exams.examterm'),
        ),
    ]
