# Generated by Django 2.2.24 on 2021-08-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    def initial_terms(apps, schema_editor):
        ExamTerm = apps.get_model('exams', 'ExamTerm')
        ExamTerm.objects.bulk_create([
            ExamTerm(name='Term 1', code='term1'),
            ExamTerm(name='Term 2', code='term2'),
        ])

    dependencies = [
        ('exams', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(initial_terms)
    ]
