# Generated by Django 3.2 on 2022-10-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_cumulativetype'),
        ('students', '0003_auto_20220925_2227'),
        ('staffs', '0002_staffstandardmapping'),
        ('exams', '0004_custom_exam_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleCumulativeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.FloatField(null=True)),
                ('min_marks', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cumulative_type', models.ManyToManyField(related_name='exam_schedule_cumulative_mapping_cumulative_type', to='classes.CumulativeType')),
            ],
        ),
        migrations.CreateModel(
            name='GradePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_standard_section',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='standard_ids',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='modified',
        ),
        migrations.CreateModel(
            name='StudentCumulativeMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam_cumulative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_cumulative_mark_cumulative', to='exams.examschedulecumulativemapping')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradeExamScheduleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
                ('grade_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_exam_schedule_mapping_grade_plan', to='exams.gradeplan')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standardsectionmapping')),
            ],
        ),
        migrations.AddField(
            model_name='examschedulecumulativemapping',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_cumulative_mapping_exam_schedule', to='exams.examschedule'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_grade_plan', to='exams.gradeplan'),
        ),
    ]
