# Generated by Django 3.2 on 2022-10-20 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_cumulativetype'),
        ('institutes', '0006_institute_name'),
        ('students', '0003_auto_20220925_2227'),
        ('exams', '0005_auto_20221010_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_min_marks', models.FloatField(null=True)),
                ('is_fail_if_not_min', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('0', 'Unapproved'), ('1', 'Approved'), ('2', 'Rejected'), ('3', 'Pending')], default='0', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_configuration_exam', to='exams.exam')),
                ('grade_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_configuration_grade_plan', to='exams.gradeplan')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_configuration_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResultConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_result_configs_academic_year', to='institutes.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='examschedule',
            name='next_linking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_next_linking_id', to='exams.examschedule'),
        ),
        migrations.AlterField(
            model_name='resultconfiguration',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_configuration_term', to='exams.examterm'),
        ),
        migrations.AlterField(
            model_name='resultmarksconfiguration',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_marks_configuration_exam', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='resultmarksconfiguration',
            name='result_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_marks_configuration_result_section', to='exams.resultsectionmapping'),
        ),
        migrations.AlterField(
            model_name='resultsectionmapping',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_result', to='exams.resultconfiguration'),
        ),
        migrations.AlterField(
            model_name='resultsectionmapping',
            name='standard_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.AlterField(
            model_name='resultsectionmapping',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_subject', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='studentexamfinalresult',
            name='changed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exam_changed_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentexamfinalresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exam_exam', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='studentexamfinalresult',
            name='result_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exam_result', to='exams.resultconfiguration'),
        ),
        migrations.AlterField(
            model_name='studentexamfinalresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exam_student', to='students.student'),
        ),
        migrations.CreateModel(
            name='FinalResultMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail')], max_length=10)),
                ('marks_json', models.JSONField(null=True)),
                ('is_announced', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('final_result_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_mark_final_result_config', to='exams.finalresultconfig')),
                ('grade_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_marks_grade_plan', to='exams.gradeplan')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_mark_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultSubjectConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_max_marks', models.FloatField(null=True)),
                ('configured_min_marks', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam_result_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_subject_configuration_exam_result_configuration', to='exams.examresultconfiguration')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_subject_configuration_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultMarksObtained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained_marks', models.FloatField(null=True)),
                ('marks_json', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam_result_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_marks_obtained_exam_result_configuration', to='exams.examresultconfiguration')),
                ('grade_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_marks_obtained_grade_plan', to='exams.gradeplan')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_marks_obtained_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultCumulativeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_max_marks', models.FloatField(null=True)),
                ('configured_min_marks', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cumulative_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_cumulative_config_cumulative_type', to='classes.cumulativetype')),
                ('exam_result_subject_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_cumulative_config_exam_result_subject_config', to='exams.examresultsubjectconfiguration')),
            ],
        ),
    ]
