# Generated by Django 3.2 on 2022-11-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20221020_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalresultmark',
            name='final_result_config',
        ),
        migrations.RemoveField(
            model_name='finalresultmark',
            name='grade_plan',
        ),
        migrations.RemoveField(
            model_name='finalresultmark',
            name='student',
        ),
        migrations.RenameField(
            model_name='examresultcumulativeconfiguration',
            old_name='configured_max_marks',
            new_name='configured_marks',
        ),
        migrations.RenameField(
            model_name='examresultsubjectconfiguration',
            old_name='configured_max_marks',
            new_name='configured_marks',
        ),
        migrations.RemoveField(
            model_name='examresultcumulativeconfiguration',
            name='configured_min_marks',
        ),
        migrations.RemoveField(
            model_name='examresultcumulativeconfiguration',
            name='cumulative_type',
        ),
        migrations.AddField(
            model_name='examresultconfiguration',
            name='is_announced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresultcumulativeconfiguration',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresultcumulativeconfiguration',
            name='schedule_cumulative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_cumulative_config_cumulative_type', to='exams.examschedulecumulativemapping'),
        ),
        migrations.AddField(
            model_name='examresultmarksobtained',
            name='total_configured_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='examresultsubjectconfiguration',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FinalResultConfig',
        ),
        migrations.DeleteModel(
            name='FinalResultMark',
        ),
    ]
