# Generated by Django 3.2 on 2022-11-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_subject_part_type'),
        ('exams', '0007_auto_20221120_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresultmarksobtained',
            name='marks_json',
        ),
        migrations.AddField(
            model_name='resultmarksconfiguration',
            name='cum_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultmarksconfiguration',
            name='is_cum_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultmarksconfiguration',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ResultSectionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.BooleanField(default=False)),
                ('is_announced', models.BooleanField(default=False)),
                ('is_announced_for_academic', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('grade_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_approval_grade_plan', to='exams.gradeplan')),
                ('result_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_approval_result_config', to='exams.resultconfiguration')),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_approval_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
    ]
