# Generated by Django 3.2 on 2023-01-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0007_visitordocumentmapping'),
        ('classes', '0007_subject_part_type'),
        ('exams', '0008_auto_20221128_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsectionapproval',
            name='is_announced_for_academic',
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='final_result_configured_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='final_result_configured_min_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='final_result_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='final_result_min_for_subject',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ExamFinalResultConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_max_marks', models.FloatField(null=True)),
                ('total_min_marks', models.FloatField(null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_final_result_configuration_academic_year', to='institutes.academicyear')),
                ('grade_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_final_result_configuration_grade_plan', to='exams.gradeplan')),
                ('result_config_term', models.ManyToManyField(blank=True, related_name='exam_final_result_configuration_result_config_term', to='exams.ResultConfiguration')),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_final_result_configuration_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
    ]
