# Generated by Django 3.2 on 2023-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20230109_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmarksconfiguration',
            name='cum_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resultmarksconfiguration',
            name='is_cum_disabled',
            field=models.BooleanField(null=True),
        ),
    ]
