# Generated by Django 3.2 on 2023-06-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20230114_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamschedulemapping',
            name='is_final_marks_grade_plan',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gradeplan',
            name='is_percentage',
            field=models.BooleanField(default=True),
        ),
    ]
