# Generated by Django 3.2 on 2023-07-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20230626_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamschedulemapping',
            name='grade_plan_for_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_exam_schedule_mapping_grade_plan_for_total', to='exams.gradeplan'),
        ),
    ]
