# Generated by Django 3.2 on 2023-08-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_gradeexamschedulemapping_grade_plan_for_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='grade_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_grade_plan', to='exams.gradeplan'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='is_marks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradeplan',
            name='grade_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcumulativemark',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
