# Generated by Django 3.2 on 2023-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20230819_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='totalgrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
