# Generated by Django 3.2 on 2023-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_studentexamfinalresult_totalgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='is_sub_disabled_for_halticket',
            field=models.BooleanField(default=False),
        ),
    ]
