# Generated by Django 3.2 on 2023-11-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_machineuserlog_operation_id'),
        ('exams', '0015_examschedule_is_sub_disabled_for_halticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultConfigurationMergeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='examterm',
            name='alias_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resultmarksconfiguration',
            name='is_only_grade_for_config',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='resultsectionapproval',
            name='total_grade_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_approval_total_grade_plan', to='exams.gradeplan'),
        ),
        migrations.AddField(
            model_name='resultsectionmapping',
            name='grade_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_section_mapping_grade_plan', to='exams.gradeplan'),
        ),
        migrations.AlterField(
            model_name='resultmarksconfiguration',
            name='marks',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ResultConfigurationMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam', models.ManyToManyField(blank=True, related_name='result_configuration_merge_exam', to='exams.Exam')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_configuration_merge_name', to='exams.resultconfigurationmergename')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_configuration_merge_result', to='exams.resultconfiguration')),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_configuration_merge_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
    ]
