# Generated by Django 3.2 on 2024-03-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_auto_20231109_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultconfiguration',
            name='remarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_configuration_remarks', to='exams.gradeplan'),
        ),
        migrations.AddField(
            model_name='examresultconfiguration',
            name='total_grade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result_configuration_total_grade_plan', to='exams.gradeplan'),
        ),
    ]
