# Generated by Django 3.2 on 2024-07-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0014_banner_user_type'),
        ('exams', '0017_auto_20240330_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamschedulemapping',
            name='max_no_of_days_attendance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marked_attendance_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marked_attendance_is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mark_remark', to='institutes.reason'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='remark_is_global',
            field=models.BooleanField(default=True),
        ),
    ]
