# Generated by Django 3.2 on 2025-04-01 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_staffstandardsectionmapping_studentleavedates_studentleaves_studentleavetype_studentleavetypeacademi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0010_auto_20240730_1717'),
        ('institutes', '0017_custom_resourse'),
        ('exams', '0018_auto_20240724_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResultConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_configuration_academic_year', to='institutes.academicyear')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_configuration_exam', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResultConfigurationMergeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamFinalResultForFinalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail')], max_length=10)),
                ('is_announced', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('totalgrade', models.CharField(blank=True, max_length=10, null=True)),
                ('changed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_student_exam_changed_user_id', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_student_exam_exam', to='exams.exam')),
                ('final_result_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_student_exam_result', to='exams.finalresultconfiguration')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_student_exam_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResultSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_marks', models.FloatField(null=True)),
                ('max_marks', models.FloatField(null=True)),
                ('final_result_configured_marks', models.FloatField(null=True)),
                ('final_result_configured_min_marks', models.FloatField(null=True)),
                ('final_result_disabled', models.BooleanField(default=False)),
                ('final_result_min_for_subject', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('final_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_result', to='exams.finalresultconfiguration')),
                ('grade_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_mapping_grade_plan', to='exams.gradeplan')),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_standard_section', to='classes.standardsectionmapping')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_subject', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResultSectionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.BooleanField(default=False)),
                ('is_announced', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('final_result_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_approval_result_config', to='exams.finalresultconfiguration')),
                ('grade_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_approval_grade_plan', to='exams.gradeplan')),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_approval_standard_section', to='classes.standardsectionmapping')),
                ('total_grade_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_section_approval_total_grade_plan', to='exams.gradeplan')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResultMarksConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(null=True)),
                ('cum_marks', models.FloatField(null=True)),
                ('is_disabled', models.IntegerField(default=0)),
                ('is_cum_disabled', models.BooleanField(null=True)),
                ('is_only_grade_for_config', models.BooleanField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_marks_configuration_exam', to='exams.exam')),
                ('result_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_marks_configuration_result_section', to='exams.finalresultsectionmapping')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResultConfigurationMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam', models.ManyToManyField(blank=True, related_name='final_result_configuration_merge_exam', to='exams.Exam')),
                ('final_result_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_configuration_merge_result', to='exams.finalresultconfiguration')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_configuration_merge_name', to='exams.resultconfigurationmergename')),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_result_configuration_merge_standard_section', to='classes.standardsectionmapping')),
            ],
        ),
    ]
