# Generated by Django 3.2 on 2025-07-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_finalresultconfiguration_finalresultconfigurationmerge_finalresultconfigurationmergename_finalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='section_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamfinalresult',
            name='standard_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
