# Generated by Django 3.2 on 2025-07-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0020_auto_20250729_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarkAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='exams.studentmark')),
            ],
            options={
                'ordering': ['-edited_on'],
            },
        ),
    ]
