# Generated by Django 3.2 on 2025-07-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_studentmarkauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='schedule_sequence',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_fail_grade',
            field=models.BooleanField(default=False),
        ),
    ]
