# Generated by Django 3.2 on 2025-09-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_staff_blood_group'),
        ('students', '0010_auto_20240730_1717'),
        ('classes', '0028_courseoutcome_programoutcome_programspecificoutcome_staffsubjectdetails_subjectcategory_subjectcours'),
        ('exams', '0022_auto_20250731_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleQuestionmapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=255)),
                ('sub_question_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('max_marks', models.FloatField(null=True)),
                ('min_marks', models.FloatField(null=True)),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_question_mapping_course_outcome', to='classes.courseoutcome')),
                ('exam_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examschedule')),
                ('option_link_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedule_question_mapping_option_link_id', to='exams.examschedulequestionmapping')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarkQuestionWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam_schedule_question_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examschedulequestionmapping')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
