# Generated by Django 3.2 on 2025-10-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_examschedulequestionmapping_studentmarkquestionwise'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeexamschedulemapping',
            name='attendance_from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradeexamschedulemapping',
            name='attendance_to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
