# Generated by Django 3.2 on 2025-10-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0030_auto_20251010_1108'),
        ('exams', '0024_auto_20251010_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='marksentry_lastdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='questionframe_lastdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentMarkSectionSubjectWiseApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('0', 'Unapproved'), ('1', 'Finalized')], default='0', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
                ('standard_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standardsectionmapping')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.subject')),
            ],
        ),
    ]
