# Generated by Django 3.2 on 2025-10-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_auto_20251010_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='grade',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
