# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_or_husband_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_num', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_num', models.CharField(blank=True, max_length=255, null=True)),
                ('alternate_mobile_num', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_status', models.CharField(choices=[('F', 'Fulltime'), ('P', 'Parttime'), ('C', 'Contract')], default='F', max_length=1)),
                ('frequency', models.CharField(blank=True, choices=[('M', 'Month'), ('W', 'Week'), ('H', 'Hour'), ('D', 'Day')], max_length=1, null=True)),
                ('measure', models.IntegerField(blank=True, null=True)),
                ('previous_job_details', models.JSONField(null=True)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_in_num', models.CharField(blank=True, max_length=255, null=True)),
                ('dl_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile_pic', to='shared.document')),
            ],
        ),
        migrations.CreateModel(
            name='StaffNomineeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_num', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_detail', to='staffs.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CP', 'CurrentPermanent'), ('C', 'Current'), ('P', 'Permanent')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.district')),
                ('map_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.mapaddress')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_address', to='staffs.staff')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.state')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_num', models.CharField(max_length=255)),
                ('mobile_num', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('pan_num', models.CharField(blank=True, max_length=255, null=True)),
                ('pf_num', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='staffs.staff')),
            ],
        ),
    ]
