# Generated by Django 3.2 on 2022-07-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_custom_standard_data'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffStandardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_standard_mapping_staff', to='staffs.staff')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_standard_mapping_standard', to='classes.standard')),
            ],
        ),
    ]
