# Generated by Django 3.2 on 2024-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_department_departmentmanager_departmentstaffmapping_staffsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='esi_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='uan_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
