# Generated by Django 3.2 on 2024-07-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0037_alter_documenttype_group_type'),
        ('staffs', '0004_auto_20240326_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_nationality', to='shared.nationality'),
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_religion', to='shared.religion'),
        ),
        migrations.CreateModel(
            name='StaffDocumentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_document_mapping_document', to='shared.document')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_document_mapping_document_type', to='shared.documenttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_document_mapping_staff', to='staffs.staff')),
            ],
        ),
    ]
