# Generated by Django 3.2 on 2025-02-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_staffstandardsectionmapping_studentleavedates_studentleaves_studentleavetype_studentleavetypeacademi'),
        ('staffs', '0005_auto_20240709_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentstaffmapping',
            name='dept_no',
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_branch', to='classes.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentstaffmapping',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='staffs.department'),
            preserve_default=False,
        ),
    ]
