# Generated by Django 3.2 on 2026-03-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_staffstandardsectionmapping_allocation_type'),
        ('staffs', '0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaffmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departmentstaffmapping',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_staff_mapping_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_branch', to='classes.branch'),
        ),
    ]
