# Generated by Django 3.2 on 2026-05-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_auto_20260330_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsalary',
            name='is_active',
        ),
    ]
