# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_initial'),
        ('quiz', '0002_initial'),
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
        ('institutes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_evaluted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_form', to='quiz.form'),
        ),
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='question_document', to='shared.Document'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_form', to='quiz.form'),
        ),
        migrations.AddField(
            model_name='matchthefollowing',
            name='choice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_the_following_choice', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='matchthefollowing',
            name='correct_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_the_following_correct_match', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='matchthefollowing',
            name='shuffled_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_the_following_shuffled_match', to='quiz.choice'),
        ),
        migrations.AddField(
            model_name='formstandardsectionmapping',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_standard_section_mapping_form', to='quiz.form'),
        ),
        migrations.AddField(
            model_name='formstandardsectionmapping',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_standard_section_mapping_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='form',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_academic_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='form',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_document', to='shared.document'),
        ),
        migrations.AddField(
            model_name='form',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_subject', to='classes.subject'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choice_answer_choice', to='quiz.Choice'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer_document', to='shared.document'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer_evaluted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer_question', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer_response', to='quiz.response'),
        ),
        migrations.AddField(
            model_name='choice',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_document', to='shared.document'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_question', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='alternateteachermapping',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_teacher_mapping_form', to='quiz.form'),
        ),
        migrations.AddField(
            model_name='alternateteachermapping',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_teacher_mapping_staff', to='staffs.staff'),
        ),
    ]
