# Generated by Django 3.2 on 2023-02-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
