# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('students', '0001_initial'),
        ('institutes', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userattendance_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userattendance_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomallocation_room', to='institutes.room'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomallocation_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomallocation_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='depositandwithdraw',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_and_with_draw_academic_year', to='institutes.academicyear'),
        ),
    ]
