# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositandwithdraw',
            name='deposited_or_withdraw_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_and_with_draw_deposited_or_withdraw_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositandwithdraw',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_and_with_draw_student', to='students.student'),
        ),
    ]
