import React from "react";
import { GET_URL, POST_URL, PATCH_URL } from "Includes/urls";

import PermissionsView from "Containers/GroupsPermissions/PermissionsView";
import AssignGroups from "Containers/GroupsPermissions/AssignGroup";
import AddCustomizeMenu from "Containers/GroupsPermissions/AddCustomizeMenu";
import SettingView from "Containers/Setting/SettingView";
import FormDefinitionView from "Containers/Admin/FormDefinition/FormDefinitionView";
import FormDefinitionEdit from "Containers/Admin/FormDefinition/FormDefinitionEdit";
import AddInvoiceMapping from "Containers/Invoices/AddInvoiceMapping";
import ViewInvoiceMapping from "Containers/Invoices/ViewInvoiceMapping";
import ViewCustomForm from "Containers/Admin/CustomForm/ViewCustomForm";
import AddCustomForm from "Containers/Admin/CustomForm/AddCustomForm";
import SyncPage from "Containers/Admin/SyncPage";
import ViewFeeTermBenificiary from "Containers/Finance/ViewFeeTermBenificiary";
import CreateFeeTermBenificiary from "Containers/Finance/CreateFeeTermBenificiary";
import DummyReciept from "Containers/Finance/Components/DummyReciept";
import StudentUserNameList from "Containers/Student/StudentUserNameList";
import StudentUserNameAdd from "Containers/Student/StudentUserNameAdd";
import UsersActiveList from "Containers/Enrolement/UsersActiveList";
import BirthdayList from "Containers/Student/BirthdayList";
import Settings from "Containers/Settings";
import PrivacyPolicy from "Containers/PrivacyPolicy"

const Actions = {
  admin_permissions: {
    view: {
      codenames: [
        GET_URL.groups.basename,
        GET_URL.users.basename,
        GET_URL.permissionlist.basename,
        GET_URL.staffpermissionlist.basename,
        PATCH_URL.groups.basename,
        PATCH_URL.users.basename,
      ],
      action_code: "visible_admin_permissions_view",
      is_superuser_action: true,
      name: "Add Permissions",
      label: "Permissions",
      action: "sub-menu",
      url: "/admin/permissions/view",
      component: <PermissionsView />,
      permission_needed: true,
    },
    name: "Permissions View",
    type: "admin",
  },
  customize_menu: {
    create: {
      codenames: [],
      action_code: "",
      is_superuser_action: true,
      name: "Customize Menu",
      label: "Customize Menu",
      action: "sub-menu",
      url: "/admin/customize-menu",
      component: <AddCustomizeMenu />,
      permission_needed: false,
    },
    name: "Customize View",
    type: "admin",
  },
  settings_form: {
    view: {
      codenames: [],
      action_code: "",
      is_superuser_action_only: true,
      name: "Setting",
      label: "Setting",
      action: "sub-menu",
      url: "/admin/settings_form",
      component: <SettingView />,
      permission_needed: false,
    },
    name: "Setting Forms",
    type: "admin",
  },
  form_definition: {
    view: {
      codenames: [],
      action_code: "",
      is_superuser_action: true,
      name: "Form_Definition",
      label: "Form Definition View",
      action: "sub-menu",
      url: "/admin/form-definition",
      component: <FormDefinitionView />,
      permission_needed: false,
      associated_urls: ["/admin/form-definition/edit"],
    },
    update: {
      codenames: [],
      action_code: "",
      is_superuser_action: true,
      name: "Form_Definition",
      label: "Form Definition Edit",
      action: "action-url",
      url: "/admin/form-definition/edit",
      component: <FormDefinitionEdit />,
      permission_needed: false,
    },
    name: "Form Definition",
    type: "admin",
  },
  invoice_mapping: {
    create: {
      codenames: [],
      action_code: "visible_invoice_mapping_add",
      is_superuser_action: false,
      name: "Add Invoice Mapping",
      label: "Add Invoice Mapping",
      action: "action-url",
      url: "/templatemapping/add",
      component: <AddInvoiceMapping />,
      permission_needed: true,
    },
    view: {
      codenames: [],
      action_code: "visible_invoice_mapping_view",
      is_superuser_action: false,
      name: "View Template Mapping",
      label: "View Template Mapping",
      action: "sub-menu",
      url: "/templatemapping",
      component: <ViewInvoiceMapping />,
      permission_needed: true,
      associated_urls: ["/templatemapping/add"],
    },
    name: "Invoice Mapping",
    type: "Invoice",
  },
  custom_form: {
    view: {
      codenames: [],
      action_code: "visible_custom_form_view",
      is_superuser_action_only: true,
      name: "Custom Form",
      label: "Custom Form",
      action: "sub-menu",
      url: "/customform/view",
      component: <ViewCustomForm />,
      permission_needed: true,
      associated_urls: [
        "/transport/gpsmachine/add",
        "/transport/gpsmachine/edit",
      ],
    },
    create: {
      codenames: [],
      action_code: "visible_custom_form_add",
      is_superuser_action_only: true,
      name: "Custom Form",
      label: "Create Custom Form",
      action: "action-url",
      url: "/customform/add",
      component: <AddCustomForm />,
      permission_needed: true,
    },
    update: {
      codenames: [],
      action_code: "visible_custom_form_edit",
      is_superuser_action_only: true,
      name: "Custom Form",
      label: "Create Custom Form",
      action: "action-url",
      url: "/customform/edit",
      component: <AddCustomForm />,
      permission_needed: true,
    },
    delete: {
      codenames: [],
      action_code: "visible_custom_form_delete",
      is_superuser_action_only: true,
      name: "Delete Custom Form",
      label: "Delete",
      action: "action",
      permission_needed: true,
    },
    name: "Custom Form",
    type: "admin",
  },
  sync_page: {
    view: {
      codenames: [],
      action_code: "",
      name: "Sync Page",
      label: "Sync Page",
      action: "sub-menu",
      url: "/admin/syncpage",
      component: <SyncPage />,
      is_superuser_action_only: true,
      permission_needed: false,
    },
    name: "Sync Page",
    type: "admin",
  },
  fee_term_benificiary: {
    view: {
      codenames: [],
      action_code: "visible_fee_term_benificiary_view",
      name: "View Fee Term Benificiary",
      label: "Fee Term Benificiary",
      action: "sub-menu",
      associated_urls: ["/admin/feeterm/benificiary/create/"],
      url: "/admin/feeterm/benificiary/view",
      component: <ViewFeeTermBenificiary />,
      is_superuser_action_only: true,
      permission_needed: false,
      exclude_roles: [7],
    },
    create: {
      codenames: [],
      action_code: "visible_fee_term_benificiary_add",
      name: "Fee Term Benificiary",
      label: "Fee Term Benificiary",
      action: "action-url",
      url: "/admin/feeterm/benificiary/create",
      component: <CreateFeeTermBenificiary />,
      is_superuser_action_only: true,
      permission_needed: false,
      exclude_roles: [7],
    },
    name: "Fee Term Benificary",
    type: "admin",
  },
  fee_reciept_sample: {
    view: {
      codenames: [],
      action_code: "visible_fee_reciept_sample_view",
      is_superuser_action: false,
      name: "Fee Reciept Sample",
      label: "Fee Reciept Sample",
      action: "sub-menu",
      associated_urls: [],
      url: "/admin/fee/reciept/sample",
      component: <DummyReciept />,
      is_superuser_action_only: true,
      permission_needed: false,
      exclude_roles: [7],
    },
    name: "Fee Reciept Sample",
    type: "admin",
  },
  student_username_list: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandardandsection.basename,
        GET_URL.student.basename,
      ],
      action_code: "visible_student_username_list_view",
      is_superuser_action: false,
      name: "Student User Name",
      label: "Student User Name",
      action: "sub-menu",
      url: "/student/username/list",
      component: <StudentUserNameList />,
      permission_needed: true,
      associated_urls: ["/student/username/add"],
    },
    create: {
      codenames: [GET_URL.student.basename, POST_URL.updateuserdata.basename],
      action_code: "visible_student_username_list_add",
      is_superuser_action: false,
      name: "Student User Name",
      label: "Modify UserName",
      action: "action-url",
      url: "/student/username/add",
      component: <StudentUserNameAdd />,
      permission_needed: true,
    },
    name: "Student User Name List",
    type: "admin",
  },
  student_admission_list: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandardandsection.basename,
        GET_URL.student.basename,
      ],
      action_code: "visible_student_admission_list_view",
      is_superuser_action: false,
      name: "Student Admission Number",
      label: "Student Admission Number",
      action: "sub-menu",
      url: "/student/admissionnum/list",
      component: <StudentUserNameList />,
      permission_needed: true,
      associated_urls: ["/student/admissionnum/add"],
    },
    create: {
      codenames: [GET_URL.student.basename, POST_URL.updateuserdata.basename],
      action_code: "visible_student_admission_list_add",
      is_superuser_action: false,
      name: "Student Admission Number",
      label: "Student Admission Number",
      action: "action-url",
      url: "/student/admissionnum/add",
      component: <StudentUserNameAdd />,
      permission_needed: true,
    },
    name: "Student Admission List",
    type: "admin",
  },
  user_active_list: {
    view: {
      codenames: [
        GET_URL.userreport.basename,
        GET_URL.student.basename,
        GET_URL.staff.basename,
        GET_URL.getstandard.basename,
      ],
      action_code: "visible_user_active_list_view",
      is_superuser_action: false,
      name: "User Active List",
      label: "User Active List",
      action: "sub-menu",
      url: "/user/active/list",
      component: <UsersActiveList />,
      permission_needed: true,
    },
    name: "User Active List",
    type: "admin",
  },
  user_birthday_list: {
    view: {
      codenames: [GET_URL.userbirthday.basename],
      action_code: "visible_user_birthday_list_view",
      is_superuser_action: false,
      name: "User Birthdays",
      label: "User Birthdays",
      action: "sub-menu",
      url: "/user/birthday/list",
      component: <BirthdayList />,
      permission_needed: true,
    },
    name: "User Birthdays",
    type: "admin",
  },
  settings: {
    view: {
      codenames: [],
      action_code: "visible_settings_view",
      is_superuser_action: false,
      name: "Setting",
      label: "Setting",
      action: "sub-menu",
      url: "/settings",
      component: <Settings />,
      permission_needed: true,
    },
    name: "Settings",
    type: "admin",
  },
  privacypolicy: {
    view: {
      codenames: [],
      action_code: "",
      is_superuser_action_only: false,
      name: "Setting",
      label: "Setting",
      action: "sub-menu",
      url: "/admin/privacypolicy",
      component: <PrivacyPolicy />,
      permission_needed: false,
    },
    name: "Setting",
    type: "admin",
  },
};

export default Actions;
