import React, { lazy } from 'react';
import { FormattedMessage } from 'react-intl';
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from 'Includes/urls';
import commonMessages from 'Constants/messages'
import messages from './messages';
// import StrengthCards from 'Containers/BasicDetails/StrengthCards';
import DynamicAcadamic from 'Containers/BasicDetails/DynamicAcadamic';
import SchoolBasicView from 'Containers/BasicDetails/SchoolBasicView';
import ManageYear from 'Containers/BasicDetails/ManageYear';
import AcademicYearList from 'Containers/BasicDetails/AcademicYearList';
import FinancialYearList from 'Containers/BasicDetails/FinancialYearList'
import ManageFinancialYear from 'Containers/BasicDetails/ManageFinancialYear'
import ManageSection from 'Containers/BasicDetails/ManageSection';
import ManageSectionView from 'Containers/BasicDetails/ManageSectionView';
import ManageSubjects from 'Containers/BasicDetails/ManageSubjects';
import ManageSubjectView from 'Containers/BasicDetails/ManageSubjectView';
import ManageSubjectEngineer from 'Containers/BasicDetails/ManageSubjectEngineer';
import ManageSubjectViewEngineer from 'Containers/BasicDetails/ManageSubjectViewEngineer';
import BasicSchool from 'Containers/BasicDetails/Components/BasicSchool';
import FormatGenerator from 'Containers/BasicDetails/FormatGenerator';
import BannerList from 'Containers/BasicDetails/BannerList';
import AddBanner from 'Containers/BasicDetails/AddBanner';
import SchoolBuildingList from 'Containers/BasicDetails/SchoolBuildingList';
import AddSchoolBuilding from 'Containers/BasicDetails/AddSchoolBuilding';
import ViewIndividualSchoolBuilding from 'Containers/BasicDetails/ViewIndividualSchoolBuilding';
import VisitorReasonList from 'Containers/BasicDetails/VisitorReasonList';
import AddVisitorReason from 'Containers/BasicDetails/AddVisitorReason';
import SchoolAddressView from 'Containers/BasicDetails/SchoolAddressView';
import SchoolAddressAdd from 'Containers/BasicDetails/SchoolAddressAdd';
import SchoolAddressIndividualView from 'Containers/BasicDetails/SchoolAddressIndividualView';
import SchoolTimingView from 'Containers/BasicDetails/SchoolTimingView';
import SchoolTimingAdd from 'Containers/BasicDetails/SchoolTimingAdd';
import SchoolTimingIndividualView from 'Containers/BasicDetails/SchoolTimingIndividualView';
import AssignTeacher from 'Containers/BasicDetails/AssignTeacher';
import ViewAssignTeacher from 'Containers/BasicDetails/ViewAssignTeacher';
import ManageDepartment from 'Containers/BasicDetails/AddDepartment'
import ManageDepartmentView from 'Containers/BasicDetails/ViewDepartment';
import AddSubjectCategory from 'Containers/BasicDetails/AddSubjectCategory';
import ViewSubjectCategory from 'Containers/BasicDetails/ViewSubjectCategory';
import StaffDepartmentMapping from 'Containers/BasicDetails/StaffDepartmentMapping';
import StaffDepartmentMappingView from 'Containers/BasicDetails/StaffDepartmentMappingView';
import AddSubjectDetails from 'Containers/BasicDetails/AddSubjectDetails'
import MentorStudentList from 'Containers/BasicDetails/MentorStudentList'

const StrengthCards = lazy(() => import('Containers/BasicDetails/StrengthCards'));

const alias_names = JSON.parse(localStorage.getItem('alias_name')) ? JSON.parse(localStorage.getItem('alias_name')) : {}


const Actions = {
    school_details: {
        view: {
            codenames: [GET_URL.institute.basename],
            action_code: 'visible_school_details_view',
            is_superuser_action: false,
            name: `${alias_names['school']} Details`,
            label: `${alias_names['school']} Details`,
            action: 'sub-menu',
            url: '/basicdetails/school/view',
            component: <SchoolBasicView />,
            permission_needed: true,
            associated_urls: ['/basicdetails/school/add', '/basicdetails/school/edit'],
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [GET_URL.country.basename, GET_URL.getstatesforcountry.basename, GET_URL.getdistrictsforstate.basename,
            GET_URL.getcitiesfordistrict.basename, POST_URL.uploads.basename],
            action_code: 'visible_school_details_add',
            is_superuser_action: false,
            name: `${alias_names['school']} Details`,
            label: `${alias_names['school']} Details`,
            action: 'action-url',
            url: '/basicdetails/school/add',
            component: <BasicSchool />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [GET_URL.country.basename, GET_URL.institute.basename, GET_URL.getstatesforcountry.basename,
            GET_URL.getdistrictsforstate.basename, GET_URL.getcitiesfordistrict.basename, PUT_URL.institute.basename,
            POST_URL.uploads.basename],
            action_code: 'visible_school_details_change',
            is_superuser_action: false,
            name: 'Update School Details',
            label: `${alias_names['school']} Details`,
            action: 'action-url',
            url: '/basicdetails/school/edit',
            component: <BasicSchool />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: `${alias_names['school']} Details`,
        type: 'basic_info',
    },
    academic_year: {
        view: {
            codenames: [GET_URL.academicyear.basename],
            action_code: 'visible_academic_year_view',
            is_superuser_action: false,
            name: 'View Academic Year',
            label: 'Academic Year',
            action: 'sub-menu',
            url: '/basicdetails/academic/view',
            component: <AcademicYearList />,
            permission_needed: true,
            associated_urls: ['/basicdetails/academic/add'],
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [POST_URL.academicyear.basename],
            action_code: 'visible_academic_year_add',
            is_superuser_action: false,
            name: 'Create Academic Year',
            label: 'Academic Year',
            action: 'action-url',
            url: '/basicdetails/academic/add',
            component: <ManageYear />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.academicyear.basename],
            action_code: 'visible_academic_year_change',
            is_superuser_action: false,
            name: 'Update Academic Year',
            label: 'Academic Year',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.academicyear.basename],
            action_code: 'visible_academic_year_delete',
            is_superuser_action: false,
            name: 'Delete Year',
            label: 'Academic Year',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Academic Year',
        type: 'basic_info',

    },
    financial_year: {
        view: {
            codenames: [GET_URL.financialyear.basename],
            action_code: 'visible_financial_year_view',
            is_superuser_action: false,
            name: 'View Financial Year',
            label: 'Financial Year',
            action: 'sub-menu',
            url: '/basicdetails/financial/view',
            component: <FinancialYearList />,
            permission_needed: true,
            associated_urls: ['/basicdetails/financial/add'],
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [POST_URL.financialyear.basename],
            action_code: 'visible_financial_year_add',
            is_superuser_action: false,
            name: 'Create Financial Year',
            label: 'Financial Year',
            action: 'action-url',
            url: '/basicdetails/financial/add',
            component: <ManageFinancialYear />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.financialyear.basename],
            action_code: 'visible_financial_year_change',
            is_superuser_action: false,
            name: 'Update Financial Year',
            label: 'Financial Year',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.financialyear.basename],
            action_code: 'visible_financial_year_delete',
            is_superuser_action: false,
            name: 'Delete Year',
            label: 'Financial Year',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Financial Year',
        type: 'basic_info',

    },
    sections: {
        view: {
            codenames: [GET_URL.section.basename],
            action_code: 'visible_sections_view',
            is_superuser_action: false,
            name: 'View Sections',
            label: `${alias_names['section']}`,
            action: 'sub-menu',
            url: '/basicdetails/sections/view',
            component: <ManageSectionView />,
            permission_needed: true,
            associated_urls: ['/basicdetails/sections/add'],
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [POST_URL.section.basename],
            action_code: 'visible_sections_add',
            is_superuser_action: false,
            name: 'Create Sections',
            label: `${alias_names['section']}`,
            action: 'action-url',
            url: '/basicdetails/sections/add',
            component: <ManageSection />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.section.basename],
            action_code: 'visible_sections_change',
            is_superuser_action: false,
            name: 'Update Sections',
            label: 'Sections',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.section.basename],
            action_code: 'visible_sections_delete',
            is_superuser_action: false,
            name: 'Delete Sections',
            label: 'Sections',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Sections',
        type: 'basic_info',
    },
    standard_strength: {
        view: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.strength.basename, GET_URL.section.basename],
            action_code: 'visible_standard_strength_view',
            is_superuser_action: false,
            name: 'View Standard Strength',
            label: `${alias_names['standard']}`,
            action: 'sub-menu',
            url: '/basicdetails/strengths/view',
            component: <StrengthCards />,
            permission_needed: true,
            associated_urls: ['/basicdetails/strengths/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.strength.basename, GET_URL.section.basename, GET_URL.standard.basename,
            POST_URL.strength.basename],
            action_code: 'visible_standard_strength_add',
            is_superuser_action: false,
            name: 'Create Standard Strength',
            label: `${alias_names['standard']}`,
            action: 'action-url',
            url: '/basicdetails/strengths/add',
            component: <DynamicAcadamic />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.strength.basename],
            action_code: 'visible_standard_strength_change',
            is_superuser_action: false,
            name: 'Update Strength',
            label: 'Standards',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.strength.basename],
            action_code: 'visible_standard_strength_delete',
            is_superuser_action: false,
            name: 'Delete Standard Strength',
            label: 'Standards',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Standard Strength',
        type: 'basic_info',
    },
    single_standard_strength: {
        create: {
            codenames: [POST_URL.strength.basename],
            action_code: 'visible_single_standard_strength_view',
            is_superuser_action: false,
            name: 'Single Standard Strength',
            label: 'Add Strength',
            action: 'action',
            permission_needed: false,//not to show in permission screen because already declared in standard_strength
        },
        name: 'Single Standard Strength',
        type: 'basic_info',
    },
    subjects: {
        view: {
            codenames: [GET_URL.subject.basename, GET_URL.subjectparttype.basename],
            action_code: 'visible_subjects_view',
            is_superuser_action: false,
            name: 'View Subjects',
            label: 'Subjects',
            action: 'sub-menu',
            url: '/basicdetails/subjects/view',
            component: <ManageSubjectView />,
            permission_needed: true,
            associated_urls: ['/basicdetails/subjects/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.subject.basename, GET_URL.subjectparttype.basename],
            action_code: 'visible_subjects_add',
            is_superuser_action: false,
            name: 'Create Subjects',
            label: 'Subjects',
            action: 'action-url',
            url: '/basicdetails/subjects/add',
            component: <ManageSubjects />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.subject.basename],
            action_code: 'visible_subjects_change',
            is_superuser_action: false,
            name: 'Update Subjects',
            label: 'Subjects',
            action: 'action-url',
            url: '/basicdetails/subjects/edit',
            component: <ManageSubjects />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        delete: {
            codenames: [DEL_URL.subject.basename],
            action_code: 'visible_subjects_delete',
            is_superuser_action: false,
            name: 'Delete Subjects',
            label: 'Subjects',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Subjects',
        type: 'basic_info',
    },
    subjects_engineer: {
        view: {
            codenames: [GET_URL.subject.basename, GET_URL.subjectparttype.basename],
            action_code: 'visible_subjects_engineer_view',
            is_superuser_action: false,
            name: 'View Subjects Engineer',
            label: 'Subjects Engineer',
            action: 'sub-menu',
            url: '/basicdetails/subjectsengineer/view',
            component: <ManageSubjectViewEngineer />,
            permission_needed: true,
            associated_urls: ['/basicdetails/subjects/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.subject.basename, GET_URL.subjectparttype.basename],
            action_code: 'visible_subjects_engineer_add',
            is_superuser_action: false,
            name: 'Create Subjects Engineer',
            label: 'Subjects Engineer',
            action: 'action-url',
            url: '/basicdetails/subjectsengineer/add',
            component: <ManageSubjectEngineer />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.subject.basename],
            action_code: 'visible_subjects_engineer_change',
            is_superuser_action: false,
            name: 'Update Subjects Engineer',
            label: 'Subjects Engineer',
            action: 'action-url',
            url: '/basicdetails/subjectsengineer/edit',
            component: <ManageSubjectEngineer />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        delete: {
            codenames: [DEL_URL.subject.basename],
            action_code: 'visible_subjects_engineer_delete',
            is_superuser_action: false,
            name: 'Delete Subjects Engineer',
            label: 'Subjects Engineer',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Subjects Engineer',
        type: 'basic_info',
    },
    counter_format_setup: {
        create: {
            codenames: [GET_URL.counter.basename, POST_URL.counter.basename],
            action_code: 'visible_counter_format_setup_add',
            is_superuser_action: false,
            name: 'Counter Format Setup',
            label: 'Counter Format',
            action: 'sub-menu',
            url: '/basicdetails/counter/add',
            component: <FormatGenerator />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: 'Counter Format Setup',
        type: 'basic_info',
    },
    mobile_banner: {
        view: {
            codenames: [GET_URL.banner.basename],
            action_code: 'visible_mobile_banner_view',
            is_superuser_action: false,
            name: 'Banners',
            label: 'Mobile Banners',
            action: 'sub-menu',
            url: '/basicdetails/banners/view',
            component: <BannerList />,
            permission_needed: true,
            associated_urls: ['/basicdetails/strengths/add'],
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [POST_URL.banner.basename],
            action_code: 'visible_mobile_banner_add',
            is_superuser_action: false,
            name: 'Banners',
            label: 'Mobile Banners',
            action: 'action-url',
            url: '/basicdetails/banners/add',
            component: <AddBanner />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: 'Mobile Banner',
        type: 'basic_info',
    },
    school_building: {
        view: {
            codenames: [GET_URL.buildingdata.basename, DEL_URL.buildingdata.basename],
            action_code: 'visible_school_building_view',
            is_superuser_action: false,
            name: `${alias_names['school']} Buildin List`,
            label: `${alias_names['school']} Buildin List`,
            action: 'sub-menu',
            url: '/school/school_building/list',
            component: <SchoolBuildingList />,
            associated_urls: ['/school/school_building/add', '/school/school_building/detail/view'],
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [POST_URL.buildingdata.basename],
            action_code: 'visible_school_building_add',
            is_superuser_action: false,
            name: 'Create School Building',
            label: `${alias_names['school']} Building`,
            action: 'action-url',
            url: '/school/school_building/add',
            component: <AddSchoolBuilding />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [POST_URL.buildingdata.basename],
            action_code: 'visible_school_building_change',
            is_superuser_action: false,
            name: 'Update School Building',
            label: 'Update School Building',
            action: 'action-url',
            url: '/school/school_building/edit',
            component: <AddSchoolBuilding />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        delete: {
            codenames: [DEL_URL.buildingdata.basename],
            action_code: 'visible_school_building_delete',
            is_superuser_action: false,
            name: 'Delete School Building',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: `${alias_names['school']} Building`,
        type: 'basic_info',
    },
    standard_assign_teacher: {
        view: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.section.basename, GET_URL.staffstandardsectionmapping.basename,
            GET_URL.staff.basename],
            action_code: 'visible_standard_strength_view',
            is_superuser_action: false,
            name: 'Assign Teacher List',
            label: `Assign Teacher List`,
            action: 'sub-menu',
            url: '/basicdetails/assignteacher/view',
            component: <ViewAssignTeacher />,
            permission_needed: true,
            associated_urls: ['/basicdetails/strengths/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.strength.basename, GET_URL.section.basename, GET_URL.standard.basename,
            POST_URL.strength.basename, GET_URL.staffstandardsectionmapping.basename, GET_URL.staff.basename],
            action_code: 'visible_standard_strength_add',
            is_superuser_action: false,
            name: 'Assign Class Teacher',
            label: 'CREATE',
            action: 'action-url',
            url: '/basicdetails/assignteacher/create',
            component: <AssignTeacher />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.staffstandardsectionmapping.basename, GET_URL.staff.basename],
            action_code: 'visible_standard_strength_change',
            is_superuser_action: false,
            name: 'Update Assign Teacher',
            label: 'Standards',
            action: 'action',
            url: '/basicdetails/assignteacher/update',
            component: <AssignTeacher />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.strength.basename],
            action_code: 'visible_standard_strength_delete',
            is_superuser_action: false,
            name: 'Delete Assign Teacher',
            label: 'Standards',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Assign Teacher',
        type: 'basic_info',
    },
    building_individual: {
        view: {
            codenames: [GET_URL.buildingdata.basename],
            action_code: 'visible_building_individual_view',
            is_superuser_action: false,
            name: `${alias_names['school']} Building`,
            label: `${alias_names['school']} Building`,
            action: 'action',
            url: '/school/building/detail/view',
            component: <ViewIndividualSchoolBuilding />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: `${alias_names['school']} Building Individual View`,
        type: 'basic_info',
    },
    mentor_details: {
        view: {
            codenames: [GET_URL.mentorstudentmapping.basename,GET_URL.getacademicyear.basename,GET_URL.studentacademicdetails.basename,
                GET_URL.bookappointment.basename,POST_URL.getfeelistforstudent.basename,POST_URL.bookappointment.basename
            ],
            action_code: 'visible_mentor_details_view',
            is_superuser_action: false,
            name: `Mentor Details`,
            label: `Mentor Details`,
            action: 'sub-menu',
            url: '/mentor/view',
            component: <MentorStudentList/>,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: `Mentor Details View`,
        type: 'basic_info',
    },
    visitor_reasons: {
        view: {
            codenames: [GET_URL.reason.basename, PUT_URL.reason.basename, DEL_URL.reason.basename],
            action_code: 'visible_visitor_reasons_view',
            is_superuser_action: false,
            name: 'Reason List',
            label: 'Reason List',
            action: 'sub-menu',
            url: '/school/visitor_reasons/list',
            component: <VisitorReasonList />,
            associated_urls: ['/school/visitor_reasons/add', '/school/visitor_reasons/detail/view'],
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [POST_URL.reason.basename],
            action_code: 'visible_visitor_reasons_add',
            is_superuser_action: false,
            name: 'Create Reason',
            label: 'Create Reason',
            action: 'action-url',
            url: '/school/visitor_reasons/add',
            component: <AddVisitorReason />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [],
            action_code: 'visible_visitor_reasons_change',
            is_superuser_action: false,
            name: 'Update Reason',
            label: 'Update Reason',
            action: 'action',
            url: '/school/visitor_reasons/edit',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [],
            action_code: 'visible_visitor_reasons_delete',
            is_superuser_action: false,
            name: 'Delete Reason',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Reason Types',
        type: 'basic_info',
    },
    school_address: {
        view: {
            codenames: [GET_URL.instituteaddress.basename, DEL_URL.instituteaddress.basename],
            action_code: 'visible_school_address_view',
            is_superuser_action: false,
            name: `Institute Address List`,
            label: `${alias_names['school']} Address List`,
            action: 'sub-menu',
            url: '/school/address/list',
            component: <SchoolAddressView />,
            associated_urls: ['/school/address/add', '/school/address/edit', '/school/address/detail/view'],
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [GET_URL.instituteaddress.basename, POST_URL.instituteaddress.basename],
            action_code: 'visible_school_address_add',
            is_superuser_action: false,
            name: 'Institute Address',
            label: `${alias_names['school']} Address`,
            action: 'action-url',
            url: '/school/address/add',
            component: <SchoolAddressAdd />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [POST_URL.instituteaddress.basename],
            action_code: 'visible_school_address_change',
            is_superuser_action: false,
            name: 'Update Institute Address',
            label: `Update ${alias_names['school']} Address`,
            action: 'action-url',
            url: '/school/address/edit',
            component: <SchoolAddressAdd />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        delete: {
            codenames: [DEL_URL.instituteaddress.basename],
            action_code: 'visible_school_address_delete',
            is_superuser_action: false,
            name: 'Delete Institute Address',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Institute Address',
        type: 'basic_info',
    },
    address_individual: {
        view: {
            codenames: [GET_URL.instituteaddress.basename],
            action_code: 'visible_address_individual_view',
            is_superuser_action: false,
            name: `${alias_names['school']} Address`,
            label: `${alias_names['school']} Address`,
            action: 'action',
            url: '/school/address/detail/view',
            component: <SchoolAddressIndividualView />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: 'Institute Address Individual',
        type: 'basic_info',
    },
    school_timing: {
        view: {
            codenames: [GET_URL.schooltimings.basename, DEL_URL.schooltimings.basename],
            action_code: 'visible_school_timing_view',
            is_superuser_action: false,
            name: `${alias_names['school']} Timing`,
            label: `${alias_names['school']} Timing`,
            action: 'sub-menu',
            url: '/school/timing/list',
            component: <SchoolTimingView />,
            associated_urls: ['/school/timing/add', '/school/timing/detail/view', '/school/timing/edit'],
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        create: {
            codenames: [GET_URL.schooltimings.basename, POST_URL.schooltimings.basename],
            action_code: 'visible_school_timing_add',
            is_superuser_action: false,
            name: `${alias_names['school']} Timing`,
            label: `${alias_names['school']} Timing`,
            action: 'action-url',
            url: '/school/timing/add',
            component: <SchoolTimingAdd />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [POST_URL.schooltimings.basename],
            action_code: 'visible_school_timing_change',
            is_superuser_action: false,
            name: `${alias_names['school']} Timing`,
            label: `${alias_names['school']} Timing`,
            action: 'action-url',
            url: '/school/timing/edit',
            component: <SchoolTimingAdd />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        delete: {
            codenames: [DEL_URL.schooltimings.basename],
            action_code: 'visible_school_timing_delete',
            is_superuser_action: false,
            name: 'Delete School Timing',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: `${alias_names['school']} Timing`,
        type: 'basic_info',
    },
    school_timing_individual: {
        view: {
            codenames: [GET_URL.schooltimings.basename],
            action_code: 'visible_school_timing_individual_view',
            is_superuser_action: false,
            name: `${alias_names['school']} Timing`,
            label: `${alias_names['school']} Timing`,
            action: 'action',
            url: '/school/timing/detail/view',
            component: <SchoolTimingIndividualView />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        name: `${alias_names['school']} Timing ndividual`,
        type: 'basic_info',
    },
    departmentdata: {
        view: {
            codenames: [GET_URL.branch.basename],
            action_code: 'visible_departmentdata_view',
            is_superuser_action: false,
            name: 'View Department',
            label: 'Department',
            action: 'sub-menu',
            url: '/basicdetails/departmentdata/view',
            component: <ManageDepartmentView />,
            permission_needed: true,
            associated_urls: ['/basicdetails/departmentdata/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.branch.basename],
            action_code: 'visible_departmentdata_add',
            is_superuser_action: false,
            name: 'Create Department',
            label: 'Department',
            action: 'action-url',
            url: '/basicdetails/departmentdata/add',
            component: <ManageDepartment />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.branch.basename],
            action_code: 'visible_departmentdata_change',
            is_superuser_action: false,
            name: 'Update Department',
            label: 'Department',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.branch.basename],
            action_code: 'visible_departmentdata_delete',
            is_superuser_action: false,
            name: 'Delete Department',
            label: 'Department',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Department',
        type: 'basic_info',
    },
    subejct_category: {
        view: {
            codenames: [GET_URL.subjectcategory.basename],
            action_code: 'visible_subejct_category_view',
            is_superuser_action: false,
            name: 'View Subejct Category',
            label: 'Subejct Category',
            action: 'sub-menu',
            url: '/basicdetails/Subejctcategory/view',
            component: <ViewSubjectCategory />,
            permission_needed: true,
            associated_urls: ['/basicdetails/Subejctcategory/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.subjectcategory.basename],
            action_code: 'visible_subejct_category_add',
            is_superuser_action: false,
            name: 'Create Subejct Category',
            label: 'Subejct Category',
            action: 'action-url',
            url: '/basicdetails/subejctcategory/add',
            component: <AddSubjectCategory />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [PUT_URL.subjectcategory.basename],
            action_code: 'visible_subejct_category_change',
            is_superuser_action: false,
            name: 'Update Subejct Category',
            label: 'Subejct Category',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.subjectcategory.basename],
            action_code: 'visible_subejct_category_delete',
            is_superuser_action: false,
            name: 'Delete Subejct Category',
            label: 'Subejct Category',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Subejct Category',
        type: 'basic_info',
    },
    assign_department: {
        view: {
            codenames: [GET_URL.staffhodbranchmapping.basename, GET_URL.branch.basename],
            action_code: "visible_assign_department_view",
            is_superuser_action: false,
            name: "View Assign Department",
            label: "Assign Department",
            action: "sub-menu",
            url: "/basicdetails/assign/view",
            component: <StaffDepartmentMappingView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ["/basicdetails/assign/department"],
        },
        create: {
            codenames: [
                GET_URL.staffhodbranchmapping.basename,
                POST_URL.branch.basename,
            ],
            action_code: "visible_assign_department_add",
            is_superuser_action: false,
            name: "Create Assign Department",
            label: "Assign Department",
            action: "action-url",
            url: "/basicdetails/assign/department",
            component: <StaffDepartmentMapping />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.staffhodbranchmapping.basename],
            action_code: "visible_assign_department_change",
            is_superuser_action: false,
            name: "Update Assign Shift",
            label: "Edit",
            action: "action",
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.staffhodbranchmapping.basename],
            action_code: "visible_assign_department_delete",
            is_superuser_action: false,
            name: "Delete Assign Shift",
            label: "Delete",
            action: "action",
            permission_needed: true,
            exclude_roles: [7],
        },
        name: "Assign Departemnt",
        type: "basic_info",
    },
    subejct_details: {
    view: {
    //   codenames: [GET_URL.staffhodbranchmapping.basename, GET_URL.branch.basename],
      action_code: "visible_subejct_details_view",
      is_superuser_action: false,
      name: "View Subject Details",
      label: "Subject Details",
      action: "sub-menu",
      url: "/basicdetails/subjectdetails/view",
      component: <StaffDepartmentMappingView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/basicdetails/subjectdetails/department"],
    },
    create: {
    //   codenames: [
    //     GET_URL.staffhodbranchmapping.basename,
    //     POST_URL.branch.basename,
    //   ],
      action_code: "visible_subejct_details_add",
      is_superuser_action: false,
      name: "Create Subject Details",
      label: "Subject Details",
      action: "action-url",
      url: "/basicdetails/subjectdetails/add",
      component: <AddSubjectDetails />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
    //   codenames: [PUT_URL.staffhodbranchmapping.basename],
      action_code: "visible_subejct_details_change",
      is_superuser_action: false,
      name: "Update Subject Details",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
    //   codenames: [DEL_URL.staffhodbranchmapping.basename],
      action_code: "visible_subejct_details_delete",
      is_superuser_action: false,
      name: "Delete Subject Details",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Subject Details",
    type: "basic_info",
  },


}
export default Actions;