import React from "react";
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from "Includes/urls";

import CanteenDashboard from "Containers/Canteen/CanteenDashboard";
import CanteenSetup from "Containers/Canteen/CanteenSetup";
import FoodCategoryList from "Containers/Canteen/FoodCategoryList";
import AddFoodCategory from "Containers/Canteen/AddFoodCategory";
import FoodItemList from "Containers/Canteen/FoodItemList";
import AddFoodItem from "Containers/Canteen/AddFoodItem";
import FoodComboList from "Containers/Canteen/FoodComboList";
import AddFoodCombo from "Containers/Canteen/AddFoodCombo";
import MenuList from "Containers/Canteen/MenuList";
import AddMenu from "Containers/Canteen/AddMenu";
import MealPackageList from "Containers/Canteen/MealPackageList";
import AddMealPackage from "Containers/Canteen/AddMealPackage";
import TabTodaysMenu from "Containers/Canteen/TabTodaysMenu";
import TabOrders from "Containers/Canteen/TabOrders";
import TabWallets from "Containers/Canteen/TabWallets";
import TabDiscounts from "Containers/Canteen/TabDiscounts";
import TabSubscriptions from "Containers/Canteen/TabSubscriptions";
import TodaysMenuSetup from "Containers/Canteen/TodaysMenuSetup";
import FoodRequestPage from "Containers/Canteen/FoodRequestPage";
import FoodRequestKitchen from "Containers/Canteen/FoodRequestKitchen";
import FoodRequestConfig from "Containers/Canteen/FoodRequestConfig";

const CanteenActions = {
  canteen_dashboard: {
    view: {
      codenames: [
        GET_URL.food_category.basename, GET_URL.food_item.basename,
        GET_URL.food_combo.basename, GET_URL.canteen_menu.basename,
        GET_URL.canteen_order.basename, GET_URL.canteen_wallet.basename,
      ],
      action_code: "visible_canteen_dashboard_view",
      is_superuser_action: false,
      name: "Canteen",
      label: "Canteen",
      action: "sub-menu",
      associated_urls: [
        "/canteen/todays-menu", "/canteen/orders", "/canteen/wallets",
        "/canteen/discounts", "/canteen/subscriptions", "/canteen/food-requests",
      ],
      url: "/canteen",
      component: <CanteenDashboard />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Canteen",
    type: "canteen",
  },

  canteen_setup: {
    view: {
      codenames: [
        GET_URL.food_category.basename, GET_URL.food_item.basename,
        GET_URL.food_combo.basename, GET_URL.canteen_menu.basename,
        GET_URL.meal_package.basename,
      ],
      action_code: "visible_canteen_setup_view",
      is_superuser_action: false,
      name: "Canteen Setup",
      label: "Canteen Setup",
      action: "sub-menu",
      associated_urls: [
        "/canteen/food-category", "/canteen/food-category/add",
        "/canteen/food-item", "/canteen/food-item/add",
        "/canteen/food-combo", "/canteen/food-combo/add",
        "/canteen/canteen-menu", "/canteen/canteen-menu/add",
        "/canteen/meal-package", "/canteen/meal-package/add",
        "/canteen/todays-menu-setup", "/canteen/food-request-config",
      ],
      url: "/canteen-setup",
      component: <CanteenSetup />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Canteen Setup",
    type: "canteen",
  },

  canteen_todays_menu: {
    view: {
      codenames: [GET_URL.canteen_menu_item.basename],
      action_code: "visible_canteen_todays_menu_view",
      is_superuser_action: false,
      name: "Today's Menu (POS)",
      label: "Today's Menu",
      action: "sub-menu",
      url: "/canteen/todays-menu",
      component: <TabTodaysMenu />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.canteen_menu_item.basename, POST_URL.canteen_order.basename],
      action_code: "visible_canteen_todays_menu_add",
      is_superuser_action: false,
      name: "Place Order (POS)",
      label: "Place Order",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Today's Menu (POS)",
    type: "canteen",
  },

  food_category: {
    view: {
      codenames: [GET_URL.food_category.basename],
      action_code: "visible_food_category_view",
      is_superuser_action: false,
      name: "Food Category",
      label: "Food Category",
      action: "sub-menu",
      associated_urls: ["/canteen/food-category/add"],
      url: "/canteen/food-category",
      component: <FoodCategoryList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.food_category.basename, POST_URL.food_category.basename],
      action_code: "visible_food_category_add",
      is_superuser_action: false,
      name: "Add Food Category",
      label: "Add Food Category",
      action: "action-url",
      url: "/canteen/food-category/add",
      component: <AddFoodCategory />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.food_category.basename],
      action_code: "visible_food_category_change",
      is_superuser_action: false,
      name: "Update Food Category",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.food_category.basename],
      action_code: "visible_food_category_delete",
      is_superuser_action: false,
      name: "Delete Food Category",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Food Category",
    type: "canteen",
  },

  food_item: {
    view: {
      codenames: [GET_URL.food_item.basename],
      action_code: "visible_food_item_view",
      is_superuser_action: false,
      name: "Food Item",
      label: "Food Item",
      action: "sub-menu",
      associated_urls: ["/canteen/food-item/add"],
      url: "/canteen/food-item",
      component: <FoodItemList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.food_item.basename, POST_URL.food_item.basename],
      action_code: "visible_food_item_add",
      is_superuser_action: false,
      name: "Add Food Item",
      label: "Add Food Item",
      action: "action-url",
      url: "/canteen/food-item/add",
      component: <AddFoodItem />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.food_item.basename],
      action_code: "visible_food_item_change",
      is_superuser_action: false,
      name: "Update Food Item",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.food_item.basename],
      action_code: "visible_food_item_delete",
      is_superuser_action: false,
      name: "Delete Food Item",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Food Item",
    type: "canteen",
  },

  food_combo: {
    view: {
      codenames: [GET_URL.food_combo.basename],
      action_code: "visible_food_combo_view",
      is_superuser_action: false,
      name: "Food Combo",
      label: "Food Combo",
      action: "sub-menu",
      associated_urls: ["/canteen/food-combo/add"],
      url: "/canteen/food-combo",
      component: <FoodComboList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.food_combo.basename, POST_URL.food_combo.basename],
      action_code: "visible_food_combo_add",
      is_superuser_action: false,
      name: "Add Food Combo",
      label: "Add Food Combo",
      action: "action-url",
      url: "/canteen/food-combo/add",
      component: <AddFoodCombo />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.food_combo.basename],
      action_code: "visible_food_combo_change",
      is_superuser_action: false,
      name: "Update Food Combo",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.food_combo.basename],
      action_code: "visible_food_combo_delete",
      is_superuser_action: false,
      name: "Delete Food Combo",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Food Combo",
    type: "canteen",
  },

  /* ─── Canteen Orders ─── */
  canteen_order: {
    view: {
      codenames: [GET_URL.canteen_order.basename],
      action_code: "visible_canteen_order_view",
      is_superuser_action: false,
      name: "Canteen Orders",
      label: "Canteen Orders",
      action: "sub-menu",
      url: "/canteen/orders",
      component: <TabOrders />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.canteen_order.basename, POST_URL.canteen_order.basename],
      action_code: "visible_canteen_order_add",
      is_superuser_action: false,
      name: "Place Order",
      label: "Place Order",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.canteen_order.basename],
      action_code: "visible_canteen_order_change",
      is_superuser_action: false,
      name: "Update Order",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.canteen_order.basename],
      action_code: "visible_canteen_order_delete",
      is_superuser_action: false,
      name: "Cancel Order",
      label: "Cancel",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Canteen Orders",
    type: "canteen",
  },

  /* ─── Canteen Wallet ─── */
  canteen_wallet: {
    view: {
      codenames: [GET_URL.canteen_wallet.basename],
      action_code: "visible_canteen_wallet_view",
      is_superuser_action: false,
      name: "Canteen Wallet",
      label: "Canteen Wallet",
      action: "sub-menu",
      url: "/canteen/wallets",
      component: <TabWallets />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.canteen_wallet.basename, POST_URL.canteen_wallet.basename],
      action_code: "visible_canteen_wallet_add",
      is_superuser_action: false,
      name: "Create Wallet",
      label: "Create Wallet",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.canteen_wallet.basename],
      action_code: "visible_canteen_wallet_change",
      is_superuser_action: false,
      name: "Update Wallet",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.canteen_wallet.basename],
      action_code: "visible_canteen_wallet_delete",
      is_superuser_action: false,
      name: "Delete Wallet",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Canteen Wallet",
    type: "canteen",
  },

  /* ─── Canteen Menu (management) ─── */
  canteen_menu: {
    view: {
      codenames: [GET_URL.canteen_menu.basename],
      action_code: "visible_canteen_menu_view",
      is_superuser_action: false,
      name: "Canteen Menu",
      label: "Canteen Menu",
      action: "sub-menu",
      associated_urls: ["/canteen/canteen-menu/add"],
      url: "/canteen/canteen-menu",
      component: <MenuList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.canteen_menu.basename, POST_URL.canteen_menu.basename],
      action_code: "visible_canteen_menu_add",
      is_superuser_action: false,
      name: "Add Canteen Menu",
      label: "Add Menu",
      action: "action-url",
      url: "/canteen/canteen-menu/add",
      component: <AddMenu />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.canteen_menu.basename],
      action_code: "visible_canteen_menu_change",
      is_superuser_action: false,
      name: "Update Canteen Menu",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.canteen_menu.basename],
      action_code: "visible_canteen_menu_delete",
      is_superuser_action: false,
      name: "Delete Canteen Menu",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Canteen Menu",
    type: "canteen",
  },

  /* ─── Today's Menu Setup ─── */
  canteen_todays_menu_setup: {
    view: {
      codenames: [GET_URL.canteen_menu.basename, GET_URL.canteen_menu_item.basename],
      action_code: "visible_canteen_todays_menu_setup_view",
      is_superuser_action: false,
      name: "Today's Menu Setup",
      label: "Today's Menu Setup",
      action: "sub-menu",
      url: "/canteen/todays-menu-setup",
      component: <TodaysMenuSetup />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Today's Menu Setup",
    type: "canteen",
  },

  /* ─── Meal Package ─── */
  meal_package: {
    view: {
      codenames: [GET_URL.meal_package.basename],
      action_code: "visible_meal_package_view",
      is_superuser_action: false,
      name: "Meal Package",
      label: "Meal Package",
      action: "sub-menu",
      associated_urls: ["/canteen/meal-package/add"],
      url: "/canteen/meal-package",
      component: <MealPackageList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.meal_package.basename, POST_URL.meal_package.basename],
      action_code: "visible_meal_package_add",
      is_superuser_action: false,
      name: "Add Meal Package",
      label: "Add Package",
      action: "action-url",
      url: "/canteen/meal-package/add",
      component: <AddMealPackage />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.meal_package.basename],
      action_code: "visible_meal_package_change",
      is_superuser_action: false,
      name: "Update Meal Package",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.meal_package.basename],
      action_code: "visible_meal_package_delete",
      is_superuser_action: false,
      name: "Delete Meal Package",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Meal Package",
    type: "canteen",
  },

  /* ─── Discounts ─── */
  menu_discount: {
    view: {
      codenames: [GET_URL.menu_discount.basename],
      action_code: "visible_menu_discount_view",
      is_superuser_action: false,
      name: "Menu Discounts",
      label: "Menu Discounts",
      action: "sub-menu",
      url: "/canteen/discounts",
      component: <TabDiscounts />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.menu_discount.basename, POST_URL.menu_discount.basename],
      action_code: "visible_menu_discount_add",
      is_superuser_action: false,
      name: "Add Discount",
      label: "Add Discount",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.menu_discount.basename],
      action_code: "visible_menu_discount_change",
      is_superuser_action: false,
      name: "Update Discount",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.menu_discount.basename],
      action_code: "visible_menu_discount_delete",
      is_superuser_action: false,
      name: "Delete Discount",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Menu Discounts",
    type: "canteen",
  },

  /* ─── Subscriptions ─── */
  meal_package_subscription: {
    view: {
      codenames: [GET_URL.meal_package_subscription.basename],
      action_code: "visible_meal_package_subscription_view",
      is_superuser_action: false,
      name: "Meal Package Subscriptions",
      label: "Subscriptions",
      action: "sub-menu",
      url: "/canteen/subscriptions",
      component: <TabSubscriptions />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.meal_package_subscription.basename, POST_URL.meal_package_subscription.basename],
      action_code: "visible_meal_package_subscription_add",
      is_superuser_action: false,
      name: "Create Subscription",
      label: "Subscribe",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.meal_package_subscription.basename],
      action_code: "visible_meal_package_subscription_change",
      is_superuser_action: false,
      name: "Update Subscription",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.meal_package_subscription.basename],
      action_code: "visible_meal_package_subscription_delete",
      is_superuser_action: false,
      name: "Cancel Subscription",
      label: "Cancel",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Meal Package Subscriptions",
    type: "canteen",
  },

  /* ─── Food Requests ─── */
  food_request: {
    view: {
      codenames: [GET_URL.food_request.basename],
      action_code: "visible_food_request_view",
      is_superuser_action: false,
      name: "Food Requests",
      label: "Food Requests",
      action: "sub-menu",
      url: "/canteen/food-requests",
      component: <FoodRequestPage />,
      permission_needed: true,
    },
    create: {
      codenames: [GET_URL.food_request.basename, POST_URL.food_request.basename],
      action_code: "visible_food_request_add",
      is_superuser_action: false,
      name: "Submit Food Request",
      label: "Request",
      action: "action",
      permission_needed: true,
    },
    change: {
      codenames: [PUT_URL.food_request.basename],
      action_code: "visible_food_request_change",
      is_superuser_action: false,
      name: "Manage Food Requests",
      label: "Manage",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.food_request.basename],
      action_code: "visible_food_request_delete",
      is_superuser_action: false,
      name: "Delete Food Request",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Food Requests",
    type: "canteen",
  },

  /* ─── Food Request Kitchen (admin review) ─── */
  food_request_kitchen: {
    view: {
      codenames: [GET_URL.food_request.basename, PUT_URL.food_request.basename],
      action_code: "visible_food_request_kitchen_view",
      is_superuser_action: false,
      name: "Food Request Kitchen",
      label: "Kitchen Requests",
      action: "sub-menu",
      url: "/canteen/food-requests-kitchen",
      component: <FoodRequestKitchen />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Food Request Kitchen",
    type: "canteen",
  },

  /* ─── Food Request Config ─── */
  food_request_config: {
    view: {
      codenames: [GET_URL.food_request_config.basename],
      action_code: "visible_food_request_config_view",
      is_superuser_action: false,
      name: "Food Request Config",
      label: "Request Config",
      action: "sub-menu",
      url: "/canteen/food-request-config",
      component: <FoodRequestConfig />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.food_request_config.basename, POST_URL.food_request_config.basename],
      action_code: "visible_food_request_config_add",
      is_superuser_action: false,
      name: "Create Request Config",
      label: "Configure",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    change: {
      codenames: [PUT_URL.food_request_config.basename],
      action_code: "visible_food_request_config_change",
      is_superuser_action: false,
      name: "Update Request Config",
      label: "Edit Config",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Food Request Configuration",
    type: "canteen",
  },
};

export default CanteenActions;