import React from 'react';
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from 'Includes/urls';
import ScheduleExamView from 'Containers/Exam Engineer/ScheduleExamView';
import ScheduleExamAdd from 'Containers/Exam Engineer/ScheduleExamAdd';
import ExamMarksView from 'Containers/Exam Engineer/ExamMarksView';
import ExamMarksAdd from 'Containers/Exam Engineer/ExamMarksAdd';
import ManageCourseOutcome from 'Containers/Exam Engineer/ManageCourseOutcome';
import ManageCourseOutcomeView from 'Containers/Exam Engineer/ManageCourseOutcomeView';
import ManageProgramOutcome from 'Containers/Exam Engineer/ ManageProgramOutcome';
import ManageProgramOutcomeView from 'Containers/Exam Engineer/ManageProgramOutcomeView';
import ManageProgramSpecificOutcome from 'Containers/Exam Engineer/ManageProgramSpecificOutcome';
import ManageProgramSpecificOutcomeView from 'Containers/Exam Engineer/ManageProgramSpecificOutcomeView';
import AddCourseDesign from 'Containers/Exam Engineer/AddCourseDesign'
import ViewCourseDesign from 'Containers/Exam Engineer/ViewCourseDesign';
import ManageSubjectCourseOutcomeProgramOutcomeMapping from 'Containers/Exam Engineer/ManageSubjectCourseOutcomeProgramOutcomeMapping';
import ViewCoPoMatricPage from 'Containers/Exam Engineer/ViewCoPoMatricPage';
import EngineerExamSchedulePage from 'Containers/Exam Engineer/EngineerExamSchedulePage'
import EngineerExamScheduleViewPage from 'Containers/Exam Engineer/EngineerExamScheduleViewPage';

const alias_names = JSON.parse(localStorage.getItem('alias_name')) ? JSON.parse(localStorage.getItem('alias_name')) : {}

const Actions = {
    schedule_exam_engineer: {
        view: {
            codenames: [GET_URL.schedule.basename,GET_URL.subjectparttype.basename,GET_URL.getacademicyear.basename,GET_URL.examterms.basename, GET_URL.exam.basename, GET_URL.schedule.basename],
            action_code: 'visible_schedule_exam_engineer_view',
            is_superuser_action: false,
            name: 'Schedule Exam Engineer',
            label: 'Schedule Exam Engineer',
            action: 'sub-menu',
            url: '/examengineer/schedule/view',
            component: <ScheduleExamView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/examengineer/schedule/add'],
        },
        create: {
            codenames: [GET_URL.schedule.basename, POST_URL.schedule.basename, PUT_URL.examapprove.basename,
            GET_URL.studentgrade.basename, GET_URL.cumulativetype.basename],
            action_code: 'visible_schedule_exam_engineer_add',
            is_superuser_action: false,
            name: 'Schedule Exam Engineer',
            label: 'Schedule Exam Engineer',
            action: 'action-url',
            url: '/examengineer/schedule/add',
            component: <ScheduleExamAdd />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Schedule Exam Engineer',
        type: 'examengineer',
    },
    schedule_exam_engineer_approve: {
        create: {
            codenames: [PUT_URL.examapprove.basename],
            action_code: 'visible_schedule_exam_engineer_approve_add',
            is_superuser_action: false,
            name: 'Approve Schedule Exam',
            label: 'Approve Schedule Exam',
            action: 'action-url',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Approve Schedule Exam Engineer',
        type: 'examengineer',
    },
    courseoutcomedata: {
        view: {
            codenames: [GET_URL.courseoutcome.basename,PUT_URL.courseoutcome.basename,DEL_URL.courseoutcome.basename],
            action_code: 'visible_courseoutcomedata_view',
            is_superuser_action: false,
            name: 'View Course Outcome',
            label: 'Course Outcome',
            action: 'sub-menu',
            url: '/examengineer/courseoutcomedata/view',
            component: <ManageCourseOutcomeView />,
            permission_needed: true,
            associated_urls: ['/examengineer/courseoutcome/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.courseoutcome.basename, GET_URL.courseoutcome.basename],
            action_code: 'visible_courseoutcomedata_add',
            is_superuser_action: false,
            name: 'Create Course Outcome',
            label: 'Course Outcome',
            action: 'action-url',
            url: '/examengineer/courseoutcomedata/add',
            component: <ManageCourseOutcome />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames:[GET_URL.courseoutcome.basename,PUT_URL.courseoutcome.basename,DEL_URL.courseoutcome.basename],
            action_code: 'visible_courseoutcomedata_change',
            is_superuser_action: false,
            name: 'Update Course Outcome',
            label: 'Course Outcome',
            action: 'action-url',
            url: '/examengineer/courseoutcomedata/edit',
            component: <ManageCourseOutcomeView />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [GET_URL.courseoutcome.basename,PUT_URL.courseoutcome.basename,DEL_URL.courseoutcome.basename],
            action_code: 'visible_courseoutcomedata_delete',
            is_superuser_action: false,
            name: 'Delete Course Outcome',
            label: 'Course Outcome',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Course Outcome Data',
        type: 'examengineer',
    },
    programoutcomedata: {
        view: {
            codenames: [GET_URL.programoutcome.basename,PUT_URL.programoutcome.basename,DEL_URL.programoutcome.basename],
            action_code: 'visible_programoutcomedata_view',
            is_superuser_action: false,
            name: 'View Program Outcome',
            label: 'Program Outcome',
            action: 'sub-menu',
            url: '/examengineer/programoutcomedata/view',
            component: <ManageProgramOutcomeView />,
            permission_needed: true,
            associated_urls: ['/examengineer/programoutcomedata/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.programoutcome.basename, GET_URL.programoutcome.basename],
            action_code: 'visible_programoutcomedata_add',
            is_superuser_action: false,
            name: 'Create Program Outcome',
            label: 'Program Outcome',
            action: 'action-url',
            url: '/examengineer/programoutcomedata/add',
            component: <ManageProgramOutcome />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [GET_URL.programoutcome.basename,PUT_URL.programoutcome.basename,DEL_URL.programoutcome.basename],
            action_code: 'visible_programoutcomedata_change',
            is_superuser_action: false,
            name: 'Update Course Outcome',
            label: 'Course Outcome',
            action: 'action-url',
            url: '/examengineer/programoutcomedata/edit',
            component: <ManageProgramOutcomeView />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [GET_URL.programoutcome.basename,PUT_URL.programoutcome.basename,DEL_URL.programoutcome.basename],
            action_code: 'visible_programoutcomedata_delete',
            is_superuser_action: false,
            name: 'Delete Program Outcome',
            label: 'Program Outcome',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Program Outcome Data',
        type: 'examengineer',
    },
    programspecificoutcomedata :{
        view: {
            codenames: [GET_URL.programspecificoutcome.basename,PUT_URL.programspecificoutcome.basename,DEL_URL.programspecificoutcome.basename],
            action_code: 'visible_programspecificoutcomedata_view',
            is_superuser_action: false,
            name: 'View Program Specific Outcome',
            label: 'Program Specific Outcome',
            action: 'sub-menu',
            url: '/examengineer/programspecificoutcomedata/view',
            component: <ManageProgramSpecificOutcomeView />,
            permission_needed: true,
            associated_urls: ['/examengineer/programspecificoutcomedata/add'],
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.programspecificoutcome.basename, GET_URL.programspecificoutcome.basename],
            action_code: 'visible_programspecificoutcomedata_add',
            is_superuser_action: false,
            name: 'Create Program Specific Outcome',
            label: 'Program Specific Outcome',
            action: 'action-url',
            url: '/examengineer/programspecificoutcomedata/add',
            component: <ManageProgramSpecificOutcome />,
            permission_needed: true,
            exclude_roles: [7],
            hide_branch_dropdown: true,
            hide_board_dropdown: true,
        },
        update: {
            codenames: [GET_URL.programspecificoutcome.basename,PUT_URL.programspecificoutcome.basename,DEL_URL.programspecificoutcome.basename],
            action_code: 'visible_programspecificoutcomedata_change',
            is_superuser_action: false,
            name: 'Update Program Specific Outcome',
            label: 'Program Specific Outcome',
            action: 'action-url',
            url: '/examengineer/programspecificoutcomedata/edit',
            component: <ManageProgramSpecificOutcomeView />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [GET_URL.programspecificoutcome.basename,PUT_URL.programspecificoutcome.basename,DEL_URL.programspecificoutcome.basename],
            action_code: 'visible_programspecificoutcomedata_delete',
            is_superuser_action: false,
            name: 'Delete Program Specific Outcome',
            label: 'Program Specific Outcome',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Program Specific Outcome Data',
        type: 'examengineer',
    },
    course_design: {
        view: {
            codenames: [GET_URL.staffsubjectcoursedesign.basename],
            action_code: 'visible_course_design_view',
            is_superuser_action: false,
            name: 'Course Design',
            label: 'Course Design',
            action: 'sub-menu',
            url: '/examengineer/course/view',
            component: <ViewCourseDesign />,
            permission_needed: true,
            exclude_roles: [7],
        },
        create: {
            codenames: [GET_URL.programeducationalobjectives.basename,GET_URL.programspecificoutcome.basename,GET_URL.programoutcome.basename,
                GET_URL.courseoutcome.basename,GET_URL.staffsubjectcoursedesign.basename,POST_URL.staffsubjectcoursedesign.basename],
            action_code: 'visible_course_design_add',
            is_superuser_action: false,
            name: 'Course Design',
            label: 'Course Design',
            action: 'action-url',
            url: '/examengineer/course/add',
            component: <AddCourseDesign />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [GET_URL.programeducationalobjectives.basename,GET_URL.programspecificoutcome.basename,GET_URL.programoutcome.basename,
                GET_URL.courseoutcome.basename,GET_URL.staffsubjectcoursedesign.basename,POST_URL.staffsubjectcoursedesign.basename],
            action_code: 'visible_course_design_change',
            is_superuser_action: false,
            name: 'Exam',
            label: 'Exam',
            action: 'action-url',
            url: '/examengineer/course/edit',
            component: <AddCourseDesign />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [GET_URL.programeducationalobjectives.basename,GET_URL.programspecificoutcome.basename,GET_URL.programoutcome.basename,
                GET_URL.courseoutcome.basename,GET_URL.staffsubjectcoursedesign.basename,POST_URL.staffsubjectcoursedesign.basename],
            action_code: 'visible_course_design_delete',
            is_superuser_action: false,
            name: 'Delete Course Design',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Course Design',
        type: 'exam engineer',
    },
    subjectcourseoutcomemappingdata: {
        view: {
            codenames:[GET_URL.staffsubjectcoursedesign.basename,GET_URL.subjectcopopsomappingmatrix.basename],
            action_code: 'visible_subjectcourseoutcomemappingdata_view',
            name: 'Subject Courseoutcome Mapping',
            label: 'Subject Courseoutcome Mapping',
            action: 'sub-menu',
            url: '/examengineer/subjectcourseoutcomemappingdata/view',
            component: <ViewCoPoMatricPage />,
            permission_needed: true,
            exclude_roles: [7],
        },
        create: {
            codenames: [GET_URL.staffsubjectcoursedesign.basename,GET_URL.subjectcopopsomappingmatrix.basename],
            action_code: 'visible_subjectcourseoutcomemappingdata_add',
            is_superuser_action: false,
            name: 'Subject Courseoutcome Mapping',
            label: 'Subject Courseoutcome Mapping',
            action: 'action-url',
            url: '/examengineer/subjectcourseoutcomemappingdata/add',
            component: <ManageSubjectCourseOutcomeProgramOutcomeMapping />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Subject Course Outcome Design',
        type: 'exam engineer',
    },
    exam_schedule_engineer: {
        view: {
            codenames:[GET_URL.examschedulequestionmapping.basename],
            action_code: 'visible_exam_schedule_engineer_view',
            name: 'Exam Schedule Engineer',
            label: 'Exam Schedule Engineer',
            action: 'sub-menu',
            url: '/examengineer/examschedule/view',
            component: <EngineerExamScheduleViewPage />,
            permission_needed: true,
            exclude_roles: [7],
        },
        create: {
            codenames: [GET_URL.getacademicyear.basename,GET_URL.exam.basename,GET_URL.staffsubjectcoursedesign.basename,
                GET_URL.staffsubjectcoursedesign.basename,POST_URL.examschedulequestionmapping.api],
            action_code: 'visible_subjectcourseoutcomemapping_add',
            is_superuser_action: false,
            name: 'Exam Schedule Engineer',
            label: 'Exam Schedule Engineer',
            action: 'action-url',
            url: '/examengineer/examschedule/add',
            component: <EngineerExamSchedulePage />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Exam Schedule Engineer',
        type: 'exam engineer',
    },
    exam_engineer_marks_enter: {
        view: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.examterms.basename,GET_URL.exam.basename,GET_URL.standardsectiondataforexam.basename,
                GET_URL.studentmarkclasssummary.basename,PUT_URL.examapprove.basename],
            action_code: 'visible_exam_engineer_marks_enter_view',
            is_superuser_action: false,
            name: 'Exam Marks Engineer',
            label: 'Exam Marks Engineer',
            action: 'sub-menu',
            url: '/examengineer/marks/view',
            component: <ExamMarksView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/examengineer/marks/add'],
        },
        create: {
            codenames: [GET_URL.questionwisemarksentry.basename, GET_URL.marksreportamrita.basename,
            POST_URL.questionwisemarksentry.basename,POST_URL.reason.basename],
            action_code: 'visible_exam_engineer_marks_enter_add',
            is_superuser_action: false,
            name: 'Exam Marks Engineer',
            label: 'Exam Marks Engineer',
            action: 'action-url',
            url: '/examengineer/marks/add',
            component: <ExamMarksAdd />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Manage Exam Marks',
        type: 'examengineer',
    },

}
export default Actions;