import React from 'react';
import { FormattedMessage } from 'react-intl';
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from 'Includes/urls';
import commonMessages from 'Constants/messages';

import ViewExamType from 'Containers/Exam/ViewExamType';
import AddExamType from 'Containers/Exam/AddExamType';
import ScheduleExamView from 'Containers/Exam/ScheduleExamView';
import ScheduleExamViewOld from 'Containers/Exam/ScheduleExamViewOld';
import ScheduleExamAdd from 'Containers/Exam/ScheduleExamAdd';
import ScheduleExamAddOld from 'Containers/Exam/ScheduleExamAddOld';
import ViewExam from 'Containers/Exam/ViewExam';
import AddExam from 'Containers/Exam/AddExam';
import HallTicketGenerator from 'Containers/Exam/HallTicketGenerator';
import ExamMarksView from 'Containers/Exam/ExamMarksView';
import ExamMarksAdd from 'Containers/Exam/ExamMarksAdd';
import ViewResultConfiguration from 'Containers/Exam/ViewResultConfiguration';
import AddResultConfiguration from 'Containers/Exam/AddExamResultConfiguration';
import TermResultConfiguration from 'Containers/Exam/AddTermResultConfiguration';
import GradePlanView from 'Containers/Exam/GradePlanView';
import GradePlanAdd from 'Containers/Exam/GradePlanAdd';
import ResultSummaryView from 'Containers/Exam/ResultSummaryView';
import ResultSectionView from 'Containers/Exam/ResultSectionView';
import ViewCumulativeType from 'Containers/Exam/ViewCumulativeType';
import AddCumulativeType from 'Containers/Exam/AddCumulativeType';
import ViewFinalResultConfig from 'Containers/Exam/ViewFinalResultConfig';
import ViewFinalResultConfignew from 'Containers/Exam/ViewFinalResultConfignew';
import AddFinalResultConfig from 'Containers/Exam/AddFinalResultConfig'
import AddFinalResultConfignew from 'Containers/Exam/AddFinalResultConfignew';
import MarksCardGenerator from 'Containers/Exam/MarksCardGenerator';
import MarksCardGeneratorV2 from 'Containers/Exam/MarksCardGeneratorV2';
import SubjectWiseReport from 'Containers/Exam/SubjectWiseReport';
import StudentWiseReport from 'Containers/Exam/StudentWiseReport';
import RankWiseReport from 'Containers/Exam/StudentWiseReport';
import CumulativeReport from 'Containers/Exam/CumulativeReport';
import AttendanceReport from 'Containers/Exam/AttendanceReport';
import AuditLogReport from 'Containers/Exam/AuditLogReport';
import ExamMarksSendNotification from 'Containers/Exam/ExamMarksSendNotification';

const alias_names = JSON.parse(localStorage.getItem('alias_name')) ? JSON.parse(localStorage.getItem('alias_name')) : {}

const Actions = {
    exam_type: {
        view: {
            codenames: [GET_URL.examtypes.basename],
            action_code: 'visible_exam_type_view',
            is_superuser_action: false,
            name: 'Exam Type',
            label: 'Exams Type',
            action: 'sub-menu',
            url: '/exam/type/view',
            component: <ViewExamType />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/type/add', '/exam/type/edit'],
        },
        create: {
            codenames: [POST_URL.examtypes.basename],
            action_code: 'visible_exam_type_add',
            is_superuser_action: false,
            name: 'Exam Type',
            label: 'Exam Type',
            action: 'action-url',
            url: '/exam/type/add',
            component: <AddExamType />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.examtypes.basename],
            action_code: 'visible_exam_type_change',
            is_superuser_action: false,
            name: 'Exam',
            label: 'Exam',
            action: 'action-url',
            url: '/exam/type/edit',
            component: <ViewExamType />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.examtypes.basename],
            action_code: 'visible_exam_type_delete',
            is_superuser_action: false,
            name: 'Delete Exam Type',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Exam Type',
        type: 'exam',
    },
    cumulative_type: {
        view: {
            codenames: [GET_URL.cumulativetype.basename],
            action_code: 'visible_cumulative_type_view',
            is_superuser_action: false,
            name: 'Cumulative Type',
            label: `${alias_names['cumulative']} Type`,
            action: 'sub-menu',
            url: '/cumulative/type/view',
            component: <ViewCumulativeType />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/cumulative/type/add', '/cumulative/type/edit'],
        },
        create: {
            codenames: [POST_URL.cumulativetype.basename],
            action_code: 'visible_cumulative_type_add',
            is_superuser_action: false,
            name: 'Cumulative Type',
            label: `${alias_names['cumulative']} Type`,
            action: 'action-url',
            url: '/cumulative/type/add',
            component: <AddCumulativeType />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [POST_URL.cumulativetype.basename],
            action_code: 'visible_cumulative_type_change',
            is_superuser_action: false,
            name: 'Cumulative',
            label: `${alias_names['cumulative']} Type`,
            action: 'action-url',
            url: '/cumulative/type/edit',
            component: <ViewCumulativeType />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.cumulativetype.basename],
            action_code: 'visible_cumulative_type_delete',
            is_superuser_action: false,
            name: 'Delete  Type',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Cumulative Type',
        type: 'exam',
    },
    exams: {
        view: {
            codenames: [GET_URL.examterms.basename, GET_URL.exam.basename],
            action_code: 'visible_exams_view',
            is_superuser_action: false,
            name: 'Exams',
            label: 'Exams',
            action: 'sub-menu',
            url: '/exam/view',
            component: <ViewExam />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/add', '/exam/edit'],
        },
        create: {
            codenames: [
                GET_URL.exam.basename, POST_URL.exam.basename, PUT_URL.exam.basename,
                GET_URL.getstandardandsection.basename, GET_URL.examtypes.basename, GET_URL.examterms.basename
            ],
            action_code: 'visible_exams_add',
            is_superuser_action: false,
            name: 'Exam',
            label: 'Exam',
            action: 'action-url',
            url: '/exam/add',
            component: <AddExam />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [
                GET_URL.exam.basename, POST_URL.exam.basename, PUT_URL.exam.basename,
                GET_URL.getstandardandsection.basename, GET_URL.examtypes.basename, GET_URL.examterms.basename
            ],
            action_code: 'visible_exams_change',
            is_superuser_action: false,
            name: 'Exam',
            label: 'Exam',
            action: 'action-url',
            url: '/exam/edit',
            component: <AddExam />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.exam.basename],
            action_code: 'visible_exams_delete',
            is_superuser_action: false,
            name: 'Delete Exam',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Exam',
        type: 'exam',
    },
    schedule_exam: {
        view: {
            codenames: [GET_URL.examterms.basename, GET_URL.exam.basename, GET_URL.schedule.basename, GET_URL.examscheduledashboard.basename, PUT_URL.examapprove.basename],
            action_code: 'visible_schedule_exam_view',
            is_superuser_action: false,
            name: 'Schedule Exam',
            label: 'Schedule Exam',
            action: 'sub-menu',
            url: '/exam/schedule/view',
            component: <ScheduleExamView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/schedule/add'],
        },
        create: {
            codenames: [GET_URL.schedule.basename, POST_URL.schedule.basename, POST_URL.copyschedule.basename, POST_URL.bulkclearexamschedule.basename, PUT_URL.examapprove.basename,
            GET_URL.studentgrade.basename, GET_URL.cumulativetype.basename],
            action_code: 'visible_schedule_exam_add',
            is_superuser_action: false,
            name: 'Schedule Exam',
            label: 'Schedule Exam',
            action: 'action-url',
            url: '/exam/schedule/add',
            component: <ScheduleExamAdd />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Schedule Exam',
        type: 'exam',
    },
    schedule_exam_old: {
        view: {
            codenames: [GET_URL.examterms.basename, GET_URL.exam.basename, GET_URL.schedule.basename, PUT_URL.examapprove.basename],
            action_code: 'visible_schedule_exam_old_view',
            is_superuser_action: false,
            name: 'Schedule Exam (Old UI)',
            label: 'Schedule Exam (Old UI)',
            action: 'sub-menu',
            url: '/exam/schedule/old-view',
            component: <ScheduleExamViewOld />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/schedule/old-add'],
        },
        create: {
            codenames: [GET_URL.schedule.basename, POST_URL.schedule.basename, POST_URL.copyschedule.basename, POST_URL.bulkclearexamschedule.basename, PUT_URL.examapprove.basename,
            GET_URL.studentgrade.basename, GET_URL.cumulativetype.basename],
            action_code: 'visible_schedule_exam_old_add',
            is_superuser_action: false,
            name: 'Schedule Exam (Old UI)',
            label: 'Schedule Exam (Old UI)',
            action: 'action-url',
            url: '/exam/schedule/old-add',
            component: <ScheduleExamAddOld />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Schedule Exam Old UI',
        type: 'exam',
    },
    schedule_exam_approve: {
        create: {
            codenames: [PUT_URL.examapprove.basename],
            action_code: 'visible_schedule_exam_approve_add',
            is_superuser_action: false,
            name: 'Approve Schedule Exam',
            label: 'Approve Schedule Exam',
            action: 'action-url',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Approve Schedule Exam',
        type: 'exam',
    },
    hall_ticket_generator: {
        view: {
            codenames: [GET_URL.exam.basename, GET_URL.hallticket.basename, GET_URL.getsection.basename,
            GET_URL.getenrolledstudents.basename, GET_URL.examterms.basename],
            action_code: 'visible_hall_ticket_generator_view',
            is_superuser_action: false,
            name: 'Hall Ticket',
            label: 'Hall Ticket',
            action: 'sub-menu',
            url: '/exam/hall-ticket-generator',
            component: <HallTicketGenerator />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hall Ticket Generator',
        type: 'exam',
    },
    marks_card_generator: {
        view: {
            codenames: [GET_URL.exam.basename, GET_URL.studentmark.basename, GET_URL.getsection.basename,
            GET_URL.getenrolledstudents.basename, GET_URL.examterms.basename],
            action_code: 'visible_marks_card_generator_view',
            is_superuser_action: false,
            name: 'Marks Card',
            label: 'Marks Card',
            action: 'sub-menu',
            url: '/exam/marks-card-generator',
            component: <MarksCardGenerator />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Marks Card Generator',
        type: 'exam',
    },
    marks_card_generator_v2: {
        view: {
            codenames: [GET_URL.exam.basename, GET_URL.studentmarkv2.basename, GET_URL.getsection.basename,
            GET_URL.getenrolledstudents.basename, GET_URL.examterms.basename, GET_URL.announceexamresultconfigv2.basename,
            GET_URL.studentmarkresultconfigv2.basename, GET_URL.studentmarkresultfinalconfigv2.basename],
            action_code: 'visible_marks_card_generator_v2_view',
            is_superuser_action: false,
            name: 'Marks Card V2',
            label: 'Marks Card V2',
            action: 'sub-menu',
            url: '/exam/marks-card-generator-v2',
            component: <MarksCardGeneratorV2 />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Marks Card Generator V2',
        type: 'exam',
    },
    result_config: {
        view: {
            codenames: [GET_URL.examresultconfig.basename, GET_URL.examterms.basename, GET_URL.exam.basename, GET_URL.resultconfiguration.basename,],
            action_code: 'visible_result_config_view',
            is_superuser_action: false,
            name: 'Result Configuration',
            label: 'Result Configuration',
            action: 'sub-menu',
            url: '/exam/result/config/view',
            component: <ViewResultConfiguration />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/result/config/add', 'term/result/config/add'],
        },
        create: {
            codenames: [GET_URL.examresultconfigindividual.basename, GET_URL.studentgrade.basename,
            POST_URL.examresultconfig.basename, POST_URL.approveexamresultconfig.basename],
            action_code: 'visible_result_config_add',
            is_superuser_action: false,
            name: 'Exam Result Configuration',
            label: 'Exam Result Configuration',
            action: 'action-url',
            url: '/exam/result/config/add',
            component: <AddResultConfiguration />,
            permission_needed: false,
            exclude_roles: [7],
        },
        name: 'Exam Result Configuration',
        type: 'exam',
    },
    term_result_config: {
        create: {
            codenames: [GET_URL.individual.basename, POST_URL.resultconfiguration.basename],
            action_code: 'visible_term_result_config_add',
            is_superuser_action: false,
            name: 'Term Result Configuration',
            label: 'Term Result Configuration',
            action: 'action-url',
            url: '/term/result/config/add',
            component: <TermResultConfiguration />,
            permission_needed: false,
            exclude_roles: [7],
        },
        name: 'Term Result Configuration',
        type: 'exam',
    },
    exam_marks_enter: {
        view: {
            codenames: [GET_URL.examterms.basename, GET_URL.exam.basename,
            GET_URL.studentmarkclasssummary.basename, PUT_URL.examapprove.basename],
            action_code: 'visible_exam_marks_enter_view',
            is_superuser_action: false,
            name: 'Exam Marks',
            label: 'Exam Marks',
            action: 'sub-menu',
            url: '/exam/marks/view',
            component: <ExamMarksView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/marks/add', '/exam/marks/send-notification'],
        },
        create: {
            codenames: [GET_URL.studentmark.basename, POST_URL.studentmark.basename,
            POST_URL.approvestudentmark.basename],
            action_code: 'visible_exam_marks_enter_add',
            is_superuser_action: false,
            name: 'Exam Marks',
            label: 'Exam Marks',
            action: 'action-url',
            url: '/exam/marks/add',
            component: <ExamMarksAdd />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Manage Exam Marks',
        type: 'exam',
    },
    exam_marks_send_notification: {
        create: {
            codenames: [GET_URL.language.basename, GET_URL.medium.basename, GET_URL.bulknotification.basename,
                GET_URL.groups.basename, GET_URL.getstafffullname.basename, GET_URL.getenrolledstudents.basename,
                GET_URL.getacademicyear.basename, GET_URL.getstandardandsection.basename, POST_URL.studentmarkbulknotification.basename,
                GET_URL.getcustombulknotification.basename],
            action_code: 'visible_exam_marks_enter_view',
            is_superuser_action: false,
            name: 'Send Notification',
            label: 'Send Notification',
            action: 'action-url',
            url: '/exam/marks/send-notification',
            component: <ExamMarksSendNotification />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Send Notification',
        type: 'exam',
    },
    exam_grade_plan: {
        view: {
            codenames: [GET_URL.studentgrade.basename],
            action_code: 'visible_exam_grade_plan_view',
            is_superuser_action: false,
            name: 'Grade Plan',
            label: 'Grade Plan',
            action: 'sub-menu',
            url: '/exam/grade/view',
            component: <GradePlanView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/grade/add'],
        },
        create: {
            codenames: [GET_URL.studentgrade.basename, POST_URL.studentgrade.basename],
            action_code: 'visible_exam_grade_plan_add',
            is_superuser_action: false,
            name: 'Grade Plan',
            label: 'Grade Plan',
            action: 'action-url',
            url: '/exam/grade/add',
            component: <GradePlanAdd />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [GET_URL.studentgrade.basename, POST_URL.studentgrade.basename],
            action_code: 'visible_exam_grade_plan_change',
            is_superuser_action: false,
            name: 'Grade Plan',
            label: 'Grade Plan',
            action: 'action-url',
            url: '/exam/grade/edit',
            component: <GradePlanAdd />,
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.studentgrade.basename],
            action_code: 'visible_exams_delete',
            is_superuser_action: false,
            name: 'Delete Grade Plan',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Grade Plan',
        type: 'exam',
    },
    exam_result_summary: {
        view: {
            codenames: [GET_URL.examterms.basename, GET_URL.exam.basename, GET_URL.announceresult.basename,
            GET_URL.announceresultconfig.basename, GET_URL.announceexamresultconfig.basename],
            action_code: 'visible_exam_result_summary_view',
            is_superuser_action: false,
            name: 'Exam Result Summary',
            label: 'Exam Result Summary',
            action: 'sub-menu',
            url: '/exam/result/summary/view',
            component: <ResultSummaryView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/result/individual/view'],
        },
        name: 'Result Summary',
        type: 'exam',
    },
    exam_result_individual: {
        view: {
            codenames: [GET_URL.studentmark.basename, GET_URL.studentmarkresultconfig.basename, POST_URL.examstatusupdate.basename,
            POST_URL.announceresult.basename, POST_URL.announceresultconfig.basename,],
            action_code: 'visible_exam_result_individual_view',
            is_superuser_action: false,
            name: 'Individual Result Exam',
            label: 'Individual Result Exams',
            action: 'action',
            url: '/exam/result/individual/view',
            component: <ResultSectionView />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Result Individual',
        type: 'exam',
    },
    final_result_config: {
        view: {
            codenames: [GET_URL.examfinalresultconfiguration.basename],
            action_code: 'visible_final_result_config_view',
            is_superuser_action: false,
            name: 'Final Result Config',
            label: 'Final Result Config',
            action: 'sub-menu',
            url: '/exam/finalresultconfig/view',
            component: <ViewFinalResultConfig />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/finalresultconfig/add'],
        },
        create: {
            codenames: [GET_URL.studentgrade.basename, GET_URL.individual.basename,
            GET_URL.examfinalresultconfigurationindividual.basename, POST_URL.resultconfiguration.basename,
            POST_URL.approveresultconfiguration.basename, POST_URL.examfinalresultconfiguration.basename, PUT_URL.examfinalresultconfiguration.basename],
            action_code: 'visible_final_result_config_add',
            is_superuser_action: false,
            name: 'Final Result Config',
            label: 'Final Result Config',
            action: 'action-url',
            url: '/exam/finalresultconfig/add',
            component: <AddFinalResultConfig />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Final Result Config',
        type: 'exam',
    },
    final_result_config_new: {
        view: {
            codenames: [GET_URL.examfinalresultconfigurationnew.basename],
            action_code: 'visible_final_result_config_view',
            is_superuser_action: false,
            name: 'Final Result Config',
            label: 'Final Result Config',
            action: 'sub-menu',
            url: '/exam/finalresultconfignew/view',
            component: <ViewFinalResultConfignew />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/exam/finalresultconfignew/add'],
        },
        create: {
            codenames: [GET_URL.studentgrade.basename, GET_URL.individual.basename,
            GET_URL.examfinalresultconfigurationindividual.basename, POST_URL.resultconfiguration.basename,
            POST_URL.approveresultconfiguration.basename, POST_URL.examfinalresultconfiguration.basename, PUT_URL.examfinalresultconfiguration.basename],
            action_code: 'visible_final_result_config_add',
            is_superuser_action: false,
            name: 'Final Result Config',
            label: 'Final Result Config',
            action: 'action-url',
            url: '/exam/finalresultconfignew/add',
            component: <AddFinalResultConfignew />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Final Result Config',
        type: 'exam',
    },
    reports_subject_wise: {
        view: {
          codenames: ['view_report_subject_wise'],  // update with your actual backend permission codenames
          action_code: 'visible_report_subject_wise_view',
          is_superuser_action: false,
          name: 'Subject-wise Report',
          label: 'Subject-wise Report',
          action: 'sub-menu',
          url: '/reports/subject-wise',
          component: <SubjectWiseReport />,
          permission_needed: true,
          exclude_roles: [7],
        },
        name: 'Subject-wise Report',
        type: 'report',
      },
    
    //   reports_student_wise: {
    //     view: {
    //       codenames: ['view_report_student_wise'],
    //       action_code: 'visible_report_student_wise_view',
    //       is_superuser_action: false,
    //       name: 'Student-wise Report',
    //       label: 'Student-wise Report',
    //       action: 'sub-menu',
    //       url: '/reports/student-wise',
    //       component: <StudentWiseReport />,
    //       permission_needed: true,
    //       exclude_roles: [7],
    //     },
    //     name: 'Student-wise Report',
    //     type: 'report',
    //   },
    
    //   reports_rank_wise: {
    //     view: {
    //       codenames: ['view_report_rank_wise'],
    //       action_code: 'visible_report_rank_wise_view',
    //       is_superuser_action: false,
    //       name: 'Rank-wise Report',
    //       label: 'Rank-wise Report',
    //       action: 'sub-menu',
    //       url: '/reports/rank-wise',
    //       component: <RankWiseReport />,
    //       permission_needed: true,
    //       exclude_roles: [7],
    //     },
    //     name: 'Rank-wise Report',
    //     type: 'report',
    //   },
    
    //   reports_cumulative: {
    //     view: {
    //       codenames: ['view_report_cumulative'],
    //       action_code: 'visible_report_cumulative_view',
    //       is_superuser_action: false,
    //       name: 'Cumulative Report',
    //       label: 'Cumulative Report',
    //       action: 'sub-menu',
    //       url: '/reports/cumulative',
    //       component: <CumulativeReport />,
    //       permission_needed: true,
    //       exclude_roles: [7],
    //     },
    //     name: 'Cumulative Report',
    //     type: 'report',
    //   },
    
    //   reports_attendance: {
    //     view: {
    //       codenames: ['view_report_attendance'],
    //       action_code: 'visible_report_attendance_view',
    //       is_superuser_action: false,
    //       name: 'Attendance Report',
    //       label: 'Attendance Report',
    //       action: 'sub-menu',
    //       url: '/reports/attendance',
    //       component: <AttendanceReport />,
    //       permission_needed: true,
    //       exclude_roles: [7],
    //     },
    //     name: 'Attendance Report',
    //     type: 'report',
    //   },
    //   reports_audit_log: {
    //     view: {
    //       codenames: ['view_report_audit_log'],
    //       action_code: 'visible_report_audit_log_view',
    //       is_superuser_action: false,
    //       name: 'Audit Log Report',
    //       label: 'Audit Log',
    //       action: 'sub-menu',
    //       url: '/reports/audit-log',
    //       component: <AuditLogReport />,
    //       permission_needed: true,
    //       exclude_roles: [7],
    //     },
    //     name: 'Audit Log Report',
    //     type: 'report',
    //   },

}
export default Actions;