import React from "react";
import { GET_URL, POST_URL, DEL_URL, PUT_URL } from "Includes/urls";

import ViewExpensesType from "Containers/Expenses/ViewExpensesType";
import AddExpensesType from "Containers/Expenses/AddExpensesType";
import ViewExpensePlan from "Containers/Expenses/ViewExpensePlan";
import AddExpensePlan from "Containers/Expenses/AddExpensePlan";
import ViewExpenses from "Containers/Expenses/ViewExpenses";
import CreateExpenses from "Containers/Expenses/CreateExpenses";
import ViewExpenseIndividual from "Containers/Expenses/ViewExpenseIndividual";
import ViewFuelToken from "Containers/Expenses/ViewFuelToken";
import AddFuelToken from "Containers/Expenses/AddFuelToken";
import ViewExpenseCategory from "Containers/Expenses/ViewExpenseCategory";
import AddExpenseCategory from "Containers/Expenses/AddExpenseCategory";

const Actions = {
  expenses_category: {
    view: {
      codenames: [GET_URL.expensecategory.basename],
      action_code: "visible_expenses_category_view",
      is_superuser_action: false,
      name: "Expenses Categry",
      label: "Expenses Categry",
      action: "sub-menu",
      url: "/expenses/category/view",
      component: <ViewExpenseCategory />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/expenses/category/add"],
    },
    create: {
      codenames: [POST_URL.expensecategory.basename],
      action_code: "visible_expenses_category_add",
      is_superuser_action: false,
      name: "Create Expenses Category",
      label: "Expenses Category",
      action: "action-url",
      url: "/expenses/category/add",
      component: <AddExpenseCategory />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.expensecategory.basename],
      action_code: "visible_expenses_category_change",
      is_superuser_action: false,
      name: "Update Expenses Category",
      label: "Update Expenses Category",
      action: "action-url",
      url: "/expenses/category/edit",
      component: <ViewExpensesType />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.expensecategory.basename],
      action_code: "visible_expenses_category_delete",
      is_superuser_action: false,
      name: "Delete Expenses Category",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Expenses Category",
    type: "expenses",
  },
  expenses_type: {
    view: {
      codenames: [
        GET_URL.expensecategory.basename,
        GET_URL.expensetype.basename,
      ],
      action_code: "visible_expenses_type_view",
      is_superuser_action: false,
      name: "View Expenses Type",
      label: "Manage Expenses Type",
      action: "sub-menu",
      url: "/expenses/type/view",
      component: <ViewExpensesType />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/expenses/type/add"],
    },
    create: {
      codenames: [
        GET_URL.expensecategory.basename,
        POST_URL.expensetype.basename,
      ],
      action_code: "visible_expenses_type_add",
      is_superuser_action: false,
      name: "Create Expenses Type",
      label: "Expenses Type",
      action: "action-url",
      url: "/expenses/type/add",
      component: <AddExpensesType />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.expensetype.basename],
      action_code: "visible_expenses_type_change",
      is_superuser_action: false,
      name: "Update Expenses Type",
      label: "Update Expenses Type",
      action: "action-url",
      url: "/expenses/type/edit",
      component: <ViewExpensesType />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.expensetype.basename],
      action_code: "visible_expenses_type_delete",
      is_superuser_action: false,
      name: "Delete Expenses Type",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Expenses Type",
    type: "expenses",
  },
  expenses_plan: {
    view: {
      codenames: [
        GET_URL.expenseplan.basename,
        GET_URL.getfinancialyear.basename,
      ],
      action_code: "visible_expenses_plan_view",
      is_superuser_action: false,
      name: "View Expenses Plan",
      label: "Expenses Plan",
      action: "sub-menu",
      url: "/expenses/plan/view",
      component: <ViewExpensePlan />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/expenses/plan/add"],
    },
    create: {
      codenames: [POST_URL.expenseplan.basename],
      action_code: "visible_expenses_plan_add",
      is_superuser_action: false,
      name: "Create Expenses Plan",
      label: "Expenses Plan",
      action: "action-url",
      url: "/expenses/plan/add",
      component: <AddExpensePlan />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.expenseplan.basename],
      action_code: "visible_expenses_plan_change",
      is_superuser_action: false,
      name: "Update Expenses Plan",
      label: "Update Expenses Plan",
      action: "action-url",
      url: "/expenses/plan/edit",
      component: <ViewExpensePlan />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.expenseplan.basename],
      action_code: "visible_expenses_plan_delete",
      is_superuser_action: false,
      name: "Delete Expenses Plan",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Expenses Plan",
    type: "expenses",
  },
  expenses_create: {
    view: {
      codenames: [
        GET_URL.expense.basename,
        GET_URL.expenseplan.basename,
        GET_URL.financialyear.basename,
      ],
      action_code: "visible_expenses_create_view",
      is_superuser_action: false,
      name: "View Expenses",
      label: "View Expenses",
      action: "sub-menu",
      url: "/expenses/view",
      component: <ViewExpenses />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: [
        "/expenses/add",
        "/expenses/edit",
        "/expenses/detail/view",
      ],
    },
    create: {
      codenames: [
        POST_URL.expense.basename,
        GET_URL.expenseplan.basename,
        GET_URL.vehicle.basename,
        GET_URL.token.basename,
      ],
      action_code: "visible_expenses_create_add",
      is_superuser_action: false,
      name: "Create Expenses",
      label: "Create Expenses",
      action: "action-url",
      url: "/expenses/add",
      component: <CreateExpenses />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        PUT_URL.expense.basename,
        GET_URL.expenseplan.basename,
        GET_URL.vehicle.basename,
        GET_URL.token.basename,
      ],
      action_code: "visible_expenses_create_change",
      is_superuser_action: false,
      name: "Update Expenses",
      label: "Update Expenses",
      action: "action-url",
      url: "/expenses/edit",
      component: <CreateExpenses />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.expense.basename],
      action_code: "visible_expenses_create_delete",
      is_superuser_action: false,
      name: "Delete Expenses",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Expenses Create",
    type: "expenses",
  },
  expenses_individual: {
    view: {
      codenames: [GET_URL.expense.basename],
      action_code: "visible_expenses_create_view",
      is_superuser_action: false,
      name: "View Expenses",
      label: "View Expenses",
      action: "action",
      url: "/expenses/detail/view",
      component: <ViewExpenseIndividual />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Expenses Individual View",
    type: "expenses",
  },
  fuel_token: {
    view: {
      codenames: [GET_URL.token.basename, DEL_URL.token.basename],
      action_code: "visible_fuel_token_view",
      is_superuser_action: false,
      name: "View Fuel Token",
      label: "View Fuel Token",
      action: "sub-menu",
      url: "/expenses/fuel-token/view",
      component: <ViewFuelToken />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/expenses/fuel-token/add"],
    },
    create: {
      codenames: [
        POST_URL.token.basename,
        GET_URL.staff.basename,
        GET_URL.vehicle.basename,
      ],
      action_code: "visible_fuel_token_add",
      is_superuser_action: false,
      name: "Create Fuel Token",
      label: "Fuel Token",
      action: "action-url",
      url: "/expenses/fuel-token/add",
      component: <AddFuelToken />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.token.basename],
      action_code: "visible_fuel_token_delete",
      is_superuser_action: false,
      name: "Delete Expenses",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fuel Token",
    type: "expenses",
  },
};
export default Actions;
