import React from "react";
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from "Includes/urls";

import AddFeesType from "Containers/Finance/AddFeesType";
import AddFeeTypeAdd from "Containers/Finance/AddFeeTypeAdd";
import FeesType from "Containers/Finance/FeesType";
import EnableStudentFeatures from "Containers/Finance/EnableStudentFeatures";
import FeePlanView from "Containers/Finance/FeePlanView";
import CreateFeePlan from "Containers/Finance/CreateFeePlan";
import CreateFeeTerm from "Containers/Finance/CreateFeeTerm";
import FeeCollectionNew from "Containers/Finance/FeeCollectionNew";
import FeesCollectionView from "Containers/Finance/FeesCollectionView";
import ViewFeesTypes from "Containers/Finance/ViewFeesType";
import AddApplicationFee from "Containers/Finance/AddApplicationFee";
import ApplicationFeeView from "Containers/Finance/ApplicationFeeView";
import EnableFeaturePopup from "Containers/Finance/Components/EnableFeaturePopup";
import ConcessionType from "Containers/Finance/ConcessionType";
import ConcessionTypeAdd from "Containers/Finance/ConcessionTypeAdd";
import FeesConcessionView from "Containers/Finance/FeesConcessionView";
import StudentFeeConcession from "Containers/Finance/StudentFeeConcessionNew";
import Cashbook from "Containers/Finance/Cashbook";
import TallyView from "Containers/Finance/TallyView";
import AccountingView from "Containers/Finance/AccountingView";
import ApplicationFeesTransaction from "Containers/Finance/ApplicationFeesTransaction";
import FeeCollectionReport from "Containers/Finance/FeeCollectionReport";
import AddBank from "Containers/Finance/AddBank";
import ViewBank from "Containers/Finance/ViewBank";
import ViewFeeTypeBankMap from "Containers/Finance/ViewFeeTypeBankMap";
import AddFeeTypeBankMap from "Containers/Finance/AddFeeTypeBankMap";
import ViewFeeTypeBankBalance from "Containers/Finance/ViewFeeTypeBankBalance";
import AddBankTransaction from "Containers/Finance/AddBankTransaction";
import ViewBankTransactions from "Containers/Finance/ViewBankTransactions";
import AddBankTransfer from "Containers/Finance/AddBankTransfer";
import ViewBankTransfer from "Containers/Finance/ViewBankTransfer";
import TransactionSummaryDashboard from "Containers/Finance/TransactionSummaryDashboard";
import CashInHandOpeningBalance from "Containers/Finance/CashInHandOpeningBalance";
import AddCashInHandOpeningBalance from "Containers/Finance/AddCashInHandOpeningBalance";
import BankBalanceCarryForward from "Containers/Finance/BankBalanceCarryForward";
import ViewFeeTerm from "Containers/Finance/ViewFeeTerm";
import FeeTermViewIndividual from "Containers/Finance/Components/FeeTermViewIndividual";
import StandardConcessionView from "Containers/Finance/StandardConcessionView";
import StandardConcessionAdd from "Containers/Finance/StandardConcessionAdd";
import ConcessionViewIndividual from "Containers/Finance/Components/ConcessionViewIndividual";
import FeeGroupList from "Containers/Finance/FeeGroupList";
import AddFeeGroup from "Containers/Finance/AddFeeGroup";
import FeeStudentStoreList from "Containers/Finance/FeeStudentStoreList";
import StudentCustomFees from "Containers/Finance/StudentCustomFees";
import FeeAdjustmentApprovalList from "Containers/Finance/FeeAdjustmentApprovalList";
import FundBorrowList from "Containers/Finance/FundBorrowList";
import AdditionalFeeTypeList from "Containers/Finance/AdditionalFeeTypeList";
import AdditionalFeeTypeAdd from "Containers/Finance/AdditionalFeeTypeAdd";
import AdditionalFeePlanList from "Containers/Finance/AdditionalFeePlanList";
import AdditionalFeePlan from "Containers/Finance/AdditionalFeePlan";
import ViewAdditionalCharge from "Containers/Finance/ViewAdditionalCharge";
import CreateTermAdditionalCharge from "Containers/Finance/CreateTermAdditionalCharge";
import FeeCategoryList from "Containers/Finance/FeeCategoryList";
import FeeCategoryAdd from "Containers/Finance/FeeCategoryAdd";
import AdvanceFeeTypeList from "Containers/Finance/AdvanceFeeTypeList";
import AdvanceFeeTypeAdd from "Containers/Finance/AdvanceFeeTypeAdd";
import AdvanceFeeCollectionList from "Containers/Finance/AdvanceFeeCollectionList";
import AdvanceFeeCollectionAdd from "Containers/Finance/AdvanceFeeCollectionAdd";
import FeeCategoryPlanList from "Containers/Finance/FeeCategoryPlanList";
import FeeCategoryPlanAdd from "Containers/Finance/FeeCategoryPlanAdd";
import StudentPayMyFees from "Containers/Finance/StudentPayMyFees";
import FinanceDashboard from "Containers/Finance/FinanceDashboard";
import AreaWisePendingReport from "Containers/Finance/AreaWisePendingReport";
// Asset Management
import AssetGroupList from "Containers/Finance/AssetGroupList";
import AddAssetGroup from "Containers/Finance/AddAssetGroup";
import AssetList from "Containers/Finance/AssetList";
import AddAsset from "Containers/Finance/AddAsset";
import DepreciationRun from "Containers/Finance/DepreciationRun";
import FixedAssetRegister from "Containers/Finance/FixedAssetRegister";
import FixedAssetCostRegister from "Containers/Finance/FixedAssetCostRegister";
import AssetReports from "Containers/Finance/AssetReports";
// Salary Advance
import SalaryAdvanceList from "Containers/Finance/SalaryAdvance/SalaryAdvanceList";
import SalaryAdvanceCreate from "Containers/Finance/SalaryAdvance/SalaryAdvanceCreate";
import SalaryAdvanceDetail from "Containers/Finance/SalaryAdvance/SalaryAdvanceDetail";
import SalaryAdvanceEdit from "Containers/Finance/SalaryAdvance/SalaryAdvanceEdit";
import SalaryAdvanceStatement from "Containers/Finance/SalaryAdvance/SalaryAdvanceStatement";
import SalaryAdvanceAddRecovery from "Containers/Finance/SalaryAdvance/SalaryAdvanceAddRecovery";


import BalanceSheet from "Containers/Finance/BalanceSheet";
import FinanceAuditLog from "Containers/Finance/FinanceAuditLog";

// Unified Recoverable Assets
import RecoverableAssetCategoryList from "Containers/Finance/RecoverableAsset/RecoverableAssetCategoryList";
import RecoverableAssetRegister from "Containers/Finance/RecoverableAsset/RecoverableAssetRegister";
import RecoverableAssetTransactions from "Containers/Finance/RecoverableAsset/RecoverableAssetTransactions";

import CombinedAssetDashboard from "Containers/Finance/CombinedAssetDashboard";
import AddRecoverableAsset from "Containers/Finance/RecoverableAsset/AddRecoverableAsset";
import EditRecoverableAsset from "Containers/Finance/RecoverableAsset/EditRecoverableAsset";
import AddRecoverableAssetTransaction from "Containers/Finance/RecoverableAsset/AddRecoverableAssetTransaction";
import AddRecoverableAssetCategory from "Containers/Finance/RecoverableAsset/AddRecoverableAssetCategory";
import EditRecoverableAssetCategory from "Containers/Finance/RecoverableAsset/EditRecoverableAssetCategory";

// Fee Mismatch
import FeeMismatchList from "Containers/Finance/FeeMismatchList";
import DenominationList from "Containers/Finance/DenominationList";
import AddDenomination from "Containers/Finance/AddDenomination";
import OnlinePaymentList from "Containers/Finance/OnlinePaymentList";


const pathAlias = JSON.parse(localStorage.getItem("pathAlias"))
  ? JSON.parse(localStorage.getItem("pathAlias"))
  : {};

const Actions = {
  feature_enable: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.fianceStudentlist.basename,
        GET_URL.feature.basename,
      ],
      action_code: "visible_feature_enable_view",
      is_superuser_action: false,
      name: "Features",
      label: "Features",
      action: "sub-menu",
      url: "/finance/features/view",
      component: <EnableStudentFeatures />,
      permission_needed: true,
      exclude_roles: [7],
      old_url: "/finance/features/view",
    },
    create: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.fianceStudentlist.basename,
        POST_URL.feature.basename,
        GET_URL.feature.basename,
        "visible_feature_enable_view",
      ],
      action_code: "visible_feature_enable_add",
      is_superuser_action: false,
      name: "EnableFeatures",
      label: "Enable Features",
      action: "action",
      // url: '/finance/features/view',
      // component: <EnableFeaturePopup />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Enable features to students",
    type: "finance",
    old_code: "feature_enable",
  },
  application_fees: {
    view: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.applicationFeesPlan.basename,
      ], //
      action_code: "visible_application_fees_view",
      is_superuser_action: false,
      name: "View Application Fees",
      label: "Application Fee",
      action: "sub-menu",
      url: "/finance/application-fees/view",
      associated_urls: ["/finance/add-application-fees"],
      component: <ApplicationFeeView />,
      permission_needed: true,
      exclude_roles: [7],
      old_url: "/finance/application-fees/view",
    },
    create: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.applicationFeesPlan.basename,
        POST_URL.applicationplan.basename,
      ],
      action_code: "visible_application_fees_add",
      is_superuser_action: false,
      name: "Application Fees",
      label: "Application Fee",
      action: "action-url",
      url: "/finance/add-application-fees",
      component: <AddApplicationFee />,
      permission_needed: true,
      exclude_roles: [7],
      old_url: "/finance/add-application-fees",
    },
    update: {
      codenames: [PUT_URL.applicationplan.basename],
      action_code: "visible_application_fees_change",
      is_superuser_action: false,
      name: "Update Application Fees",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Application Fees",
    type: "finance",
    old_code: "application_fees",
  },
  fee_type: {
    view: {
      codenames: [GET_URL.addFeeType.basename],
      action_code: "visible_fee_type_view",
      is_superuser_action: false,
      name: "view Fee Type",
      label: "Fee Types",
      action: "sub-menu",
      associated_urls: ["/finance/addfeestype/add"],
      url: "/finance/addfeestype",
      component: <AddFeesType />,
      permission_needed: true,
      exclude_roles: [7],
      old_url: "/finance/addfeestype",
    },
    create: {
      codenames: [POST_URL.addFeeType.basename, GET_URL.addFeeType.basename],
      action_code: "visible_fee_type_add",
      is_superuser_action: false,
      name: "Add Fee Type",
      label: "Fee Types",
      action: "action-url",
      url: "/finance/addfeestype/add",
      component: <AddFeeTypeAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.addFeeType.basename],
      action_code: "visible_fee_type_change",
      is_superuser_action: false,
      name: "Update Fee Type",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.addFeeType.basename],
      action_code: "visible_fee_type_delete",
      is_superuser_action: false,
      name: "Delete Fee Type",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },

    name: "Fee Type",
    type: "finance",
    old_code: "fee_type",
  },
  additional_fee_type: {
    view: {
      codenames: [GET_URL.additionalchargetype.basename],
      action_code: "visible_additional_fee_type_view",
      is_superuser_action: false,
      name: "Additional Fee Type",
      label: "Additional Fee Type",
      action: "sub-menu",
      associated_urls: ["/finance/additionfeestype/add"],
      url: "/finance/additionfeestype",
      component: <AdditionalFeeTypeList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        POST_URL.additionalchargetype.basename,
        GET_URL.additionalchargetype.basename,
      ],
      action_code: "visible_additional_fee_type_add",
      is_superuser_action: false,
      name: "Additional Fee Type",
      label: "Additional Fee Type",
      action: "action-url",
      url: "/finance/additionfeestype/add",
      component: <AdditionalFeeTypeAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.additionalchargetype.basename,
        POST_URL.additionalchargetype.api,
      ],
      action_code: "visible_additional_fee_type_change",
      is_superuser_action: false,
      name: "Additional Fee Type",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.additionalchargetype.basename],
      action_code: "visible_additional_fee_type_delete",
      is_superuser_action: false,
      name: "Additional Fee Type",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Additional Fee Type",
    type: "finance",
  },
  additional_fee_plan: {
    view: {
      codenames: [
        GET_URL.additionalchargetype.basename,
        GET_URL.additionalcharge.basename,
      ],
      action_code: "visible_additional_fee_plan_view",
      is_superuser_action: false,
      name: "Additional Fee Plan",
      label: "Additional Fee Plan",
      action: "sub-menu",
      associated_urls: ["/finance/additionfeesplan/add"],
      url: "/finance/additionfeesplan",
      component: <AdditionalFeePlanList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        POST_URL.additionalchargetype.basename,
        GET_URL.additionalchargetype.basename,
      ],
      action_code: "visible_additional_fee_plan_add",
      is_superuser_action: false,
      name: "Additional Fee Plan",
      label: "Additional Fee Plan",
      action: "action-url",
      url: "/finance/additionfeesplan/add",
      component: <AdditionalFeePlan />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [POST_URL.additionalchargetype.basename],
      action_code: "visible_additional_fee_plan_change",
      is_superuser_action: false,
      name: "Additional Fee Plan",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.additionalchargetype.basename],
      action_code: "visible_additional_fee_plan_delete",
      is_superuser_action: false,
      name: "Additional Fee Plan",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Additional Fee Plan",
    type: "finance",
  },
  assigned_fee_types: {
    view: {
      codenames: [GET_URL.getFeeTypes.basename],
      action_code: "visible_assigned_fee_types_view",
      is_superuser_action: false,
      name: "View Assigned Fee Types",
      label: "Fee Plan",
      action: "sub-menu",
      associated_urls: ["/finance/feeplan/add"],
      url: "/finance/feeplan",
      component: <ViewFeesTypes />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.getFeeTypes.basename,
        GET_URL.addFeeType.basename,
        POST_URL.feetypes.basename,
      ],
      action_code: "visible_assigned_fee_types_add",
      is_superuser_action: false,
      name: "Assign Fee Types",
      label: "Fee Plan",
      action: "action-url",
      url: "/finance/feeplan/add",
      component: <FeesType />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.getFeeTypes.basename,
        PUT_URL.feetypes.basename,
        GET_URL.feegroup.basename,
        PUT_URL.feetypesindividual.basename,
      ],
      action_code: "visible_assigned_fee_types_change",
      is_superuser_action: false,
      name: "Update Assigned Fee Types",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.getFeeTypes.basename,
        DEL_URL.feetypes.basename,
        POST_URL.feetypesdeleteall.basename,
      ],
      action_code: "visible_assigned_fee_types_delete",
      is_superuser_action: false,
      name: "Delete Assigned Fee Types",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Assign Fee Types",
    type: "finance",
    old_code: "assigned_fee_types",
  },
  fee_term: {
    view: {
      codenames: [GET_URL.getFeeTermPlan.basename, GET_URL.feeplan.basename],
      action_code: "visible_fee_term_view",
      is_superuser_action: false,
      name: "View Fee Term",
      label: "Fee Term",
      action: "sub-menu",
      associated_urls: ["/finance/feeterm/create/"],
      url: "/finance/feeterm/view",
      component: <ViewFeeTerm />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.getFeeTermPlan.basename,
        GET_URL.feeplan.basename,
        POST_URL.feeplan.basename,
        GET_URL.feeplan.basename,
      ],
      action_code: "visible_fee_term_add",
      is_superuser_action: false,
      name: "Fee Term",
      label: "Fee Term",
      action: "action-url",
      url: "/finance/feeterm/create",
      component: <CreateFeeTerm />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Term",
    type: "finance",
    old_code: "fee_term",
  },
  fee_term_individual: {
    view: {
      codenames: [GET_URL.getFeeTermPlan.basename],
      action_code: "visible_fee_term_view_individual",
      is_superuser_action: false,
      name: "View Fee Term",
      label: "Fee Term",
      action: "action-url",
      associated_urls: ["/finance/feeterm/create/"],
      url: "/finance/feeterm/viewindividual",
      component: <FeeTermViewIndividual />,
      permission_needed: false, // false because in fee_term view itself we have given permission
    },
    name: "Fee Term Individual",
    type: "finance",
    old_code: "fee_term_individual",
  },
  fee_standard_concession: {
    view: {
      codenames: [GET_URL.feeplanconcession.basename],
      action_code: "visible_fee_standard_concession_view",
      is_superuser_action: false,
      name: "Fee Standard Concession",
      label: "Fee Standard Concession",
      action: "sub-menu",
      associated_urls: ["/finance/standard/concession/create/"],
      url: "/finance/standard/concession/view",
      component: <StandardConcessionView />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.concessiontypes.basename,
        GET_URL.feeplan.basename,
        POST_URL.feeplanconcession.basename,
      ],
      action_code: "visible_fee_standard_concession_add",
      is_superuser_action: false,
      name: "Fee Standard Concession",
      label: "Fee Standard Concession",
      action: "action-url",
      url: "/finance/standard/concession/create",
      component: <StandardConcessionAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Standard Concession",
    type: "finance",
  },
  fee_concession_individual: {
    view: {
      codenames: [GET_URL.feeplan.basename],
      action_code: "visible_fee_term_view_individual",
      is_superuser_action: false,
      name: "View Fee Term",
      label: "Fee Term",
      action: "action-url",
      associated_urls: ["/finance/standard/concession/create"],
      url: "/finance/standard/concession/individual",
      component: <ConcessionViewIndividual />,
      permission_needed: false, // false because in fee_term view itself we have given permission
    },
    name: "Fee Term Individual",
    type: "finance",
  },
  approve_fee_plan: {
    create: {
      codenames: [
        GET_URL.getFeeTermPlan.basename,
        POST_URL.finance_approve.basename,
      ],
      action_code: "visible_approve_fee_plan_add",
      is_superuser_action: false,
      name: "Approve Fee Plan",
      label: "Approve",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Approve Fee Plan",
    type: "finance",
    old_code: "approve_fee_plan",
  },
  fee_collection: {
    view: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.fianceStudentlist.basename,
        GET_URL.feecollection.basename,
        GET_URL.payment.basename,
        GET_URL.feereciept.basename,
      ],
      action_code: "visible_fee_collection_view",
      is_superuser_action: false,
      name: "Fee Collection",
      label: "Fee Collection",
      action: "sub-menu",
      associated_urls: ["/finance/student-fees-collection"],
      url: "/finance/feescollection",
      component: <FeesCollectionView />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.feeplan.basename,
        GET_URL.fianceStudentlist.basename,
        GET_URL.feecollection.basename,
        POST_URL.feecollection.basename,
        POST_URL.adjustment.basename,
        DEL_URL.feecollection.basename,
      ],
      action_code: "visible_fee_collection_add",
      is_superuser_action: false,
      name: "Student Fee Collection",
      label: "Student Fee Collection",
      action: "action-url",
      url: "/finance/student-fees-collection",
      component: <FeeCollectionNew />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.feecollection.basename],
      action_code: "visible_fee_collection_change",
      is_superuser_action: false,
      name: "Update Fee Collection",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.feecollection.basename],
      action_code: "visible_fee_collection_delete",
      is_superuser_action: false,
      name: "Delete Fee Collection",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee collection",
    type: "finance",
    old_code: "fee_collection",
  },
  online_payment_list: {
    view: {
      codenames: [GET_URL.payment_gateway_list.basename],
      action_code: "visible_online_payment_list_view",
      is_superuser_action: false,
      name: "Online Payment List",
      label: "Online Payment List",
      action: "sub-menu",
      associated_urls: ["/finance/online-payments"],
      url: "/finance/online-payments",
      component: <OnlinePaymentList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Online Payment List",
    type: "finance",
  },
  fee_collection_editable: {
    create: {
      codenames: [],
      action_code: "visible_fee_collection_editable_add",
      is_superuser_action: false,
      name: "Student Fee Collection",
      label: "Student Fee Collection",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee collection Edit",
    type: "finance",
  },
  fee_adjustment: {
    view: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.fianceStudentlist.basename,
        GET_URL.feecollection.basename,
        GET_URL.payment.basename,
      ],
      action_code: "visible_fee_adjustment_view",
      is_superuser_action: false,
      name: "Fee Adjustment",
      label: "Fee Adjustment",
      action: "sub-menu",
      associated_urls: ["/finance/adjustment"],
      url: "/finance/adjustment/view",
      component: <FeesCollectionView />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.feeplan.basename,
        GET_URL.fianceStudentlist.basename,
        GET_URL.feecollection.basename,
        POST_URL.feecollection.basename,
        POST_URL.adjustment.basename,
        POST_URL.reason.basename,
        GET_URL.reason.basename,
      ],
      action_code: "visible_fee_adjustment_add",
      is_superuser_action: false,
      name: "Student Fee Collection",
      label: "Student Fee Collection",
      action: "action-url",
      url: "/finance/adjustment",
      component: <FeeCollectionNew />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Adjustment",
    type: "finance",
    old_code: "fee_adjustment",
  },
  concession_type: {
    view: {
      codenames: [GET_URL.concessiontypes.basename],
      action_code: "visible_concession_type_view",
      is_superuser_action: false,
      name: "Concession Type",
      label: "Concession Type",
      action: "sub-menu",
      associated_urls: ["/finance/concession-type/add"],
      url: "/finance/concession-type",
      component: <ConcessionType />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.concessiontypes.basename,
        POST_URL.concessiontypes.basename,
      ],
      action_code: "visible_concession_type_add",
      is_superuser_action: false,
      name: "Concession Type",
      label: "Concession Type",
      action: "action-url",
      url: "/finance/concession-type/add",
      component: <ConcessionTypeAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.concessiontypes.basename,
        PUT_URL.concessiontypes.basename,
      ],
      action_code: "visible_concession_type_change",
      is_superuser_action: false,
      name: "Update Concession Type",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.concessiontypes.basename,
        DEL_URL.concessiontypes.basename,
      ],
      action_code: "visible_concession_type_delete",
      is_superuser_action: false,
      name: "Delete Concession Type",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Concession Type",
    type: "finance",
    old_code: "concession_type",
  },
  student_fee_concession: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.concessionstudentlist.basename,
      ],
      action_code: "visible_student_fee_concession_view",
      is_superuser_action: false,
      name: "Fee Concession",
      label: "Fee Concession",
      action: "sub-menu",
      associated_urls: ["/finance/student-concessions/add"],
      url: "/finance/student-concessions",
      component: <FeesConcessionView />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.concessionstudentlist.basename,
        GET_URL.concessionapprove.basename,
        GET_URL.concession.basename,
        GET_URL.concessionstudentlist.basename,
        POST_URL.concessionstudent.basename,
        GET_URL.concessiontypes.basename,
        POST_URL.concession.basename,
      ],
      action_code: "visible_student_fee_concession_add",
      is_superuser_action: false,
      name: "Fee Concession",
      label: "Fee Concession",
      action: "action-url",
      url: "/finance/student-concessions/add",
      component: <StudentFeeConcession />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.concessionstudentlist.basename,
        GET_URL.concessionapprove.basename,
        GET_URL.concession.basename,
        GET_URL.concessionstudentlist.basename,
      ],
      action_code: "visible_student_fee_concession_delete",
      is_superuser_action: false,
      name: "Delete Students Fee Concession",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Concession",
    type: "finance",
    old_code: "student_fee_concession",
  },
  student_fee_concession_individual: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.concessionstudentlist.basename,
        GET_URL.concessionapprove.basename,
        GET_URL.concession.basename,
        GET_URL.concessionstudentlist.basename,
        GET_URL.concessiontypes.basename,
      ],
      action_code: "",
      is_superuser_action: false,
      name: "Fee Concession",
      label: "Fee Concession",
      action: "action-url",
      url: "/finance/student-concessions/individual",
      component: <StudentFeeConcession />,
      permission_needed: false,
    },
    name: "Fee Concession View",
    type: "finance",
    old_code: "student_fee_concession_individual",
  },
  cashbook: {
    view: {
      codenames: [
        GET_URL.getstandard.basename,
        GET_URL.cashbook.basename,
        GET_URL.expense.basename,
        GET_URL.expenseplan.basename,
        GET_URL.financialyear.basename,
        GET_URL.balance.basename,
        GET_URL.addFeeType.basename
      ],
      action_code: "visible_cashbook_view",
      is_superuser_action: false,
      name: "Cashbook",
      label: "Cashbook",
      action: "sub-menu",
      url: "/finance/cashbook",
      component: <Cashbook />,
      permission_needed: true,
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
      exclude_roles: [7],
    },
    name: "Cashbook",
    type: "finance",
    old_code: "cashbook",
  },
  tally_view: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.tally.basename,
        GET_URL.getstandard.basename,
      ],
      action_code: "visible_tally_view",
      is_superuser_action: false,
      name: "Tally View",
      label: "Tally View",
      action: "sub-menu",
      url: "/finance/tally",
      component: <TallyView />,
      permission_needed: true,
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    name: "Tally View",
    type: "finance",
    old_code: "tally_view",
  },
  accounting_view: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.accounting.basename,
        GET_URL.longRunningProcess.basename,
      ],
      action_code: "visible_accounting_view",
      is_superuser_action: false,
      name: "Accounting",
      label: "Accounting",
      action: "sub-menu",
      url: "/finance/accounting",
      component: <AccountingView />,
      permission_needed: true,
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    name: "Accounting",
    type: "finance",
    old_code: "accounting_view",
  },
  applicationfeestransactions: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.applicationfeestransaction.basename,
        PUT_URL.applicationfeestransaction.basename,
      ],
      action_code: "visible_applicationfeestransactions_view",
      is_superuser_action: false,
      name: "Application Payment Detail",
      label: "Application Payment Detail",
      action: "sub-menu",
      url: "/finance/applicationfees",
      component: <ApplicationFeesTransaction />,
      permission_needed: true,
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
      exclude_roles: [7],
    },
    name: "Application Fees",
    type: "finance",
  },
  fee_collection_report: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.feecollectionreport.basename,
      ],
      action_code: "visible_fee_collection_report_view",
      is_superuser_action: false,
      name: "Fee collection report",
      label: "Fee collection report",
      action: "sub-menu",
      url: "/finance/reports/fee-collection",
      component: <FeeCollectionReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee collection report",
    type: "finance",
    old_code: "fee_collection_report",
  },
  manage_banks: {
    view: {
      codenames: [GET_URL.bankdetail.basename],
      action_code: "visible_manage_banks_view",
      is_superuser_action: false,
      name: "view Bank List",
      label: "View Bank List",
      action: "sub-menu",
      associated_urls: ["/finance/bank/add"],
      url: "/finance/bank/view",
      component: <ViewBank />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.bankdetail.basename],
      action_code: "visible_manage_banks_add",
      is_superuser_action: false,
      name: "Add Bank",
      label: "Add Bank",
      action: "action-url",
      url: "/finance/bank/add",
      component: <AddBank />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.bankdetail.basename],
      action_code: "visible_manage_banks_change",
      is_superuser_action: false,
      name: "Update Bank",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.bankdetail.basename],
      action_code: "visible_manage_banks_delete",
      is_superuser_action: false,
      name: "Delete Bank",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Manage Banks",
    type: "finance",
    old_code: "manage_banks",
  },
  fee_type_bank_map: {
    view: {
      codenames: [GET_URL.bankdetail.basename, GET_URL.bankfeetype.basename],
      action_code: "visible_fee_type_bank_map_view",
      is_superuser_action: false,
      name: "view Fee Type Bank Map",
      label: "View Fee Type Bank Map",
      action: "sub-menu",
      associated_urls: ["/finance/feetype/bankmap/add"],
      url: "/finance/feetype/bankmap/view",
      component: <ViewFeeTypeBankMap />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.bankfeetype.basename, GET_URL.addFeeType.basename],
      action_code: "visible_fee_type_bank_map_add",
      is_superuser_action: false,
      name: "Add Fee Type Bank Map",
      label: "Add Fee Type Bank Map",
      action: "action-url",
      url: "/finance/feetype/bankmap/add",
      component: <AddFeeTypeBankMap />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Type Bank Map",
    type: "finance",
    old_code: "fee_type_bank_map",
  },
  fee_type_bank_balance: {
    view: {
      codenames: [GET_URL.banktransaction.basename],
      action_code: "visible_fee_type_bank_balance_view",
      is_superuser_action: false,
      name: "view Fee Type Bank Balance",
      label: "Fee Type Bank Balance",
      action: "sub-menu",
      associated_urls: [
        "/finance/feetype/transaction/view",
        "/finance/feetype/transaction/add",
      ],
      url: "/finance/feetype/bankbalance/view",
      component: <ViewFeeTypeBankBalance />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Type Bank Balance Overview",
    type: "finance",
    old_code: "fee_type_bank_balance",
  },
  denominations: {
    view: {
      codenames: [GET_URL.denominations.basename],
      action_code: "visible_denominations_view",
      is_superuser_action: false,
      name: "View Denominations",
      label: "Denominations",
      action: "sub-menu",
      associated_urls: ["/finance/denominations/add"],
      url: "/finance/denominations/view",
      component: <DenominationList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.denominations.basename,
        POST_URL.denominations.basename,
      ],
      action_code: "visible_denominations_add",
      is_superuser_action: false,
      name: "Add Denomination",
      label: "Add Denomination",
      action: "action-url",
      url: "/finance/denominations/add",
      component: <AddDenomination />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.denominations.basename],
      action_code: "visible_denominations_change",
      is_superuser_action: false,
      name: "Update Denomination",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.denominations.basename],
      action_code: "visible_denominations_delete",
      is_superuser_action: false,
      name: "Delete Denomination",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Denominations Setup",
    type: "finance",
  },
  fee_type_bank_transactions: {
    view: {
      codenames: [GET_URL.banktransaction.basename],
      action_code: "visible_fee_type_bank_transactions_view",
      is_superuser_action: false,
      name: "view Bank Balance Transactions",
      label: "View Bank Balance Transactions",
      action: "action-url",
      associated_urls: ["/finance/feetype/transaction/add"],
      url: "/finance/feetype/transaction/view",
      component: <ViewBankTransactions />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.addFeeType.basename,
        GET_URL.staff.basename,
        GET_URL.bankfeetype.basename,
        POST_URL.banktransaction.basename,
      ],
      action_code: "visible_fee_type_bank_transactions_add",
      is_superuser_action: false,
      name: "Add Deposit or WithDraw",
      label: "Add Deposit or WithDraw",
      action: "action-url",
      url: "/finance/feetype/transaction/add",
      component: <AddBankTransaction />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Bank Transactions",
    type: "finance",
    old_code: "fee_type_bank_transactions",
  },
  bank_transfers: {
    view: {
      codenames: [GET_URL.banktransaction.basename],
      action_code: "visible_bank_transfers_view",
      is_superuser_action: false,
      name: "view Bank Transfers",
      label: "View Bank Transfers",
      action: "sub-menu",
      associated_urls: ["/finance/transfer/add"],
      url: "/finance/banktransactions/view",
      component: <ViewBankTransfer />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.bankdetail.basename,
        GET_URL.staff.basename,
        POST_URL.banktransaction.basename,
      ],
      action_code: "visible_bank_transfers_add",
      is_superuser_action: false,
      name: "Add Bank Transfer",
      label: "Add Bank Transfer",
      action: "action-url",
      url: "/finance/banktransactions/add",
      component: <AddBankTransfer />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Bank Transfers",
    type: "finance",
    old_code: "bank_transfers",
  },
  transaction_summary: {
    view: {
      codenames: [GET_URL.depositdata.basename],
      action_code: "visible_transaction_summary_view",
      is_superuser_action: false,
      name: "view Transaction Summary",
      label: "Transaction Summary Dashboard",
      action: "sub-menu",
      associated_urls: [],
      url: "/finance/transactions/summary",
      component: <TransactionSummaryDashboard />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Transaction Summary",
    type: "finance",
    old_code: "transaction_summary",
  },
  cash_in_hand_opening_balance: {
    view: {
      codenames: [GET_URL.staffWallet.basename],
      action_code: "visible_cash_in_hand_opening_balance_view",
      is_superuser_action: false,
      name: "Cash In Hand Opening Balance",
      label: "Cash In Hand Opening Balance",
      action: "sub-menu",
      associated_urls: ["/finance/cash-in-hand/opening-balance/add"],
      url: "/finance/cash-in-hand/opening-balance",
      component: <CashInHandOpeningBalance />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.staffWallet.basename],
      action_code: "visible_cash_in_hand_opening_balance_add",
      is_superuser_action: false,
      name: "Add Opening Balance",
      label: "Add Opening Balance",
      action: "action-url",
      url: "/finance/cash-in-hand/opening-balance/add",
      component: <AddCashInHandOpeningBalance />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Cash In Hand Opening Balance",
    type: "finance",
    old_code: "cash_in_hand_opening_balance",
  },
  bank_balance_carry_forward: {
    view: {
      codenames: [GET_URL.bankBalanceCarryForward.basename],
      action_code: "visible_bank_balance_carry_forward_view",
      is_superuser_action: false,
      name: "Bank Balance Carry Forward",
      label: "Bank Balance Carry Forward",
      action: "sub-menu",
      url: "/finance/bank/carry-forward",
      component: <BankBalanceCarryForward />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Bank Balance Carry Forward",
    type: "finance",
    old_code: "bank_balance_carry_forward",
  },
  fee_group: {
    view: {
      codenames: [GET_URL.addFeeType.basename],
      action_code: "visible_fee_group_view",
      is_superuser_action: false,
      name: "view Fee Type",
      label: "Fee Group",
      action: "sub-menu",
      associated_urls: ["/finance/feegroup/add"],
      url: "/finance/feegroup/list",
      component: <FeeGroupList />,
      permission_needed: true,
      exclude_roles: [7],
      old_url: "/finance/addfeestype",
    },
    create: {
      codenames: [POST_URL.addFeeType.basename, GET_URL.addFeeType.basename],
      action_code: "visible_fee_group_add",
      is_superuser_action: false,
      name: "Add Fee Type",
      label: "Fee Group",
      action: "action-url",
      url: "/finance/feegroup/add",
      component: <AddFeeGroup />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.addFeeType.basename],
      action_code: "visible_fee_group_change",
      is_superuser_action: false,
      name: "Update Fee Group",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.addFeeType.basename],
      action_code: "visible_fee_group_delete",
      is_superuser_action: false,
      name: "Delete Fee Group",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },

    name: "Fee Group",
    type: "finance",
    old_code: "fee_group",
  },
  fee_student_store_list: {
    view: {
      codenames: [],
      action_code: "visible_fee_student_store_list_view",
      is_superuser_action: false,
      name: "Fee Student Store List",
      label: "Fee Student Store List",
      action: "sub-menu",
      associated_urls: ["/finance/student/store/add"],
      url: "/finance/student/store/list",
      component: <FeeStudentStoreList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [],
      action_code: "visible_fee_student_store_list_add",
      is_superuser_action: false,
      name: "Fee Student Store",
      label: "Fee Student Store List",
      action: "action-url",
      url: "/finance/student/store/add",
      component: <AddFeeGroup />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Student Store List",
    type: "finance",
  },
  student_custom_fees: {
    view: {
      codenames: [
        GET_URL.addFeeType.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.fianceStudentlist.basename,
        GET_URL.getstandard.basename,
        POST_URL.feature.basename,
      ],
      action_code: "visible_student_custom_fees_view",
      is_superuser_action: false,
      name: "Student Custom Fees",
      label:
        pathAlias?.["/finance/student/custom/list"] ?? "Student Custom Fees",
      action: "sub-menu",
      url: "/finance/student/custom/list",
      component: <StudentCustomFees />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Student Custom Fees List",
    type: "finance",
  },
  fee_adjustment_request: {
    create: {
      codenames: [],
      action_code: "visible_fee_adjustment_request_add",
      is_superuser_action: false,
      name: "Fee Adjustment Request",
      label: "Fee Adjustment Request",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Adjustment Request",
    type: "finance",
  },
  fee_adjustment_approval: {
    create: {
      codenames: [],
      action_code: "visible_fee_adjustment_approval_add",
      is_superuser_action: false,
      name: "Fee Adjustment Approval",
      label: "Fee Adjustment Approval",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Adjustment Approval",
    type: "finance",
  },
  fee_adjustment_approval_list: {
    view: {
      codenames: [],
      action_code: "visible_fee_adjustment_approval_list_view",
      is_superuser_action: false,
      name: "Adjustment Approval",
      label:
        pathAlias?.["/finance/adjustment/approval/list"] ??
        "Adjustment Approval",
      action: "sub-menu",
      url: "/finance/adjustment/approval/list",
      component: <FeeAdjustmentApprovalList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Adjustment Approval List",
    type: "finance",
  },
  fee_fund_borrow: {
    view: {
      codenames: [],
      action_code: "visible_fee_fund_borrow_view",
      is_superuser_action: false,
      name: "Fund Borrow List",
      label: pathAlias?.["/finance/fund/borrow/list"] ?? "Fund Borrow List",
      action: "sub-menu",
      url: "/finance/fund/borrow/list",
      component: <FundBorrowList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [],
      action_code: "visible_fee_fund_borrow_add",
      is_superuser_action: false,
      name: "Fund Borrow List",
      label: pathAlias?.["/finance/fund/borrow/list"] ?? "Add Fund Borrow",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fund Borrow List",
    type: "finance",
  },
  fee_additional_charge_plan: {
    view: {
      codenames: [GET_URL.getFeeTermPlan.basename, GET_URL.feeplan.basename],
      action_code: "visible_fee_additional_charge_plan_view",
      is_superuser_action: false,
      name: "Fee Additional Charge Plan",
      label: "Fee Additional Charge Plan",
      action: "sub-menu",
      associated_urls: ["/finance/additionalcharge/plan/create/"],
      url: "/finance/additionalcharge/plan/view",
      component: <ViewAdditionalCharge />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.getFeeTermPlan.basename,
        GET_URL.additionalcharge.basename,
        POST_URL.feeplanadditionalchargemapping.basename,
        GET_URL.feeplan.basename,
      ],
      action_code: "visible_fee_additional_charge_plan_add",
      is_superuser_action: false,
      name: "Fee Additional Charge Plan",
      label: "Fee Additional Charge Plan",
      action: "action-url",
      url: "/finance/additionalcharge/plan/create",
      component: <CreateTermAdditionalCharge />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Additional Charge Plan",
    type: "finance",
  },
  fee_category: {
    view: {
      codenames: [GET_URL.feecategory.basename],
      action_code: "visible_fee_category_view",
      is_superuser_action: false,
      name: "Fee Category",
      label: "Fee Category",
      action: "sub-menu",
      associated_urls: ["/finance/category/type/add"],
      url: "/finance/category/type/list",
      component: <FeeCategoryList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.feecategory.basename],
      action_code: "visible_fee_category_add",
      is_superuser_action: false,
      name: "Fee Category",
      label: "Fee Category",
      action: "action-url",
      url: "/finance/category/type/add",
      component: <FeeCategoryAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.feecategory.basename],
      action_code: "visible_fee_category_change",
      is_superuser_action: false,
      name: "Fee Category",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.feecategory.basename],
      action_code: "visible_fee_category_delete",
      is_superuser_action: false,
      name: "Fee Category",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Category",
    type: "finance",
  },
  advance_fee_type: {
    view: {
      codenames: [GET_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_view",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Advance Fee Type",
      action: "sub-menu",
      associated_urls: ["/finance/advance-fee-type/add"],
      url: "/finance/advance-fee-type/list",
      component: <AdvanceFeeTypeList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_add",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Add Advance Fee Type",
      action: "action-url",
      url: "/finance/advance-fee-type/add",
      component: <AdvanceFeeTypeAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_change",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_delete",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Advance Fee Type",
    type: "finance",
  },
  advance_fee_collection: {
    view: {
      codenames: [GET_URL.feeadvancecollection.basename],
      action_code: "visible_advance_fee_collection_view",
      is_superuser_action: false,
      name: "Advance Fee Collection",
      label: "Advance Fee Collection",
      action: "sub-menu",
      associated_urls: ["/finance/advance-fee-collection/add"],
      url: "/finance/advance-fee-collection",
      component: <AdvanceFeeCollectionList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.feeadvancecollection.basename],
      action_code: "visible_advance_fee_collection_add",
      is_superuser_action: false,
      name: "Advance Fee Collection",
      label: "Collect Advance Fee",
      action: "action-url",
      url: "/finance/advance-fee-collection/add",
      component: <AdvanceFeeCollectionAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Advance Fee Collection",
    type: "finance",
  },
  fee_category_plan: {
    view: {
      codenames: [GET_URL.feecategorystandardsectionwise.basename],
      action_code: "visible_fee_category_plan_view",
      is_superuser_action: false,
      name: "Fee Category Plan",
      label: "Fee Category Plan",
      action: "sub-menu",
      associated_urls: ["/finance/category/plan/add"],
      url: "/finance/category/plan/list",
      component: <FeeCategoryPlanList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.feecategorystandardsectionwise.basename],
      action_code: "visible_fee_category_plan_add",
      is_superuser_action: false,
      name: "Fee Category Plan",
      label: "Fee Category Plan",
      action: "action-url",
      url: "/finance/category/plan/add",
      component: <FeeCategoryPlanAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [POST_URL.feecategorystandardsectionwise.basename],
      action_code: "visible_fee_category_plan_change",
      is_superuser_action: false,
      name: "Fee Category Plan",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Category Plan",
    type: "finance",
  },
  fee_cancelled: {
    view: {
      codenames: [],
      action_code: "visible_fee_cancelled_view",
      is_superuser_action: false,
      name: "Fee Category Plan",
      label: "Fee Category Plan",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Cancelled",
    type: "finance",
  },
  manual_receipt_date: {
    create: {
      codenames: [],
      action_code: "visible_manual_receipt_date_add",
      is_superuser_action: false,
      name: "Manual Receipt Date",
      label: "Manual Receipt Date",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Manual Receipt Date",
    type: "finance",
  },
  student_fee_collection: {
    create: {
      codenames: [],
      action_code: "visible_student_fee_collection_add",
      is_superuser_action: false,
      name: "Pay My Fees",
      label: "Pay My Fees",
      action: "sub-menu",
      url: "/finance/student-pay-fees",
      component: <StudentPayMyFees />,
      permission_needed: true,
      exclude_roles: [],
    },
    name: "Pay My Fees",
    type: "finance",
  },
  finance_dashboard: {
    view: {
      codenames: [
        GET_URL.finance_dashboard.basename,
        GET_URL.academicyear.basename,
        GET_URL.standard.basename,
      ],
      action_code: "visible_finance_dashboard_view",
      is_superuser_action: false,
      name: "Finance Dashboard",
      label: "Finance Dashboard",
      action: "sub-menu",
      url: "/finance/dashboard",
      component: <FinanceDashboard />,
      permission_needed: true,
      exclude_roles: [7],
      old_url: "/finance/dashboard",
    },
    name: "Finance Dashboard",
    type: "finance",
    old_code: "finance_dashboard",
  },
  area_wise_pending_report: {
    view: {
      codenames: [
        GET_URL.area_wise_pending_report.basename,
        GET_URL.academicyear.basename,
        GET_URL.standard.basename,
      ],
      action_code: "visible_area_wise_pending_report_view",
      is_superuser_action: false,
      name: "Area-wise Pending Report",
      label: "Area-wise Pending Report",
      action: "sub-menu",
      url: "/finance/area-wise-pending-report",
      component: <AreaWisePendingReport />,
      permission_needed: true,
      exclude_roles: [],
    },
    name: "Area-wise Pending Report",
    type: "finance",
  },
  // Asset Management
  combined_asset_dashboard: {
    view: {
      codenames: [GET_URL.assetList.basename, GET_URL.assetGroups.basename, GET_URL.recoverableAssetDashboard.basename],
      action_code: "visible_combined_asset_dashboard_view",
      is_superuser_action: false,
      name: "Asset Dashboard",
      label: "Asset Dashboard",
      action: "sub-menu",
      url: "/finance/combined-asset-dashboard",
      component: <CombinedAssetDashboard />,
      permission_needed: true,
      exclude_roles: [7], // Exclude parents
    },
    name: "Combined Asset Dashboard",
    type: "finance",
  },
  asset_groups: {
    view: {
      codenames: [GET_URL.assetGroups.basename],
      action_code: "visible_asset_groups_view",
      is_superuser_action: false,
      name: "Asset Groups",
      label: "Asset Groups",
      action: "sub-menu",
      associated_urls: ["/finance/asset-groups/add"],
      url: "/finance/asset-groups",
      component: <AssetGroupList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.assetGroups.basename, POST_URL.assetGroups.basename],
      action_code: "visible_asset_groups_add",
      is_superuser_action: false,
      name: "Add Asset Group",
      label: "Add Asset Group",
      action: "action-url",
      url: "/finance/asset-groups/add",
      component: <AddAssetGroup />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.assetGroups.basename],
      action_code: "visible_asset_groups_change",
      is_superuser_action: false,
      name: "Update Asset Group",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.assetGroups.basename],
      action_code: "visible_asset_groups_delete",
      is_superuser_action: false,
      name: "Delete Asset Group",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Asset Groups",
    type: "finance",
  },
  assets: {
    view: {
      codenames: [GET_URL.assetList.basename, GET_URL.assetGroups.basename],
      action_code: "visible_assets_view",
      is_superuser_action: false,
      name: "Fixed Assets",
      label: "Fixed Assets",
      action: "sub-menu",
      associated_urls: ["/finance/assets/add", "/finance/assets/edit"],
      url: "/finance/assets",
      component: <AssetList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.assetGroups.basename, POST_URL.assetList.basename],
      action_code: "visible_assets_add",
      is_superuser_action: false,
      name: "Add Asset",
      label: "Add Asset",
      action: "action-url",
      url: "/finance/assets/add",
      component: <AddAsset />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.assetList.basename],
      action_code: "visible_assets_change",
      is_superuser_action: false,
      name: "Update Asset",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.assetList.basename],
      action_code: "visible_assets_delete",
      is_superuser_action: false,
      name: "Delete Asset",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fixed Assets",
    type: "finance",
  },
  depreciation: {
    view: {
      codenames: [GET_URL.depreciation.basename, GET_URL.financialyear.basename],
      action_code: "visible_depreciation_view",
      is_superuser_action: false,
      name: "Run Depreciation",
      label: "Run Depreciation",
      action: "sub-menu",
      url: "/finance/depreciation",
      component: <DepreciationRun />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.depreciation.basename],
      action_code: "visible_depreciation_add",
      is_superuser_action: false,
      name: "Generate Depreciation",
      label: "Generate",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Depreciation",
    type: "finance",
  },
  fixed_asset_register: {
    view: {
      codenames: [GET_URL.fixedAssetRegister.basename, GET_URL.financialyear.basename],
      action_code: "visible_fixed_asset_register_view",
      is_superuser_action: false,
      name: "Fixed Asset Register",
      label: "Fixed Asset Register",
      action: "sub-menu",
      url: "/finance/fixed-asset-register",
      component: <FixedAssetRegister />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fixed Asset Register",
    type: "finance",
  },
  fixed_asset_cost_register: {
    view: {
      codenames: [GET_URL.fixedAssetCostRegister.basename, GET_URL.financialyear.basename],
      action_code: "visible_fixed_asset_cost_register_view",
      is_superuser_action: false,
      name: "Fixed Asset Cost Register",
      label: "Cost Register",
      action: "sub-menu",
      url: "/finance/fixed-asset-cost-register",
      component: <FixedAssetCostRegister />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fixed Asset Cost Register",
    type: "finance",
  },
  asset_reports: {
    view: {
      codenames: [GET_URL.fixedAssetRegister.basename, GET_URL.assetGroupSummary.basename, GET_URL.depreciationSchedule.basename, GET_URL.fixedAssetCostRegister.basename, GET_URL.assetGroupCostSummary.basename, GET_URL.financialyear.basename],
      action_code: "visible_asset_reports_view",
      is_superuser_action: false,
      name: "Asset Reports",
      label: "Asset Reports",
      action: "sub-menu",
      url: "/finance/asset-reports",
      component: <AssetReports />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Asset Reports",
    type: "finance",
  },
  salary_advance: {
    view: {
      codenames: [GET_URL.salaryAdvance.basename],
      action_code: "visible_salary_advance_view",
      is_superuser_action: false,
      name: "Salary Advance",
      label: "Salary Advance",
      action: "sub-menu",
      associated_urls: ["/finance/salary-advance/add", "/finance/salary-advance/detail", "/finance/salary-advance/edit", "/finance/salary-advance/add-recovery"],
      url: "/finance/salary-advance/view",
      component: <SalaryAdvanceList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.salaryAdvance.basename, POST_URL.salaryAdvance.basename],
      action_code: "visible_salary_advance_add",
      is_superuser_action: false,
      name: "Add Salary Advance",
      label: "Add Salary Advance",
      action: "action-url",
      url: "/finance/salary-advance/add",
      component: <SalaryAdvanceCreate />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.salaryAdvance.basename],
      action_code: "visible_salary_advance_change",
      is_superuser_action: false,
      name: "Edit Salary Advance",
      label: "Edit",
      action: "action-url",
      url: "/finance/salary-advance/edit",
      component: <SalaryAdvanceEdit />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.salaryAdvance.basename],
      action_code: "visible_salary_advance_delete",
      is_superuser_action: false,
      name: "Delete Salary Advance",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Salary Advance",
    type: "finance",
  },
  salary_advance_detail: {
    view: {
      codenames: [GET_URL.salaryAdvance.basename, GET_URL.salaryAdvanceTransaction.basename],
      action_code: "visible_salary_advance_view",
      is_superuser_action: false,
      name: "Salary Advance Detail",
      label: "Salary Advance Detail",
      action: "action-url",
      url: "/finance/salary-advance/detail",
      component: <SalaryAdvanceDetail />,
      permission_needed: false,
    },
    name: "Salary Advance Detail",
    type: "finance",
  },
  salary_advance_recovery: {
    create: {
      codenames: [POST_URL.salaryAdvanceRecovery.basename, GET_URL.salaryAdvance.basename],
      action_code: "visible_salary_advance_recovery_add",
      is_superuser_action: false,
      name: "Add Salary Advance Recovery",
      label: "Add Recovery",
      action: "action-url",
      url: "/finance/salary-advance/add-recovery",
      component: <SalaryAdvanceAddRecovery />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Salary Advance Recovery",
    type: "finance"
  },
  salary_advance_statement: {
    view: {
      codenames: [GET_URL.salaryAdvanceStatement.basename],
      action_code: "visible_salary_advance_statement_view",
      is_superuser_action: false,
      name: "Salary Advance Statement",
      label: "Salary Advance Statement",
      action: "sub-menu",
      url: "/finance/salary-advance-statement/view",
      component: <SalaryAdvanceStatement />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Salary Advance Statement",
    type: "finance",
  },


  balance_sheet: {
    view: {
      codenames: [GET_URL.balanceSheet.basename, GET_URL.financialyear.basename],
      action_code: "visible_balance_sheet_view",
      is_superuser_action: false,
      name: "Balance Sheet",
      label: "Balance Sheet",
      action: "sub-menu",
      url: "/finance/balance-sheet/view",
      component: <BalanceSheet />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Balance Sheet",
    type: "finance",
  },
  finance_audit_log: {
    view: {
      codenames: [GET_URL.financeAuditLog.basename],
      action_code: "visible_finance_audit_log_view",
      is_superuser_action: false,
      name: "Audit Log",
      label: "Audit Log",
      action: "sub-menu",
      url: "/finance/audit-log",
      component: <FinanceAuditLog />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Finance Audit Log",
    type: "finance",
  },
  recoverable_asset_categories: {
    view: {
      codenames: [GET_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_categories_view",
      is_superuser_action: false,
      name: "Asset Categories",
      label: "Asset Categories",
      action: "sub-menu",
      associated_urls: ["/finance/recoverable-assets/categories/add", "/finance/recoverable-assets/categories/edit"],
      url: "/finance/recoverable-assets/categories",
      component: <RecoverableAssetCategoryList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_categories_add",
      is_superuser_action: false,
      name: "Add Category",
      label: "Add",
      action: "action-url",
      associated_urls: ["/finance/recoverable-assets/categories/add"],
      url: "/finance/recoverable-assets/categories/add",
      component: <AddRecoverableAssetCategory />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_categories_change",
      is_superuser_action: false,
      name: "Update Category",
      label: "Edit",
      action: "action-url",
      url: "/finance/recoverable-assets/categories/edit",
      component: <EditRecoverableAssetCategory />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_categories_delete",
      is_superuser_action: false,
      name: "Delete Category",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Asset Categories",
    type: "finance",
  },
  recoverable_asset_register: {
    view: {
      codenames: [GET_URL.recoverableAsset.basename, GET_URL.recoverableAssetCategory.basename, GET_URL.financialyear.basename],
      action_code: "visible_recoverable_asset_register_view",
      is_superuser_action: false,
      name: "Asset Register",
      label: "Asset Register",
      action: "sub-menu",
      associated_urls: ["/finance/recoverable-assets/register/add"],
      url: "/finance/recoverable-assets/register",
      component: <RecoverableAssetRegister />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.recoverableAsset.basename, GET_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_register_add",
      is_superuser_action: false,
      name: "Register Asset",
      label: "Add",
      action: "action-url",
      url: "/finance/recoverable-assets/register/add",
      component: <AddRecoverableAsset />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.recoverableAsset.basename, GET_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_register_change",
      is_superuser_action: false,
      name: "Update Asset",
      label: "Edit",
      action: "action-url",
      url: "/finance/recoverable-assets/register/edit",
      component: <EditRecoverableAsset />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.recoverableAsset.basename],
      action_code: "visible_recoverable_asset_register_delete",
      is_superuser_action: false,
      name: "Delete Asset",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Recoverable Asset Register",
    type: "finance",
  },
  recoverable_asset_transactions: {
    view: {
      codenames: [GET_URL.recoverableAssetTransaction.basename, GET_URL.recoverableAsset.basename, GET_URL.recoverableAssetCategory.basename],
      action_code: "visible_recoverable_asset_transactions_view",
      is_superuser_action: false,
      name: "Asset Transactions",
      label: "Asset Transactions",
      action: "sub-menu",
      url: "/finance/recoverable-assets/transactions",
      component: <RecoverableAssetTransactions />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.recoverableAssetTransaction.basename, GET_URL.recoverableAsset.basename],
      action_code: "visible_recoverable_asset_transactions_add",
      is_superuser_action: false,
      name: "Add Transaction",
      label: "Add",
      action: "action-url",
      associated_urls: ["/finance/recoverable-assets/transactions/add"],
      url: "/finance/recoverable-assets/transactions/add",
      component: <AddRecoverableAssetTransaction />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.recoverableAssetTransaction.basename],
      action_code: "visible_recoverable_asset_transactions_change",
      is_superuser_action: false,
      name: "Update Transaction",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.recoverableAssetTransaction.basename],
      action_code: "visible_recoverable_asset_transactions_delete",
      is_superuser_action: false,
      name: "Delete Transaction",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Recoverable Asset Transactions",
    type: "finance",
  },
  fee_mismatch: {
    view: {
      codenames: [
        GET_URL.feeMismatch.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
      ],
      action_code: "visible_fee_mismatch_view",
      is_superuser_action: false,
      name: "Fee Mismatch",
      label: "Fee Mismatch",
      action: "sub-menu",
      url: "/finance/fee-mismatch/view",
      component: <FeeMismatchList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        POST_URL.feeMismatch.basename,
        GET_URL.feeMismatch.basename,
      ],
      action_code: "visible_fee_mismatch_add",
      is_superuser_action: false,
      name: "Reconcile Fee Mismatch",
      label: "Reconcile",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fee Mismatch Reconciliation",
    type: "finance",
  },
  advance_fee_type: {
    view: {
      codenames: [GET_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_view",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Advance Fee Type",
      action: "sub-menu",
      associated_urls: ["/finance/advance-fee-type/add"],
      url: "/finance/advance-fee-type/list",
      component: <AdvanceFeeTypeList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_add",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Add Advance Fee Type",
      action: "action-url",
      url: "/finance/advance-fee-type/add",
      component: <AdvanceFeeTypeAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_change",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.feeadvancetype.basename],
      action_code: "visible_advance_fee_type_delete",
      is_superuser_action: false,
      name: "Advance Fee Type",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Advance Fee Type",
    type: "finance",
  },
  advance_fee_collection: {
    view: {
      codenames: [GET_URL.feeadvancecollection.basename],
      action_code: "visible_advance_fee_collection_view",
      is_superuser_action: false,
      name: "Advance Fee Collection",
      label: "Advance Fee Collection",
      action: "sub-menu",
      associated_urls: ["/finance/advance-fee-collection/add"],
      url: "/finance/advance-fee-collection",
      component: <AdvanceFeeCollectionList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.feeadvancecollection.basename],
      action_code: "visible_advance_fee_collection_add",
      is_superuser_action: false,
      name: "Advance Fee Collection",
      label: "Collect Advance Fee",
      action: "action-url",
      url: "/finance/advance-fee-collection/add",
      component: <AdvanceFeeCollectionAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Advance Fee Collection",
    type: "finance",
  },
};
export default Actions;
