import React from "react";
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from "Includes/urls";

import CountryView from "Containers/General/CountryView";
import ManageCountries from "Containers/General/ManageCountries";
import StateView from "Containers/General/StateView";
import ManageStates from "Containers/General/ManageStates";
import DistrictView from "Containers/General/DistrictView";
import ManageDistricts from "Containers/General/ManageDistricts";
import CityView from "Containers/General/CityView";
import ManageCities from "Containers/General/ManageCities";
import HolidayCalenderView from "Containers/General/HolidayCalenderView";
import ManageHolidayCalender from "Containers/General/ManageHolidayCalender";
import StudentHolidayCalenderView from "Containers/General/StudentHolidayCalenderView";
import StudentHolidayCalenderAdd from "Containers/General/StudentHolidayCalenderAdd";
import NotificationList from "Containers/General/NotificationList";
import NotificationCreate from "Containers/General/NotificationCreate";
import NotificationTemplateList from "Containers/General/NotificationTemplateList";
import NotificationTemplateCreate from "Containers/General/NotificationTemplateCreate";
import NotificationTemplateIndividual from "Containers/General/NotificationTemplateIndividual";
import NotificationIndividual from "Containers/General/NotificationIndividual";
import TemplateCardList from "Containers/General/TemplateCardList";
import TemplateCardCreate from "Containers/General/TemplateCardCreate";
import StudentHolidayCalenderPlanView from "Containers/General/StudentHolidayCalenderPlanView";
import StudentHolidayCalenderPlanAdd from "Containers/General/StudentHolidayCalenderPlanAdd";
import IdCardGenerator from "Containers/General/IdCardGenerator";
import StaffIdCardGenerator from "Containers/General/StaffIdCardGenerator";

const Actions = {
  manage_countries: {
    view: {
      codenames: [GET_URL.country.basename],
      action_code: "visible_manage_countries_view",
      is_superuser_action: false,
      name: "Countries",
      label: "Countries",
      action: "sub-menu",
      url: "/general/country/view",
      component: <CountryView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/general/country/add"],
    },
    create: {
      codenames: [POST_URL.country.basename],
      action_code: "visible_manage_countries_add",
      is_superuser_action: false,
      name: "Create Countries",
      label: "Add Countries",
      action: "action-url",
      url: "/general/country/add",
      component: <ManageCountries />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.country.basename],
      action_code: "visible_manage_countries_change",
      is_superuser_action: false,
      name: "Update Countries",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.country.basename],
      action_code: "visible_manage_countries_delete",
      is_superuser_action: false,
      name: "Delete Countries",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Countries",
    type: "General",
  },
  manage_states: {
    view: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
      ],
      action_code: "visible_manage_states_view",
      is_superuser_action: false,
      name: "View  States",
      label: " States",
      action: "sub-menu",
      url: "/general/state/view",
      component: <StateView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/general/state/add"],
    },
    create: {
      codenames: [GET_URL.country.basename, POST_URL.state.basename],
      action_code: "visible_manage_states_add",
      is_superuser_action: false,
      name: "Create States",
      label: "Add States",
      action: "action-url",
      url: "/general/state/add",
      component: <ManageStates />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [GET_URL.getstatesforcountry.basename, PUT_URL.state.basename],
      action_code: "visible_manage_states_change",
      is_superuser_action: false,
      name: "Update States",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [GET_URL.getstatesforcountry.basename, DEL_URL.state.basename],
      action_code: "visible_manage_states_delete",
      is_superuser_action: false,
      name: "Delete States",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "States",
    type: "General",
  },
  manage_districts: {
    view: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
      ],
      action_code: "visible_manage_districts_view",
      is_superuser_action: false,
      name: "View Districts",
      label: "Districts",
      action: "sub-menu",
      url: "/general/district/view",
      component: <DistrictView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/general/district/add"],
    },
    create: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        POST_URL.district.basename,
      ],
      action_code: "visible_manage_districts_add",
      is_superuser_action: false,
      name: "Create Districts",
      label: "Add Districts",
      action: "action-url",
      url: "/general/district/add",
      component: <ManageDistricts />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        PUT_URL.district.basename,
      ],
      action_code: "visible_manage_districts_change",
      is_superuser_action: false,
      name: "Update Districts",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        DEL_URL.district.basename,
      ],
      action_code: "visible_manage_districts_delete",
      is_superuser_action: false,
      name: "Delete Districts",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Districts",
    type: "General",
  },
  manage_cities: {
    view: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
      ],
      action_code: "visible_manage_cities_view",
      is_superuser_action: false,
      name: "View Cities",
      label: "Cities",
      action: "sub-menu",
      url: "/general/city/view",
      component: <CityView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/general/city/add"],
    },
    create: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        POST_URL.city.basename,
      ],
      action_code: "visible_manage_cities_add",
      is_superuser_action: false,
      name: "Create Cities",
      label: "Add Cities",
      action: "action-url",
      url: "/general/city/add",
      component: <ManageCities />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        PUT_URL.city.basename,
      ],
      action_code: "visible_manage_cities_change",
      is_superuser_action: false,
      name: "Update Cities",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        DEL_URL.city.basename,
      ],
      action_code: "visible_manage_cities_delete",
      is_superuser_action: false,
      name: "Delete Cities",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Cities",
    type: "General",
  },
  view_holiday_calender: {
    view: {
      codenames: [
        GET_URL.holidaycalender.basename,
        GET_URL.financialyear.basename,
      ],
      action_code: "visible_view_holiday_calender_view",
      is_superuser_action: false,
      name: "Staff Holiday Calendar",
      label: "Staff Holiday Calendar",
      action: "sub-menu",
      url: "/general/holiday-calender/view",
      component: <HolidayCalenderView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/general/holiday-calender/add"],
    },
    create: {
      codenames: [
        GET_URL.financialyear.basename,
        POST_URL.holidaycalender.basename,
      ],
      action_code: "visible_view_holiday_calender_add",
      is_superuser_action: false,
      name: "Create Holiday calendar",
      label: "Holiday calendar",
      action: "action-url",
      url: "/general/holiday-calender/add",
      component: <ManageHolidayCalender />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.financialyear.basename,
        PUT_URL.holidaycalender.basename,
      ],
      action_code: "visible_view_holiday_calender_change",
      is_superuser_action: false,
      name: "Update Holiday Calender",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.financialyear.basename,
        DEL_URL.holidaycalender.basename,
      ],
      action_code: "visible_view_holiday_calender_delete",
      is_superuser_action: false,
      name: "Delete Holiday Calendar",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Holiday Calendar",
    type: "General",
  },
  student_holiday_calender_plan: {
    view: {
      codenames: [
        GET_URL.holidaycalenderforstudent.basename,
        GET_URL.getacademicyear.basename,
      ],
      action_code: "visible_student_holiday_calender_plan_view",
      is_superuser_action: false,
      name: "Student Holiday Calendar Plan",
      label: "Student Holiday Calendar Plan",
      action: "sub-menu",
      url: "/general/student/calender/plan/view",
      component: <StudentHolidayCalenderPlanView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/general/student/calender/add"],
    },
    create: {
      codenames: [
        GET_URL.financialyear.basename,
        POST_URL.holidaycalenderforstudent.basename,
      ],
      action_code: "visible_student_holiday_calender_plan_add",
      is_superuser_action: false,
      name: "Create Holiday calendar",
      label: "Add Calender Plan",
      action: "action-url",
      url: "/general/student/calender/plan/add",
      component: <StudentHolidayCalenderPlanAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.holidaycalenderforstudent.basename,
        PUT_URL.holidaycalenderforstudent.basename,
      ],
      action_code: "visible_student_holiday_calender_plan_change",
      is_superuser_action: false,
      name: "Update Holiday Calender",
      label: "Edit",
      url: "/general/student/calender/plan/edit",
      action: "action-url",
      permission_needed: true,
      component: <StudentHolidayCalenderPlanAdd />,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.financialyear.basename,
        DEL_URL.holidaycalenderforstudent.basename,
      ],
      action_code: "visible_student_holiday_calender_plan_delete",
      is_superuser_action: false,
      name: "Delete Holiday Calendar",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Student Holiday Calendar Plan",
    type: "General",
  },
  student_holiday_calender: {
    view: {
      codenames: [
        GET_URL.holidaycalenderforstudent.basename,
        GET_URL.getacademicyear.basename,
      ],
      action_code: "visible_student_holiday_calender_view",
      is_superuser_action: false,
      name: "Student Holiday Calendar",
      label: "Student Holiday Calendar",
      action: "sub-menu",
      url: "/general/student/calender/view",
      component: <StudentHolidayCalenderView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: [
        "/general/student/calender/add",
        "/general/student/calender/plan/add",
      ],
    },
    create: {
      codenames: [
        GET_URL.financialyear.basename,
        POST_URL.holidaycalenderforstudent.basename,
      ],
      action_code: "visible_student_holiday_calender_add",
      is_superuser_action: false,
      name: "Create Holiday calendar",
      label: "Calendar For Student",
      action: "action-url",
      url: "/general/student/calender/add",
      component: <StudentHolidayCalenderAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.holidaycalenderforstudent.basename,
        PUT_URL.holidaycalenderforstudent.basename,
      ],
      action_code: "visible_student_holiday_calender_change",
      is_superuser_action: false,
      name: "Update Holiday Calender",
      url: "/general/student/calender/update",
      component: <StudentHolidayCalenderAdd />,
      label: "Edit",
      action: "action-url",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [
        GET_URL.financialyear.basename,
        DEL_URL.holidaycalenderforstudent.basename,
      ],
      action_code: "visible_student_holiday_calender_delete",
      is_superuser_action: false,
      name: "Delete Holiday Calendar",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Student Holiday Calendar",
    type: "General",
  },
  notification_template: {
    view: {
      codenames: [
        GET_URL.notificationtemplate.basename,
        DEL_URL.notificationtemplate.basename,
      ],
      action_code: "visible_notification_template_view",
      is_superuser_action: false,
      name: "Notification Template List",
      label: "Notification Template List",
      action: "sub-menu",
      url: "/notification/template/list",
      component: <NotificationTemplateList />,
      associated_urls: [
        "/notification/template/add",
        "/notification/template/edit",
        "/notification/template/detail/view",
      ],
      permission_needed: true,
      exclude_roles: [7],
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    create: {
      codenames: [
        GET_URL.language.basename,
        GET_URL.medium.basename,
        GET_URL.notificationtemplate.basename,
        POST_URL.notificationtemplate.basename,
      ],
      action_code: "visible_notification_template_add",
      is_superuser_action: false,
      name: "Notification Template",
      label: "Notification Template",
      action: "action-url",
      url: "/notification/template/add",
      component: <NotificationTemplateCreate />,
      permission_needed: true,
      exclude_roles: [7],
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    update: {
      codenames: [
        GET_URL.language.basename,
        GET_URL.medium.basename,
        GET_URL.notificationtemplate.basename,
        POST_URL.notificationtemplate.basename,
      ],
      action_code: "visible_notification_template_change",
      is_superuser_action: false,
      name: "Update Notification Template",
      label: "Update Notification Template",
      action: "action-url",
      url: "/notification/template/edit",
      component: <NotificationTemplateCreate />,
      permission_needed: true,
      exclude_roles: [7],
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    delete: {
      codenames: [],
      action_code: "visible_notification_template_delete",
      is_superuser_action: false,
      name: "Delete Notification Template",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Notification Template",
    type: "General",
  },
  notification_template_individual: {
    view: {
      codenames: [GET_URL.notificationtemplate.basename],
      action_code: "visible_notification_template_individual_view",
      is_superuser_action: false,
      name: "Notification Template View",
      label: "Notification Template View",
      action: "action",
      url: "/notification/template/detail/view",
      component: <NotificationTemplateIndividual />,
      permission_needed: true,
      exclude_roles: [7],
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    name: "Notification Template Individual",
    type: "General",
  },
  bulk_notification: {
    view: {
      codenames: [
        GET_URL.bulknotification.basename,
        DEL_URL.bulknotification.basename,
      ],
      action_code: "visible_bulk_notification_view",
      is_superuser_action: false,
      name: "Bulk notification list",
      label: "Bulk notification list",
      action: "sub-menu",
      url: "/bulknotification/list",
      component: <NotificationList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/bulknotification/create", "/bulknotification/edit"],
    },
    create: {
      codenames: [
        GET_URL.language.basename,
        GET_URL.medium.basename,
        GET_URL.bulknotification.basename,
        GET_URL.groups.basename,
        GET_URL.getstafffullname.basename,
        GET_URL.getenrolledstudents.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.getstandardandsection.basename,
        POST_URL.bulknotification.basename,
        GET_URL.getcustombulknotification.basename,
      ],
      action_code: "visible_bulk_notification_add",
      is_superuser_action: false,
      name: "Bulk notification create",
      label: "Bulk notification create",
      action: "action-url",
      url: "/bulknotification/create",
      component: <NotificationCreate />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.language.basename,
        GET_URL.medium.basename,
        GET_URL.bulknotification.basename,
        GET_URL.groups.basename,
        GET_URL.getstafffullname.basename,
        GET_URL.getenrolledstudents.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.getstandardandsection.basename,
        POST_URL.bulknotification.basename,
      ],
      action_code: "visible_bulk_notification_change",
      is_superuser_action: false,
      name: "Bulk notification edit",
      label: "Bulk notification edit",
      action: "action-url",
      url: "/bulknotification/edit",
      component: <NotificationCreate />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [],
      action_code: "visible_bulk_notification_delete",
      is_superuser_action: false,
      name: "Delete bulk notification",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Bulk Notification",
    type: "General",
  },
  bulk_notification_individual: {
    view: {
      codenames: [GET_URL.bulknotification.basename],
      action_code: "visible_bulk_notification_individual_view",
      is_superuser_action: false,
      name: "Bulk Notification View",
      label: "Bulk NotificationView",
      action: "action",
      url: "/bulknotification/detail/view",
      component: <NotificationIndividual />,
      permission_needed: true,
      exclude_roles: [7],
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    name: "Bulk Notification Individual",
    type: "General",
  },
  template_card: {
    view: {
      codenames: [],
      action_code: "visible_template_card_view",
      is_superuser_action: false,
      name: "Template List",
      label: "Template List",
      action: "sub-menu",
      url: "/general/templatecard/list",
      component: <TemplateCardList />,
      permission_needed: true,
      exclude_roles: [7],
      hide_branch_dropdown: true,
      hide_board_dropdown: true,
    },
    create: {
      codenames: [],
      action_code: "visible_template_card_add",
      is_superuser_action: false,
      name: "Template Create",
      label: "Template Create",
      action: "action-url",
      url: "/general/templatecard/create",
      component: <TemplateCardCreate />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Template Card",
    type: "General",
  },
  id_card_list: {
    view: {
      codenames: [
        GET_URL.getstandardandsection.basename,
        POST_URL.generateidcard.basename,
      ],
      action_code: "visible_id_card_list_view",
      is_superuser_action: false,
      name: "ID Card List",
      label: "ID Card List",
      action: "sub-menu",
      url: "/general/generate/idcard/list",
      old_url: "/general/idcard/list",
      component: <IdCardGenerator />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Id Card",
    type: "General",
  },
  staff_id_card_list: {
    view: {
      codenames: [
        GET_URL.longprocessingapiresult.basename,
        GET_URL.grouptypes.basename,
        GET_URL.staff.basename,
        POST_URL.generateidcardforstaff.basename,
      ],
      action_code: "visible_staff_id_card_list_view",
      is_superuser_action: false,
      name: "Staff ID Card List",
      label: "Staff ID Card List",
      action: "sub-menu",
      url: "/general/generate/staff/idcard/list",
      component: <StaffIdCardGenerator />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Id Card",
    type: "General",
  },
};

export default Actions;
