import React from 'react';
import { GET_URL, POST_URL, DEL_URL, PUT_URL } from 'Includes/urls';


import ListHostelBuildings from 'Containers/HostelManagement/ListHostelBuildings';
import AddHostelBuilding from 'Containers/HostelManagement/AddHostelBuilding';
import ViewIndividualHostel from 'Containers/HostelManagement/ViewIndividualHostel';
import ViewAssetTypes from 'Containers/HostelManagement/ViewAssetTypes';
import AddAssetTypes from 'Containers/HostelManagement/AddAssetTypes';
import ViewRoomStrength from 'Containers/HostelManagement/ViewRoomStrength';
import AddRoomStrength from 'Containers/HostelManagement/AddRoomStrength';
import ViewIndividualRoomStrength from 'Containers/HostelManagement/ViewIndividualRoomStrength';
import RoomAllocationList from 'Containers/HostelManagement/RoomAllocationList';
import ViewRoomAllocation from 'Containers/HostelManagement/ViewRoomAllocation';
import ListVisitors from 'Containers/HostelManagement/ListVisitors';
import AddVisitor from 'Containers/HostelManagement/AddVisitor';
import ListCheckInCheckout from 'Containers/HostelManagement/ListCheckInCheckout';
import IndividualCheckInOutHistory from 'Containers/HostelManagement/IndividualCheckInOutHistory';
import IndividualVisitorView from 'Containers/HostelManagement/IndividualVisitorView';
import HostelViewExpensesType from 'Containers/HostelManagement/HostelViewExpensesType';
import HostelAddExpensesType from 'Containers/HostelManagement/HostelAddExpensesType';
import HostelViewExpensePlan from 'Containers/HostelManagement/HostelViewExpensePlan';
import HostelAddExpensePlan from 'Containers/HostelManagement/HostelAddExpensePlan';
import HostelViewExpenses from 'Containers/HostelManagement/HostelViewExpenses';
import HostelCreateExpenses from 'Containers/HostelManagement/HostelCreateExpenses';
import HostelViewExpenseIndividual from 'Containers/HostelManagement/HostelViewExpenseIndividual';
import HostelStudentTransactionList from 'Containers/HostelManagement/HostelStudentTransactionList';
import HostelAddTransactionStudent from 'Containers/HostelManagement/HostelAddTransactionStudent';
import HostelStudentTransactionHistory from 'Containers/HostelManagement/HostelStudentTransactionHistory';
import HostelBuidlingSummary from 'Containers/HostelManagement/HostelBuidlingSummary';
import HostelStudentRoomHistory from 'Containers/HostelManagement/HostelStudentRoomHistory';

const Actions = {
    hostel: {
        view: {
            codenames: [GET_URL.buildingdata.basename, DEL_URL.buildingdata.basename],
            action_code: 'visible_hostel_view',
            is_superuser_action: false,
            name: 'Hostel Building List',
            label: 'Hostel Building List',
            action: 'sub-menu',
            url: '/hostel/building/list',
            component: <ListHostelBuildings />,
            associated_urls: ['/hostel/building/add', '/hostel/building/detail/view'],
            permission_needed: true,
            exclude_roles: [7],

        },
        create: {
            codenames: [POST_URL.buildingdata.basename],
            action_code: 'visible_hostel_add',
            is_superuser_action: false,
            name: 'Create Hostel Building',
            label: 'Hostel Building',
            action: 'action-url',
            url: '/hostel/building/add',
            component: <AddHostelBuilding />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [POST_URL.buildingdata.basename],
            action_code: 'visible_hostel_change',
            is_superuser_action: false,
            name: 'Update Hostel Building',
            label: 'Update Hostel Building',
            action: 'action-url',
            url: '/hostel/building/edit',
            component: <AddHostelBuilding />,
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.buildingdata.basename],
            action_code: 'visible_hostel_delete',
            is_superuser_action: false,
            name: 'Delete Hostel Building',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Building',
        type: 'hostel',
    },
    hostel_individual: {
        view: {
            codenames: [GET_URL.buildingdata.basename],
            action_code: 'visible_hostel_individual_view',
            is_superuser_action: false,
            name: 'Hostel Building',
            label: 'Hostel Building',
            action: 'action',
            url: '/hostel/building/detail/view',
            component: <ViewIndividualHostel />,
            permission_needed: true,
            exclude_roles: [7],

        },
        name: 'Hostel Building Individual View',
        type: 'hostel',
    },
    hostel_asset: {
        view: {
            codenames: [GET_URL.asset.basename, PUT_URL.asset.basename, DEL_URL.asset.basename],
            action_code: 'visible_hostel_asset_view',
            is_superuser_action: false,
            name: 'Asset Type',
            label: 'Asset Type',
            action: 'sub-menu',
            url: '/hostel/assettype/view',
            component: <ViewAssetTypes />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/assettype/add'],


        },
        create: {
            codenames: [POST_URL.asset.basename],
            action_code: 'visible_hostel_asset_add',
            is_superuser_action: false,
            name: 'Create Asset Type',
            label: 'Add Asset Type',
            action: 'action-url',
            url: '/hostel/assettype/add',
            component: <AddAssetTypes />,
            permission_needed: true,
            exclude_roles: [7],

        },
        update: {
            codenames: [PUT_URL.asset.basename],
            action_code: 'visible_hostel_asset_change',
            is_superuser_action: false,
            name: 'Update  Asset Type',
            label: 'Edit',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.asset.basename],
            action_code: 'visible_hostel_asset_delete',
            is_superuser_action: false,
            name: 'Delete  Asset Type',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Asset Types',
        type: 'hostel',
    },
    room_strength: {
        view: {
            codenames: [GET_URL.asset.basename, GET_URL.buildingdata.basename, GET_URL.room.basename],
            action_code: 'visible_room_strength_view',
            is_superuser_action: false,
            name: 'Assigned Room',
            label: 'Assigned Room',
            action: 'sub-menu',
            url: '/hostel/roomstrength/list',
            component: <ViewRoomStrength />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/roomstrength/add', '/hostel/roomstrength/detail/view'],

        },
        create: {
            codenames: [GET_URL.asset.basename, POST_URL.room.basename],
            action_code: 'visible_room_strength_add',
            is_superuser_action: false,
            name: 'Assign Room',
            label: 'Assign Room',
            action: 'action-url',
            url: '/hostel/roomstrength/add',
            component: <AddRoomStrength />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [GET_URL.asset.basename, POST_URL.room.basename],
            action_code: 'visible_room_strength_change',
            is_superuser_action: false,
            name: 'Update Assigned Room ',
            label: 'Update Assigned Room ',
            action: 'action-url',
            url: '/hostel/roomstrength/edit',
            component: <AddRoomStrength />,
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.room.basename],
            action_code: 'visible_room_strength_delete',
            is_superuser_action: false,
            name: 'Delete Room Strength',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Room',
        type: 'hostel',
    },
    room_strength_individual: {
        view: {
            codenames: [GET_URL.room.basename],
            action_code: 'visible_room_strength_individual_view',
            is_superuser_action: false,
            name: 'Room Strength',
            label: 'Room Strength',
            action: 'action',
            url: '/hostel/roomstrength/detail/view',
            component: <ViewIndividualRoomStrength />,
            permission_needed: true,
            exclude_roles: [7],

        },
        name: 'Hostel Room Individual View',
        type: 'hostel',
    },
    room_allocation_list: {
        view: {
            codenames: [GET_URL.roomallocation.basename, GET_URL.buildingdata.basename],
            action_code: 'visible_room_allocation_list_view',
            is_superuser_action: false,
            name: 'Room Allocation',
            label: 'Room Allocation',
            action: 'sub-menu',
            url: '/hostel/roomallocation/list',
            component: <RoomAllocationList />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/roomallocation/view'],
        },
        name: 'Room Allocation List',
        type: 'hostel',
    },
    room_allocation: {
        view: {
            codenames: [GET_URL.roomallocation.basename,],
            action_code: 'visible_room_allocation_view',
            is_superuser_action: false,
            name: 'Room Allocation',
            label: 'Room Allocation',
            action: 'action',
            url: '/hostel/roomallocation/view',
            component: <ViewRoomAllocation />,
            permission_needed: true,
            exclude_roles: [7],

        },
        create: {
            codenames: [POST_URL.roomallocation.basename, GET_URL.getacademicyear.basename, GET_URL.usercheckincheckout.basename],
            action_code: 'visible_room_allocation_add',
            is_superuser_action: false,
            name: 'Assign Room Allocation',
            label: 'Assign Room Allocation',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [POST_URL.roomallocation.basename],
            action_code: 'visible_room_allocation_change',
            is_superuser_action: false,
            name: 'Update Assigned Room ',
            label: 'Update Assigned Room ',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Room Allocation',
        type: 'hostel',
    },
    hostel_summary: {
        view: {
            codenames: [GET_URL.hostelsummary.basename,GET_URL.buildingdata.basename],
            action_code: 'visible_hostel_summary_view',
            is_superuser_action: false,
            name: 'Hostel Summary',
            label: 'Hostel Summary',
            action: 'sub-menu',
            url: '/hostel/summary/',
            component: <HostelBuidlingSummary />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Summary',
        type: 'hostel',
    },
    hostel_visitor: {
        view: {
            codenames: [GET_URL.visitor.basename],
            action_code: 'visible_hostel_visitor_view',
            is_superuser_action: false,
            name: 'Visitors',
            label: 'Hostel Visitors',
            action: 'sub-menu',
            url: '/hostel/visitors/list',
            component: <ListVisitors />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/visitors/add', '/hostel/hostelvisitor/detail/view'],
        },
        create: {
            codenames: [POST_URL.visitor.basename, GET_URL.reason.basename, POST_URL.reason.basename],
            action_code: 'visible_hostel_visitor_add',
            is_superuser_action: false,
            name: 'Add Visitor',
            label: 'Visitor',
            action: 'action-url',
            url: '/hostel/visitors/add',
            component: <AddVisitor />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [GET_URL.visitor.basename, POST_URL.visitor.basename],
            action_code: 'visible_hostel_visitor_change',
            is_superuser_action: false,
            name: 'Update Visitor',
            label: 'Update Visitor',
            action: 'action-url',
            url: '/hostel/visitors/edit',
            component: <AddVisitor />,
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.visitor.basename],
            action_code: 'visible_hostel_visitor_delete',
            is_superuser_action: false,
            name: 'Delete Room Strength',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Manage Visitors',
        type: 'hostel',
    },
    hostel_visitor_individual: {
        view: {
            codenames: [GET_URL.visitor.basename],
            action_code: 'visible_hostel_visitor_individual_view',
            is_superuser_action: false,
            name: 'Hostel Visitor',
            label: 'Hostel Visitor',
            action: 'action',
            url: '/hostel/hostelvisitor/detail/view',
            component: <IndividualVisitorView />,
            permission_needed: true,
            exclude_roles: [7],

        },
        name: 'Hostel Visitor Individual',
        type: 'hostel',
    },
    checkIn_checkOut_List: {
        view: {
            codenames: [GET_URL.buildingdata.basename, GET_URL.usercheckincheckout.basename],
            action_code: 'visible_checkIn_checkOut_List_view',
            is_superuser_action: false,
            name: 'CheckIn Checkout',
            label: 'CheckIn Checkout List',
            action: 'sub-menu',
            url: '/hostel/checkinout/list',
            component: <ListCheckInCheckout />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/checkinout/detail/view'],
        },
        create: {
            codenames: [GET_URL.buildingdata.basename, GET_URL.usercheckincheckout.basename, POST_URL.usercheckincheckout.basename],
            action_code: 'visible_checkIn_checkOut_List_add',
            is_superuser_action: false,
            name: 'Create Check In-Out',
            label: 'Create Check In-Out',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.usercheckincheckout.basename],
            action_code: 'visible_checkIn_checkOut_List_delete',
            is_superuser_action: false,
            name: 'Delete Check In-out',
            label: 'Delete Check In-out',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'CheckIn Checkout List',
        type: 'hostel',
    },
    checkIn_checkOut_Individual: {
        view: {
            codenames: [GET_URL.usercheckincheckout.basename],
            action_code: 'visible_checkIn_checkOut_Individual_view',
            is_superuser_action: false,
            name: 'CheckIn Checkout',
            label: 'CheckIn Checkout',
            action: 'action',
            url: '/hostel/checkinout/detail/view',
            component: <IndividualCheckInOutHistory />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Check In-Out History ',
        type: 'hostel',
    },
    hostel_expenses_type: {
        view: {
            codenames: [GET_URL.expensetype.basename],
            action_code: 'visible_hostel_expenses_type_view',
            is_superuser_action: false,
            name: 'Hostel Expenses Type',
            label: 'Hostel Expenses Type',
            action: 'sub-menu',
            url: '/hostel/expenses/type/view',
            component: <HostelViewExpensesType />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/expenses/type/add'],

        },
        create: {
            codenames: [POST_URL.expensetype.basename],
            action_code: 'visible_hostel_expenses_type_add',
            is_superuser_action: false,
            name: 'Create Hostel Expenses Type',
            label: 'Add Hostel Expenses Type',
            action: 'action-url',
            url: '/hostel/expenses/type/add',
            component: <HostelAddExpensesType />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.expensetype.basename],
            action_code: 'visible_hostel_expenses_type_change',
            is_superuser_action: false,
            name: 'Update Expenses Type',
            label: 'Update Expenses Type',
            action: 'action-url',
            url: '/hostel/expenses/type/edit',
            component: <HostelViewExpensesType />,
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.expensetype.basename],
            action_code: 'visible_hostel_expenses_type_delete',
            is_superuser_action: false,
            name: 'Delete Expenses Type',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Expenses Type',
        type: 'hostel',
    },
    hostel_expenses_plan: {
        view: {
            codenames: [GET_URL.expenseplan.basename, GET_URL.getfinancialyear.basename],
            action_code: 'visible_hostel_expenses_plan_view',
            is_superuser_action: false,
            name: 'Hostel Expenses Plan',
            label: 'Hostel Expenses Plan',
            action: 'sub-menu',
            url: '/hostel/expenses/plan/view',
            component: <HostelViewExpensePlan />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/expenses/plan/add'],
        },
        create: {
            codenames: [POST_URL.expenseplan.basename],
            action_code: 'visible_hostel_expenses_plan_add',
            is_superuser_action: false,
            name: 'Create Hostel Expenses Plan',
            label: 'Add Hostel Expenses Plan',
            action: 'action-url',
            url: '/hostel/expenses/plan/add',
            component: <HostelAddExpensePlan />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.expenseplan.basename],
            action_code: 'visible_hostel_expenses_plan_change',
            is_superuser_action: false,
            name: 'Update Expenses Plan',
            label: 'Update Expenses Plan',
            action: 'action-url',
            url: '/hostel/expenses/plan/edit',
            component: <HostelViewExpensePlan />,
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.expenseplan.basename],
            action_code: 'visible_hostel_expenses_plan_delete',
            is_superuser_action: false,
            name: 'Delete Expenses Plan',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Expenses Plan',
        type: 'hostel',
    },
    hostel_expenses_create: {
        view: {
            codenames: [GET_URL.expense.basename, GET_URL.expenseplan.basename, GET_URL.financialyear.basename],
            action_code: 'visible_hostel_expenses_create_view',
            is_superuser_action: false,
            name: 'Hostel Expenses',
            label: 'Hostel Expenses',
            action: 'sub-menu',
            url: '/hostel/expenses/view',
            component: <HostelViewExpenses />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/expenses/add', '/hostel/expenses/edit', '/hostel/expenses/detail/view'],

        },
        create: {
            codenames: [POST_URL.expense.basename, GET_URL.expenseplan.basename],
            action_code: 'visible_hostel_expenses_create_add',
            is_superuser_action: false,
            name: 'Create Hostel Expenses',
            label: 'Hostel Expenses',
            action: 'action-url',
            url: '/hostel/expenses/add',
            component: <HostelCreateExpenses />,
            permission_needed: true,
            exclude_roles: [7],
        },
        update: {
            codenames: [PUT_URL.expense.basename, GET_URL.expenseplan.basename],
            action_code: 'visible_hostel_expenses_create_change',
            is_superuser_action: false,
            name: 'Update Hostel Expenses',
            label: 'Update Hostel Expenses',
            action: 'action-url',
            url: '/hostel/expenses/edit',
            component: <HostelCreateExpenses />,
            permission_needed: true,
            exclude_roles: [7],

        },
        delete: {
            codenames: [DEL_URL.expense.basename],
            action_code: 'visible_hostel_expenses_create_delete',
            is_superuser_action: false,
            name: 'Delete Expenses',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Expenses Create',
        type: 'hostel',
    },
    hostel_expenses_individual: {
        view: {
            codenames: [GET_URL.expense.basename],
            action_code: 'visible_hostel_expenses_create_view',
            is_superuser_action: false,
            name: 'Hostel Expenses',
            label: 'Hostel Expenses',
            action: 'action',
            url: '/hostel/expenses/detail/view',
            component: <HostelViewExpenseIndividual />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Expenses Individual View',
        type: 'hostel',
    },
    hostel_student_transaction_list: {
        view: {
            codenames: [GET_URL.buildingdata.basename, GET_URL.studenttransactionlist.basename],
            action_code: 'visible_hostel_student_transaction_list_view',
            is_superuser_action: false,
            name: 'Hostel Students List',
            label: 'Hostel Students List',
            action: 'sub-menu',
            old_url: '/hostel/student/transaction/list',
            url: '/hostel/student/list',
            component: <HostelStudentTransactionList />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/hostel/student/add/transaction','/hostel/student/detail/view','/hostel/student/room/history'],
        },
        create: {
            codenames: [
                GET_URL.studenttransactionlist.basename, GET_URL.buildingdata.basename,
                GET_URL.getstandardandsection.basename, POST_URL.withdraw.basename, POST_URL.deposit.basename],
            action_code: 'visible_hostel_student_transaction_list_add',
            is_superuser_action: false,
            name: 'Hostel Add Transaction',
            label: 'Add Transaction',
            action: 'action-url',
            url: '/hostel/student/add/transaction',
            component: <HostelAddTransactionStudent />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Student List',
        type: 'hostel',
    },
    hostel_student_transaction_view: {
        view: {
            codenames: [GET_URL.studenttransactionlist.basename],
            action_code: 'visible_hostel_student_transaction_view_view',
            is_superuser_action: false,
            name: 'Hostel Student Detail',
            label: 'Hostel Student Detail',
            action: 'action',
            url: '/hostel/student/detail/view',
            component: <HostelStudentTransactionHistory />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Student Transaction Individual View',
        type: 'hostel',
    },
    hostel_student_room_history: {
        view: { 
            codenames: [GET_URL.student_hostel_details.basename],
            action_code: 'visible_hostel_student_room_history_view',
            is_superuser_action: false,
            name: 'Hostel Student Room History',
            label: 'Hostel Student Room History',
            action: 'action-url',
            url: '/hostel/student/room/history',
            component: <HostelStudentRoomHistory />,
            permission_needed: true, 
            exclude_roles: [7],
        },
        name: 'Hostel Student Room History',
        type: 'hostel',
    },
    hostel_withdraw: {
        create: {
            codenames: [POST_URL.returnback.basename],
            action_code: 'visible_hostel_withdraw_add',
            is_superuser_action: false,
            name: 'Hostel Student Withdraw',
            label: 'Hostel Student Withdraw',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Hostel Student Withdraw',
        type: 'hostel',
    },
}
export default Actions;