import React from "react";
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from "Includes/urls";

import StaffsList from "Containers/HrManagement/StaffsList";
import ShiftsView from "Containers/HrManagement/ShiftsView";
import NewAddShift from "Containers/HrManagement/NewAddShift";
import HrAssignShiftView from "Containers/HrManagement/HrAssignShiftView";
import HrAssignShift from "Containers/HrManagement/HrAssignShift";
import HrAssignCustomShift from "Containers/HrManagement/HrAssignCustomShift";
import HrAssignCustomShiftView from "Containers/HrManagement/HrAssignCustomShiftView";
import HrStaffAttendanceView from "Containers/HrManagement/HrStaffAttendanceView";
import HrSubjectView from "Containers/HrManagement/HrSubjectView";
import HrStaffAttendance from "Containers/HrManagement/HrStaffAttendance";
import HrSubjectAddModify from "Containers/HrManagement/HrSubjectAddModify";
import HrSubjectStandardSectionAddModify from "Containers/HrManagement/HrSubjectStandardSectionAddModify";
import HrStaffForm from "Containers/HrManagement/components/HrStaffForm";
import StaffView from "Containers/HrManagement/StaffView";
import IndividualShiftView from "Containers/HrManagement/components/IndividualShiftView";
import StaffMapWithStandardsList from "Containers/BasicDetails/StaffMapWithStandardsList";
import StaffMapWithStandards from "Containers/BasicDetails/StaffMapWithStandards";
import HrStaffOrganizationChart from "Containers/HrManagement/HrStaffOrganizationChart";
import StaffUserNameList from "Containers/HrManagement/StaffUserNameList";
import StaffUserNameAdd from "Containers/HrManagement/StaffUserNameAdd";
import StaffAttendnaceReport from "Containers/HrManagement/StaffAttendanceReport";
import StaffSalaryList from "Containers/HrManagement/StaffSalaryList";
import StaffSalaryAdd from "Containers/HrManagement/StaffSalaryAdd";
import HrAssignStandardSectionView from "Containers/HrManagement/HrAssignStandardSectionView";
import HrAssignStandardSection from "Containers/HrManagement/HrAssignStandardSection";
import HrStaffDepartmentList from "Containers/HrManagement/HrStaffDepartmentList";
import HrStaffDepartmentAdd from "Containers/HrManagement/HrStaffDepartmentAdd";
import HrStaffDepartmentMappingList from "Containers/HrManagement/HrStaffDepartmentMappingList";
import HrStaffDepartmentMappingAdd from "Containers/HrManagement/HrStaffDepartmentMappingAdd";

const alias_names = JSON.parse(localStorage.getItem("alias_name"))
  ? JSON.parse(localStorage.getItem("alias_name"))
  : {};

const Actions = {
  staff_list: {
    view: {
      codenames: [GET_URL.staff.basename],
      action_code: "visible_staff_list_view",
      is_superuser_action: false,
      name: "View Staff List",
      label: "View Staffs",
      action: "sub-menu",
      url: "/hr/staff/list",
      component: <StaffsList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/staff/add", "/hr/staff/edit", "/hr/staff/view"],
    },
    create: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        POST_URL.checkusernamenotexist.basename,
        GET_URL.groups.basename,
        POST_URL.staffalldetail.basename,
        GET_URL.users.basename,
        POST_URL.uploads.basename,
      ],
      action_code: "visible_staff_list_add",
      is_superuser_action: false,
      name: "Create Staff List",
      label: "Add Staff",
      action: "action-url",
      url: "/hr/staff/add",
      component: <HrStaffForm />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        GET_URL.staffalldetail.basename,
        PUT_URL.staffalldetail.basename,
        GET_URL.groups.basename,
        POST_URL.uploads.basename,
        GET_URL.users.basename,
      ],
      action_code: "visible_staff_list_change",
      is_superuser_action: false,
      name: "Update Subjects",
      label: "Edit Staff",
      action: "action",
      url: "/hr/staff/edit",
      component: <HrStaffForm />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.staff.basename],
      action_code: "visible_staff_list_delete",
      is_superuser_action: false,
      name: "Delete Staff List",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff List",
    type: "hr_management",
  },
  general_staff: {
    view: {
      codenames: [GET_URL.staffalldetail.basename],
      action_code: "visible_general_staff_view",
      is_superuser_action: false,
      name: "View Staff ",
      label: "General Staff",
      action: "action-url",
      url: "/hr/staff/view",
      component: <StaffView />,
      permission_needed: true,
      exclude_roles: [7],
    },

    name: "Staff",
    type: "hr_management",
  },
  manage_shift_types: {
    view: {
      codenames: [GET_URL.shift.basename],
      action_code: "visible_manage_shift_types_view",
      is_superuser_action: false,
      name: "View Manage Shift Types",
      label: "Manage Shift Types",
      action: "sub-menu",
      url: "/hr/shifts/list",
      component: <ShiftsView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/shifts/add", "/hr/shifts/edit", "/hr/shifts/view"],
    },
    create: {
      codenames: [POST_URL.shift.basename, GET_URL.days.basename],
      action_code: "visible_manage_shift_types_add",
      is_superuser_action: false,
      name: "Create Manage Shift Types",
      label: "Add Shifts",
      action: "action-url",
      url: "/hr/shifts/add",
      component: <NewAddShift />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.shift.basename],
      action_code: "visible_manage_shift_types_change",
      is_superuser_action: false,
      name: "Update Manage Shift Types",
      label: "Edit",
      url: "/hr/shifts/edit",
      component: <NewAddShift />,
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.shift.basename],
      action_code: "visible_manage_shift_types_delete",
      is_superuser_action: false,
      name: "Delete Staff List",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Manage Shift Types",
    type: "hr_management",
  },

  manage_shift_types_individual: {
    view: {
      codenames: [GET_URL.shift.basename],
      action_code: "visible_manage_shift_types_individual_view",
      is_superuser_action: false,
      name: "View Manage Shift Types",
      label: "Manage Shift Types",
      action: "action-url",
      url: "/hr/shifts/view",
      component: <IndividualShiftView />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Shift Individual View",
    type: "hr_management",
  },
  hr_department: {
    view: {
      codenames: [GET_URL.hr_department.basename],
      action_code: "visible_hr_department_view",
      is_superuser_action: false,
      name: "View Department",
      label: "Department",
      action: "sub-menu",
      url: "/hr/department/list",
      component: <HrStaffDepartmentList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/department/add"],
    },
    create: {
      codenames: [POST_URL.hr_department.basename],
      action_code: "visible_hr_department_add",
      is_superuser_action: false,
      name: "Add Department",
      label: "Add Department",
      action: "action-url",
      url: "/hr/department/add",
      component: <HrStaffDepartmentAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.hr_department.basename],
      action_code: "visible_hr_department_change",
      is_superuser_action: false,
      name: "Update Department",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.hr_department.basename],
      action_code: "visible_hr_department_delete",
      is_superuser_action: false,
      name: "Delete Department",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Department",
    type: "hr_management",
  },
  hr_assign_department: {
    view: {
      codenames: [GET_URL.department_staff_mapping.basename],
      action_code: "visible_hr_assign_department_view",
      is_superuser_action: false,
      name: "View Assign Department",
      label: "Assign Department",
      action: "sub-menu",
      url: "/hr/assign/department/list",
      component: <HrStaffDepartmentMappingList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/assign/department"],
    },
    create: {
      codenames: [
        POST_URL.department_staff_mapping.basename,
      ],
      action_code: "visible_hr_assign_department_add",
      is_superuser_action: false,
      name: "Create Assign Department",
      label: "Assign Department",
      action: "action-url",
      url: "/hr/assign/department/add",
      component: <HrStaffDepartmentMappingAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.department_staff_mapping.basename],
      action_code: "visible_hr_assign_department_change",
      is_superuser_action: false,
      name: "Update Assign Department",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.department_staff_mapping.basename],
      action_code: "visible_hr_assign_department_delete",
      is_superuser_action: false,
      name: "Delete Assign Department",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Assign Department",
    type: "hr_management",
  },
  assign_shift: {
    view: {
      codenames: [GET_URL.assignshift.basename, GET_URL.shift.basename],
      action_code: "visible_assign_shift_view",
      is_superuser_action: false,
      name: "View Assign Shift",
      label: "Assign Shift",
      action: "sub-menu",
      url: "/hr/assign/shift-view",
      component: <HrAssignShiftView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/assign/shift"],
    },
    create: {
      codenames: [
        GET_URL.assignshift.basename,
        GET_URL.getfinancialyear.basename,
        GET_URL.getunassigned.basename,
        POST_URL.assignshift.basename,
      ],
      action_code: "visible_assign_shift_add",
      is_superuser_action: false,
      name: "Create Assign Shift",
      label: "Assign Shift",
      action: "action-url",
      url: "/hr/assign/shift",
      component: <HrAssignShift />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.assignshift.basename],
      action_code: "visible_assign_shift_change",
      is_superuser_action: false,
      name: "Update Assign Shift",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.assignshift.basename],
      action_code: "visible_assign_shift_delete",
      is_superuser_action: false,
      name: "Delete Assign Shift",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Assign Shift",
    type: "hr_management",
  },
  assign_custom_shift: {
    view: {
      codenames: [
        GET_URL.assignshift.basename,
        GET_URL.shift.basename
      ],
      action_code: "visible_assign_custom_shift_view",
      is_superuser_action: false,
      name: "View Assign Custom Shift",
      label: "Assign Custom Shift",
      action: "sub-menu",
      url: "/hr/assign/custom-shift-view",
      component: <HrAssignCustomShiftView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/assign/custom-shift"],
    },
    create: {
      codenames: [
        GET_URL.assignshift.basename,
        GET_URL.getfinancialyear.basename,
        GET_URL.getunassigned.basename,
        POST_URL.assignshift.basename,
      ],
      action_code: "visible_assign_custom_shift_add",
      is_superuser_action: false,
      name: "Create Assign Custom Shift",
      label: "Assign Custom Shift",
      action: "action-url",
      url: "/hr/assign/custom-shift",
      component: <HrAssignCustomShift />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.assignshift.basename],
      action_code: "visible_assign_custom_shift_change",
      is_superuser_action: false,
      name: "Update Assign Custom Shift",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.assignshift.basename],
      action_code: "visible_assign_custom_shift_delete",
      is_superuser_action: false,
      name: "Delete Assign Custom Shift",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Assign Custom Shift",
    type: "hr_management",
  },
  assign_subject: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstaffsubject.basename,
      ],
      action_code: "visible_assign_subject_view",
      is_superuser_action: false,
      name: "View Assign Subject",
      label: "Assign Subject to Staff",
      action: "sub-menu",
      url: "/hr/assignsubject/view",
      component: <HrSubjectView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/assignsubject/add"],
    },
    create: {
      codenames: [
        GET_URL.getstaffsubject.basename,
        POST_URL.staffsubject.basename,
      ],
      action_code: "visible_assign_subject_add",
      is_superuser_action: false,
      name: "Create Assign Subject",
      label: "Add/Modify",
      action: "action-url",
      url: "/hr/assignsubject/add",
      component: <HrSubjectAddModify />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Assign Subject",
    type: "hr_management",
  },
  manage_staff_attendance: {
    view: {
      codenames: [
        GET_URL.staffattendance.basename,
        GET_URL.financialyear.basename,
      ],
      action_code: "visible_manage_staff_attendance_view",
      is_superuser_action: false,
      name: "View Manage Staff Attendance",
      label: "Attendance View ",
      action: "sub-menu",
      url: "/hr/staff/attendance/view",
      component: <HrStaffAttendanceView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/staff/attendance/add"],
    },
    create: {
      codenames: [
        GET_URL.staffunmarkedattendance.basename,
        POST_URL.staffattendance.basename,
      ],
      action_code: "visible_manage_staff_attendance_add",
      is_superuser_action: false,
      name: "Create Manage Staff Attendance",
      label: "Mark Staff Attendance",
      action: "action-url",
      url: "/hr/staff/attendance/add",
      component: <HrStaffAttendance />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        PUT_URL.staffattendance.basename,
        PUT_URL.staffattendancebulk.basename,
      ],
      action_code: "visible_manage_staff_attendance_change",
      is_superuser_action: false,
      name: "Update Manage Staff Attendance",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Manage Staff Attendance",
    type: "hr_management",
  },
  assign_standard: {
    view: {
      codenames: [
        GET_URL.staff_standard_mapping.basename,
        POST_URL.staff_standard_mapping.basename,
        GET_URL.getstandardandsection.basename,
      ],
      action_code: "visible_assign_standard_view",
      is_superuser_action: false,
      name: "View Assign Standard",
      label: `Assigned ${alias_names["standard"]}`,
      action: "sub-menu",
      url: "/hr/assign/standard/list",
      component: <StaffMapWithStandardsList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/assign/standard/add"],
    },
    create: {
      codenames: [
        GET_URL.staff_standard_mapping.basename,
        POST_URL.staff_standard_mapping.basename,
        GET_URL.getstandardandsection.basename,
      ],
      action_code: "visible_assign_standard_add",
      is_superuser_action: false,
      name: "Create Assign Standard",
      label: "Assign Standard",
      action: "action-url",
      url: "/hr/assign/standard/add",
      component: <StaffMapWithStandards />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [],
      action_code: "visible_assign_standard_change",
      is_superuser_action: false,
      name: "Update Assign Shift",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Assign Standard",
    type: "hr_management",
  },
  assign_standard_section: {
    view: {
      codenames: [
        GET_URL.staffstandardsectionmapping.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.section.basename,
        GET_URL.staff.basename,
      ],
      action_code: "visible_assign_standard_section_view",
      is_superuser_action: false,
      name: "View Assign Standard Section",
      label: `Assigned ${alias_names["standard"]} Section`,
      action: "sub-menu",
      url: "/hr/assign/standard/section/list",
      component: <HrAssignStandardSectionView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/assign/standard/section/add"],
    },
    create: {
      codenames: [
        GET_URL.staffstandardsectionmapping.basename,
        POST_URL.staffstandardsectionmapping.basename,
        GET_URL.getstandardandsection.basename,
        GET_URL.staff.basename,
      ],
      action_code: "visible_assign_standard_section_add",
      is_superuser_action: false,
      name: "Create Assign Standard Section",
      label: "Assign Standard Section",
      action: "action-url",
      url: "/hr/assign/standard/section/add",
      component: <HrAssignStandardSection />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [
        PUT_URL.staffstandardsectionmapping.basename,
        GET_URL.staff.basename,
      ],
      action_code: "visible_assign_standard_section_change",
      is_superuser_action: false,
      name: "Update Assign Standard Section",
      label: "Edit",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.staffstandardsectionmapping.basename],
      action_code: "visible_assign_standard_section_delete",
      is_superuser_action: false,
      name: "Delete Assign Standard Section",
      label: "Delete",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Assign Standard Section",
    type: "hr_management",
  },
  staff_organization_chart: {
    view: {
      codenames: [GET_URL.usertreestructure.basename],
      action_code: "visible_staff_organization_chart_view",
      is_superuser_action: false,
      name: "Organization Chart",
      label: "Organization Chart",
      action: "sub-menu",
      url: "/hr/staff/organization/view",
      component: <HrStaffOrganizationChart />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Organization",
    type: "hr_management",
  },
  staff_usernames: {
    view: {
      codenames: [GET_URL.staff.basename],
      action_code: "visible_staff_usernames_view",
      is_superuser_action: false,
      name: "View Staff User Names",
      label: " Staff User Names ",
      action: "sub-menu",
      url: "/hr/staff/username/list",
      component: <StaffUserNameList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/staff/username/add"],
    },
    create: {
      codenames: [GET_URL.staff.basename, POST_URL.updateuserdata.basename],
      action_code: "visible_staff_usernames_add",
      is_superuser_action: false,
      name: "Staff User Names",
      label: "Staff User Names",
      action: "action-url",
      url: "/hr/staff/username/add",
      component: <StaffUserNameAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff UserNames",
    type: "hr_management",
  },
  staff_attendance_report: {
    view: {
      codenames: [
        GET_URL.staffattendance.basename,
      ],
      action_code: "visible_staff_attendance_report_view",
      is_superuser_action: false,
      name: "Staff Attendnace Report",
      label: "Staff Attendnace Report",
      action: "sub-menu",
      url: "/hr/staff/attendance/report",
      component: <StaffAttendnaceReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [GET_URL.staff.basename, POST_URL.updateuserdata.basename],
      action_code: "visible_staff_attendance_report_add",
      is_superuser_action: false,
      name: "Staff Attendnace Report",
      label: "Staff Attendnace Report",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Attendance Report",
    type: "hr_management",
  },
  staff_salary: {
    view: {
      codenames: [GET_URL.staff.basename],
      action_code: "visible_staff_salary_view",
      is_superuser_action: false,
      name: "Staff Salart",
      label: " Staff Salary ",
      action: "sub-menu",
      url: "/hr/staff/salary/list",
      component: <StaffSalaryList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/hr/staff/username/add"],
    },
    create: {
      codenames: [GET_URL.staff.basename, POST_URL.updateuserdata.basename],
      action_code: "visible_staff_salary_add",
      is_superuser_action: false,
      name: "Staff Salary",
      label: "Staff Salary",
      action: "action-url",
      url: "/hr/staff/salary/add",
      component: <StaffSalaryAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Salary",
    type: "hr_management",
  },
};

export default Actions;