import React from "react";
import { GET_URL, POST_URL, DEL_URL, PUT_URL } from "Includes/urls";
import LibCategoryList from "Containers/Library/LibCategoryList";
import AddLibCategory from "Containers/Library/AddLibCategory";
import AddLibSubCategory from "Containers/Library/AddLibSubCategory";
import ListAuthors from "Containers/Library/ListAuthors";
import AddAuthors from "Containers/Library/AddAuthors";
import ListBooks from "Containers/Library/ListBooks";
import AddBook from "Containers/Library/AddBook";
import ListPublisher from "Containers/Library/ListPublisher";
import AddPublisher from "Containers/Library/AddPublisher";
import LibSubCategoryList from "Containers/Library/LibSubCategoryList";
import IssueBookList from "Containers/Library/IssueBookList";
import IssueBooksNew from "Containers/Library/IssueBooksNew";
import LibConfigurationView from "Containers/Library/LibConfigurationView";
import LibConfigurationAdd from "Containers/Library/LibConfigurationAdd";
import LibraryDashboard from "Containers/Library/LibraryDashboard";
import MembershipLibrary from "Containers/Library/MembershipLibrary";
import LibVendorView from "Containers/Library/LibVendorView";
import AddLibVendors from "Containers/Library/AddLibVendors";
import LibCheckinoutCreate from "Containers/Library/LibCheckinoutCreate";
import FinePendingList from "Containers/Library/FinePendingList";
import FineCollectionList from "Containers/Library/FineCollectionList";
import ListRacks from "Containers/Library/ListRacks";
import AddRacks from "Containers/Library/AddRacks";
import LibraryStockVerification from "Containers/Library/LibraryStockVerification";
import LibraryStockVerificationReport from "Containers/Library/LibraryStockVerificationReport";
import LibraryStockVerificationParent from "Containers/Library/ViewLibraryStockVerificationParent";
import AddLibraryStockVerificationParent from "Containers/Library/AddLibraryStockVerificationParent";

const Actions = {
  library_dashboard: {
    view: {
      codenames: [POST_URL.librarydashboard.basename],
      action_code: "visible_library_dashboard_view",
      is_superuser_action: false,
      name: "Library Dashboard",
      label: "Library Dashboard",
      action: "sub-menu",
      url: "/lib/dashboard",
      component: <LibraryDashboard />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library Dashboard",
    type: "library",
  },
  library_categegory: {
    view: {
      codenames: [GET_URL.librarycategory.basename],
      action_code: "visible_library_categegory_view",
      is_superuser_action: false,
      name: "Library Category",
      label: "Library Category",
      action: "sub-menu",
      url: "/lib/category/view",
      component: <LibCategoryList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/category/create"],
    },
    update: {
      codenames: [PUT_URL.librarycategory.basename],
      action_code: "visible_library_categegory_change",
      is_superuser_action: false,
      name: "Update Library Category",
      label: "Library Category",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.librarycategory.basename],
      action_code: "visible_library_categegory_delete",
      is_superuser_action: false,
      name: "Delete Library Category",
      label: "Library Category",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.librarycategory.basename],
      action_code: "visible_library_categegory_change",
      is_superuser_action: false,
      name: "Add Library Category",
      label: "Library Category",
      url: "/lib/category/create",
      component: <AddLibCategory />,
      action: "action-url",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library Category",
    type: "library",
  },
  library_sub_categegory: {
    view: {
      codenames: [
        GET_URL.librarycategory.basename,
        GET_URL.librarysubcategory.basename,
      ],
      action_code: "visible_library_sub_categegory_view",
      is_superuser_action: false,
      name: "Library Sub Category",
      label: "Library Sub Category",
      action: "sub-menu",
      url: "/lib/subcategory/view",
      component: <LibSubCategoryList />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/subcategory/add"],
    },
    update: {
      codenames: [PUT_URL.librarysubcategory.basename],
      action_code: "visible_library_sub_categegory_change",
      is_superuser_action: false,
      name: "Library Sub Category",
      label: "Library Sub Category",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.librarysubcategory.basename],
      action_code: "visible_library_sub_categegory_delete",
      is_superuser_action: false,
      name: "Library Sub Category",
      label: "Library Sub Category",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.librarysubcategory.basename],
      action_code: "visible_library_sub_categegory_add",
      is_superuser_action: false,
      name: "Library Sub Category",
      label: "Library Sub Category",
      action: "action-url",
      url: "/lib/subcategory/add",
      component: <AddLibSubCategory />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library Sub Category",
    type: "library",
  },
  library_authors: {
    view: {
      codenames: [GET_URL.libraryauthor.basename],
      action_code: "visible_library_authors_view",
      is_superuser_action: false,
      name: "Book Authors",
      label: "Book Authors",
      action: "sub-menu",
      url: "/lib/authors/view",
      component: <ListAuthors />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/authors/create"],
    },
    update: {
      codenames: [PUT_URL.libraryauthor.basename],
      action_code: "visible_library_authors_change",
      is_superuser_action: false,
      name: "Book Authors",
      label: "Book Authors",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.libraryauthor.basename],
      action_code: "visible_library_authors_delete",
      is_superuser_action: false,
      name: "Book Authors",
      label: "Book Authors",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.libraryauthor.basename],
      action_code: "visible_library_authors_change",
      is_superuser_action: false,
      name: "Book Authors",
      label: "Book Authors",
      url: "/lib/authors/create",
      component: <AddAuthors />,
      action: "action-url",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Book Authors",
    type: "library",
  },
  library_publisher: {
    view: {
      codenames: [GET_URL.librarypublisher.basename],
      action_code: "visible_library_publisher_view",
      is_superuser_action: false,
      name: "Book Publisher",
      label: "Book Publisher",
      action: "sub-menu",
      url: "/lib/publisher/view",
      component: <ListPublisher />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/publisher/create"],
    },
    update: {
      codenames: [PUT_URL.librarypublisher.basename],
      action_code: "visible_library_publisher_change",
      is_superuser_action: false,
      name: "Book Publisher",
      label: "Book Publisher",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.librarypublisher.basename],
      action_code: "visible_library_publisher_delete",
      is_superuser_action: false,
      name: "Book Publisher",
      label: "Book Publisher",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.librarypublisher.basename],
      action_code: "visible_library_publisher_change",
      is_superuser_action: false,
      name: "Book Publisher",
      label: "Book Publisher",
      url: "/lib/publisher/create",
      component: <AddPublisher />,
      action: "action-url",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Book Publisher",
    type: "library",
  },
  library_racks: {
    view: {
      codenames: [GET_URL.libraryrack.basename,
                  PUT_URL.libraryrack.basename,
                  DEL_URL.libraryrack.basename],
      action_code: "visible_library_racks_view",
      is_superuser_action: false,
      name: "Book Racks",
      label: "Book Racks",
      action: "sub-menu",
      url: "/lib/racks/view",
      component: <ListRacks />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/racks/create"],
    },
    update: {
      codenames: [PUT_URL.libraryrack.basename],
      action_code: "visible_library_racks_change",
      is_superuser_action: false,
      name: "Book Racks",
      label: "Book Racks",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.libraryrack.basename],
      action_code: "visible_library_racks_delete",
      is_superuser_action: false,
      name: "Book Racks",
      label: "Book Racks",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.libraryrack.basename],
      action_code: "visible_library_racks_change",
      is_superuser_action: false,
      name: "Book Racks",
      label: "Book Racks",
      url: "/lib/racks/create",
      component: <AddRacks />,
      action: "action-url",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Book Racks",
    type: "library",
  },
  library_books: {
    view: {
      codenames: [
        GET_URL.librarycategory.basename,
        GET_URL.librarysubcategory.basename,
        GET_URL.librarybook.basename,
        GET_URL.librarybookcopy.basename,
      ],
      action_code: "visible_library_books_view",
      is_superuser_action: false,
      name: "Library Books",
      label: "Library Books",
      action: "sub-menu",
      url: "/lib/books/view",
      component: <ListBooks />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/books/create", "/lib/books/update"],
    },
    create: {
      codenames: [
        GET_URL.librarycategory.basename,
        GET_URL.librarysubcategory.basename,
        GET_URL.librarybook.basename,
        GET_URL.librarybookcopy.basename,
        POST_URL.librarybook.basename,
      ],
      action_code: "visible_library_books_add",
      is_superuser_action: false,
      name: "Library Book",
      label: "Library Book",
      action: "action-url",
      url: "/lib/books/create",
      component: <AddBook />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [GET_URL.librarybook.basename, POST_URL.librarybook.basename],
      action_code: "visible_library_books_change",
      is_superuser_action: false,
      name: "Library Book",
      label: "Library Book",
      action: "action-url",
      url: "/lib/books/update",
      component: <AddBook />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.librarybookcopy.basename],
      action_code: "visible_library_books_delete",
      is_superuser_action: false,
      name: "Delete Book",
      label: "Delete Book",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library Books",
    type: "library",
  },
  library_issue_book: {
    view: {
      codenames: [
        GET_URL.librarycategory.basename,
        GET_URL.librarysubcategory.basename,
        GET_URL.issuereturnbook.basename,
      ],
      action_code: "visible_library_issue_book_view",
      is_superuser_action: false,
      name: "Issued Books",
      label: "Issued/Returned Books",
      action: "action-url",
      url: "/lib/books/issue/view",
      component: <IssueBookList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [
        GET_URL.staff.basename,
        GET_URL.bookandusersearch.basename,
        POST_URL.issuereturnbook.basename,
      ],
      action_code: "visible_library_issue_book_add",
      is_superuser_action: false,
      name: "Issue Book",
      label: "Issue/Return Book",
      action: "sub-menu",
      url: "/lib/books/issue/create",
      component: <IssueBooksNew />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/books/issue/view"],
    },
    name: "Issue Books",
    type: "library",
  },
  library_configuration: {
    view: {
      codenames: [GET_URL.libraryconfiguration.basename],
      action_code: "visible_library_configuration_view",
      is_superuser_action: false,
      name: "Library Configuration",
      label: "Library Configuration",
      action: "sub-menu",
      url: "/lib/config/view",
      component: <LibConfigurationView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/config/create"],
    },
    create: {
      codenames: [
        GET_URL.libraryconfiguration.basename,
        GET_URL.getstandardandsection.basename,
      ],
      action_code: "visible_library_configuration_add",
      is_superuser_action: false,
      name: "Library Configuration",
      label: "Library Configuration",
      action: "action-url",
      url: "/lib/config/create",
      component: <LibConfigurationAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [],
      action_code: "visible_library_configuration_change",
      is_superuser_action: false,
      name: "Library Configuration",
      label: "Library Configuration",
      action: "action-url",
      url: "/lib/config/update",
      component: <LibConfigurationAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.libraryconfiguration.basename],
      action_code: "visible_library_configuration_delete",
      is_superuser_action: false,
      name: "Library Configuration",
      label: "Library Configuration",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library Configuration",
    type: "library",
  },
  library_membership: {
    view: {
      codenames: [GET_URL.student.basename, GET_URL.getstandard.basename],
      action_code: "visible_library_membership_view",
      is_superuser_action: false,
      name: "Library Membership",
      label: "Library Membership",
      action: "sub-menu",
      url: "/lib/membership",
      component: <MembershipLibrary />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [],
      action_code: "visible_library_membership_add",
      is_superuser_action: false,
      name: "Library Membership",
      label: "Library Membership",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [],
      action_code: "visible_library_membership_change",
      is_superuser_action: false,
      name: "Library Membership",
      label: "Library Membership",
      action: "action-url",
      url: "/lib/config/update",
      component: <LibConfigurationAdd />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library Membership",
    type: "library",
  },
  library_checkin_checkout: {
    view: {
      codenames: [
        POST_URL.libraryuserattendance.basename,
        POST_URL.usercheckincheckout.basename,
      ],
      action_code: "visible_library_checkin_checkout_view",
      is_superuser_action: false,
      name: "Library In Out",
      label: "Library In Out",
      action: "sub-menu",
      url: "/lib/inout",
      component: <LibCheckinoutCreate />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [],
      action_code: "visible_library_checkin_checkout_add",
      is_superuser_action: false,
      name: "Library In Out",
      label: "Library In Out",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Library In Out",
    type: "library",
  },
  library_vendors: {
    view: {
      codenames: [GET_URL.vendor.basename],
      action_code: "visible_library_vendors_view",
      is_superuser_action: false,
      name: "View Vendors",
      label: "Vendors",
      action: "sub-menu",
      url: "/lib/vendors/view",
      component: <LibVendorView />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/vendors/create"],
    },
    create: {
      codenames: [POST_URL.vendor.basename],
      action_code: "visible_library_vendors_add",
      is_superuser_action: false,
      name: "View Vendors",
      label: "Vendors",
      action: "action-url",
      url: "/lib/vendors/create",
      component: <AddLibVendors />,
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.vendor.basename],
      action_code: "visible_library_vendors_change",
      is_superuser_action: false,
      name: "Update Item",
      label: "Update Item",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    delete: {
      codenames: [DEL_URL.vendor.basename],
      action_code: "visible_library_vendors_delete",
      is_superuser_action: false,
      name: "Delete Item",
      label: "Delete Item",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Vendors",
    type: "library",
  },
  library_pending_fine_list: {
    view: {
      codenames: [POST_URL.libraryreport.basename],
      action_code: "visible_library_pending_fine_list_view",
      is_superuser_action: false,
      name: "Fine Pending List",
      label: "Fine Pending List",
      action: "sub-menu",
      url: "/lib/fine/pending/view",
      component: <FinePendingList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fine Pending List",
    type: "library",
  },
  library_collected_fine_list: {
    view: {
      codenames: [POST_URL.libraryfine.basename],
      action_code: "visible_library_collected_fine_list_view",
      is_superuser_action: false,
      name: "Fine Collected List",
      label: "Fine Collected List",
      action: "sub-menu",
      url: "/lib/fine/collected/view",
      component: <FineCollectionList />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Fine Collected List",
    type: "library",
  },
  library_stock_verifiction: {
    view: {
      codenames: [
      ],
      action_code: "visible_library_stock_verifiction_view",
      is_superuser_action: false,
      name: "Library Stock Verification",
      label: "Library Stock Verification",
      action: "sub-menu",
      url: "/lib/stockverification/view",
      component: <LibraryStockVerification />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/lib/stockverification/report"],
    },
    create: {
      codenames: [],
      action_code: "visible_library_stock_verifiction_view",
      is_superuser_action: false,
      name: "Library Stock Verification Report",
      label: "Library Stock Verification Report",
      action: "action-url",
      url: "/lib/stockverification/report",
      component: <LibraryStockVerificationReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    // create: {
    //   codenames: [],
    //   action_code: "visible_library_stock_verifiction_add",
    //   is_superuser_action: false,
    //   name: "Add Library Stock Verification",
    //   label: "Add Library Stock Verification",
    //   action: "sub-menu",
    //   url: "/lib/stockverification/create",
    //   component: <LibraryStockVerification />,
    //   permission_needed: true,
    //   exclude_roles: [7],
    // },
    name: "Library Stock Verification",
    type: "library",
  },
  library_stock_verification_parent: {
    view: {
        codenames: [],
        action_code: 'visible_library_stock_verification_parent_view',
        is_superuser_action: false,
        name: 'Library Verification For',
        label: 'Library Verification For',
        action: 'sub-menu',
        url: '/lib/libraryverificationfor/view',
        component: <LibraryStockVerificationParent />,
        permission_needed: true,
        exclude_roles:[7],
        associated_urls: ['/libraryverificationfor/create'],
    },
    update: {
        codenames: [],
        action_code: 'visible_library_stock_verification_parent_change',
        is_superuser_action: false,
        name: 'Update Library Verification For',
        label: 'Library Verification For',
        action: 'action',
        permission_needed: true,
        exclude_roles:[7],
    },
    delete: {
        codenames: [],
        action_code: 'visible_library_stock_verification_parent_delete',
        is_superuser_action: false,
        name: 'Delete Library Verification For',
        label: 'Library Verification For',
        action: 'action',
        permission_needed: true,
        exclude_roles:[7],
    },
    create: {
        codenames: [],
        action_code: 'visible_library_stock_verification_parent_add',
        is_superuser_action: false,
        name: 'Add Library Verification For',
        label: 'Library Verification For',
        url: '/lib/libraryverificationfor/create',
        component: <AddLibraryStockVerificationParent />,
        action: 'action-url',
        permission_needed: true,
        exclude_roles:[7],
    },
    name: 'Library Verification For',
    type: 'library',
  },
};
export default Actions;
