import React from "react";
import { GET_URL, POST_URL, DEL_URL, PUT_URL } from "Includes/urls";
import CategoryView from "Containers/StoreManagement/CategoryView"
import AddCategory from "Containers/StoreManagement/AddCategory";
import SubCategoryView from "Containers/StoreManagement/SubCategoryView"
import AddSubCategory from "Containers/StoreManagement/AddSubCategory"
import PropertiesView from "Containers/StoreManagement/PropertiesView"
import AddProperties from "Containers/StoreManagement/AddProperties"
import PropertiesValue from "Containers/StoreManagement/PropertiesValue"
import AddPropertiesValue from "Containers/StoreManagement/AddPropertiesValue"
import ItemView from "Containers/StoreManagement/ItemView"
import AddItem from "Containers/StoreManagement/AddItem"
import VendorView from "Containers/StoreManagement/VendorView"
import AddVendors from "Containers/StoreManagement/AddVendors"
import ManageStockItems from "Containers/StoreManagement/ManageStockItems";
import AddStockItems from "Containers/StoreManagement/AddStockItems"
import PurchaseView from "Containers/StoreManagement/PurchaseView";
import AddPurchase from "Containers/StoreManagement/AddPurchase";
import ReturnItem from "Containers/StoreManagement/ReturnItem";
import ReturnItemList from "Containers/StoreManagement/ReturnItemList";
import ItemIssueView from "Containers/StoreManagement/ItemIssueView";
import IssueItems from "Containers/StoreManagement/IssueItems";
import messages from 'Containers/StoreManagement/messages';
import { FormattedMessage } from 'react-intl';
import PackageView from "Containers/StoreManagement/PackageView";
import AddPackage from "Containers/StoreManagement/AddPackage";

const Actions = {
    store_inventory_category: {
        view: {
            codenames: [GET_URL.storecategory.basename, PUT_URL.storecategory.basename],
            action_code: 'visible_store_inventory_category_view',
            is_superuser_action: false,
            name: 'Category Type',
            label: 'Category Type',
            action: 'sub-menu',
            url: '/category/view',
            component: <CategoryView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/category/create'],
        },
        update: {
            codenames: [PUT_URL.storecategory.basename],
            action_code: 'visible_store_inventory_category_change',
            is_superuser_action: false,
            name: 'Update Category Type',
            label: 'Category Type',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        delete: {
            codenames: [DEL_URL.storecategory.basename],
            action_code: 'visible_store_inventory_category_delete',
            is_superuser_action: false,
            name: 'Delete Category Type',
            label: 'Category Type',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        create: {
            codenames: [POST_URL.storecategory.basename],
            action_code: 'visible_store_inventory_category_change',
            is_superuser_action: false,
            name: 'Add Category Type',
            label: 'Category Type',
            url: '/category/create',
            component: <AddCategory />,
            action: 'action-url',
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Category Type',
        type: 'storemanagement',
    },
    store_inventory_subcategory: {
        view: {
            codenames: [GET_URL.storecategory.basename, GET_URL.subcategory.basename],
            action_code: 'visible_store_inventory_subcategory_view',
            is_superuser_action: false,
            name: 'View Subcategories',
            label: 'Sub Category',
            action: 'sub-menu',
            url: '/subcategory/view',
            component: <SubCategoryView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/subcategory/add'],
        },
        update: {
            codenames: [PUT_URL.subcategory.basename],
            action_code: 'visible_store_inventory_subcategory_change',
            is_superuser_action: false,
            name: 'Update SubCategory',
            label: 'Update SubCategory',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        delete: {
            codenames: [DEL_URL.subcategory.basename],
            action_code: 'visible_store_inventory_subcategory_delete',
            is_superuser_action: false,
            name: 'Delete SubCategory',
            label: 'Delete SubCategory',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        create: {
            codenames: [POST_URL.subcategory.basename],
            action_code: 'visible_store_inventory_subcategory_add',
            is_superuser_action: false,
            name: 'Add Sub Categories',
            label: 'Sub Categories',
            action: 'action-url',
            url: '/subcategory/add',
            component: <AddSubCategory />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Sub Category Type',
        type: 'storemanagement',
    },
    store_inventory_properties: {
        view: {
            codenames: [GET_URL.properties.basename],
            action_code: 'visible_store_inventory_properties_view',
            is_superuser_action: false,
            name: 'View Properties',
            label: 'Property Types',
            action: 'sub-menu',
            url: '/store/properties',
            component: <PropertiesView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/store/properties/add'],
        },
        update: {
            codenames: [PUT_URL.properties.basename],
            action_code: 'visible_store_inventory_properties_change',
            is_superuser_action: false,
            name: 'Update Properties',
            label: 'Update Properties',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        delete: {
            codenames: [DEL_URL.properties.basename],
            action_code: 'visible_store_inventory_properties_delete',
            is_superuser_action: false,
            name: 'Delete Properties',
            label: 'Delete Properties',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        create: {
            codenames: [POST_URL.properties.basename],
            action_code: 'visible_store_inventory_properties_add',
            is_superuser_action: false,
            name: 'Add Properties',
            label: 'Property Types',
            action: 'action-url',
            url: '/store/properties/add',
            component: <AddProperties />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Property Types',
        type: 'storemanagement',
    },
    store_inventory_properties_values: {
        view: {
            codenames: [GET_URL.properties.basename, GET_URL.propertyvalue.basename],
            action_code: 'visible_store_inventory_properties_values_view',
            is_superuser_action: false,
            name: 'View Properties Values',
            label: 'Properties Values',
            action: 'sub-menu',
            url: '/store/properties/values',
            component: <PropertiesValue />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/store/properties/values/add'],
        },
        update: {
            codenames: [PUT_URL.propertyvalue.basename],
            action_code: 'visible_store_inventory_properties_values_change',
            is_superuser_action: false,
            name: 'Update Properties Values',
            label: 'Update Properties Values',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        delete: {
            codenames: [DEL_URL.propertyvalue.basename],
            action_code: 'visible_store_inventory_properties_values_delete',
            is_superuser_action: false,
            name: 'Delete Properties Values',
            label: 'Delete Properties Values',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        create: {
            codenames: [POST_URL.propertyvalue.basename],
            action_code: 'visible_store_inventory_properties_values_add',
            is_superuser_action: false,
            name: 'Add Properties Values',
            label: 'Property Value',
            action: 'action-url',
            url: '/store/properties/values/add',
            component: <AddPropertiesValue />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Properties Values',
        type: 'storemanagement',
    },
    store_inventory_item: {
        view: {
            codenames: [GET_URL.item.basename],
            action_code: 'visible_store_inventory_item_view',
            is_superuser_action: false,
            name: 'View Items',
            label: 'Items',
            action: 'sub-menu',
            url: '/store/item',
            component: <ItemView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/store/item/add'],
        },
        update: {
            codenames: [PUT_URL.item.basename],
            action_code: 'visible_store_inventory_item_change',
            is_superuser_action: false,
            name: 'Update Item',
            label: 'Update Item',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        delete: {
            codenames: [DEL_URL.item.basename],
            action_code: 'visible_store_inventory_item_delete',
            is_superuser_action: false,
            name: 'Delete Item',
            label: 'Delete Item',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        create: {
            codenames: [POST_URL.item.basename],
            action_code: 'visible_store_inventory_item_add',
            is_superuser_action: false,
            name: 'Add Item',
            label: 'Items',
            action: 'action-url',
            url: '/store/item/add',
            component: <AddItem />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Item List',
        type: 'storemanagement',
    },
    store_inventory_vendors: {
        view: {
            codenames: [GET_URL.vendor.basename],
            action_code: 'visible_store_inventory_vendors_view',
            is_superuser_action: false,
            name: 'View Vendors',
            label: 'Vendors',
            action: 'sub-menu',
            url: '/vendors/view',
            component: <VendorView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/vendors/create'],
        },
        update: {
            codenames: [PUT_URL.vendor.basename],
            action_code: 'visible_store_inventory_vendors_change',
            is_superuser_action: false,
            name: 'Update Item',
            label: 'Update Item',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        delete: {
            codenames: [DEL_URL.vendor.basename],
            action_code: 'visible_store_inventory_vendors_delete',
            is_superuser_action: false,
            name: 'Delete Item',
            label: 'Delete Item',
            action: 'action',
            permission_needed: true,
            exclude_roles:[7],
        },
        create: {
            codenames: [POST_URL.vendor.basename],
            action_code: 'visible_store_inventory_vendors_add',
            is_superuser_action: false,
            name: 'View Vendors',
            label: 'Vendors',
            action: 'action-url',
            url: '/vendors/create',
            component: <AddVendors />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Vendors',
        type: 'storemanagement',
    },
    store_stock_items: {
        view: {
            codenames: [GET_URL.storecategory.basename, GET_URL.subcategory.basename, GET_URL.stock.basename],
            action_code: 'visible_store_stock_items_view',
            is_superuser_action: false,
            name: 'View Items',
            label: 'Stock Items',
            action: 'sub-menu',
            url: '/stock/items/view',
            component: <ManageStockItems />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/stock/items/create','/stock/items/update'],
        },
        create: {
            codenames: [GET_URL.storecategory.basename, GET_URL.subcategory.basename, GET_URL.item.basename, GET_URL.properties.basename, GET_URL.propertyvalue.basename, POST_URL.stock.basename],
            action_code: 'visible_store_stock_items_add',
            is_superuser_action: false,
            name: 'View Items',
            label: 'Stock Items',
            action: 'action-url',
            url: '/stock/items/create',
            component: <AddStockItems />,
            permission_needed: true,
            exclude_roles:[7],
        },
        update: {
            codenames: [GET_URL.storecategory.basename, GET_URL.subcategory.basename, GET_URL.item.basename, GET_URL.properties.basename, GET_URL.propertyvalue.basename, PUT_URL.stock.basename],
            action_code: 'visible_store_stock_items_change',
            is_superuser_action: false,
            name: 'View Items',
            label: 'Stock Items',
            action: 'action-url',
            url: '/stock/items/update',
            component: <AddStockItems />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Stock Items',
        type: 'storemanagement',
    },
    store_purchase_items: {
        view: {
            codenames: [GET_URL.purchasemaster.basename],
            action_code: 'visible_store_purchase_items_view',
            is_superuser_action: false,
            name: 'View Purchase',
            label: 'Purchase',
            action: 'sub-menu',
            url: '/store/purchase/items',
            component: <PurchaseView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/store/purchase/create'],
        },
        create: {
            codenames: [GET_URL.vendor.basename, POST_URL.purchasemaster.basename],
            action_code: 'visible_store_purchase_items_add',
            is_superuser_action: false,
            name: 'Add Purchase',
            label: 'Purchase',
            action: 'action-url',
            url: '/store/purchase/create',
            component: <AddPurchase />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Purchase Master',
        type: 'storemanagement',
    },
    store_return_items: {
        create: {
            codenames: [GET_URL.vendor.basename, GET_URL.purchasemaster.basename, POST_URL.purchasemasterreturn.basename],
            action_code: 'visible_store_return_items_view',
            is_superuser_action: false,
            name: 'Return Purchase',
            label: 'Return Purchase',
            action: 'action-url',
            url: '/store/return/items',
            component: <ReturnItem />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Return Item',
        type: 'storemanagement',
    },
    store_return_items_list: {
        view: {
            codenames: [GET_URL.purchasemasterreturn.basename,],
            action_code: 'visible_store_return_items_list_view',
            is_superuser_action: false,
            name: 'Return Item List',
            label: 'Return Item List',
            action: 'sub-menu',
            url: '/store/return/items/list',
            component: <ReturnItemList />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Return Item List',
        type: 'storemanagement',
    },
    store_issue_items: {
        view: {
            codenames: [GET_URL.storecategory.basename,GET_URL.itemsold.basename],
            action_code: 'visible_store_issue_items_view',
            is_superuser_action: false,
            name: 'Issue Items',
            label: 'Issue Items',
            action: 'sub-menu',
            url: '/store/issued/items/list',
            component: <ItemIssueView />,
            permission_needed: true,
            exclude_roles:[7],
            associated_urls: ['/store/issue/items'],
        },
        create: {
            codenames: [GET_URL.staff.basename, GET_URL.stock.basename, GET_URL.storecategory.basename,
                 GET_URL.getstandardandsection.basename,GET_URL.student.basename, POST_URL.itemsold.basename
            ],
            action_code: 'visible_store_issue_items_add',
            is_superuser_action: false,
            name: 'Issue Items',
            label: 'Issue Items',
            action: 'action-url',
            url: '/store/issue/items',
            component: <IssueItems />,
            permission_needed: true,
            exclude_roles:[7],
        },
        name: 'Manage Issue Items',
        type: 'storemanagement',
    },
    store_inventory_package: {
        view: {
            codenames: [GET_URL.package.api],
            action_code: 'visible_store_inventory_package_view',
            is_superuser_action: false,
            name: 'View Packages',
            label: 'Packages',
            action: 'sub-menu',
            url: '/store/package/view',
            component: <PackageView />,
            permission_needed: true,
            exclude_roles: [7],
            associated_urls: ['/store/package/add'],
        },
        update: {
            codenames: [PUT_URL.package.api],
            action_code: 'visible_store_inventory_package_change',
            is_superuser_action: false,
            name: 'Update Package',
            label: 'Update Package',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        delete: {
            codenames: [DEL_URL.package.api],
            action_code: 'visible_store_inventory_package_delete',
            is_superuser_action: false,
            name: 'Delete Package',
            label: 'Delete Package',
            action: 'action',
            permission_needed: true,
            exclude_roles: [7],
        },
        create: {
            codenames: [POST_URL.package.api],
            action_code: 'visible_store_inventory_package_add',
            is_superuser_action: false,
            name: 'Add Package',
            label: 'Add Package',
            action: 'action-url',
            url: '/store/package/add',
            component: <AddPackage />,
            permission_needed: true,
            exclude_roles: [7],
        },
        name: 'Package Management',
        type: 'storemanagement',
    },
}
export default Actions;