import React from "react";
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from "Includes/urls";

import EnquiryStudentsList from "Containers/StudentForms/EnquiryStudentsListWithPosterQr";
import EnquiryForm from "Containers/StudentForms/Components/EnquiryForm";
import EnqueryView from "Containers/StudentForms/EnqueryView";
import ApplicationStudentList from "Containers/StudentForms/ApplicationStudentList";
import ApplicationForm from "Containers/StudentForms/Components/ApplicationForm";
import ApplicationView from "Containers/StudentForms/ApplicationView";
import AdmissionForm from "Containers/StudentForms/Components/AdmissionForm";
import AdmissionView from "Containers/StudentForms/AdmissionView";
import AdmissionStudentList from "Containers/StudentForms/AdmissionStudentList";
import StudentTypeSwitch from "Containers/StudentForms/StudentTypeSwitch";
import StudentTypeSwitchIndividual from "Containers/StudentForms/StudentTypeSwitchIndividual";
import StudentForm from "Containers/Student/Components/StudentForm";
import StudentList from "Containers/Student/StudentList";
import StudentView from "Containers/Student/StudentView";
import UserLoggedInList from "Containers/Student/UserLoggedInList";
import StudentBulkUpdateList from "Containers/Student/StudentBulkUpdateList";
import StudentBulkUpdate from "Containers/Student/StudentBulkUpdate";

let Actions = {
  enquiry_student_list: {
    view: {
      codenames: [GET_URL.getenquiry.basename],
      action_code: "visible_enquiry_student_list_view",
      is_superuser_action: false,
      name: "View Enquiry Student List",
      label: "Enquiry Form",
      action: "sub-menu",
      url: "/studentdetails/enquiry/list",
      component: <EnquiryStudentsList />,
      permission_needed: true,
      associated_urls: [
        "/studentdetails/enquiry/add",
        "/studentdetails/enquiry/edit",
        "/studentdetails/enquiry/view",
      ],
    },
    create: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        POST_URL.enquiry.basename,
        GET_URL.customform.basename,
      ],
      action_code: "visible_enquiry_student_list_add",
      is_superuser_action: false,
      name: "Create Enquiry Student List",
      label: "Enquiry Form",
      action: "action-url",
      url: "/studentdetails/enquiry/add",
      component: <EnquiryForm />,
      permission_needed: true,
    },
    update: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        GET_URL.getenquiry.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        PUT_URL.enquiry.basename,
        GET_URL.customform.basename,
      ],
      action_code: "visible_enquiry_student_list_change",
      is_superuser_action: false,
      name: "Update Enquiry Student List",
      label: "Edit",
      action: "action-url",
      url: "/studentdetails/enquiry/edit",
      component: <EnquiryForm />,
      permission_needed: true,
    },
    delete: {
      codenames: [DEL_URL.enquiry.basename],
      action_code: "visible_enquiry_student_list_delete",
      is_superuser_action: false,
      name: "Delete Enquiry Student List",
      label: "Delete",
      action: "action",
      permission_needed: true,
    },
    name: "Enquiry Form",
    type: "student_forms",
  },
  enquiry_student: {
    view: {
      codenames: [GET_URL.getenquiry.basename, GET_URL.customform.basename],
      action_code: "visible_enquiry_student_view",
      is_superuser_action: false,
      name: "View Enquiry Student List",
      label: "view",
      action: "action-url",
      url: "/studentdetails/enquiry/view",
      component: <EnqueryView />,
      permission_needed: true,
    },
    name: "Enquiry Student",
    type: "student_forms",
  },
  application_student_list: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.application.basename,
        GET_URL.applicationFeesReceipt.basename,
        GET_URL.getstandard.basename,
      ],
      action_code: "visible_application_student_list_view",
      is_superuser_action: false,
      name: "View Application Student List",
      label: "Application Form",
      action: "sub-menu",
      url: "/studentdetails/application/list",
      component: <ApplicationStudentList />,
      permission_needed: true,
      is_depend_on_setting: true,
      setting: [{ name: "is_application", value: ["1"] }],
      associated_urls: [
        "/studentdetails/application/add",
        "/studentdetails/application/edit",
        "/studentdetails/application/view",
      ],
    },
    create: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        GET_URL.getenquiryforapplication.basename,
        GET_URL.applicationFeesPlan.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        POST_URL.enquiry.basename,
        POST_URL.application.basename,
        POST_URL.uploads.basename,
        GET_URL.applicationFeesReceipt.basename,
        GET_URL.nationality.basename,
        GET_URL.religion.basename,
        GET_URL.category.basename,
        GET_URL.customform.basename,
        GET_URL.documenttype.basename,
      ],
      action_code: "visible_application_student_list_add",
      is_superuser_action: false,
      name: "Create Application Student List",
      label: "Application Form",
      action: "action-url",
      url: "/studentdetails/application/add",
      component: <ApplicationForm />,
      permission_needed: true,
    },
    update: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        GET_URL.getapplication.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        PUT_URL.application.basename,
        POST_URL.uploads.basename,
        GET_URL.nationality.basename,
        GET_URL.religion.basename,
        GET_URL.category.basename,
        GET_URL.caste.basename,
        GET_URL.customform.basename,
        GET_URL.documenttype.basename,
      ],
      action_code: "visible_application_student_list_change",
      is_superuser_action: false,
      name: "Update Application Student List",
      label: "Edit",
      action: "action-url",
      url: "/studentdetails/application/edit",
      component: <ApplicationForm />,
      permission_needed: true,
    },
    delete: {
      codenames: [DEL_URL.application.basename],
      action_code: "visible_application_student_list_delete",
      is_superuser_action: false,
      name: "Delete Application Student List",
      label: "Delete",
      action: "action",
      permission_needed: true,
    },
    name: "Application Form",
    type: "student_forms",
  },
  application_student: {
    view: {
      codenames: [GET_URL.getapplication.basename, GET_URL.customform.basename],
      action_code: "visible_application_student_view",
      is_superuser_action: false,
      name: "Student complete Details",
      label: "View",
      action: "action-url",
      url: "/studentdetails/application/view",
      component: <ApplicationView />,
      permission_needed: true,
    },
    name: "Application Student",
    type: "student_forms",
  },
  admission_student_list: {
    view: {
      codenames: [
        GET_URL.student.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.getstudentgroups.basename
      ],
      action_code: "visible_admission_student_list_view",
      is_superuser_action: false,
      name: "View Admission Student List",
      label: "Admission Form",
      action: "sub-menu",
      url: "/studentdetails/admission/list",
      component: <AdmissionStudentList />,
      permission_needed: true,
      associated_urls: [
        "/studentdetails/admission/add",
        "/studentdetails/admission/edit",
        "/studentdetails/admission/view",
      ],
    },
    create: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        POST_URL.checkusernamenotexist.basename,
        GET_URL.getapplicationforadmission.basename,
        GET_URL.singlefeeplan.basename,
        GET_URL.feature.basename,
        GET_URL.getAssignSubject.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        POST_URL.studentall.basename,
        POST_URL.uploads.basename,
        GET_URL.nationality.basename,
        GET_URL.religion.basename,
        GET_URL.category.basename,
        GET_URL.customform.basename,
        GET_URL.documenttype.basename,
        GET_URL.getstandard.basename,
        GET_URL.student.basename,
        GET_URL.getstudentgroups.basename
      ],
      action_code: "visible_admission_student_list_add",
      is_superuser_action: false,
      name: "Create Admission Student List",
      label: "Admission Form",
      action: "action-url",
      url: "/studentdetails/admission/add",
      component: <AdmissionForm />,
      permission_needed: true,
    },
    update: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        GET_URL.getallstudents.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        PUT_URL.studentall.basename,
        POST_URL.uploads.basename,
        GET_URL.nationality.basename,
        GET_URL.religion.basename,
        GET_URL.category.basename,
        GET_URL.caste.basename,
        GET_URL.customform.basename,
        GET_URL.documenttype.basename,
        GET_URL.getstandard.basename,
        GET_URL.student.basename,
        GET_URL.getstudentgroups.basename
      ],
      action_code: "visible_admission_student_list_change",
      is_superuser_action: false,
      name: "Update Admission Student List",
      label: "Edit",
      action: "action-url",
      url: "/studentdetails/admission/edit",
      component: <AdmissionForm />,
      permission_needed: true,
    },
    delete: {
      codenames: [DEL_URL.studentall.basename],
      action_code: "visible_admission_student_list_delete",
      is_superuser_action: false,
      name: "Delete Admission Student List",
      label: "Delete",
      action: "action",
      permission_needed: true,
    },
    name: "Admission Student List",
    type: "student_forms",
  },
  admission_student: {
    view: {
      codenames: [
        GET_URL.getallstudents.basename,
        GET_URL.getstandard.basename,
        GET_URL.customform.basename,
      ],
      action_code: "visible_admission_student_view",
      is_superuser_action: false,
      name: "View Admission Student",
      label: "View",
      action: "action-url",
      url: "/studentdetails/admission/view",
      component: <AdmissionView />,
      permission_needed: true,
    },
    name: "Admission Student",
    type: "student_forms",
  },
  general_student_list: {
    view: {
      codenames: [
        GET_URL.student.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.getstudentgroups.basename,
      ],
      action_code: "visible_general_student_list_view",
      is_superuser_action: false,
      name: "View Student List",
      label: "Student List",
      action: "sub-menu",
      url: "/student/list",
      component: <StudentList />,
      permission_needed: true,
      associated_urls: ["/student/edit", "/student/view", "/student/fee/view"],
    },
    update: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandard.basename,
        GET_URL.country.basename,
        GET_URL.getallstudents.basename,
        GET_URL.getstatesforcountry.basename,
        GET_URL.getdistrictsforstate.basename,
        GET_URL.getcitiesfordistrict.basename,
        PUT_URL.studentall.basename,
        POST_URL.uploads.basename,
        GET_URL.nationality.basename,
        GET_URL.religion.basename,
        GET_URL.category.basename,
        GET_URL.caste.basename,
        GET_URL.customform.basename,
        GET_URL.documenttype.basename,
        GET_URL.getstandard.basename,
        GET_URL.student.basename,
        GET_URL.getstudentgroups.basename
      ],
      action_code: "visible_general_student_list_change",
      is_superuser_action: false,
      name: "Update Student List",
      label: "Edit",
      action: "action-url",
      url: "/student/edit",
      component: <StudentForm />,
      permission_needed: true,
    },
    delete: {
      codenames: [DEL_URL.studentall.basename],
      action_code: "visible_general_student_list_delete",
      is_superuser_action: false,
      name: "Delete Student List",
      label: "Delete",
      action: "action",
      permission_needed: true,
    },
    name: "Student List",
    type: "student_forms",
  },
  general_student: {
    view: {
      codenames: [GET_URL.getallstudents.basename, GET_URL.customform.basename],
      action_code: "visible_general_student_view",
      is_superuser_action: false,
      name: "View  Student",
      label: "View",
      action: "action-url",
      url: "/student/view",
      component: <StudentView />,
      permission_needed: true,
    },
    name: " Student Complete Details",
    type: "student_forms",
  },
  student_type_switch: {
    view: {
      codenames: [GET_URL.student.basename, GET_URL.getstandard.basename],
      action_code: "visible_student_type_switch_view",
      is_superuser_action: false,
      name: "View Student Type Switch List",
      label: "Student Type Switch List",
      action: "sub-menu",
      url: "/student/switch/list",
      component: <StudentTypeSwitch />,
      permission_needed: true,
      is_depend_on_setting: true,
      setting: [{ name: "is_residential", value: ["1"] }],
      associated_urls: ["/student/switch/view"],
    },
    name: "Student Type Switch List",
    type: "student_forms",
  },
  student_type_switch_individual: {
    view: {
      codenames: [
        GET_URL.studenttype.basename,
        POST_URL.studenttype.basename,
        PUT_URL.studenttype.basename,
      ],
      action_code: "visible_student_type_switch_individual_view",
      is_superuser_action: false,
      name: "View Individual Student Switch Detail",
      label: "View",
      action: "action-url",
      url: "/student/switch/view",
      component: <StudentTypeSwitchIndividual />,
      permission_needed: true,
    },
    update: {
      codenames: [POST_URL.studenttype.basename, PUT_URL.studenttype.basename],
      action_code: "visible_student_type_switch_individual_change",
      is_superuser_action: false,
      name: "Update Individual Student Switch Detail",
      label: "Edit",
      action: "action",
      component: <StudentTypeSwitchIndividual />,
      permission_needed: true,
    },
    name: "Student Type Switch Individual Detail",
    type: "student_forms",
  },
  fee_collection_student: {
    view: {
      codenames: [
        GET_URL.feecollection.basename,
        GET_URL.payment.basename,
        GET_URL.feeplan.basename,
        POST_URL.getfeelistforstudent.basename,
        DEL_URL.feecollection.basename,
        PUT_URL.feecollection.basename,
      ],
      action_code: "visible_fee_collection_student_view",
      is_superuser_action: false,
      name: "View  Student",
      label: "View",
      action: "action-url",
      url: "/student/fee/view",
      component: <StudentView />,
      permission_needed: true,
    },
    name: "Fee Summary",
    type: "student_forms",
  },
  fee_history_student: {
    view: {
      codenames: [
        GET_URL.feeplan.basename,
        POST_URL.getfeelistforstudent.basename,
      ],
      action_code: "visible_fee_history_student_view",
      is_superuser_action: false,
      name: "View  Student",
      label: "View",
      action: "action-url",
      url: "/student/fee/history/view",
      component: <StudentView />,
      permission_needed: true,
    },
    name: "Fee History",
    type: "student_forms",
  },
  custom_report_download: {
    view: {
      codenames: [POST_URL.studentreport.basename],
      action_code: "visible_custom_report_download_view",
      is_superuser_action: false,
      name: "Custom Download Report",
      label: "Custom Download Report",
      action: "action",
      permission_needed: true,
    },
    name: "Download Custom Report",
    type: "student_forms",
  },
  student_bulk_update: {
    view: {
      codenames: [],
      action_code: "visible_student_bulk_update_view",
      is_superuser_action: false,
      name: "View Individual Student Switch Detail",
      label: "Student Bulk List",
      action: "sub-menu",
      url: "/student/bulk/list",
      component: <StudentBulkUpdateList />,
      associated_urls: ["/student/bulk/update"],
      permission_needed: true,
    },
    update: {
      codenames: [],
      action_code: "visible_student_bulk_update_change",
      is_superuser_action: false,
      name: "Update Individual Student Switch Detail",
      label: "Modify Bulk Student",
      action: "action-url",
      url: "/student/bulk/update",
      component: <StudentBulkUpdate />,
      permission_needed: true,
    },
    name: "Student Bulk Update",
    type: "student_forms",
  },
};

export default Actions;
