import React from "react";
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from "Includes/urls";
import StudentAttendanceRegister from "Containers/StudentAttendance/StudentAttendanceRegister";
import StudentAttendance from "Containers/StudentAttendance/StudentAttendance";
import StudentAttendanceReport from "Containers/StudentAttendance/StudentAttendanceReport";
import StudentRfidAttendanceReport from "Containers/StudentAttendance/StudentRfidAttendanceReport";
import StudentIndividualRFIDReport from "Containers/StudentAttendance/StudentIndividualRFIDReport";
import StudentRfidList from "Containers/Enrolement/StudentRfidList";
import StudentRfidAdd from "Containers/Enrolement/StudentRfidAdd";
import StudentRfidAttendanceReportAdd from "Containers/StudentAttendance/StudentRfidAttendanceReportAdd";
import StandardSectionSummaryReport from "Containers/StudentAttendance/StandardSectionSummaryReport";
import ViewAttendanceBatch from "Containers/StudentAttendance/ViewAttendanceBatch";
import AddAttendanceBatch from "Containers/StudentAttendance/AddAttendanceBatch";
import AttendanceBatchStudent from "Containers/StudentAttendance/AttendanceBatchStudent";
import StudentBatchAttendanceRegister from "Containers/StudentAttendance/StudentBatchAttendanceRegister";
import StaffTimebaleAttendanceReport from "Containers/StudentAttendance/StaffTimebaleAttendanceReport";
import StudentBatchAttendance from "Containers/StudentAttendance/StudentBatchAttendance";
import UpdateSubjectAttendance from "Containers/StudentAttendance/UpdateSubjectAttendance";

const Actions = {
  studentattendance_register: {
    view: {
      codenames: [GET_URL.attendancedetail.basename],
      action_code: "visible_studentattendance_register_view",
      is_superuser_action: false,
      name: "Attendance Register", 
      label: "Attendance Register",
      action: "sub-menu",
      url: "/studentattendance/manageattendance",
      component: <StudentAttendanceRegister />,
      permission_needed: true,
      exclude_roles: [7],
      associated_urls: ["/studentattendance/markattendance"],
    },
    name: "Attendance Register",
    type: "student attendance",
  },

  studentattendance_attendance: {
    view: {
      codenames: [
        GET_URL.attendance.basename,
        GET_URL.getenrolledstudents.basename,
      ],
      action_code: "visible_studentattendance_attendance_view",
      is_superuser_action: false,
      name: "Attendance Register",
      label: "Attendance Register",
      action: "action-url",
      url: "/studentattendance/markattendance",
      component: <StudentAttendance />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [POST_URL.attendance.basename],
      action_code: "visible_studentattendance_attendance_add",
      is_superuser_action: false,
      name: "Mark Attendance",
      label: "Attendance Register",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    update: {
      codenames: [PUT_URL.attendance.basename],
      action_code: "visible_studentattendance_attendance_change",
      is_superuser_action: false,
      name: "Edit Attendance",
      label: "Edit Attendance",
      action: "action",
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Attendance Entry",
    type: "student attendance",
  },

  stafftimetableattendance_report: {
    view: {
      codenames: [
        GET_URL.stafftimetableattendance.basename,
        GET_URL.staff.basename,
        GET_URL.getacademicyear.basename,
        GET_URL.getstandardandsection.basename,
        GET_URL.subject.basename,
      ],
      action_code: "visible_stafftimetableattendance_report_view",
      is_superuser_action: false,
      name: "Staff Timetable Attendance Report",
      label: "Staff Timetable Attendance Report",
      action: "sub-menu",
      url: "/stafftimetableattendance/attendancereport",
      component: <StaffTimebaleAttendanceReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Staff Timetable Attendance Report",
    type: "stafftimetable attendance",
  },

  studentattendance_report: {
    view: {
      codenames: [
        GET_URL.attendancedetail.basename,
        GET_URL.attendance.basename,
      ],
      action_code: "visible_studentattendance_report_view",
      is_superuser_action: false,
      name: "Attendance Report",
      label: "Attendance Report",
      action: "sub-menu",
      url: "/studentattendance/attendancereport",
      component: <StudentAttendanceReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Attendance Report",
    type: "student attendance",
  },
  student_rfid_list: {
    view: {
      codenames: [
        GET_URL.getacademicyear.basename,
        GET_URL.getstandardandsection.basename,
        GET_URL.getenrolledstudents.basename,
        POST_URL.studentrfidregister.basename,
      ],
      action_code: "visible_student_rfid_list_view",
      is_superuser_action: false,
      name: "RFID Students",
      label: "RFID Students",
      action: "sub-menu",
      url: "/enrollment/student/rfid/list",
      component: <StudentRfidList />,
      permission_needed: true,
      associated_urls: ["/enrollment/student/rfid/add"],
    },
    create: {
      codenames: [
        GET_URL.getenrolledstudents.basename,
        POST_URL.studentrfidregister.basename,
      ],
      action_code: "visible_student_rfid_list_add",
      is_superuser_action: false,
      name: "RFID Students",
      label: "Change RFID No.",
      action: "action-url",
      url: "/enrollment/student/rfid/add",
      component: <StudentRfidAdd />,
      permission_needed: true,
    },
    update: {
      codenames: [POST_URL.studentrfidregister.basename],
      action_code: "visible_student_rfid_list_change",
      is_superuser_action: false,
      name: "RFID Students",
      label: "Change RFID No.",
      action: "action",
      permission_needed: true,
    },
    name: "Student RFID List",
    type: "Classes",
  },
  student_rfid_attendance_report: {
    view: {
      codenames: [
        GET_URL.attendancedetail.basename,
        GET_URL.studentrfidattendancereport.basename,
      ],
      action_code: "visible_student_rfid_attendance_report_view",
      is_superuser_action: false,
      name: "RFID Attendance Report",
      label: "RFID Attendance Report",
      action: "sub-menu",
      url: "/student/rfid/attendance/report",
      component: <StudentRfidAttendanceReport />,
      associated_urls: ["/student/rfid/attendance/history"],
      permission_needed: true,
      exclude_roles: [7],
    }, 
    create: {
      codenames: [
        GET_URL.getenrolledstudents.basename,
        POST_URL.studentrfidregister.basename,
      ],
      action_code: "visible_student_rfid_attendance_report_add",
      is_superuser_action: false,
      name: "RFID Attendance Update",
      label: "Update Attendance",
      action: "action-url",
      url: "/student/rfid/attendance/report/add",
      component: <StudentRfidAttendanceReportAdd />,
      permission_needed: true,
    },
    name: "RFID Attendance Report",
    type: "student attendance",
  },
  student_rfid_attendance_history: {
    view: {
      codenames: [
        GET_URL.attendancedetail.basename,
        GET_URL.studentrfidattendancereport.basename,
      ],
      action_code: "visible_student_rfid_attendance_history_view",
      is_superuser_action: false,
      name: "Attendance History",
      label: "Attendance History",
      action: "action-url",
      url: "/student/rfid/attendance/history",
      component: <StudentIndividualRFIDReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    create: {
      codenames: [],
      action_code: "visible_student_rfid_attendance_history_add",
      is_superuser_action: false,
      name: "Update Attendance",
      label: "Update Attendance",
      action: "action",
      permission_needed: true,
    },
    name: "RFID Attendance Detailed",
    type: "student attendance",
  },
  standard_section_summary_report: {
    view: {
      codenames: [GET_URL.attendancedetail.basename],
      action_code: "visible_standard_section_summary_report_view",
      is_superuser_action: false,
      name: "Section Summary Report",
      label: "Section Summary Report",
      action: "sub-menu",
      url: "/studentattendance/section-summary",
      component: <StandardSectionSummaryReport />,
      permission_needed: true,
      exclude_roles: [7],
    },
    name: "Section Summary Report",
    type: "student attendance",
  },
  attendance_batch: {
    view: {
        codenames: [GET_URL.attendancebatch.basename,
          GET_URL.getacademicyear.api,
          PUT_URL.attendancebatch.api,
          DEL_URL.attendancebatch.api
        ],
        action_code: 'visible_attendance_batch_view',
        is_superuser_action: false,
        name: 'Attendance Batch',
        label: 'Attendance Batch',
        action: 'sub-menu',
        url: '/attendancebatch/view',
        old_url: '/attendancebatch/view',
        component: <ViewAttendanceBatch />,
        permission_needed: true,
        exclude_roles:[7],
        associated_urls: ['/attendancebatch/add']
    },
    create: {
        codenames: [POST_URL.attendancebatch.basename],
        action_code: 'visible_attendance_batch_add',
        is_superuser_action: false,
        name: 'Add Attendance Batch',
        label: 'Attendance Batch',
        action: 'action-url',
        url: '/attendancebatch/add',
        old_url: '/attendancebatch/add',
        component: <AddAttendanceBatch />,
        permission_needed: true,
        exclude_roles:[7],
    },
    delete: {
        codenames: [DEL_URL.attendancebatch.basename],
        action_code: 'visible_attendance_batch_delete',
        is_superuser_action: false,
        name: 'Delete Attendance Batch',
        label: 'Delete Attendance Batch',
        action: 'action',
        permission_needed: true,
        exclude_roles:[7],

    },
    update: {
        codenames: [PUT_URL.attendancebatch.basename],
        action_code: 'visible_attendance_batch_change',
        is_superuser_action: false,
        name: 'Update Attendance Batch',
        label: 'Update Attendance Batch',
        action: 'action-url',
        component: <AddAttendanceBatch />,
        url: '/attendancebatch/edit',
        old_url: '/attendancebatch/edit',
        permission_needed: true,
        exclude_roles:[7],
    },
    name: 'Attendance Batch',
    type: 'Attendance Batch',
    old_code: 'attendance_batch'
},
attendancebatch_student: {
  create: {
    codenames: [
      GET_URL.getacademicyear.basename,
      GET_URL.getstandard.basename,
      GET_URL.getbatchstudents.basename,
      GET_URL.getstudentsforbatch.basename,
      POST_URL.attendancebatchstudentmapping.basename,
    ],
    action_code: "visible_attendancebatch_student_add",
    is_superuser_action: false,
    name: "Assign Student to Attendance Batch",
    label: "Assign Student to Attendance Batch",
    action: "sub-menu",
    url: "/attendancebatchstudentmapping/add",
    component: < AttendanceBatchStudent />,
    permission_needed: true,
    exclude_roles: [7],
  },
  name: "Batch Student Mapping",
  type: "Attendance Batch",
},
studentbatchattendance: {
  view: {
    codenames: [GET_URL.batchattendancedetail.basename],
    action_code: "visible_studentbatchattendance_view",
    is_superuser_action: false,
    name: "Batch Attendance Register", 
    label: "Batch Attendance Register",
    action: "sub-menu",
    url: "/studentbatchattendance/manageattendance",
    component: <StudentBatchAttendanceRegister />,
    permission_needed: true,
    exclude_roles: [7],
    associated_urls: ["/studentbatchattendance/markattendance"],
  },
  name: "Batch Attendance Register",
  type: "Attendance Batch",
},
studentbatchattendance_attendance: {
  view: {
    codenames: [
      GET_URL.batchattendance.basename,
      GET_URL.getbatchstudents.basename,
    ],
    action_code: "visible_studentbatchattendance_attendance_view",
    is_superuser_action: false,
    name: "Attendance Register",
    label: "Attendance Register",
    action: "action-url",
    url: "/studentbatchattendance/markattendance",
    component: <StudentBatchAttendance />,
    permission_needed: true,
    exclude_roles: [7],
  },
  create: {
    codenames: [POST_URL.batchattendance.basename],
    action_code: "visible_studentbatchattendance_attendance_add",
    is_superuser_action: false,
    name: "Mark Attendance",
    label: "Attendance Register",
    action: "action",
    permission_needed: true,
    exclude_roles: [7],
  },
  update: {
    codenames: [PUT_URL.batchattendance.basename],
    action_code: "visible_studentbatchattendance_attendance_change",
    is_superuser_action: false,
    name: "Edit Attendance",
    label: "Edit Attendance",
    action: "action",
    permission_needed: true,
    exclude_roles: [7],
  },
  name: "Attendance Entry",
  type: "Attendance Batch",
},
update_subject_attendance: {
  view: {
    codenames: [
      GET_URL.subjectattendance.basename,
      GET_URL.getenrolledstudents.basename,
      GET_URL.getAssignSubject.basename,
      GET_URL.subjectattendance.basename,
    ],
    action_code: "visible_update_subject_attendance_view",
    is_superuser_action: false,
    name: "Update Subject Attendance",
    label: "Update Subject Attendance",
    action: "sub-menu",
    url: "/studentattendance/update-subject-attendance",
    component: <UpdateSubjectAttendance />,
    permission_needed: true,
    exclude_roles: [7],
  },
  update: {
    codenames: [PUT_URL.subjectattendance.basename],
    action_code: "visible_update_subject_attendance_change",
    is_superuser_action: false,
    name: "Update Subject Attendance",
    label: "Update Subject Attendance",
    action: "action",
    permission_needed: true,
    exclude_roles: [7],
  },
  name: "Update Subject Attendance",
  type: "student attendance",
},
};

export default Actions;
