import React from 'react';
import { GET_URL, POST_URL, PUT_URL, DEL_URL } from 'Includes/urls';

import VehicleView from 'Containers/Transport/VehicleView';
import AddVehicle from 'Containers/Transport/AddVehicle';
import AddKilometerPrice from 'Containers/Transport/AddKilometerPrice';
import KilometerPriceViewList from 'Containers/Transport/KilometerPriceViewList';
import AssignVehicleToDriverView from 'Containers/Transport/AssignVehicleToDriverView';
import StudentLocationRegistrationView from 'Containers/Transport/StudentLocationRegistrationView';
import AddRouteArea from 'Containers/Transport/AddRouteArea';
import RouteAreaView from 'Containers/Transport/RouteAreaView';
import AddStudentLocationRegistration from 'Containers/Transport/AddStudentLocationRegistration';
import AddPricePlan from 'Containers/Transport/KmPricePlan/AddPricePlan';
import PricePlanView from 'Containers/Transport/KmPricePlan/PricePlanView';
import AddDepartment from 'Containers/Transport/AddDepartment';
import ViewDepartment from 'Containers/Transport/ViewDepartment';
import GoogleRoutePlanList from 'Containers/Transport/GoogleRoutePlanList';
import GoogleRoutePlan from 'Containers/Transport/GoogleRoutePlan';
import ViewGpsMachine from 'Containers/Transport/ViewGpsMachine';
import AddGpsMachine from 'Containers/Transport/AddGpsMachine';
import ViewMap from 'Containers/Transport/ViewMap';

const Actions = {
    transport_vehicle: {
        create: {
            codenames: [POST_URL.vehicle.basename, GET_URL.vehicle.basename],
            action_code: 'visible_transport_vehicle_add',
            is_superuser_action: false,
            name: 'Add Vehicle',
            label: 'Vehicle',
            action: 'action-url',
            url: '/transport/vehicle/add',
            component: <AddVehicle />,
            permission_needed: true,
        },
        view: {
            codenames: [GET_URL.vehicle.basename],
            action_code: 'visible_transport_vehicle_view',
            is_superuser_action: false,
            name: 'Vehicles',
            label: 'Vehicles',
            action: 'sub-menu',
            url: '/transport/vehicle/view',
            component: <VehicleView />,
            permission_needed: true,
            associated_urls: ['/transport/vehicle/add', '/transport/vehicle/edit']
        },
        update: {
            codenames: [PUT_URL.vehicle.basename],
            action_code: 'visible_transport_vehicle_change',
            is_superuser_action: false,
            name: 'Update Vehicle',
            label: 'Edit Vehicle',
            action: 'action-url',
            url: '/transport/vehicle/edit',
            component: <AddVehicle />,
            permission_needed: true,
        },
        delete: {
            codenames: [GET_URL.vehicle.basename, DEL_URL.vehicle.basename],
            action_code: 'visible_transport_vehicle_delete',
            is_superuser_action: false,
            name: 'Delete Vehcile',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
        },
        name: 'Vehicles',
        type: 'transport',
    },
    transport_price: {
        create: {
            codenames: [GET_URL.routePrice.basename, POST_URL.routePrice.basename, GET_URL.area.basename],
            action_code: 'visible_transport_price_add',
            is_superuser_action: false,
            name: 'Add Price',
            label: 'Add Price',
            action: 'action-url',
            url: '/transport/kmprices/add',
            component: <AddKilometerPrice />,
            permission_needed: true
        },
        update: {
            codenames: [PUT_URL.routePrice.basename],
            action_code: 'visible_transport_price_change',
            is_superuser_action: false,
            name: 'Update Price',
            label: 'Update Price',
            action: 'action-url',
            url: '/transport/kmprices/edit',
            component: <AddKilometerPrice />,
            permission_needed: true
        },
        delete: {
            codenames: [DEL_URL.routePrice.basename],
            action_code: 'visible_transport_price_delete',
            is_superuser_action: false,
            name: 'Delete Price',
            label: 'Delete Price',
            action: 'action',
            permission_needed: true
        },
        view: {
            codenames: [GET_URL.routepriceplan.basename, GET_URL.getacademicyear.basename, GET_URL.routePrice.basename],
            action_code: 'visible_transport_price_view',
            is_superuser_action: false,
            name: 'KM prices',
            label: 'KM prices',
            action: 'sub-menu',
            url: '/transport/kmprices',
            component: <KilometerPriceViewList />,
            permission_needed: true,
            associated_urls: ['/transport/kmprices/add', '/transport/kmprices/edit']
        },
        name: 'Transport Km Price',
        type: 'transport',
    },
    transport_assign_vehicle_driver: {
        view: {
            codenames: [GET_URL.transportdriver.basename, GET_URL.vehicle.basename],
            action_code: 'visible_transport_assign_vehicle_driver_view',
            is_superuser_action: false,
            name: 'Assign Driver to Vehicle',
            label: 'Assign Driver to Vehicle',
            action: 'sub-menu',
            url: '/transport/assignvehicletodriver/view',
            component: <AssignVehicleToDriverView />,
            permission_needed: true,
        },
        update: {
            codenames: [GET_URL.transportdriver.basename, GET_URL.vehicle.basename, POST_URL.vehicledriver.basename],
            action_code: 'visible_transport_assign_vehicle_driver_change',
            is_superuser_action: false,
            name: 'Assign Driver to Vehicle',
            label: 'Assign Driver to Vehicle',
            action: 'action',
            permission_needed: true,
        },
        name: 'Assign Driver to Vehicle',
        type: 'transport',
    },
    transport_student_address_registration: {
        view: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.routeuseraddress.basename],
            action_code: 'visible_transport_student_address_registration_view',
            is_superuser_action: false,
            name: 'Student Address Registration',
            label: 'Student Address Registration',
            action: 'sub-menu',
            url: '/transport/studentlocation/view',
            component: <StudentLocationRegistrationView />,
            permission_needed: true,
            associated_urls: ['/transport/studentlocation/add', '/transport/studentlocation/edit']
        },
        create: {
            codenames: [
                GET_URL.area.basename, GET_URL.instituteaddress.basename, POST_URL.routeuseraddress.basename
            ],
            action_code: 'visible_transport_student_address_registration_add',
            is_superuser_action: false,
            name: 'Student Address Registration',
            label: 'Add Student Address',
            action: 'action-url',
            url: '/transport/studentlocation/add',
            component: <AddStudentLocationRegistration />,
            permission_needed: true,
        },
        update: {
            codenames: [
                GET_URL.area.basename, GET_URL.instituteaddress.basename, POST_URL.routeuseraddress.basename
            ],
            action_code: 'visible_transport_student_address_registration_change',
            is_superuser_action: false,
            name: 'Edit Student Address',
            label: 'Edit Student Address',
            action: 'action-url',
            url: '/transport/studentlocation/edit',
            component: <AddStudentLocationRegistration />,
            permission_needed: true,
        },
        name: 'Student Address Registration',
        type: 'transport',
    },
    transport_place_name: {
        create: {
            codenames: [GET_URL.area.basename, GET_URL.instituteaddress.basename, POST_URL.area.basename],
            action_code: 'visible_transport_place_name_add',
            is_superuser_action: false,
            name: 'Add Area Name',
            label: 'Area',
            action: 'action-url',
            url: '/transport/route-areas/add',
            component: <AddRouteArea />,
            permission_needed: true
        },
        view: {
            codenames: [GET_URL.instituteaddress.basename, GET_URL.area.basename, DEL_URL.area.basename],
            action_code: 'visible_transport_place_name_view',
            is_superuser_action: false,
            name: 'Areas',
            label: 'Areas',
            action: 'sub-menu',
            url: '/transport/route-areas/',
            component: <RouteAreaView />,
            permission_needed: true,
            associated_urls: ['/transport/route-areas/add', '/transport/route-areas/edit']
        },
        update: {
            codenames: [GET_URL.area.basename, GET_URL.instituteaddress.basename, POST_URL.area.basename],
            action_code: 'visible_transport_place_name_change',
            is_superuser_action: false,
            name: 'update  areas',
            label: 'update  areas',
            action: 'action-url',
            url: '/transport/route-areas/edit',
            component: <AddRouteArea />,
            permission_needed: true,
        },
        delete: {
            codenames: [DEL_URL.area.basename],
            action_code: 'visible_transport_place_name_delete',
            is_superuser_action: false,
            name: 'Delete  areas',
            label: 'delete  areas',
            action: 'action',
            permission_needed: true,
        },
        name: 'Area Names',
        type: 'transport',
    },
    transport_route_map_view: {
        view: {
            codenames: [GET_URL.vehicledriver.basename, GET_URL.route.basename, GET_URL.routeuseraddress.basename,
                 GET_URL.area.basename],
            action_code: 'visible_transport_route_map_view_view',
            is_superuser_action: false,
            name: 'Route Planning',
            label: 'Route Planning',
            action: 'action-url',
            url: '/transport/routeplanning/view',
            component: <GoogleRoutePlan />,
            permission_needed: true,
        },
        name: 'Route Planning Details',
        type: 'transport',
    },
    transport_route_map: {
        view: {
            codenames: [GET_URL.getacademicyear.basename,GET_URL.instituteaddress.basename, GET_URL.route.basename],
            action_code: 'visible_transport_route_map_view',
            is_superuser_action: false,
            name: 'Route Planning',
            label: 'Route Planning',
            action: 'sub-menu',
            url: '/transport/google/routeplanning/list',
            component: <GoogleRoutePlanList />,
            associated_urls: ['/transport/google/routeplanning/add', '/transport/google/routeplanning/edit'],
            permission_needed: true,
        },
        create: {
            codenames: [GET_URL.vehicledriver.basename, GET_URL.route.basename, GET_URL.routeuseraddress.basename,
                GET_URL.area.basename, POST_URL.route.basename],
            action_code: 'visible_transport_route_map_add',
            is_superuser_action: false,
            name: 'Route Planning',
            label: 'Route Planning',
            action: 'action-url',
            url: '/transport/google/routeplanning/add',
            component: <GoogleRoutePlan />,
            permission_needed: true,
        },
        update: {
            codenames: [GET_URL.vehicledriver.basename, GET_URL.route.basename, GET_URL.routeuseraddress.basename,
                GET_URL.area.basename, POST_URL.route.basename],
            action_code: 'visible_transport_route_map_change',
            is_superuser_action: false,
            name: 'Edit Route Planning',
            label: 'Edit Route Planning',
            action: 'action-url',
            url: '/transport/google/routeplanning/edit',
            component: <GoogleRoutePlan />,
            permission_needed: true,
        },
        delete: {
            codenames: [DEL_URL.route.basename],
            action_code: 'visible_transport_route_map_delete',
            is_superuser_action: false,
            name: 'Delete',
            label: '',
            action: 'action-url',
            permission_needed: true,
        },
        name: 'Route Planning',
        type: 'transport',
    },
    transport_priceplan: {
        view: {
            codenames: [GET_URL.getacademicyear.basename, GET_URL.routepriceplan.basename, PUT_URL.routepriceplanapprove.basename],
            action_code: 'visible_transport_priceplan_view',
            is_superuser_action: false,
            name: 'Km Price Plan',
            label: 'Km Price Plan',
            action: 'sub-menu',
            url: '/transport/priceplan',
            component: <PricePlanView />,
            permission_needed: true,
            associated_urls: ['/transport/priceplan/add', '/transport/priceplan/edit']
        },
        create: {
            codenames: [GET_URL.getstandard.basename, POST_URL.routepriceplan.basename],
            action_code: 'visible_transport_priceplan_add',
            is_superuser_action: false,
            name: 'Add Price Plan',
            label: 'Add Price Plan',
            action: 'action-url',
            url: '/transport/priceplan/add',
            component: <AddPricePlan />,
            permission_needed: true,
        },
        update: {
            codenames: [GET_URL.getstandard.basename, PUT_URL.routepriceplan.basename],
            action_code: 'visible_transport_priceplan_change',
            is_superuser_action: false,
            name: 'Update Price Plan',
            label: 'Update Price Plan',
            action: 'action-url',
            url: '/transport/priceplan/edit',
            component: <AddPricePlan />,
            permission_needed: true,
        },
        delete: {
            codenames: [DEL_URL.routepriceplan.basename],
            action_code: 'visible_transport_priceplan_delete',
            is_superuser_action: false,
            name: 'Delete',
            label: '',
            action: 'action',
            permission_needed: true,
        },
        name: 'Km Price Plan',
        type: 'transport',
    },
    transport_department: {
        view: {
            codenames: [GET_URL.department.basename],
            action_code: 'visible_transport_department_view',
            is_superuser_action: false,
            name: 'View Department',
            label: 'Department',
            action: 'sub-menu',
            url: '/transport/department/view',
            component: <ViewDepartment />,
            permission_needed: true,
            associated_urls: ['/transport/department/add'],
        },
        create: {
            codenames: [POST_URL.department.basename],
            action_code: 'visible_transport_department_add',
            is_superuser_action: false,
            name: 'Create Department',
            label: 'Department',
            action: 'action-url',
            url: '/transport/department/add',
            component: <AddDepartment />,
            permission_needed: true,
        },
        update: {
            codenames: [PUT_URL.department.basename],
            action_code: 'visible_transport_department_change',
            is_superuser_action: false,
            name: 'Update Department',
            label: 'Update Department',
            action: 'action-url',
            url: '/expenses/department/edit',
            component: <ViewDepartment />,
            permission_needed: true,

        },
        delete: {
            codenames: [DEL_URL.department.basename],
            action_code: 'visible_transport_department_delete',
            is_superuser_action: false,
            name: 'Delete Department',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
        },
        name: 'Department',
        type: 'transport',
    },
    transport_gps_machine: {
        view: {
            codenames: [GET_URL.gpsmachine.basename],
            action_code: 'visible_transport_gps_machine_view',
            is_superuser_action: false,
            name: 'GPS Machine', 
            label: 'GPS Machine',
            action: 'sub-menu',
            url: '/transport/gpsmachine/view',
            component: <ViewGpsMachine />,
            permission_needed: true,
            associated_urls: ['/transport/gpsmachine/add', '/transport/gpsmachine/edit']
        },
        create: {
            codenames: [POST_URL.gpsmachine.basename, GET_URL.gpsmachine.basename],
            action_code: 'visible_transport_gps_machine_add',
            is_superuser_action: false,
            name: 'GPS Machine',
            label: 'Create GPS Machine',
            action: 'action-url',
            url: '/transport/gpsmachine/add',
            component: <AddGpsMachine/> ,
            permission_needed: true,
        },
        update: {
            codenames: [POST_URL.gpsmachine.basename],
            action_code: 'visible_transport_gps_machine_change',
            is_superuser_action: false,
            name: 'Edit GPS Machine',
            label: 'Edit GPS Machine',
            action: 'action-url',
            url: '/transport/gpsmachine/edit',
            component: <AddGpsMachine />,
            permission_needed: true,
        },
        delete: {
            codenames: [DEL_URL.gpsmachine.basename],
            action_code: 'visible_transport_gps_machine_delete',
            is_superuser_action: false,
            name: 'Delete Gps Machine',
            label: 'Delete',
            action: 'action',
            permission_needed: true,
        },
        name: 'Gps Machine',
        type: 'transport',
    },
    transport_vehicle_sync: {
        create: {
            codenames: [],
            action_code: 'visible_transport_vehicle_sync_add',
            is_superuser_action: false,
            name: 'Vehicle Sync',
            label: 'Vehicle Sync',
            action: 'action',
            permission_needed: true,
        },
        name: 'Vehicle Sync',
        type: 'transport',
    },
    transport_view_map: {
        view: {
            codenames: [],
            action_code: 'visible_transport_view_map_view',
            is_superuser_action: false,
            name: 'View Map',
            label: 'View Map',
            action: 'sub-menu',
            url: '/transport/viewmap',
            component: <ViewMap />,
            permission_needed: true,
        },
        name: 'View Map',
        type: 'transport',
    }
}

export default Actions