# Generated by Django 3.2 on 2022-09-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentdocumentmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardiandetail',
            old_name='annual_income',
            new_name='g_annual_income',
        ),
        migrations.RenameField(
            model_name='parentdetail',
            old_name='parents_annual_income',
            new_name='f_annual_income',
        ),
        migrations.AddField(
            model_name='parentdetail',
            name='m_annual_income',
            field=models.FloatField(null=True),
        ),
    ]
