# Generated by Django 3.2 on 2022-12-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220925_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSiblingMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_ship', models.CharField(blank=True, choices=[('elderbrother', 'Elder Brother'), ('eldersister', 'Elder Sister'), ('youngerbrother', 'Younger Brother'), ('youngersister', 'Younger Sister'), ('twins', 'Twins')], max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sibling_mapping_student', to='students.student')),
                ('student_parent_tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_sibling_mapping_student_parent_tree', to='students.student')),
            ],
        ),
    ]
