# Generated by Django 3.2 on 2023-01-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentsiblingmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsiblingmapping',
            name='relation_ship',
        ),
    ]
