# Generated by Django 3.2 on 2023-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentsiblingmapping_relation_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_new_student',
            field=models.BooleanField(default=False),
        ),
    ]
