# Generated by Django 3.2 on 2023-11-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_auto_20230916_1552'),
        ('students', '0007_auto_20230415_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiandetail',
            name='g_profile_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile_pic', to='shared.document'),
        ),
        migrations.AddField(
            model_name='parentdetail',
            name='f_profile_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_profile_pic', to='shared.document'),
        ),
        migrations.AddField(
            model_name='parentdetail',
            name='m_profile_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_profile_pic', to='shared.document'),
        ),
    ]
