# Generated by Django 3.2 on 2024-07-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20240318_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousSchoolDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_left_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_school_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_tc_issued_date', models.DateField(blank=True, null=True)),
                ('pre_school_tc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_working_experiance', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_working_joining_date', models.DateField(blank=True, null=True)),
                ('pre_working_date_of_leaving', models.DateField(blank=True, null=True)),
                ('pre_total_marks', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_secured_marks', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_activities', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_school_date_of_joining', models.DateField(blank=True, null=True)),
                ('pre_school_left_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='previous_school_details_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.previousschooldetails'),
        ),
    ]
