# Generated by Django 3.2 on 2026-03-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0025_auto_20260225_2054'),
        ('shared', '0048_delete_printdocument'),
        ('students', '0010_auto_20240730_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdCardUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('admission_no', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=255, null=True)),
                ('student_class', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, default='Ungrouped', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Photos Taken', max_length=255, null=True)),
                ('print_count', models.IntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_card_update_academic_year', to='institutes.academicyear')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_id_card_update_image', to='shared.document')),
                ('processed_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_id_card_update_processed_image', to='shared.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_card_update_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='IdCardUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_update_academic_year', to='institutes.academicyear')),
            ],
        ),
    ]
