# Generated by Django 3.2 on 2024-12-18 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('classes', '0023_staffstandardsectionmapping_studentleavedates_studentleaves_studentleavetype_studentleavetypeacademi'),
        ('shared', '0040_custom_staff_app_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('folder_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GallerySetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('level', models.IntegerField()),
                ('label_name', models.CharField(max_length=255)),
                ('api_name', models.CharField(max_length=255)),
                ('filters', models.CharField(max_length=255)),
                ('allow_create_folder', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('setup_ref_table_id', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('Folder', 'File')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.gallerytreeitem')),
                ('setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.gallerysetup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryTreeItemUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_mode', models.CharField(choices=[(1, 'read'), (2, 'write'), (3, 'read_write'), (4, 'allpermission')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tree_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_user_permission_tree_item', to='gallery.gallerytreeitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_user_permission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTreeItemStandardSectionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_mode', models.CharField(choices=[(1, 'read'), (2, 'write'), (3, 'read_write'), (4, 'allpermission')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('standard_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_standard_section_permission_standard_section', to='classes.standardsectionmapping')),
                ('tree_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_standard_section_permission_tree_item', to='gallery.gallerytreeitem')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTreeItemStandardPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_mode', models.CharField(choices=[(1, 'read'), (2, 'write'), (3, 'read_write'), (4, 'allpermission')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytree_item_standard_permission_standard', to='classes.standard')),
                ('tree_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_standard_permission_tree_item', to='gallery.gallerytreeitem')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTreeItemGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_mode', models.CharField(choices=[(1, 'read'), (2, 'write'), (3, 'read_write'), (4, 'allpermission')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_user_permission_group', to='auth.group')),
                ('tree_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallerytreeitem_group_permission_tree_item', to='gallery.gallerytreeitem')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('upload_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='galleryfile_upload_file', to='shared.document')),
            ],
        ),
    ]
