# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tutorials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_initial'),
        ('shared', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeitemuserpermission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeitem_user_permission_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treeitemstandardsectionpermission',
            name='standard_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeitem_standard_section_permission_standard_section', to='classes.standardsectionmapping'),
        ),
        migrations.AddField(
            model_name='treeitemstandardsectionpermission',
            name='tree_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeitem_standard_section_permission_tree_item', to='tutorials.treeitem'),
        ),
        migrations.AddField(
            model_name='treeitemstandardpermission',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_item_standard_permission_standard', to='classes.standard'),
        ),
        migrations.AddField(
            model_name='treeitemstandardpermission',
            name='tree_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeitem_standard_permission_tree_item', to='tutorials.treeitem'),
        ),
        migrations.AddField(
            model_name='treeitemgrouppermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeitem_user_permission_group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='treeitemgrouppermission',
            name='tree_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treeitem_group_permission_tree_item', to='tutorials.treeitem'),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('Folder', 'File')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tutorials.treeitem'),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tutorials.tutorialsetup'),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_file', to='shared.document'),
        ),
    ]
