# Generated by Django 3.2 on 2026-03-21 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0033_staffstandardsectionmapping_allocation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('going_with', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('self', 'Self')], max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('expected_return_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('gate_pass_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('requested', 'REQUESTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('exited', 'EXITED'), ('returned', 'RETURNED'), ('expired', 'EXPIRED')], default='requested', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('guard_name', models.CharField(blank=True, max_length=255)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('exit_verified_at', models.DateTimeField(blank=True, help_text='When watchman verified checkout', null=True)),
                ('return_verified_at', models.DateTimeField(blank=True, help_text='When watchman verified return', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approval_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepass_approval_authority', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepasses_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepasses_requested', to=settings.AUTH_USER_MODEL)),
                ('standard_section', models.ForeignKey(blank=True, help_text='Class-Section for students; optional for staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepasses', to='classes.standardsectionmapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Pass',
                'verbose_name_plural': 'Gate Passes',
                'ordering': ['-created'],
            },
        ),
    ]
