# Generated by Django 3.2 on 2022-09-04 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_instituteadresses_default'),
        ('institutes', '0005_auto_20220814_1901'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('object_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('object_model', models.CharField(blank=True, max_length=255, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=255, null=True)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('sim_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('sim_card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('object_category', models.CharField(blank=True, choices=[('Movable', 'Mo,vable'), ('Immovable', 'Immovable')], default=3, max_length=15, null=True)),
                ('object_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('ign', models.CharField(blank=True, max_length=255, null=True)),
                ('pwr', models.CharField(blank=True, max_length=255, null=True)),
                ('gps', models.CharField(blank=True, max_length=255, null=True)),
                ('speed_detection', models.CharField(blank=True, choices=[('FromDevice', 'FromDevice'), ('FromLatLng', 'FromLatLng')], max_length=255, null=True)),
                ('battery', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('gps_installation_date', models.DateField(blank=True, null=True)),
                ('gps_warranty', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDropPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePickupPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteUserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_user_address_academic_year', to='institutes.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='RouteUserAddressHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_data', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_user_area_history_address_academic_year', to='institutes.academicyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_user_area_history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteUserDropMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_from_date', models.DateField(auto_now_add=True)),
                ('drop_to_date', models.DateField(default='9999-12-31')),
                ('drop_route_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_user_drop_mapping_drop_route_plan', to='transport.routedropplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_user_drop_mapping_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteUserPickupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_from_date', models.DateField(auto_now_add=True)),
                ('pickup_to_date', models.DateField(default='9999-12-31')),
                ('pickup_route_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_user_pickup_mapping_pickup_route_plan', to='transport.routepickupplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_user_pickup_mapping_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='routestudentaddress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='routestudentaddress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='routestudentmapping',
            name='route_plan',
        ),
        migrations.RemoveField(
            model_name='routestudentmapping',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ridestatus',
            name='route_plan',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='routearea',
            name='address',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_attendance_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='institute_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_institute_address', to='classes.instituteadresses'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_area_academic_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='address_one',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routearea',
            name='address_two',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routearea',
            name='area_type',
            field=models.CharField(choices=[(1, 'area'), (2, 'student_or_staff_area'), (3, 'group')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='routearea',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='routearea',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='routearea',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='routearea',
            name='institute_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_area_institute_address', to='classes.instituteadresses'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='is_aproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routearea',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[(1, 'pertol'), (2, 'diesel'), (3, 'gas')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicleroutemapping',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[(1, 'pickup'), (2, 'drop'), (3, 'pickupdrop')], default=3, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routearea',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicleroutemapping',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='RoutePlan',
        ),
        migrations.DeleteModel(
            name='RouteStudentAddress',
        ),
        migrations.DeleteModel(
            name='RouteStudentMapping',
        ),
        migrations.AddField(
            model_name='routeuseraddress',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_user_area', to='transport.routearea'),
        ),
        migrations.AddField(
            model_name='routeuseraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_user_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routepickupplan',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_pickup_plan_routearea', to='transport.routearea'),
        ),
        migrations.AddField(
            model_name='routepickupplan',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_pickup_plan_route', to='transport.route'),
        ),
        migrations.AddField(
            model_name='routedropplan',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_drop_plan_routearea', to='transport.routearea'),
        ),
        migrations.AddField(
            model_name='routedropplan',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_drop_plan_route', to='transport.route'),
        ),
        migrations.AddField(
            model_name='ridestatus',
            name='route_drop_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_status_route_drop_plan', to='transport.routedropplan'),
        ),
        migrations.AddField(
            model_name='ridestatus',
            name='route_pickup_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_status_route_pickup_plan', to='transport.routepickupplan'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_gps', to='transport.gpsmachine'),
        ),
    ]
