# Generated by Django 3.2 on 2023-03-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20220904_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsmachine',
            name='last_api_hit_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsmachine',
            name='last_api_requested_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='gpsmachine',
            name='vendor_code',
            field=models.CharField(default='loconav', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpsmachine',
            name='object_category',
            field=models.CharField(blank=True, choices=[('Movable', 'Movable'), ('Immovable', 'Immovable')], default=3, max_length=15, null=True),
        ),
    ]
