# Generated by Django 3.2 on 2023-06-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20230302_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
