# Generated by Django 3.2 on 2024-07-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20230630_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeuserdropmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routeuserpickupmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
