# Generated by Django 3.2 on 2024-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20240703_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
