# Generated by Django 3.2 on 2025-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_vehiclelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeprice',
            name='km',
            field=models.FloatField(null=True),
        ),
    ]
