# Generated by Django 3.2 on 2025-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_routeprice_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
