# Generated by Django 3.2 on 2024-09-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0039_report_supported_doc_formate'),
        ('chats', '0002_auto_20240904_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_document', to='shared.document'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='message_last_updated',
            field=models.DateTimeField(),
        ),
    ]
