# Generated by Django 3.2 on 2024-09-20 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20240912_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_only_admin_can_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationstandardsectionmapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationstandardsectionmapping',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
