# Generated by Django 3.2 on 2025-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_conversation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
