# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenditure', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_year', to='institutes.financialyear'),
        ),
    ]
