# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('institutes', '0001_initial'),
        ('expenditure', '0002_token_financial_year'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='token',
            name='token_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_token_mapping', to='expenditure.tokenmapping'),
        ),
        migrations.AddField(
            model_name='expenseplan',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_type', to='expenditure.expensetype'),
        ),
        migrations.AddField(
            model_name='expenseplan',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_year', to='institutes.financialyear'),
        ),
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_attachment', to='shared.document'),
        ),
        migrations.AddField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_building', to='institutes.building'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_plan', to='expenditure.expenseplan'),
        ),
        migrations.AddField(
            model_name='expense',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_expense', to='expenditure.token'),
        ),
        migrations.AddField(
            model_name='expense',
            name='token_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_for_expense', to='expenditure.tokenmapping'),
        ),
    ]
