# Generated by Django 2.2.24 on 2021-08-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    def expense_type_transport(apps, schema_editor):
        ExpenseType = apps.get_model('expenditure', 'ExpenseType')
        ExpenseType.objects.bulk_create([
            ExpenseType(name='Transport', codename='transport')
        ])

    dependencies = [
        ('expenditure', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(expense_type_transport)
    ]
