# Generated by Django 3.2 on 2023-07-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0004_custom_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online')], default='Cash', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
