# Generated by Django 3.2 on 2024-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0005_auto_20230721_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('CreditCard', 'Credit card'), ('DebitCard', 'Debit card'), ('NetBanking', 'Net Banking'), ('UPIPayments', 'UPI payments'), ('Online', 'Online'), ('Debit', 'Debit'), ('Credit', 'Credit')], default='Cash', max_length=20, null=True),
        ),
    ]
