# Generated by Django 3.2 on 2025-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0006_alter_expense_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purchased_receipt_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
