# Generated by Django 3.2 on 2025-11-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0007_expense_purchased_receipt_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cheque_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
