# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomdocumentmapping',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomdocument', to='shared.document'),
        ),
        migrations.AddField(
            model_name='roomdocumentmapping',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomdocument_room', to='institutes.room'),
        ),
        migrations.AddField(
            model_name='roomassetmapping',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.asset'),
        ),
        migrations.AddField(
            model_name='roomassetmapping',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomassetmapping_room', to='institutes.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.floor'),
        ),
        migrations.AddField(
            model_name='resourcefailurelog',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_failure_log_resource', to='institutes.resource'),
        ),
        migrations.AddField(
            model_name='institute',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.city'),
        ),
        migrations.AddField(
            model_name='institute',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.country'),
        ),
        migrations.AddField(
            model_name='institute',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.district'),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_logo', to='shared.document'),
        ),
        migrations.AddField(
            model_name='institute',
            name='map_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.mapaddress'),
        ),
        migrations.AddField(
            model_name='institute',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.state'),
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_building', to='institutes.building'),
        ),
        migrations.AddField(
            model_name='banner',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_file', to='shared.document'),
        ),
    ]
