# Generated by Django 3.2 on 2022-08-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_custom_resource_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='country',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='district',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='map_address',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='state',
        ),
    ]
