# Generated by Django 3.2 on 2022-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0005_auto_20220814_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
