# Generated by Django 3.2 on 2022-11-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_custom_form_definition'),
        ('institutes', '0006_institute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDocumentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_document_mapping_document', to='shared.document')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_document_mapping_visitor', to='institutes.visitor')),
            ],
        ),
    ]
