# Generated by Django 3.2 on 2023-04-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0007_visitordocumentmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason_type',
            field=models.CharField(default='School', max_length=50),
        ),
    ]
