# Generated by Django 3.2 on 2023-04-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_subject_subject_part_type'),
        ('institutes', '0008_alter_reason_reason_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearBranchMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_year_branch_mapping_academic_year', to='institutes.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_year_branch_mapping_branch', to='classes.branch')),
            ],
        ),
    ]
