# Generated by Django 3.2 on 2023-06-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_academicyearbranchmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaglist',
            name='token',
            field=models.CharField(default='xxx', max_length=255),
            preserve_default=False,
        ),
    ]
