# Generated by Django 3.2 on 2023-07-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0011_switchableinstitute_userswitchableinstitutemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_tag_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_no', models.CharField(blank=True, max_length=255, null=True)),
                ('expirty_data', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
