# Generated by Django 3.2 on 2024-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0012_biometricmachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricmachine',
            name='token',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
