# Generated by Django 3.2 on 2024-07-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0013_biometricmachine_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
