# Generated by Django 3.2 on 2024-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0014_banner_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='empty_space_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='dise_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='website_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
