# Generated by Django 3.2 on 2025-05-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0017_custom_resourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='app_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
