# Generated by Django 3.2 on 2025-10-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0019_custom_ivr_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='mobile_num',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
