# Generated by Django 3.2 on 2025-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0020_visitor_mobile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='mobile_num',
        ),
        migrations.AddField(
            model_name='visitor',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
