# Generated by Django 3.2 on 2026-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0022_custom_resource_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value pairs like instagram, whatsapp, phone, website'),
        ),
    ]
