# Generated by Django 3.2 on 2026-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0023_institute_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='finance_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
