# Generated by Django 3.2 on 2026-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0024_auto_20260218_1842'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='academicyearbranchmapping',
        #     name='end_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='academicyearbranchmapping',
        #     name='start_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
