# Generated by Django 3.2 on 2026-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0025_auto_20260225_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked when balance sheet is locked'),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
