# Generated by Django 3.2 on 2026-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0025_auto_20260225_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyearbranchmapping',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyearbranchmapping',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
