# Generated by Django 3.2 on 2026-04-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0026_auto_20260327_1535'),
        ('institutes', '0026_auto_20260330_1833'),
    ]

    operations = [
    ]
