from django.apps import apps as global_apps
from django.db import DEFAULT_DB_ALIAS
from django.db.models import signals

content_type_apps = {'status': False}
permission_apps = {'status': False}

basename = {'screen_name': ["invoice_mapping", "school_details", "academic_year", "financial_year", "sections", "standard_strength", "single_standard_strength", "subjects", "counter_format_setup", "studycertificatelist", 
"study_certificate", "admissionabstractlist", "admission_abstract", "assign_subjects", "fast_enrollment", "promote_student", "shuffle_student", "assign_subjects_for_students", "multi_lang_assign_subjects", "student_history_list", 
"feature_enable", "application_fees", "fee_type", "assigned_fee_types", "fee_term", "fee_term_view", "approve_fee_plan", "fee_collection", "fee_adjustment", "concession_type", "student_fee_concession", "cashbook", "fee_collection_report",
"manage_banks", "fee_type_bank_map", "fee_type_bank_balance", "fee_type_bank_transactions", "manage_countries", "manage_states", "manage_districts", "manage_cities", "view_holiday_calender", "bdu_upload", "bdu_error", "staff_list", 
"general_staff", "manage_shift_types", "manage_shift_types_individual", "assign_shift", "assign_subject", "manage_staff_attendance", "exam_type", "exam", "schedule_exam", "schedule_exam_approve", "hall_ticket_generator", "exam_result_config",
"exam_marks_enter", "exam_result_summary", "exam_result_individual", "manage_leave_types", "manage_leave_plan", "apply_leave_application", "approve_leave_application", "payroll_salarycomponent", "payroll_salaryplanhelper", "payroll_salaryplan", 
"payroll_salarypayment", "payroll_payslipstafflist", "payroll_payslip", "payroll_payout", "enquiry_student_list", "enquiry_student", "application_student_list", "application_student", "admission_student_list", "admission_student", "general_student_list", 
"general_student", "student_type_switch", "student_type_switch_individual", "transport_vehicle", "transport_price", "transport_assign_vehicle_driver", "transport_student_address_registration", "transport_place_name", "transport_route_map_view", "transport_route_map", 
"transport_priceplan", "transport_transport_priceplan", "transport_department", "upload_tutorials", "tutorial", "studentattendance_register", "studentattendance_attendance", "studentattendance_report", "period_plan", "period_plan_individual", "assign_timetable_list", 
"timetable_view", "alternate_staff_timetable", "expenses_type", "expenses_plan", "expenses_create", "fuel_token", "managehomework", "viewhomework", "miscellaneous_type", "miscellaneous_plan", "miscellaneous_collection", "miscellaneous_individual", "hostel", "hostel_individual",
"hostel_asset", "room_strength", "room_strength_individual", "room_allocation_list", "room_allocation", "hostel_visitor", "hostel_visitor_individual", "checkIn_checkOut_List", "checkIn_checkOut_Individual", "hostel_expenses_type", "hostel_expenses_plan", "hostel_expenses_create",
"store_inventory_category", "store_inventory_subcategory", "store_inventory_properties", "store_inventory_properties_values", "store_inventory_item", "store_inventory_vendors", "store_stock_items", "store_purchase_items", "store_return_items", "store_return_items_list", "store_issue_items",
"forms", "response", "evaluate", "responsesummary"],
'app_screen_name': ["change_password", "forgot_password", "driver_ridedetail", "update_driver_student_attendance", "diary_list", "diary_create", "diary", "student_diary", "update_attendance", "student_attendance_list", "attendance_profile", "leave_list", "others_leave_list", "leave_summary", 
"apply_leave", "approve_leave", "leave_detail", "upload_tutorial"]}



def do_nothing(*args, **kwargs):
    pass


signals.post_migrate.connect(
    do_nothing, dispatch_uid='django.contrib.auth.management.create_permissions')


def _get_all_permissions(basename, app_label):
    """
    Return (codename, name) for all permissions in the given opts.
    """
    permissions = ()
    builtin = _get_builtin_permissions(basename, app_label)
    custom = list(permissions)
    return builtin + custom


def _get_builtin_permissions(basename, app_label):
    """
    Return (codename, name) for all autogenerated permissions.
    By default, this is ('add', 'change', 'delete')
    """
    default_permissions = ('add', 'change', 'delete', 'view')
    perms = []
    for action in default_permissions:
        if app_label == 'screen_name':
            # visible permission
            perms.append((
                'visible_%s_%s' % (basename, action),
                'Can visible %s %s' % (action, basename)
            ))
        elif app_label == 'app_screen_name':
            perms.append((
                'app_%s_%s' % (basename, action),
                'Can visible app %s %s' % (action, basename)
            ))
        elif app_label == 'staff_app_screen_name':
            perms.append((
                'staff_app_%s_%s' % (basename, action),
                'Can visible app %s %s' % (action, basename)
            ))
        else:
            perms.append((
                '%s_%s' % (action, basename),
                'Can %s %s' % (action, basename)
            ))

    return perms

"""
    Not using this anywhere
"""
def custom_create_permissions(app_config, verbosity=2, interactive=True, using=DEFAULT_DB_ALIAS, apps=global_apps,
                              **kwargs):
    if permission_apps['status']:
        return
    try:
        ContentType = apps.get_model('contenttypes', 'ContentType')
        Permission = apps.get_model('auth', 'Permission')
    except LookupError:
        return
    permission_apps['status'] = True
    # This will hold the permissions we're looking for as
    # (content_type, (codename, name))
    searched_perms = []

    custom_ctypes = set()
    for app_label, values in basename.items():
        for app_basenames in values:
            custom_ctype = ContentType.objects.db_manager(using).get(
                model=app_basenames, app_label=app_label)
            custom_ctypes.add(custom_ctype)

            for perm in _get_all_permissions(app_basenames, app_label):
                searched_perms.append((custom_ctype, perm))

    all_perms = set(Permission.objects.using(using).filter(content_type__in=custom_ctypes).values_list(
        'content_type', 'codename'))

    perms = [
        Permission(codename=codename, name=name, content_type=ct)
        for ct, (codename, name) in searched_perms
        if (ct.pk, codename) not in all_perms
    ]
    Permission.objects.using(using).bulk_create(perms)
    if verbosity >= 2:
        for perm in perms:
            print("Adding permission '%s'" % perm)


def get_contenttypes_and_basenames(using, ContentType):
    ContentType.objects.clear_cache()

    content_types = {
        ct.model: ct
        for ct in ContentType.objects.using(using).all()
    }
    app_basenames = {}
    for app_label, value in basename.items():
        for basenames in value:
            app_basenames.update({basenames: app_label})
    return content_types, app_basenames


def custom_create_contenttypes(app_config, verbosity=2, interactive=True, using=DEFAULT_DB_ALIAS, apps=global_apps,
                               **kwargs):
    """
    Create content types for models in the given app.
    """
    if content_type_apps['status']:
        return

    try:
        ContentType = apps.get_model('contenttypes', 'ContentType')
    except LookupError:
        return
    content_type_apps['status'] = True
    content_types, app_basenames = get_contenttypes_and_basenames(
        using, ContentType)

    if not app_basenames:
        return

    cts = [
        ContentType(
            app_label=app_label,
            model=app_basename,
        )
        for (app_basename, app_label) in app_basenames.items()
        if app_basename not in content_types
    ]
    ContentType.objects.using(using).bulk_create(cts)
    if verbosity >= 2:
        for ct in cts:
            print("Adding content type '%s | %s'" % (ct.app_label, ct.model))
