import React, { Component } from "react";
import {
  nameRegex,
  emailRegex,
  nameWithQuoteRegex,
  pinCodeRegex,
} from "Constants/regularExpression";
import { GET_URL } from "Includes/urls";
import { minDate, lastYearDate } from "Constants";

import messages from "./messages";
import commonMessages from "Constants/messages";
import { FormattedMessage } from "react-intl";

import { dateFormat } from "Includes/functions";

const alias_names = JSON.parse(localStorage.getItem("alias_name"))
  ? JSON.parse(localStorage.getItem("alias_name"))
  : {};

const Form_Details = [
  {
    page_details: {
      form_name: "enquiry_form",
      form_label: "Enquiry Form",
      request_type: "web",
      sub_sections: {
        student_details: {
          name: "student_details",
          label: "Student Details",
          can_hide: false,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...commonMessages.firstName} />,
              regex: nameRegex,
              name: "first_name",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...commonMessages.middleName} />,
              regex: nameRegex,
              name: "middle_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...commonMessages.lastName} />,
              regex: nameRegex,
              name: "last_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...commonMessages.gender} />,
              regex: null,
              name: "gender",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Boy", id: "Boy" },
                { name: "Girl", id: "Girl" },
              ],
            },
            {
              label: <FormattedMessage {...commonMessages.dob} />,
              regex: null,
              name: "dob",
              md: 4,
              className: "width-form-90",
              required: true,
              maxLength: null,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "Standard will be auto-selected based on age",
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...commonMessages.mobileNo} />,
              regex: null,
              name: "mobile_num",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: <FormattedMessage {...commonMessages.email} />,
              regex: emailRegex,
              name: "email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...commonMessages.academicYear} />,
              regex: null,
              name: "entry_academic_year",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDownWithGetRequest",
              maxLength: 25,
              requestURL: GET_URL.getstandard.api,
              params: ["academic_year"],
              updateListTo: "current_standard",
              view_name: "entry_academic_year_value",
            },
            {
              label: <FormattedMessage {...commonMessages.standard} />,
              regex: null,
              name: "current_standard",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDownWithGetRequest",
              maxLength: 25,
              parent: "entry_academic_year",
              helperText: "Please select academic year to enable standard",
              view_name: "current_standard_name",
            },
            {
              label: <FormattedMessage {...messages.enquiryDate} />,
              regex: null,
              name: "enquiry_date",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: new Date(),
              rows: null,
              type: "date",
              minDate: lastYearDate(),
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...commonMessages.studentType} />,
              regex: null,
              name: "student_type",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Day Scholar", id: "Day Scholar" },
                { name: "Residential", id: "Residential" },
              ],
            },
            {
              label: <FormattedMessage {...commonMessages.transport} />,
              regex: null,
              name: "transport_required",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Yes", id: "Yes" },
                { name: "No", id: "No" },
              ],
            },
          ],
        },
        parent_details: {
          name: "parent_details",
          label: "Parent Details",
          hidden: false,
          can_hide: false,
          list: [
            {
              label: <FormattedMessage {...messages.fatherName} />,
              regex: nameRegex,
              name: "father_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...messages.fatherMobileNo} />,
              regex: null,
              name: "f_mobile_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...messages.fatherEmail} />,
              regex: emailRegex,
              name: "f_email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.motherName} />,
              regex: nameRegex,
              name: "mother_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...messages.motherMobileNo} />,
              regex: null,
              name: "m_mobile_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...messages.motherEmail} />,
              regex: emailRegex,
              name: "m_email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.guardianName} />,
              regex: nameRegex,
              name: "guardian_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...messages.guardianMobileNo} />,
              regex: null,
              name: "g_mobile_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...messages.guardianEmail} />,
              regex: emailRegex,
              name: "g_email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.fatherOccupation} />,
              regex: null,
              name: "f_occupation",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.motherOccupation} />,
              regex: null,
              name: "m_occupation",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.guardianOccupation} />,
              regex: null,
              name: "g_occupation",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
          ],
        },
        pre_school_details: {
          name: "pre_school_details",
          label: `Previous ${alias_names["school"]} Details`,
          hidden: false,
          can_hide: true,
          list: [
            {
              label: <FormattedMessage {...messages.schoolName} />,
              regex: nameWithQuoteRegex,
              name: "school_name",
              md: 6,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.schoolAddress} />,
              regex: null,
              name: "school_address",
              md: 6,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              allowDuplicates: true,
            },
            {
              label: <FormattedMessage {...commonMessages.dateOfJoining} />,
              regex: null,
              name: "from_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...commonMessages.dateLeft} />,
              regex: null,
              name: "to_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              parentMinDate: "from_date",
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.tcNo} />,
              regex: null,
              name: "school_tc_number",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
              allowDuplicates: true,
            },
            {
              label: <FormattedMessage {...messages.tcDate} />,
              regex: null,
              name: "tc_issued_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.previousStandard} />,
              regex: null,
              name: "left_standard",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
            },
            {
              label: <FormattedMessage {...commonMessages.aboutCIS} />,
              regex: nameRegex,
              name: "about_school",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
          ],
        },
        address_details: {
          name: "address_details",
          label: "Address Details",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: <FormattedMessage {...commonMessages.address} />,
              regex: null,
              name: "address",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...commonMessages.pincode} />,
              regex: pinCodeRegex,
              name: "pincode",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
            {
              label: <FormattedMessage {...commonMessages.country} />,
              regex: null,
              name: "country",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              view_name: "country_name",
            },
            {
              label: <FormattedMessage {...commonMessages.state} />,
              regex: null,
              name: "state",
              md: 4,
              className: "width-form-90",
              parentRequired: "country",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "state_name",
            },
            {
              label: <FormattedMessage {...commonMessages.district} />,
              regex: null,
              name: "district",
              md: 4,
              className: "width-form-90",
              parentRequired: "state",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "district_name",
            },
            {
              label: <FormattedMessage {...commonMessages.city} />,
              regex: null,
              name: "city",
              md: 4,
              className: "width-form-90",
              parentRequired: "district",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "city_name",
            },
          ],
        },
        exam_details: {
          name: "exam_details",
          label: "Enterance Exam",
          can_hide: false,
          hidden: false,
          list: [
            {
              label: "Eligible Type",
              regex: null,
              name: "eligible_type",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Eligible", id: 1 },
                { name: "Not Eligible", id: 2 },
              ],
              dependentChildren: ["marks", "remarks"],
            },
            {
              label: "Marks",
              regex: null,
              name: "marks",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 200,
              rows: 3,
              dependentParent: "eligible_type",
              dependentValue: 1,
              multiline: true
            },
            {
              label: "Remarks",
              regex: null,
              name: "remarks",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 200,
              rows: 3,
              dependentParent: "eligible_type",
              dependentValue: 2,
              multiline: true
            },
          ],
        },
      },
    },
  },
];

export default Form_Details;
