import {
  panNumberRegex,
  amountRegex,
  emailRegex,
  nameWithQuoteRegex,
  pinCodeRegex,
  aadharNumberRegex,
  bankAccountNumberRegex,
  bankIfscRegex,
  nameRegex,
  numberAndDotRegex,
  nameAndNumberRegex,
  dlNumberRegex,
  pfNumberRegex,
  nameAndNumberWithSpecialCharacterRegex,
  nameAndDotRegex,
} from "Constants/regularExpression";
import { GET_URL } from "Includes/urls";
import { minDate, maxDate } from "Constants";
import React, { Component } from "react";

import messages from "./messages";
import { FormattedMessage } from "react-intl";

const alias_names = JSON.parse(localStorage.getItem("alias_name"))
  ? JSON.parse(localStorage.getItem("alias_name"))
  : {};

const Form_Details = [
  {
    page_details: {
      form_name: "staff_form",
      form_label: "Staff Form",
      request_type: "web",
      sub_sections: {
        staff_details: {
          name: "staff_details",
          label: "Staff Details",
          hidden: false,
          can_hide: false,
          list: [
            {
              label: "First Name",
              regex: nameAndDotRegex,
              name: "first_name",
              md: 12,
              className: "width-form-95",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: "Middle Name",
              regex: nameRegex,
              name: "middle_name",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: "Last Name",
              regex: nameRegex,
              name: "last_name",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: "Gender",
              regex: null,
              name: "gender",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Male", id: "M" },
                { name: "Female", id: "F" },
                { name: "Other", id: "O" },
              ],
            },
            {
              label: 'Blood Group',
              regex: null,
              name: "blood_group",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "A+", id: "A+" },
                { name: "A-", id: "A-" },
                { name: "B+", id: "B+" },
                { name: "B-", id: "B-" },
                { name: "O+", id: "O+" },
                { name: "O-", id: "O-" },
                { name: "AB+", id: "AB+" },
                { name: "AB-", id: "AB-" },
              ],
            },
            {
              label: "Date of Birth",
              regex: null,
              name: "dob",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: "Email",
              regex: emailRegex,
              name: "email",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
              helperText: "Enter a proper Email to get Mails",
            },
            {
              label: "Aadhaar Card No.",
              regex: aadharNumberRegex,
              name: "aadhar_num",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              helperText: "For Example 123456789012",
              maxLength: 12,
            },
            {
              label: "Mobile No.",
              regex: null,
              name: "mobile_num",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 15,
            },
            {
              label: "Alternative No.",
              regex: null,
              name: "alternate_mobile_num",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: "Father/Husband Name",
              regex: nameRegex,
              name: "father_or_husband_name",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: "Experience in Years",
              regex: numberAndDotRegex,
              name: "experience_in_num",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "number",
              maxNumber: 100,
              helperText: "For ex: 2 years 11 month = 2.11",
            },
            {
              label: "Qualification",
              regex: nameWithQuoteRegex,
              name: "qualification",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: "Marital Status",
              regex: null,
              name: "marital_status",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              list: [
                { name: "Married", id: "Married" },
                { name: "Un Married", id: "UnMarried" },
                { name: "Divorced", id: "Divorced" },
              ],
            },
            {
              label: `Expertise ${alias_names["standard"]}`,
              regex: null,
              name: "selected_standards",
              md: 6,
              className: "width-form-90",
              list: [],
              required: false,
              id: "outlined-textarea",
              default: [],
              rows: null,
              type: "multiselect",
              maxLength: 100,
            },
            {
              label: "Documents List",
              regex: null,
              name: "document_list",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: [],
              rows: null,
              type: "multiselect",
              maxLength: 25,
              customId: "doc_id",
              list: [],
            },
            {
              label: "Barcode Number",
              regex: null,
              name: "barcode_number",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: [],
              rows: null,
              type: "text",
              maxNumber: 25,
              list: [],
            },
            {
              label: <FormattedMessage {...messages.religion} />,
              regex: null,
              name: "religion",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              view_name: "religion_name",
            },
            {
              label: <FormattedMessage {...messages.nationality} />,
              regex: null,
              name: "nationality",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              view_name: "nationality_name",
            },
          ],
        },
        joining_details: {
          name: "Joining_details",
          label: "Joining Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: "Job Title",
              regex: nameRegex,
              name: "job_title",
              md: 12,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "Designation",
              regex: nameAndNumberRegex,
              name: "designation",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
              hidden: false,
            },
            {
              label: "Joining Date",
              regex: null,
              name: "date_joined",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: maxDate,
            },

            {
              label: "Employee ID",
              regex: nameAndNumberRegex,
              name: "employee_id",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: "Annual Salary",
              regex: amountRegex,
              name: "salary",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "amount",
              maxNumber: 99999999,
              minNumber: 0,
            },
            {
              label: "Job Type",
              regex: null,
              name: "employee_status",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "F",
              rows: null,
              type: "dropDown",
              hidden: true,
              list: [{ name: "Full Time", id: "F" }],
              // list: [{ name: 'Full Time', id: 'F' }, { name: 'Part Time', id: 'P' }, { name: 'Contract', id: 'C' }]
            },
          ],
        },
        pre_job_details: {
          name: "pre_job_details",
          label: "Previous Job Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: "Institute Name",
              regex: nameWithQuoteRegex,
              name: "prev_school_name",
              md: 12,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "Date Of Joined",
              regex: null,
              name: "prev_date_joined",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: "Last working day",
              regex: null,
              name: "prev_date_left",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              parentMinDate: "prev_date_joined",
              maxDate: new Date(),
            },
            {
              label: "Designation",
              regex: nameAndNumberWithSpecialCharacterRegex,
              name: "prev_designation",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: "Reason For Leaving",
              regex: nameAndNumberWithSpecialCharacterRegex,
              name: "prev_reason_leaving",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
          ],
        },
        driver_details: {
          name: "driver_details",
          label: `Driver Details`,
          hidden: false,
          can_hide: true,
          list: [
            {
              label: "Driving Licence No.",
              regex: dlNumberRegex,
              name: "dl_number",
              md: 6,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: "Previous Work Place",
              regex: nameAndNumberRegex,
              name: "prev_work_place_name",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
          ],
        },
        current_address_details: {
          name: "current_address_details",
          label: "Current Address",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: "Address",
              regex: null,
              name: "address",
              md: 12,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 255,
            },
            {
              label: "Country",
              regex: null,
              name: "country",
              md: 6,
              className: "width-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
            },
            {
              label: "State",
              regex: null,
              name: "state",
              md: 6,
              className: "width-90",
              parentRequired: "country",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
            },
            {
              label: "District",
              regex: null,
              name: "district",
              md: 6,
              className: "width-90",
              parentRequired: "state",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
            },
            {
              label: "City",
              regex: null,
              name: "city",
              md: 6,
              className: "width-90",
              parentRequired: "district",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
            },
            {
              label: "Pincode",
              regex: pinCodeRegex,
              name: "pincode",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
          ],
        },
        permanent_address_details: {
          name: "permanent_address_details",
          label: "Permanent Address",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: "Address",
              regex: null,
              name: "address",
              md: 12,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "Country",
              regex: null,
              name: "country",
              md: 6,
              className: "width-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
            },
            {
              label: "State",
              regex: null,
              name: "state",
              md: 6,
              className: "width-90",
              parentRequired: "country",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
            },
            {
              label: "District",
              regex: null,
              name: "district",
              md: 6,
              className: "width-90",
              parentRequired: "state",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
            },
            {
              label: "City",
              regex: null,
              name: "city",
              md: 6,
              className: "width-90",
              parentRequired: "district",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
            },
            {
              label: "Pincode",
              regex: pinCodeRegex,
              name: "pincode",
              md: 6,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
          ],
        },
        nominee_details: {
          name: "nominee_details",
          label: "nominee Details",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: "Name",
              regex: nameRegex,
              name: "name",
              md: 12,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "DOB",
              regex: null,
              name: "dob",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              minDate: minDate,
              maxDate: new Date(),
              allowDuplicates: true,
            },
            {
              label: "Relationship",
              regex: null,
              name: "relationship_name",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "drop_down",
              maxLength: 25,
              allowDuplicates: true,
              list: [
                { id: "Father", name: "Father" },
                { id: "Mother", name: "Mother" },
                { id: "Son", name: "Son" },
                { id: "Daughter", name: "Daughter" },
                { id: "Spouse", name: "Spouse" },
                { id: "Friend", name: "Friend" },
                { id: "Brother", name: "Brother" },
                { id: "Sister", name: "Sister" },
              ],
              labelBackGroundClassName: "background-white",
            },
            {
              label: "Mobile No.",
              regex: null,
              name: "mobile_num",
              md: 6,
              className: "width-form-100 margin-top-15",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 15,
              allowDuplicates: true,
            },
            {
              label: "Email",
              regex: emailRegex,
              name: "email",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
              helperText: "Enter a proper Email to get Mails",
              allowDuplicates: true,
            },
            {
              label: "Address",
              regex: null,
              name: "address",
              md: 12,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              allowDuplicates: true,
            },
          ],
        },
        bank_details: {
          name: "bank_details",
          label: "Bank Details",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: "Account Name",
              regex: nameRegex,
              name: "name",
              md: 12,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "Bank Name",
              regex: nameWithQuoteRegex,
              name: "bank_name",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "Branch Name",
              regex: nameAndNumberRegex,
              name: "branch_name",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: "Account No.",
              regex: bankAccountNumberRegex,
              name: "account_num",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 18,
            },
            {
              label: "IFSC Code",
              regex: bankIfscRegex,
              name: "ifsc",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 15,
              convertUpperCase: true,
            },
            {
              label: "Mobile No.",
              regex: null,
              name: "mobile_num",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: "PAN No.",
              regex: panNumberRegex,
              name: "pan_num",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 10,
            },
            {
              label: "PF No.",
              regex: pfNumberRegex,
              name: "pf_num",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 23,
            },
            {
              label: "UAN Number",
              regex: null,
              name: "uan_num",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 23,
            },
            {
              label: "ESI No.",
              regex: null,
              name: "esi_num",
              md: 6,
              className: "width-form-100",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 23,
            },
          ],
        },
      },
    },
  },
];

export default Form_Details;
