import {
  panNumberRegex,
  amountRegex,
  numberRegex,
  emailRegex,
  nameWithQuoteRegex,
  pinCodeRegex,
  aadharNumberRegex,
  bplNumberRegex,
  nameAndDotRegex,
  nameAndNumberAndHyphenRegex,
  bankAccountNumberRegex,
  bankIfscRegex,
} from "Constants/regularExpression";
import { GET_URL } from "Includes/urls";
import { minDate, lastYearDate } from "Constants";
import React, { Component } from "react";

import messages from "./messages";
import commonMessages from "Constants/messages";
import { FormattedMessage } from "react-intl";
import { dateFormat } from "Includes/functions";
import {
  FormatColorResetOutlined,
  NewReleasesOutlined,
} from "@material-ui/icons";

const alias_names = JSON.parse(localStorage.getItem("alias_name"))
  ? JSON.parse(localStorage.getItem("alias_name"))
  : {};

const Form_Details = [
  {
    page_details: {
      form_name: "student_bulk_update",
      form_label: "Student Bulk Update",
      request_type: "web",
      sub_sections: {
        student_details: {
          name: "student_details",
          label: "Student Details",
          hidden: false,
          can_hide: false,
          list: [
            {
              label: <FormattedMessage {...commonMessages.firstName} />,
              regex: nameAndDotRegex,
              name: "first_name",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...commonMessages.middleName} />,
              regex: nameAndDotRegex,
              name: "middle_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...commonMessages.lastName} />,
              regex: nameAndDotRegex,
              name: "last_name",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...commonMessages.section} />,
              regex: null,
              name: "standard_section_id",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDownWithGetRequest",
              maxLength: 25,
              parent: "current_standard",
              helperText: "Select Standard",
              customId: "standard_section",
              hidden: true,
            },
            {
              label: "Student Type",
              regex: null,
              name: "is_new_student",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "true",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Old Student", id: "false" },
                { name: "New Student", id: "true" },
              ],
            },
            {
              label: "Student Group",
              regex: null,
              name: "student_group",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [],
              view_name: "student_group_name",
            },
            {
              label: <FormattedMessage {...commonMessages.regNum} />,
              regex: null,
              name: "current_reg_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...commonMessages.gender} />,
              regex: null,
              name: "gender",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Boy", id: "Boy" },
                { name: "Girl", id: "Girl" },
              ],
            },
            {
              label: <FormattedMessage {...commonMessages.dob} />,
              regex: null,
              name: "dob",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...commonMessages.mobileNo} />,
              regex: null,
              name: "mobile_num",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: <FormattedMessage {...commonMessages.email} />,
              regex: emailRegex,
              name: "email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...commonMessages.academicYear} />,
              regex: null,
              name: "entry_academic_year",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDownWithGetRequest",
              maxLength: 25,
              requestURL: GET_URL.getstandard.api,
              params: { academic_year: "academic_year" },
              updateListTo: "current_standard",
              view_name: "entry_academic_year_value",
            },
            {
              label: <FormattedMessage {...commonMessages.aadharNumber} />,
              regex: aadharNumberRegex,
              name: "aadhar_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              type: "text",
              maxLength: 12,
              parentValue: "eid_num",
              parentHelperText: "Already Entered Aadhar VID Number",
              helperText: "For Example 123456789012",
            },
            {
              label: <FormattedMessage {...messages.aadharEidNumber} />,
              regex: aadharNumberRegex,
              name: "eid_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              type: "text",
              maxLength: 12,
              parentValue: "aadhar_num",
              parentHelperText: "Already Entered Aadhar  Number",
              helperText: "For Example 123456789012",
            },
            {
              label: <FormattedMessage {...commonMessages.studentType} />,
              regex: null,
              name: "student_type",
              md: 4,
              className: "width-form-90",
              required: true,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "Day Scholar", id: "Day Scholar" },
                { name: "Residential", id: "Residential" },
              ],
            },
            {
              label: <FormattedMessage {...messages.motherTongue} />,
              regex: nameAndDotRegex,
              name: "mother_tongue",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...messages.placeOfBirth} />,
              regex: nameAndDotRegex,
              name: "place_of_birth",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...commonMessages.stsNumber} />,
              regex: nameAndNumberAndHyphenRegex,
              name: "sts",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...messages.nationality} />,
              regex: null,
              name: "nationality",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              view_name: "nationality_name",
            },
            {
              label: <FormattedMessage {...messages.religion} />,
              regex: null,
              name: "religion",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDown",
              maxLength: 25,
              view_name: "religion_name",
            },
            {
              label: <FormattedMessage {...messages.category} />,
              regex: null,
              name: "category",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDownWithGetRequest",
              maxLength: 25,
              requestType: "dummyParam",
              requestURL: GET_URL.caste.api,
              updateListTo: "caste",
              params: { category: "category" },
              view_name: "category_name",
            },
            {
              label: <FormattedMessage {...messages.caste} />,
              regex: null,
              name: "caste",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "dropDownWithSearchAndGetRequest",
              maxLength: 25,
              parent: "category",
              helperText: "Select Caste",
              view_name: "caste_name",
            },
            {
              label: <FormattedMessage {...messages.bloodGroup} />,
              regex: null,
              name: "blood_group",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "dropDown",
              maxLength: 25,
              list: [
                { name: "A+", id: "A+" },
                { name: "A-", id: "A-" },
                { name: "B+", id: "B+" },
                { name: "B-", id: "B-" },
                { name: "O+", id: "O+" },
                { name: "O-", id: "O-" },
                { name: "AB+", id: "AB+" },
                { name: "AB-", id: "AB-" },
              ],
            },
            {
              label: "Documents List",
              regex: null,
              name: "document_list",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: [],
              rows: null,
              type: "multiselect",
              maxLength: 25,
              customId: "doc_id",
              list: [],
            },
            {
              label: <FormattedMessage {...messages.physicallyHandicaped} />,
              regex: null,
              name: "physically_handicaped",
              md: 4,
              className: "width-form-90",
              id: "outlined-textarea",
              default: false,
              rows: null,
              type: "switch",
              dependentChildren: ["handicap_reason"],
              boolean: true,
            },
            {
              label: <FormattedMessage {...messages.handicapReason} />,
              regex: null,
              name: "handicap_reason",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              dependentParent: "physically_handicaped",
              dependentValue: true,
              maxLength: 30,
            },
          ],
        },
        medical_details: {
          name: "medical_details",
          label: "Physician/Medical Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.physicianName} />,
              regex: nameAndDotRegex,
              name: "physician_name",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...commonMessages.mobileNo} />,
              regex: null,
              name: "med_mobile",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...commonMessages.altMobileNo} />,
              regex: null,
              name: "med_altmobile",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
              maxLength: 25,
            },
            {
              label: <FormattedMessage {...messages.preferedHospital} />,
              regex: nameAndDotRegex,
              name: "hospital",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.insCompany} />,
              regex: null,
              name: "ins_company",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
              view_className: "text-transform-none",
            },
          ],
        },
        bank_details: {
          name: "bank_details",
          label: "Bank Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...commonMessages.accountNumber} />,
              regex: bankAccountNumberRegex,
              name: "account_num",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 18,
            },
            {
              label: <FormattedMessage {...commonMessages.ifscCode} />,
              regex: bankIfscRegex,
              name: "ifsc",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 15,
            },
          ],
        },
        pre_school_details: {
          name: "pre_school_details",
          label: `Previous ${alias_names["school"]} Details`,
          hidden: false,
          can_hide: true,
          list: [
            {
              label: <FormattedMessage {...messages.schoolName} />,
              regex: nameWithQuoteRegex,
              name: "school_name",
              md: 6,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.schoolAddress} />,
              regex: null,
              name: "school_address",
              md: 6,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              allowDuplicates: true,
            },
            {
              label: <FormattedMessage {...commonMessages.dateOfJoining} />,
              regex: null,
              name: "from_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              minDate: minDate,
              maxDate: new Date(),
              childDependent: "to_date",
            },
            {
              label: <FormattedMessage {...commonMessages.dateLeft} />,
              regex: null,
              name: "to_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              parentMinDate: "from_date",
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.tcNo} />,
              regex: null,
              name: "school_tc_number",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
              allowDuplicates: true,
            },
            {
              label: <FormattedMessage {...messages.tcDate} />,
              regex: null,
              name: "tc_issued_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              maxLength: null,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.previousStandard} />,
              regex: null,
              name: "left_standard",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
            },
            {
              label: (
                <FormattedMessage {...messages.particularsOfLastExamPassed} />
              ),
              regex: null,
              name: "particulars_last_exam_passed",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
          ],
        },
        sslc_details: {
          name: "sslc_details",
          label: "SSLC Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.attempts} />,
              regex: numberRegex,
              name: "attempts",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 15,
            },
            {
              label: <FormattedMessage {...messages.yearAndMonthOfPassing} />,
              regex: null,
              name: "year_month_passing",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...commonMessages.regNum} />,
              regex: null,
              name: "reg_num",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...messages.resultWithClass} />,
              regex: null,
              name: "result",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...commonMessages.percentage} />,
              regex: null,
              name: "percentage",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 10,
            },
          ],
        },
        puc_details: {
          name: "puc_details",
          label: "PUC Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.attempts} />,
              regex: numberRegex,
              name: "attempts",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 15,
            },
            {
              label: <FormattedMessage {...messages.yearAndMonthOfPassing} />,
              regex: null,
              name: "year_month_passing",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...commonMessages.regNum} />,
              regex: null,
              name: "reg_num",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...messages.resultWithClass} />,
              regex: null,
              name: "result",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 20,
            },
            {
              label: <FormattedMessage {...commonMessages.percentage} />,
              regex: null,
              name: "percentage",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 10,
            },
          ],
        },
        sslc_mark_details: {
          name: "sslc_mark_details",
          label: "SSLC Mark Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.kannada} />,
              regex: numberRegex,
              name: "kannada",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.english} />,
              regex: numberRegex,
              name: "english",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.hindi} />,
              regex: numberRegex,
              name: "hindi",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.mathematics} />,
              regex: numberRegex,
              name: "mathematics",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.science} />,
              regex: numberRegex,
              name: "science",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.socialStudies} />,
              regex: numberRegex,
              name: "social_studies",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...commonMessages.totalMarks} />,
              regex: numberRegex,
              name: "total_marks",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...commonMessages.maxMarks} />,
              regex: numberRegex,
              name: "max_marks",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...commonMessages.percentage} />,
              regex: null,
              name: "percentage",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
          ],
        },
        puc_mark_details: {
          name: "puc_mark_details",
          label: "PUC Mark Details",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.kannadaOrHindi} />,
              regex: numberRegex,
              name: "kannada_hindi",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.english} />,
              regex: numberRegex,
              name: "english",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.physics} />,
              regex: numberRegex,
              name: "physics",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.chemistry} />,
              regex: numberRegex,
              name: "chemistry",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.mathematics} />,
              regex: numberRegex,
              name: "mathematics",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...messages.biology} />,
              regex: numberRegex,
              name: "biology",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...commonMessages.totalMarks} />,
              regex: numberRegex,
              name: "total_marks",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...commonMessages.maxMarks} />,
              regex: numberRegex,
              name: "max_marks",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 3,
            },
            {
              label: <FormattedMessage {...commonMessages.percentage} />,
              regex: null,
              name: "percentage",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
          ],
        },
        second_language_details: {
          name: "second_language_details",
          label: "Second Language offered in SSLC or its equivalent Exam",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.secondLanguage} />,
              regex: null,
              name: "second_language",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
          ],
        },
        medium_instruction_details: {
          name: "medium_instruction_details",
          label: "Medium of Instruction at SSLC or its equivalent Exam",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.mediumOfInstruction} />,
              regex: null,
              name: "medium_instruction",
              md: 4,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 25,
            },
          ],
        },
        current_address_details: {
          name: "current_address_details",
          label: "Current Address",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: <FormattedMessage {...commonMessages.address} />,
              regex: null,
              name: "address",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 255,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...commonMessages.pincode} />,
              regex: pinCodeRegex,
              name: "pincode",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
            {
              label: <FormattedMessage {...commonMessages.country} />,
              regex: null,
              name: "country",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              view_name: "country_name",
            },
            {
              label: <FormattedMessage {...commonMessages.state} />,
              regex: null,
              name: "state",
              md: 4,
              className: "width-form-90",
              parentRequired: "country",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "state_name",
            },
            {
              label: <FormattedMessage {...commonMessages.district} />,
              regex: null,
              name: "district",
              md: 4,
              className: "width-form-90",
              parentRequired: "state",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "district_name",
            },
            {
              label: <FormattedMessage {...commonMessages.city} />,
              regex: null,
              name: "city",
              md: 4,
              className: "width-form-90",
              parentRequired: "district",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "city_name",
            },
          ],
        },
        permanent_address_details: {
          name: "permanent_address_details",
          label: "Permanent Address",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: <FormattedMessage {...commonMessages.address} />,
              regex: null,
              name: "address",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...commonMessages.pincode} />,
              regex: pinCodeRegex,
              name: "pincode",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 6,
            },
            {
              label: <FormattedMessage {...commonMessages.country} />,
              regex: null,
              name: "country",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              view_name: "country_name",
            },
            {
              label: <FormattedMessage {...commonMessages.state} />,
              regex: null,
              name: "state",
              md: 4,
              className: "width-form-90",
              parentRequired: "country",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "state_name",
            },
            {
              label: <FormattedMessage {...commonMessages.district} />,
              regex: null,
              name: "district",
              md: 4,
              className: "width-form-90",
              parentRequired: "state",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "district_name",
            },
            {
              label: <FormattedMessage {...commonMessages.city} />,
              regex: null,
              name: "city",
              md: 4,
              className: "width-form-90",
              parentRequired: "district",
              id: "outlined-textarea",
              default: null,
              rows: null,
              type: "DropDownWithSearch",
              required: false,
              view_name: "city_name",
            },
          ],
        },
        extra_activity_details: {
          name: "extra_activity_details",
          label:
            "Student Extra Curricular Activities sports & games participated at high school level",
          can_hide: true,
          hidden: false,
          list: [
            {
              label: <FormattedMessage {...messages.extraActivity} />,
              regex: null,
              name: "extra_activity",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text_area",
              maxLength: 500,
              view_className: "text-transform-none",
            },
          ],
        },
        father_details: {
          name: "father_details",
          label: "Father Details",
          hidden: false,
          can_hide: false,
          list: [
            {
              label: <FormattedMessage {...messages.fatherName} />,
              regex: nameAndDotRegex,
              name: "father_name",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              avoid_hide: true,
            },
            {
              label: <FormattedMessage {...messages.fatherProfilePic} />,
              regex: "",
              name: "f_profile_pic",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "image",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...messages.fatherDob} />,
              regex: null,
              name: "f_dob",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.fatherMobileNo} />,
              regex: null,
              name: "f_mobile_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: <FormattedMessage {...messages.fatherEmail} />,
              regex: emailRegex,
              name: "f_email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.fatherAadharNumber} />,
              regex: aadharNumberRegex,
              name: "f_aadhar",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 12,
              helperText: "For Example 123456789012",
            },
            {
              label: <FormattedMessage {...messages.fatherEducation} />,
              regex: null,
              name: "f_education",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.fatherOccupation} />,
              regex: null,
              name: "f_occupation",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.fatherPanNumber} />,
              regex: panNumberRegex,
              name: "f_pan",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 10,
            },
            {
              label: <FormattedMessage {...messages.fatherOfficeAddress} />,
              regex: null,
              name: "f_office_address",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: "Father Annual Income",
              regex: amountRegex,
              name: "f_annual_income",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "number",
              maxNumber: 99999999,
              minNumber: 1,
            },
            {
              label: <FormattedMessage {...messages.fatherTaxPayee} />,
              regex: null,
              name: "f_tax_payee",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: false,
              rows: null,
              type: "radio",
              maxLength: 12,
              list: [
                { label: "Yes", value: true },
                { label: "No", value: false },
              ],
              boolean: true,
            },
          ],
        },
        mother_details: {
          name: "mother_details",
          label: "Mother Details",
          hidden: false,
          can_hide: false,
          list: [
            {
              label: <FormattedMessage {...messages.motherName} />,
              regex: nameAndDotRegex,
              name: "mother_name",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              avoid_hide: true,
            },
            {
              label: <FormattedMessage {...messages.motherProfilePic} />,
              regex: "",
              name: "m_profile_pic",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "image",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...messages.motherDob} />,
              regex: null,
              name: "m_dob",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.motherMobileNo} />,
              regex: null,
              name: "m_mobile_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: <FormattedMessage {...messages.motherEmail} />,
              regex: emailRegex,
              name: "m_email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.motherAadharNumber} />,
              regex: aadharNumberRegex,
              name: "m_aadhar",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 12,
              helperText: "For Example 123456789012",
            },
            {
              label: <FormattedMessage {...messages.motherEducation} />,
              regex: null,
              name: "m_education",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.motherOccupation} />,
              regex: null,
              name: "m_occupation",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.motherPanNumber} />,
              regex: panNumberRegex,
              name: "m_pan",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 10,
            },
            {
              label: <FormattedMessage {...messages.motherOfficeAddress} />,
              regex: null,
              name: "m_office_address",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.motherTaxPayee} />,
              regex: null,
              name: "m_tax_payee",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: false,
              rows: null,
              type: "radio",
              maxLength: 12,
              list: [
                { label: "Yes", value: true },
                { label: "No", value: false },
              ],
              boolean: true,
            },
            {
              label: "Mother Annual Income",
              regex: amountRegex,
              name: "m_annual_income",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "number",
              maxNumber: 99999999,
              minNumber: 1,
            },
            {
              label: <FormattedMessage {...messages.numberOfDependents} />,
              regex: numberRegex,
              name: "dependents",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "number",
              maxNumber: 20,
              minNumber: 0,
            },
          ],
        },
        guardian_details: {
          name: "guardian_details",
          label: "Guardian Details",
          hidden: false,
          can_hide: false,
          list: [
            {
              label: <FormattedMessage {...messages.guardianName} />,
              regex: nameAndDotRegex,
              name: "guardian_name",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              avoid_hide: true,
            },
            {
              label: <FormattedMessage {...messages.guardianProfilePic} />,
              regex: "",
              name: "g_profile_pic",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "image",
              maxLength: 100,
            },
            {
              label: <FormattedMessage {...messages.guardianDob} />,
              regex: null,
              name: "g_dob",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: new Date(),
            },
            {
              label: <FormattedMessage {...messages.guardianMobileNo} />,
              regex: null,
              name: "g_mobile_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "phone_number",
            },
            {
              label: <FormattedMessage {...messages.guardianEmail} />,
              regex: emailRegex,
              name: "g_email",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 225,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.guardianAadharNumber} />,
              regex: aadharNumberRegex,
              name: "g_aadhar",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 12,
              helperText: "For Example 123456789012",
            },
            {
              label: <FormattedMessage {...messages.guardianEducation} />,
              regex: null,
              name: "g_education",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.guardianOccupation} />,
              regex: null,
              name: "g_occupation",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 50,
            },
            {
              label: <FormattedMessage {...messages.guardianPanNumber} />,
              regex: panNumberRegex,
              name: "g_pan",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 10,
            },
            {
              label: <FormattedMessage {...messages.guardianOfficeAddress} />,
              regex: null,
              name: "g_office_address",
              md: 8,
              className: "width-form-95",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 100,
              view_className: "text-transform-none",
            },
            {
              label: <FormattedMessage {...messages.guardianAnnualIncome} />,
              regex: amountRegex,
              name: "g_annual_income",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "number",
              maxNumber: 99999999,
              minNumber: 1,
            },
            {
              label: <FormattedMessage {...messages.guardianTaxPayee} />,
              regex: null,
              name: "g_tax_payee",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: false,
              rows: null,
              type: "radio",
              maxLength: 12,
              list: [
                { label: "Yes", value: true },
                { label: "No", value: false },
              ],
              boolean: true,
            },
          ],
        },
        bpl_details: {
          name: "bpl_details",
          label: "BPL Details",
          hidden: false,
          can_hide: true,
          list: [
            {
              label: <FormattedMessage {...messages.isBpl} />,
              regex: null,
              name: "is_bpl",
              md: 12,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: false,
              rows: null,
              type: "switch",
              maxLength: 12,
              dependentChildren: [
                "bpl_num",
                "bpl_issue_authority",
                "bpl_issue_date",
              ],
              boolean: true,
            },
            {
              label: <FormattedMessage {...messages.bplNumber} />,
              regex: bplNumberRegex,
              name: "bpl_num",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 12,
              dependentParent: "is_bpl",
              dependentValue: true,
            },
            {
              label: <FormattedMessage {...messages.bplIssueAuthority} />,
              regex: null,
              name: "bpl_issue_authority",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "text",
              maxLength: 30,
              dependentParent: "is_bpl",
              dependentValue: true,
            },
            {
              label: <FormattedMessage {...messages.bplIssueDate} />,
              regex: null,
              name: "bpl_issue_date",
              md: 4,
              className: "width-form-90",
              required: false,
              id: "outlined-textarea",
              default: "",
              rows: null,
              type: "date",
              helperText: "",
              minDate: minDate,
              maxDate: new Date(),
              dependentParent: "is_bpl",
              dependentValue: true,
            },
          ],
        },
      },
    },
  },
];

export default Form_Details;
