# Generated by Django 3.2 on 2026-03-04 23:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0048_auto_20260304_2124'),
        ('institutes', '0025_auto_20260225_2054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('put_to_use_date', models.DateField(blank=True, help_text='Date when asset was put to use. Defaults to purchase_date if not set.', null=True)),
                ('capitalization_date', models.DateField(blank=True, help_text='Date of capitalization. Defaults to put_to_use_date.', null=True)),
                ('original_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('useful_life_years', models.PositiveIntegerField(blank=True, help_text="Override group's useful life. If null, uses group setting.", null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_fully_depreciated', models.BooleanField(default=False, help_text='Computed flag: True when WDV reaches salvage value')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetSnapshotLockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('EDITED', 'Edited')], max_length=10)),
                ('performed_on', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, help_text='Optional reason for lock/unlock action', null=True)),
                ('snapshot_count', models.PositiveIntegerField(help_text='Number of snapshots affected by this action')),
                ('details', models.JSONField(blank=True, help_text='Detailed information about edits (asset codes, old/new values)', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_lock_history', to='institutes.financialyear')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action (null for system/CLI operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_lock_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Snapshot Lock History',
                'verbose_name_plural': 'Asset Snapshot Lock History',
                'ordering': ['-performed_on'],
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value'), ('MANUAL', 'Manual'), ('NONE', 'No Depreciation')], default='SLM', max_length=10)),
                ('useful_life_years', models.PositiveIntegerField(default=10)),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate for WDV method (e.g., 15.00 for 15%)', max_digits=5, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_groups', to='asset.assetgroup')),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField()),
                ('disposal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sale proceeds or scrap value', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('wdv_at_disposal', models.DecimalField(blank=True, decimal_places=2, help_text='Written Down Value at time of disposal', max_digits=15, null=True)),
                ('gain_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Disposal value - WDV (positive = gain, negative = loss)', max_digits=15, null=True)),
                ('reason', models.CharField(choices=[('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped'), ('DONATED', 'Donated'), ('WRITTEN_OFF', 'Written Off'), ('LOST', 'Lost / Missing'), ('OTHER', 'Other')], default='SOLD', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='asset.asset')),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCostMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('ADDITION', 'Capital Addition'), ('DISPOSAL', 'Disposal at Cost')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount (always positive)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('movement_date', models.DateField(help_text='Date of the movement (e.g., purchase date, disposal date)')),
                ('opening_source', models.CharField(blank=True, choices=[('MIGRATED', 'Migrated from Previous System'), ('PREVIOUS_FY_CLOSING', 'Previous FY Closing Balance'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], help_text='Required for OPENING type. Indicates source of opening balance.', max_length=30, null=True)),
                ('opening_reference', models.TextField(blank=True, help_text="Reference for opening balance, e.g., 'As per audited BS 2024-25'", null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_movements', to='asset.asset')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_cost_movements', to='institutes.financialyear')),
            ],
            options={
                'verbose_name': 'Asset Cost Movement',
                'verbose_name_plural': 'Asset Cost Movements',
                'ordering': ['asset', 'financial_year', 'movement_type'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset.assetgroup'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank account used for purchase of this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='finance.bankdetail'),
        ),
        migrations.CreateModel(
            name='AssetDepreciationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('additions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capital additions during year (Phase-1: always 0)', max_digits=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('depreciation_basis', models.CharField(choices=[('COST', 'Original Cost'), ('WDV', 'Written Down Value')], default='COST', help_text='COST for SLM, WDV for Written Down Value method', max_length=10)),
                ('calculation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value'), ('MANUAL', 'Manual Entry'), ('NONE', 'No Depreciation')], help_text='SLM, WDV, MANUAL, or NONE', max_length=10)),
                ('months_depreciated', models.PositiveIntegerField(default=12, help_text='Number of months depreciated (for pro-rata calculation)')),
                ('is_manual_depreciation', models.BooleanField(default=False, help_text='True if depreciation value was manually entered/edited')),
                ('original_calculation_method', models.CharField(blank=True, help_text='Original system-calculated method before manual override', max_length=10, null=True)),
                ('calculated_on', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Once locked, snapshot is immutable for audit purposes')),
                ('locked_on', models.DateTimeField(blank=True, null=True)),
                ('unlocked_on', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_snapshots', to='asset.asset')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_snapshots', to='institutes.financialyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_asset_snapshots', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_asset_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Depreciation Snapshot',
                'verbose_name_plural': 'Asset Depreciation Snapshots',
                'ordering': ['asset', 'financial_year'],
                'unique_together': {('asset', 'financial_year')},
            },
        ),
    ]
