# Generated by Django 3.2 on 2026-03-30 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_auto_20260328_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0026_auto_20260330_1833'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='expense_id',
            field=models.PositiveIntegerField(blank=True, help_text='Tracks the expense that created this asset (not FK, just tracking)', null=True),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='credit_bank',
            field=models.ForeignKey(blank=True, help_text='Bank account to credit when credit_to is BANK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposal_credit_bank', to='finance.bankdetail'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='credit_to',
            field=models.CharField(choices=[('NONE', 'None'), ('CASH', 'Cash-in-Hand'), ('BANK', 'Bank Account')], default='NONE', help_text='Where the disposal credit amount goes', max_length=10),
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='financial_year',
            field=models.ForeignKey(blank=True, help_text='Financial year this group belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_group_financial_year', to='institutes.financialyear'),
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='group_type',
            field=models.CharField(choices=[('FIXED_ASSET', 'Fixed Asset'), ('LIABILITY', 'Liability')], default='FIXED_ASSET', help_text='Whether this group belongs to Assets or Liabilities', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_asset_group', to='asset.assetgroup'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank account used for purchase of this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_bank', to='finance.bankdetail'),
        ),
        migrations.AlterField(
            model_name='assetcostmovement',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_cost_movement_asset', to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='assetcostmovement',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_cost_movement_financial_year', to='institutes.financialyear'),
        ),
        migrations.AlterField(
            model_name='assetdepreciationsnapshot',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_depreciation_snapshot_asset', to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='assetdepreciationsnapshot',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_snapshot_financial_year', to='institutes.financialyear'),
        ),
        migrations.AlterField(
            model_name='assetdepreciationsnapshot',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciation_snapshot_locked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetdepreciationsnapshot',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciation_snapshot_unlocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_disposal_asset', to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='depreciation_method',
            field=models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value'), ('MANUAL', 'Manual'), ('NONE', 'No Depreciation')], default='WDV', max_length=10),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_group_parent_group', to='asset.assetgroup'),
        ),
        migrations.AlterField(
            model_name='assetsnapshotlockhistory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_snapshot_lock_history_financial_year', to='institutes.financialyear'),
        ),
        migrations.AlterField(
            model_name='assetsnapshotlockhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system/CLI operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_snapshot_lock_history_performed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
