# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('shared', '0001_initial'),
        ('institutes', '0001_initial'),
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.city'),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.country'),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.district'),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='enquiry_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='forms.enquirystudent'),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='map_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.mapaddress'),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.state'),
        ),
        migrations.AddField(
            model_name='enquirystudent',
            name='current_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standard'),
        ),
        migrations.AddField(
            model_name='enquirystudent',
            name='entry_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_year_enquiry', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='applicationstudentparentmapping',
            name='application_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.applicationguardiandetail'),
        ),
        migrations.AddField(
            model_name='applicationstudentparentmapping',
            name='application_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.applicationparentdetail'),
        ),
        migrations.AddField(
            model_name='applicationstudentparentmapping',
            name='application_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent', to='forms.applicationstudent'),
        ),
        migrations.AddField(
            model_name='applicationstudentdetails',
            name='application_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='forms.applicationstudent'),
        ),
        migrations.AddField(
            model_name='applicationstudentdetails',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_caste', to='shared.caste'),
        ),
        migrations.AddField(
            model_name='applicationstudentdetails',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_category', to='shared.category'),
        ),
        migrations.AddField(
            model_name='applicationstudentdetails',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_nationality', to='shared.nationality'),
        ),
        migrations.AddField(
            model_name='applicationstudentdetails',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_religion', to='shared.religion'),
        ),
        migrations.AddField(
            model_name='applicationstudentaddress',
            name='application_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_address', to='forms.applicationstudent'),
        ),
        migrations.AddField(
            model_name='applicationstudentaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.city'),
        ),
        migrations.AddField(
            model_name='applicationstudentaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.country'),
        ),
        migrations.AddField(
            model_name='applicationstudentaddress',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.district'),
        ),
        migrations.AddField(
            model_name='applicationstudentaddress',
            name='map_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.mapaddress'),
        ),
        migrations.AddField(
            model_name='applicationstudentaddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.state'),
        ),
    ]
