# Generated by Django 3.2 on 2022-07-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_initial'),
        ('shared', '0001_initial'),
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_student_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='current_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.standard'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='enquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.enquirystudent'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='entry_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_year_application', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='applicationstudent',
            name='profile_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_profile_pic', to='shared.document'),
        ),
    ]
