# Generated by Django 3.2 on 2022-09-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_applicationstudentdocumentmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationguardiandetail',
            old_name='annual_income',
            new_name='g_annual_income',
        ),
        migrations.RenameField(
            model_name='applicationparentdetail',
            old_name='parents_annual_income',
            new_name='f_annual_income',
        ),
        migrations.AddField(
            model_name='applicationparentdetail',
            name='m_annual_income',
            field=models.FloatField(null=True),
        ),
    ]
