# Generated by Django 3.2 on 2023-03-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentsiblingmapping_relation_ship'),
        ('forms', '0005_auto_20220925_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_student_student', to='students.student'),
        ),
    ]
