# Generated by Django 3.2 on 2024-04-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_applicationstudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='eligible_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
