# Generated by Django 3.2 on 2025-02-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20240408_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirystudent',
            name='about_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquirystudent',
            name='student_type',
            field=models.CharField(blank=True, choices=[('Day Scholar', 'Day Scholar'), ('Residential', 'Residential')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='enquirystudent',
            name='transport_required',
            field=models.CharField(blank=True, choices=[('Yes', 'yes'), ('No', 'no')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='f_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='g_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquirystudentdetails',
            name='m_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
