# Generated by Django 3.2 on 2026-03-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_hodbranchmapping_mentorstudentmapping_staffbranchmapping_staffstudentmeeting'),
        ('forms', '0008_auto_20250224_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirystudent',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.CreateModel(
            name='EnquiryFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('no_of_followup', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Not Interested'), (3, 'Admitted')], default=1)),
                ('enquiry_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiryfollowup_enquiry_student', to='forms.enquirystudent')),
            ],
        ),
    ]
