# Generated by Django 3.2 on 2026-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20260304_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryfollowup',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
