# Generated by Django 3.2 on 2026-03-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0025_auto_20260225_2054'),
        ('forms', '0010_enquiryfollowup_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryfollowup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='enquiryfollowup',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
