# Generated by Django 3.2 on 2026-03-28 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0011_auto_20260312_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstudent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_student_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplicationUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_num', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forms_applicationuserprofile',
            },
        ),
    ]
