# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('institutes', '0001_initial'),
        ('classes', '0003_initial'),
        ('hr', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableschedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='timetableschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subject'),
        ),
        migrations.AddField(
            model_name='timetableschedule',
            name='time_table_schedule_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_schedule_time_table_schedule_parent', to='hr.timetablescheduleparent'),
        ),
        migrations.AddField(
            model_name='timetablerequestforchange',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_change_staff', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='timetablerequestforchange',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_for_change_subject', to='classes.subject'),
        ),
        migrations.AddField(
            model_name='timetablerequestforchange',
            name='timetable_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_change_staff', to='hr.timetableschedule'),
        ),
        migrations.AddField(
            model_name='timetabledaterange',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='staffteachinghour',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='staffteachinghour',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffleaves',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedby', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffleaves',
            name='attach_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shared.document'),
        ),
        migrations.AddField(
            model_name='staffleaves',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='staffleaves',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='staffleavedates',
            name='staff_leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leave_date', to='hr.staffleaves'),
        ),
        migrations.AddField(
            model_name='staffhoursubjectmapping',
            name='staff_teaching_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='hr.staffteachinghour'),
        ),
        migrations.AddField(
            model_name='staffhoursubjectmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subject'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedule_Day', to='hr.day'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedule_shift', to='hr.shift'),
        ),
        migrations.AddField(
            model_name='periodplan',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_plan_academic_year', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='perioddaymapping',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perioddaymapping_day', to='hr.day'),
        ),
        migrations.AddField(
            model_name='perioddaymapping',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perioddaymapping_period', to='hr.period'),
        ),
        migrations.AddField(
            model_name='period',
            name='period_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_period_plan', to='hr.periodplan'),
        ),
        migrations.AddField(
            model_name='leavetypemapping',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.financialyear'),
        ),
        migrations.AddField(
            model_name='leavetypemapping',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='assignshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_shift_shift', to='hr.shift'),
        ),
        migrations.AddField(
            model_name='assignshift',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
    ]
