# Generated by Django 2.2.24 on 2021-08-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    def initial_leave_type(apps, schema_editor):
        LeaveType = apps.get_model('hr', 'LeaveType')
        LeaveType.objects.bulk_create([
            LeaveType(name='Loss of pay', code='lop')
        ])

    def initial_days(apps, schema_editor):
        Day = apps.get_model('hr', 'Day')
        Day.objects.bulk_create([
            Day(name='Sunday', is_student_working_day=False, is_teacher_working_day=False),
            Day(name='Monday'),
            Day(name='Tuesday'),
            Day(name='Wednesday'),
            Day(name='Thursday'),
            Day(name='Friday'),
            Day(name='Saturday'),
        ])

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(initial_leave_type),
        migrations.RunPython(initial_days)
    ]
