# Generated by Django 3.2 on 2022-08-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_custom_leave_type_and_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleaves',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('NotApproved', 'NotApproved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='NotApproved', max_length=15, null=True),
        ),
    ]
