# Generated by Django 3.2 on 2022-10-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_staffleaves_approval_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffleavedates',
            options={'ordering': ['fordate', 'session']},
        ),
    ]
