# Generated by Django 3.2 on 2023-02-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_subject_subject_part_type'),
        ('staffs', '0002_staffstandardmapping'),
        ('hr', '0005_alter_staffleavedates_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableschedule',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='timetableschedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.subject'),
        ),
    ]
