# Generated by Django 3.2 on 2023-02-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20230225_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('halfday', 'halfday'), ('late', 'late'), ('lateandhalfday', 'lateandhalfday'), ('halfdaylate', 'halfdaylate'), ('unmarked', 'unmarked'), ('shiftnotassigned', 'shiftnotassigned'), ('nonworkingday', 'nonworkingday')], max_length=20),
        ),
    ]
