# Generated by Django 3.2 on 2023-06-26 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_staffattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypemapping',
            name='assigned_globaly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetypemapping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetypemapping',
            name='max_leave_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavetypemapping',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='marked_from',
            field=models.CharField(choices=[('web', 'web'), ('machine_attendance', 'machine_attendance')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('halfday', 'halfday'), ('late', 'late'), ('lateandhalfday', 'lateandhalfday'), ('halfdaylate', 'halfdaylate'), ('unmarked', 'unmarked'), ('shiftnotassigned', 'shiftnotassigned'), ('nonworkingday', 'nonworkingday'), ('lop_attendance', 'lop_attendance')], max_length=20),
        ),
        migrations.CreateModel(
            name='StaffLeaveTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('leave_type_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_type_mapping_leave_type_map', to='hr.leavetypemapping')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_leave_type_mapping_staff', to='hr.leavetype')),
            ],
        ),
    ]
