# Generated by Django 3.2 on 2023-07-02 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0008_auto_20230626_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='marked_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_marked_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='marked_from',
            field=models.CharField(choices=[('web', 'web'), ('machine_attendance', 'machine_attendance'), ('bulk_add', 'bulk_add')], default='web', max_length=20),
        ),
    ]
