# Generated by Django 3.2 on 2023-07-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20230702_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('halfday', 'halfday'), ('late', 'late'), ('lateandhalfday', 'lateandhalfday'), ('halfdaylate', 'halfdaylate'), ('unmarked', 'unmarked'), ('checkinmarked', 'checkinmarked'), ('shiftnotassigned', 'shiftnotassigned'), ('nonworkingday', 'nonworkingday'), ('lop_attendance', 'lop_attendance')], max_length=20),
        ),
    ]
