# Generated by Django 3.2 on 2024-03-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_staffattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('halfday', 'halfday'), ('late', 'late'), ('lateandhalfday', 'lateandhalfday'), ('halfdaylate', 'halfdaylate'), ('unmarked', 'unmarked'), ('checkinmarked', 'checkinmarked'), ('halfdayandlate', 'halfdayandlate'), ('shiftnotassigned', 'shiftnotassigned'), ('nonworkingday', 'nonworkingday'), ('lop_attendance', 'lop_attendance'), ('first_ses_leave_sec_sess_half', 'first_ses_leave_sec_sess_half'), ('first_ses_half_sec_sess_leave', 'first_ses_half_sec_sess_leave'), ('holiday', 'holiday')], max_length=30),
        ),
    ]
