# Generated by Django 3.2 on 2025-10-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_programeducationalobjectives_subjectcourseoutcomeprogrameducationalobjectivesmappingmatrix_subjectpr'),
        ('hr', '0013_alter_staffattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhoursubjectmapping',
            name='standard_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_hour_subject_maaping_standard_section', to='classes.standardsectionmapping'),
        ),
    ]
