# Generated by Django 3.2 on 2026-03-04 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0014_staffhoursubjectmapping_standard_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignshift',
            name='custom_buffer_time',
            field=models.IntegerField(blank=True, help_text='Custom buffer time (minutes) for temporary shift. If not set, uses shift schedule buffer_time.', null=True),
        ),
        migrations.AddField(
            model_name='assignshift',
            name='custom_late_buffer_time',
            field=models.IntegerField(blank=True, help_text='Custom late buffer time (minutes) for temporary shift. If not set, uses shift schedule late_buffer_time.', null=True),
        ),
        migrations.AddField(
            model_name='assignshift',
            name='custom_time_end',
            field=models.TimeField(blank=True, help_text='Custom end time for temporary shift. Only used when priority >= 10. If not set, uses shift schedule.', null=True),
        ),
        migrations.AddField(
            model_name='assignshift',
            name='custom_time_start',
            field=models.TimeField(blank=True, help_text='Custom start time for temporary shift. Only used when priority >= 10. If not set, uses shift schedule.', null=True),
        ),
        migrations.AddField(
            model_name='assignshift',
            name='priority',
            field=models.IntegerField(default=1, help_text='Higher value wins when multiple assignments overlap for same date. Use 1=regular, 10+=temporary/event.'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='is_status_manually_set',
            field=models.BooleanField(default=False, help_text='True if status was manually set by user'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for attendance status change', null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the status was manually changed', null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who manually changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_status_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignshift',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_shift_shift', to='hr.shift'),
        ),
        migrations.AddIndex(
            model_name='assignshift',
            index=models.Index(fields=['staff', 'fromdate', 'todate', 'priority'], name='assignshift_staff_dates_pri'),
        ),
        migrations.AddConstraint(
            model_name='assignshift',
            constraint=models.CheckConstraint(check=models.Q(fromdate__lte=django.db.models.expressions.F('todate')), name='assignshift_valid_date_range'),
        ),
    ]
