# Generated by Django 3.2 on 2022-07-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiary',
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('entity_name', models.CharField(choices=[('FC', 'Fee Collection')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('transaction_fees', models.DecimalField(decimal_places=2, max_digits=30)),
                ('order_status', models.CharField(default='ACTIVE', max_length=50)),
                ('tx_status', models.CharField(default='PENDING', max_length=50)),
                ('mode_of_payment', models.CharField(default='', max_length=50)),
                ('return_url', models.CharField(default='', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('data', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT_CARD_TRANSACTION_FEE', 'Debit Card Transaction fee'), ('CREDIT_CARD_TRANSACTION_FEE', 'Credit Card Transaction fee'), ('NET_BANKING_TRANSACTION_FEE', 'Net Banking Transaction fee'), ('UPI_TRANSACTION_FEE', 'UPI Transaction fee')], default='UPI_TRANSACTION_FEE', max_length=50, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=30)),
                ('is_percentage', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('online_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_online_payment', to='payments.onlinepayment')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_order_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('order_status', models.CharField(default='PENDING', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.beneficiary')),
            ],
        ),
    ]
