# Generated by Django 3.2 on 2022-08-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='failed_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Refunded')], max_length=10),
        ),
    ]
