# Generated by Django 3.2 on 2023-06-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20230605_0045'),
        ('payments', '0003_auto_20220822_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='vendor_transaction_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='onlinepaymentmethods',
            name='deduct_from_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlinepaymentmethods',
            name='max_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='vendor_transaction_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='onlinepaymentmethods',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT_CARD_TRANSACTION_FEE', 'Debit Card Transaction fee'), ('CREDIT_CARD_TRANSACTION_FEE', 'Credit Card Transaction fee'), ('NET_BANKING_TRANSACTION_FEE', 'Net Banking Transaction fee'), ('UPI_TRANSACTION_FEE', 'UPI Transaction fee'), ('UPI_PAYMENT_LINK_FEE', 'UPI Payment Link fee')], default='UPI_TRANSACTION_FEE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.CreateModel(
            name='PayoutFeeCollectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.FloatField(default=0)),
                ('adjustment_amount', models.FloatField(default=0)),
                ('fine_amount', models.FloatField(default=0)),
                ('is_configuration', models.BooleanField(default=True)),
                ('fee_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_collection', to='finance.feecollection')),
                ('fee_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plan', to='finance.feeplan')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='payments.payout')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryFeePlanMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.IntegerField(choices=[(1, 'fee_amount'), (2, 'fine_amount'), (3, 'adjustment_amount'), (4, 'transaction_fees')], default=1)),
                ('is_amount', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=30)),
                ('priority', models.IntegerField(default=1)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to='payments.beneficiary')),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_type', to='finance.feeplan')),
            ],
        ),
    ]
