# Generated by Django 3.2 on 2023-06-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20230605_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='status',
            new_name='refund_status',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='tx_status',
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='cf_payment_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='payment_status',
            field=models.CharField(default='NOT_ATTEMPTED', max_length=50),
        ),
    ]
