# Generated by Django 3.2 on 2023-07-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20230619_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='cf_payment_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
