# Generated by Django 3.2 on 2023-07-02 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_onlinepayment_cf_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
