# Generated by Django 3.2 on 2023-07-06 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_onlinepayment_expiry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('DC', 'Debit Card'), ('CC', 'Credit Card')], max_length=5)),
                ('card_number', models.CharField(max_length=30)),
                ('card_holder_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('cvv_code', models.CharField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('card_number', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAccountMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_bank_account', to='payments.userbankaccount')),
                ('online_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account_online_payment', to='payments.onlinepayment')),
            ],
        ),
    ]
