# Generated by Django 3.2 on 2024-07-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentaccountmapping_userbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('code', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='gateway_response',
            field=models.JSONField(default=dict()),
        ),
    ]
