# Generated by Django 3.2 on 2024-08-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    def create_default_vendor(apps, schema_editor):
        PaymentGateWays = apps.get_model('payments', 'PaymentGateWays')
        PaymentGateWays.objects.create(name='Cashfree', code='cashfree')


    dependencies = [
        ('payments', '0009_auto_20240731_1353'),
    ]

    operations = [
        migrations.RunPython(create_default_vendor)
    ]
