# Generated by Django 3.2 on 2024-08-06 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20240806_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryfeeplanmapping',
            name='gateway_vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentgateways'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='gateway_vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentgateways'),
        ),
        migrations.AddField(
            model_name='onlinepaymentmethods',
            name='gateway_vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentgateways'),
        ),
    ]
