# Generated by Django 3.2 on 2025-01-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0011_auto_20240806_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateways',
            name='merc_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='refund',
            name='gateway_refund_id',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='mode_of_payment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_status',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('online_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_request_online_payment', to='payments.onlinepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('request_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('response_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('request_type', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('online_payment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_log_online_payment', to='payments.onlinepayment')),
            ],
        ),
    ]
