# Generated by Django 3.2 on 2025-01-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20250106_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymentlog',
            name='online_payment',
        ),
    ]
