# Generated by Django 3.2 on 2025-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_remove_onlinepaymentlog_online_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepaymentlog',
            name='request_token',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='onlinepaymentlog',
            name='response_token',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
