# Generated by Django 3.2 on 2026-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20250422_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='entity_name',
            field=models.CharField(choices=[('FC', 'Fee Collection'), ('AF', 'Application Fee')], max_length=10),
        ),
    ]
