# Generated by Django 3.2 on 2026-04-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_onlinepayment_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='gateway_response',
            field=models.JSONField(default=dict),
        ),
    ]
